### ISSUE TITLE
displaying outlier labels properly in case `plot.type = "violin"`

### ISSUE THREAD

**Issue by IndrajeetPatil** [IndrajeetPatil/ggstatsplot#101]
Since `geom_violin()`, like `geom_boxplot()`, doesn't have outlier point highlighting, figure out a way to better display the outliers.
``` r
set.seed(123)

# plot
ggstatsplot::ggbetweenstats(
  data = ToothGrowth,
  x = supp,
  y = len,
  plot.type = "violin",
  messages = FALSE,
  results.subtitle = FALSE,
  outlier.tagging = TRUE,
  outlier.coef = 0.75,
  mean.plotting = FALSE,
  sample.size.label = FALSE
)
```

![](https://i.imgur.com/Oqoihre.png)

<sup>Created on 2018-12-11 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by IndrajeetPatil** [comment]
Related issue, changing `outlier.color` value doesn't change the color of the outlier point-
``` r
set.seed(123)

ggstatsplot::ggbetweenstats(
  data = ToothGrowth,
  x = supp,
  y = len,
  plot.type = "box",
  results.subtitle = FALSE,
  outlier.tagging = TRUE,
  outlier.coef = 0.75,
  outlier.color = "blue",
  messages = FALSE
)
```

![](https://i.imgur.com/jbiC0Jx.png)

<sup>Created on 2018-12-11 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by ibecav** [comment]
Right this is all part of what I'm working on.  Have about half the code rewritten in my sandbox should have the rest today.

**Comment by ibecav** [comment]
Okay I'm about to push a PR that handles colors and shapes after you have accepted it I'll move on to more complex matter of dots and ghost dots.

Please note that I made some immediate corrections to testing.  

There is commented code in here and I know that makes lint unhappy but if you wouldn't mind leaving it in for now as I debug that would be great!

**Comment by IndrajeetPatil** [comment]
Can you also post an example with `outlier.shape = NA`. I can't see that behavior in any of these examples.

**Comment by IndrajeetPatil** [comment]
Also, can you post an example where `outlier.label` corresponds to some other column in the data frame, and not to the default value for `y` variable.

**Comment by ibecav** [comment]
An example of `outlier.shape = NA` 

``` r
ggstatsplot::ggbetweenstats(
  data = ToothGrowth,
  x = supp,
  y = len,
  plot.type = "box",
  results.subtitle = FALSE,
  outlier.tagging = TRUE,
  outlier.coef = 0.5,
  outlier.shape = NA,
  outlier.color = "blue",
  messages = FALSE
)
```

![](https://i.imgur.com/qsc2cJq.png)

<sup>Created on 2018-12-12 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by ibecav** [comment]
With a different outlier label and outlier both NA and shape = 12

``` r
ggstatsplot::ggbetweenstats(
  data = ggplot2::msleep,
  x = vore,
  y = sleep_total,
  plot.type = "boxviolin",
  results.subtitle = FALSE,
  outlier.tagging = TRUE,
  outlier.label = genus,
  outlier.coef = 0.5,
  outlier.shape = 12,
  outlier.color = "blue",
  messages = FALSE
)
```

![](https://i.imgur.com/TKxG4If.png)

``` r

ggstatsplot::ggbetweenstats(
  data = ggplot2::msleep,
  x = vore,
  y = sleep_total,
  plot.type = "boxviolin",
  results.subtitle = FALSE,
  outlier.tagging = TRUE,
  outlier.label = genus,
  outlier.coef = 0.5,
  outlier.shape = NA,
  outlier.color = "blue",
  messages = FALSE
)
```

![](https://i.imgur.com/J0gNZUk.png)

<sup>Created on 2018-12-12 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by ibecav** [comment]
No as I keep saying I'm not done yet.  Just needed to be able to see that option in place to continue with the next logical step.

Feels like I have spent most of my day fighting github changes and providing examples and in general not being able to get anything new accomplished.

Done for the day.

**Comment by ibecav** [comment]
When you commit the PR these should be fixed.  I'll give the code another look tomorrow I'm pretty sure I left some "lint" behind and I do want to look at refactoring as well.
