### ISSUE TITLE
Warn linux users of required linux packages for ggstatsplot installation

### ISSUE THREAD

**Issue by Joao-O-Santos** [IndrajeetPatil/ggstatsplot#108]
Dear Indrajeet Patil,

Thank you so much for your hard work on this package!

I'm using archlinux, and was getting errors when trying to install this package, both from cran or directly from github.
Then I found out Linux users need to have OpenGL libraries installed in order to install this package (namely libx11, mesa and Mesa OpenGL Utility library - glu), given that its dependency 'rgl' requires it.
Could you warn linux users about this in the installation instructions in the Readme?

Best regards,
João

**Comment by IndrajeetPatil** [comment]
Thanks, the `README.Rmd` now mentions this.
