### ISSUE TITLE
Using ggcoefstats to display a tbl_df containing the output of a brms model

### ISSUE THREAD

**Issue by vinimacuch** [IndrajeetPatil/ggstatsplot#114]
Hi,

I tried displaying the output of a Bayesian regression model using `ggcoefstats` but I just can't manage to get it to work. I don't have reproducible code as it basically involves one function (`ggcoefstats()`) and one line of code, but here's my workflow, described in words:

1. After fitting my model using `brms()` and saving the output as an .RDS file, I load the .RDS file and convert it to a tidied tibble using `broom.mixed::tidy()`, which supports brms;

2. I then try displaying the tibble using `ggcoefstats`, but I get an error without any description. To be more precise, I'm trying `ggstatsplot::ggcoefstats(x = RT_model_tidy)`, without any test statistic specification. Note that the tibble has all the appropriate columns, as required (i.e., `term` and `estimate`).

Thanks in advance for any tips!

**Comment by vinimacuch** [comment]
Here's the workflow in a more reproducible format


```r
RT_model <- readRDS("model-outputs/RT_model.RDS")
#> Warning in gzfile(file, "rb"): cannot open compressed file 'model-outputs/
#> RT_model.RDS', probable reason 'No such file or directory'
#> Error in gzfile(file, "rb"): cannot open the connection

RT_model_tidy <- broom.mixed::tidy(RT_model)
#> Error in broom.mixed::tidy(RT_model): object 'RT_model' not found

ggstatsplot::ggcoefstats(
  x = RT_model_tidy)
#> Error in class(x)[[1]] %in% unsupported.mods: object 'RT_model_tidy' not found
```

**Comment by vinimacuch** [comment]
Here's a more reproducible example of my workflow:

```r
ggstatsplot::ggcoefstats(
  x = RT_model_tidy)
#> Error in class(x)[[1]] %in% unsupported.mods: object 'RT_model_tidy' not found
```

**Comment by ibecav** [comment]
Hi,

Your code is failing long before you get to `ggstatsplot::ggcoefstats`.  Both the examples you posted highlight the fact that your original model is not being found.  Could be bad path information or something about your file structure.

You need to get rid of this error first.

`RT_model <- readRDS("model-outputs/RT_model.RDS")
#> Warning in gzfile(file, "rb"): cannot open compressed file 'model-outputs/
#> RT_model.RDS', probable reason 'No such file or directory'
#> Error in gzfile(file, "rb"): cannot open the connection`

When `RT_model <- readRDS("model-outputs/RT_model.RDS")
str(RT_model )` works you'll know you're on the right track

**Comment by vinimacuch** [comment]
Hi Chuck,

Thanks a lot for that. I actually noticed exactly what you said when I tried coming up with a reproducible bit of code, but I assumed it was just a misguided error, since I am able to inspect and work with my model when I upload to R. I will have a look into this and report again.

**Comment by vinimacuch** [comment]
Hi Chuck,

Thanks very much for that. That was indeed the case when I imported the files in a wrong tab on RStudio (incomplete path information). Now that I'm doing it within the right path structure, I still get the error with `ggstatsplot::ggcoefstats`. `str(RT_model)` works fine.

**Comment by IndrajeetPatil** [comment]
I know why this is not working for you. For objects of class `tbl` (or any other kind of dataframe), the `statistic` argument should not be `NULL`. This is a bug. Apologies!

I will push a change soon to solve this.

**Comment by vinimacuch** [comment]
Right, thanks for the input, Indrajeet. However, I tried specifying that before, and there was still an error to do with factor levels, here:

Error in `levels<-`(`*tmp*`, value = as.character(levels)) : 
  factor level [5] is duplicated

**Comment by IndrajeetPatil** [comment]
Can you share what your output from `brms` models look like? It's hard to diagnose what's going on without looking at the `tbl` you are entering into the function.

**Comment by vinimacuch** [comment]
Sure. Here's the whole thing:

```r
# A tibble: 16 x 8
   effect   component group         term                      estimate std.error  conf.low conf.high
   <chr>    <chr>     <chr>         <chr>                        <dbl>     <dbl>     <dbl>     <dbl>
 1 fixed    cond      NA            (Intercept)               5.79       0.0340   5.73       5.86   
 2 fixed    cond      NA            typeFal                  -0.0299     0.0102  -0.0503    -0.00970
 3 fixed    cond      NA            typeVer                  -0.000543   0.0105  -0.0218     0.0203 
 4 ran_pars cond      item          sd__(Intercept)           0.215      0.0219   0.176      0.261  
 5 ran_pars cond      item          sd__typeFal               0.0146     0.0110   0.000473   0.0399 
 6 ran_pars cond      item          sd__typeVer               0.0212     0.0133   0.00110    0.0492 
 7 ran_pars cond      submission_id sd__(Intercept)           0.266      0.0159   0.236      0.299  
 8 ran_pars cond      submission_id sd__typeFal               0.0268     0.0163   0.00168    0.0621 
 9 ran_pars cond      submission_id sd__typeVer               0.0366     0.0134   0.0124     0.0642 
10 ran_pars cond      item          cor__(Intercept).typeFal -0.0257     0.428   -0.817      0.804  
11 ran_pars cond      item          cor__(Intercept).typeVer  0.266      0.370   -0.592      0.877  
12 ran_pars cond      item          cor__typeFal.typeVer      0.0910     0.509   -0.858      0.910  
13 ran_pars cond      submission_id cor__(Intercept).typeFal  0.280      0.352   -0.506      0.887  
14 ran_pars cond      submission_id cor__(Intercept).typeVer  0.630      0.210    0.172      0.957  
15 ran_pars cond      submission_id cor__typeFal.typeVer      0.391      0.413   -0.608      0.942  
16 ran_pars cond      Residual      sd__Observation           0.281      0.00283  0.275      0.286  
```

**Comment by vinimacuch** [comment]
Phew, glad to hear. Thanks a lot for your help.

**Comment by IndrajeetPatil** [comment]
Reopening because I think the documentation can be a bit better to help understand the user what this error is.

**Comment by IndrajeetPatil** [comment]
``` r
# data
df <- tibble::tribble(~term, ~estimate,
              "x", 0.03,
              "x", 0.05)

# attempt to create plot
ggstatsplot::ggcoefstats(df)

#> Note: No model diagnostics information available for the object of class tbl_df .
#> 
#> Note: For the object of class tbl_df , the argument `statistic` is not specified ('t', 'z', or 'f'),
#>  so no labels will be displayed.
#> 
#> Error: All elements in the column `term` should be unique.
#> 
#> Error:
```

<sup>Created on 2018-12-20 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by IndrajeetPatil** [comment]
``` r
# data
df <- tibble::tribble(~term, ~estimate,
              "x", 0.03,
              "x", 0.05)

# attempt to create plot
ggstatsplot::ggcoefstats(df)

#> Note: No model diagnostics information available for the object of class tbl_df .
#> 
#> Note: For the object of class tbl_df , the argument `statistic` is not specified ('t', 'z', or 'f'),
#>  so no labels will be displayed.
#> 
#> Error: All elements in the column `term` should be unique.
#> 
#> Error:
```

<sup>Created on 2018-12-20 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
