### ISSUE TITLE
Feature request: capitalize the first letter of correlation method in ggcorrmat

### ISSUE THREAD

**Issue by GegznaV** [IndrajeetPatil/ggstatsplot#119]
As correlation methods are family names of scientist, thus it would be nice if the first letter was capitalized in `ggcorrmat` (e.g., "Pearson" instead of "pearson"). A screenshot from [documentation ](https://indrajeetpatil.github.io/ggstatsplot/articles/web_only/ggcorrmat.html#correlation-matrix-plot-with-ggcorrmat) with the highlighted place to fix:

![image](https://user-images.githubusercontent.com/12725868/50613883-c95c1480-0ee7-11e9-9c14-eb0af467c2e5.png)

**Comment by ibecav** [comment]
Just for the sake of humor (since I'm fine with the change) we eat a [sandwich not a Sandwich](http://www.foodtimeline.org/foodsandwiches.html)
