### ISSUE TITLE
Feature suggestion: ylim for grouped_ggbetweenstats

### ISSUE THREAD

**Issue by makinate** [IndrajeetPatil/ggstatsplot#126]
I love this package! I just tried to plot some reaction times using grouped_ggbetweenstats and noticed that the ylims and ticks are set automatically for each subplot and that there is no feature that allows forcing the same ylim for each subplot. 
It would be nice to be able to set those, e.g. similar to ggplot2::ylim(0,30)

**Comment by IndrajeetPatil** [comment]
The development version allows you to do this-
``` r
# modifying individual plots using `ggplot.component` argument
ggstatsplot::grouped_ggbetweenstats(
  data = dplyr::filter(
    ggstatsplot::movies_long,
    genre %in% c("Action", "Comedy"),
    mpaa %in% c("R", "PG")
  ),
  x = genre,
  y = rating,
  grouping.var = mpaa,
  results.subtitle = FALSE,
  ggplot.component = ggplot2::scale_y_continuous(breaks = seq(1, 9, 1)),
  messages = FALSE
)
#> Scale for 'y' is already present. Adding another scale for 'y', which
#> will replace the existing scale.
#> Scale for 'y' is already present. Adding another scale for 'y', which
#> will replace the existing scale.
```

![](https://i.imgur.com/gcYVa6M.png)

<sup>Created on 2019-01-05 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Note that this still applies the modification uniformaly to all individual plots. If you want plot-specific modifications, use `purrr` instead, as show here-
file:///C:/Users/inp099/Documents/ggstatsplot/docs/articles/web_only/purrr_examples.html#ggbetweenstats

**Comment by DarioS** [comment]
For the benefit of others, it should be `scale_y_continuous(breaks = seq(1, 9, 1), limits = c(1, 9))`.

**Comment by IndrajeetPatil** [comment]
Yes, this is also documented in the examples for this function:

https://indrajeetpatil.github.io/ggstatsplot/reference/grouped_ggbetweenstats.html#ref-examples

**Comment by s87jackson** [comment]
That does work, but the lines indicating which groups are being compared and the significance stars do not adjust. Example below:

![image](https://github.com/user-attachments/assets/ed676ef3-9186-4456-b326-b7372e5c37d9)

My code is wrapped in a huge function but here is the relevant piece (below). My function passes myLims to ggplot.component to set the y-axes. I thought that ` ggsignif.args = list(textsize = 2, y_position = sigLines)` would set the y values of those lines (drawn by ggsignif) to sigLines, but it returns an error: formal argument "y_position" matched by multiple actual arguments.

`    grouped_ggbetweenstats(
      ..., 
      ggsignif.args = list(textsize = 2),
      ggplot.component = list(
        ..., scale_y_continuous(limits = myLims),
    ))
`

Any advice?
