### ISSUE TITLE
Wrong y values in ggbetweenstats

### ISSUE THREAD

**Issue by alxsimon** [IndrajeetPatil/ggstatsplot#129]
In ggbetweenstats, I noticed the y values do not correspond to the values in the dataset (I noticed this because I have a dataset not containing any negative values and some points were below zero).

I imagine this may come from y jitter which should not happen in this function in my opinion (but I had no time to check for this in the code).

Here is a minimal working example. This is the same when not using a factored x.
```r
tb <- tibble(x = as.factor(rep(1:5, 10)), y = seq(0, 1, length.out = 50))

set.seed(1289)
p1 <- ggstatsplot::ggbetweenstats(
  data = tb,
  x = x, 
  y = y
)
ggsave("plot_seed1289.pdf", p1)

set.seed(2878)
p2 <- ggstatsplot::ggbetweenstats(
  data = tb,
  x = x, 
  y = y
)
ggsave("plot_seed2878.pdf", p2)
```
[plot_seed1289.pdf](https://github.com/IndrajeetPatil/ggstatsplot/files/2730568/plot_seed1289.pdf)
[plot_seed2878.pdf](https://github.com/IndrajeetPatil/ggstatsplot/files/2730569/plot_seed2878.pdf)

**Comment by IndrajeetPatil** [comment]
You are exactly right that this is due to jitter (although I don't see any negative values any your plot). You can turn jittering off if you don't want this behavior (although see how overlapping points can no longer be distinguished from each other)-

``` r
# data
tb <- tibble::tibble(x = as.factor(rep(1:5, 10)), 
                     y = seq(0, 1, length.out = 50))

# plot-1
ggstatsplot::ggbetweenstats(
  data = tb,
  x = x, 
  y = y,
  point.jitter.width = 0,
  point.jitter.height = 0,
  messages = FALSE
)
```

![](https://i.imgur.com/tF42hSW.png)

``` r

# data
tb <- tibble::tibble(x = as.factor(rep(1:5, 10)), 
                     y = seq(0, 1, length.out = 50))

# plot-2
set.seed(2878)
ggstatsplot::ggbetweenstats(
  data = tb,
  x = x, 
  y = y,
  point.jitter.width = 0,
  point.jitter.height = 0,
  messages = FALSE
)
```

![](https://i.imgur.com/sexMByC.png)

<sup>Created on 2019-01-06 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by alxsimon** [comment]
I see, sorry for not looking thoroughly at the arguments available.
For the negative values I was referring to a dataset I am analysing, not this particular example.

I would suggest setting `point.jitter.height = 0` in this function. 
Of course this is personal taste, but I would argue that vertical jittering can be misleading on the distribution of data, having horizontal jittering should be enough to distinguish points in most cases.

Thank you for your quick answer and your work on this package.

**Comment by IndrajeetPatil** [comment]
Good point. Default for `ggbetweenstats` and its `grouped_` variant is `point.jitter.height = 0`.
