### ISSUE TITLE
goals for `1.0.0` release

### ISSUE THREAD

**Issue by IndrajeetPatil** [IndrajeetPatil/ggstatsplot#131]
Planned date: end of April 2020

To do:

**High priority**
- [x] Include `ggwithinstats` function 
- [x] Go full `rlang` rather than using short-cuts
- [x] Add confidence interval for Friedman test effect size
- [x] Adding documentation for new functions (`ggbarstats` and `ggwithinstats`)
- [x] Add support for repeated measures designs for all ANOVA subtitle making functions
- [x] Refactor code to remove `stats::na.omit()`. Take a more fine-grained approach to remove `NA`s only from columns of interest.
- [ ] Showing both 50% and 95% CIs for `ggcoefstats` (like in Bayesian inference plots: e.g., https://twitter.com/tjmahr/status/1048226472710873089)
- [ ] When there are many levels in a factor, `ggpiestats` labels can overlap; give the option to have the labels to be either `"internal"` (current default) or `"external"` to the slices
- [ ] Add `group` option for `ggscatterstats` to support grouped marginals (https://github.com/daattali/ggExtra/blob/master/inst/vignette_files/ggExtra_files/figure-markdown_strict/ggmarginal-grouping-1.png)
- [x] Adding `return` argument to all plotting functions to get both plots and subtitles in return
- [ ] Adding pairwise comparisons support for bayes factor analysis
- [ ] Adding bayes factor support for `ggcorrmat`
- [x] `ggpiestats` and `ggbarstats` should have `x` and `y` optional arguments to correspond to `main` and `condition` (just to be consistent with the rest of the function)
- [ ] Display what kind of pairwise comparisons are being displayed in `ggbetweenstats` and `ggwithinstats`
- [x] Get rid of `purrrlyr` dependency

**Medium priority**
- [ ] Add [vdiffr](https://github.com/r-lib/vdiffr) to test for visual regressions
- [x] Add `stat.title` option for consistency

**Low priority**
- [x] Input checking and good error messages
- [ ] Check font size for `theme_ggstatsplot` function; maybe give user arguments option to change all aspects of the theme?
- [ ] Clean up `.Rmd` file language using `gramr` package 

**questionable**
- [x] Make the package lighter; the number of dependencies is getting out of control

**Comment by ibecav** [comment]
Will this release include the code for #126 ?

Using Version: 0.0.8.9000

``` r
set.seed(123)
library(ggplot2)
library(ggstatsplot)
# simple example showing what I want to accomplish
# which is specifying the max and min for y scale
# many ways to do but my preferred.
ggplot(movies_long, aes(genre, rating)) + 
  geom_point() + 
  expand_limits(y = c(0, 10))
```

![](https://i.imgur.com/b2sZjzu.png)

``` r

# but ...
ggstatsplot::ggbetweenstats(
  data = dplyr::filter(
  ggstatsplot::movies_long,
  genre %in% c("Action", "Comedy"),
  mpaa %in% c("R", "PG")
  ),
  x = genre,
  y = rating,
  results.subtitle = FALSE,
  ggplot.component = ggplot2::expand_limits(y = c(0, 10)),
  messages = FALSE
)
```

![](https://i.imgur.com/mmclHYd.png)

``` r

# and more importantly
ggstatsplot::grouped_ggbetweenstats(
  data = dplyr::filter(
  ggstatsplot::movies_long,
  genre %in% c("Action", "Comedy"),
  mpaa %in% c("R", "PG")
  ),
  x = genre,
  y = rating,
  grouping.var = mpaa,
  results.subtitle = FALSE,
  ggplot.component = ggplot2::expand_limits(y = c(0, 10)),
  messages = FALSE
)
```

![](https://i.imgur.com/SCdMuAB.png)

<sup>Created on 2019-01-08 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by ibecav** [comment]
I'd also like to nominate more user input checking and better messages when they fail to provide proper input a.k.a. fail fast and with a good error message.

**Comment by IndrajeetPatil** [comment]
This feature is already part of `0.0.8`.

Hmm, not sure how `expand_limits` works, but this is how I'd do it-
``` r
ggstatsplot::ggbetweenstats(
  data = dplyr::filter(
    ggstatsplot::movies_long,
    genre %in% c("Action", "Comedy"),
    mpaa %in% c("R", "PG")
  ),
  x = genre,
  y = rating,
  results.subtitle = FALSE,
  ggplot.component = ggplot2::coord_cartesian(ylim = c(0, 10)),
  messages = FALSE
)
#> Coordinate system already present. Adding new coordinate system, which will replace the existing one.
```

![](https://i.imgur.com/CqOl5NY.png)

``` r
ggstatsplot::grouped_ggbetweenstats(
  data = dplyr::filter(
    ggstatsplot::movies_long,
    genre %in% c("Action", "Comedy"),
    mpaa %in% c("R", "PG")
  ),
  x = genre,
  y = rating,
  grouping.var = mpaa,
  results.subtitle = FALSE,
  ggplot.component = ggplot2::coord_cartesian(ylim = c(0, 10)),
  messages = FALSE
)
#> Coordinate system already present. Adding new coordinate system, which will replace the existing one.
#> Coordinate system already present. Adding new coordinate system, which will replace the existing one.
```

![](https://i.imgur.com/WZ03c7u.png)

<sup>Created on 2019-01-08 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by IndrajeetPatil** [comment]
Yeah, this is something I definitely have in mind, but I was thinking of making this part of `1.0.0` release. But maybe it's not a bad idea to get a headstart on this. I have added this item to the checklist above.

**Comment by IndrajeetPatil** [comment]
I had tried this in the past and gave up because I found it too time-consuming to learn, but I think this package desperately needs visual regression tests (using `vdiffr`). Is this something you will be interested to work on for the next release?
(Here is an example of such tests: https://github.com/wilkox/gggenes/tree/master/tests/testthat)

**Comment by ibecav** [comment]
I got the use of expand_limits straight from ggplot2 https://ggplot2.tidyverse.org/reference/expand_limits.html

**Comment by ibecav** [comment]
RE: `vdiffr` not at all convinced it's worth the effort to learn and implement. I took a hard look at the [website](https://github.com/r-lib/vdiffr) and it's not clear to me it will make our lives better or easier.  While the tests you've written by disassembling the `ggplot` object look a little ugly, they work and provide good diagnostic information about what has changed (once you understand how they are constructed).

`vdiffr` would alert to a difference that we would then have to visually compare by eye and then figure out why.  As the package author states...

> It is more of a monitoring tool that allows you to quickly check how the appearance of your figures 
> changes over time, and to manually assess whether changes reflect actual problems in your 
> packages.

**Comment by IndrajeetPatil** [comment]
@ibecav In the previous two commits, I have done some massive reduction in the code content of `grouped_` variants of function. While doing so, I noticed that some functions rely on `purrr::map()` (which is how I had originally written them), while some others rely on `purrr::pmap()` (which is your refactored version). 

Can you refactor the following functions to create a list of plots using `purrr::pmap`, just so that we are consistent across all `grouped_` functions? It will be pretty straightforward since none of these functions have any complex conditional statements. 

1. `grouped_ggcorrmat`
2. `grouped_ggdotplotstats`
3. `grouped_gghistostats`

**Comment by ibecav** [comment]
Sure I'll take a look after I sort my way through the effect size issue (more on that in a bit), but note it's a bit artificial since the only difference between map, map2, & pmap is the number of changing parameters that get passed.

**Comment by IndrajeetPatil** [comment]
Thanks.

Agreed that this is a rather minor change, but it's just that I want to be consistent across functions, which will make it easy for me to take another swipe at refactoring.

**Comment by ibecav** [comment]
About to submit the PR for grouped_gghistostats but documenting my methodology overall.

1.  Move from nested tibbles to a list of split tibbles based on the grouping variable
2.  Build a master list that is consistent across all variants of grouped_ called `flexiblelist` this always holds the parameters that are going to vary.  Consistently thats `df`, variables like `x` and `y` and the `title`
3.  Eliminate the need to nest `plotlist_purrr`
4.  Consistently use:


`plotlist_purrr <-`
`       purrr::pmap(`
`          .l = flexiblelist,`
`          .f = ggstatsplot::ggfunction,`
 **_note_** that there is no tilde and all the invariant formals simply follow the comma

**Comment by ibecav** [comment]
PR submiited for

1. grouped_ggcorrmat
2. grouped_ggdotplotstats
3. grouped_gghistostats

**Comment by IndrajeetPatil** [comment]
Would you have time to add the effect size (_r_) + confidence intervals for non-parametric variants of two- and one-sample _t_-tests soon?

The new release of `lme4` broke the `CRAN` [version](https://cran.r-project.org/web/checks/check_results_ggstatsplot.html) so I am planning to submit a new version of `ggstatsplot` by 15th of Feb.

**Comment by ibecav** [comment]
I'll put that on the list for Friday ahead of omega partial

**Comment by IndrajeetPatil** [comment]
Sounds good.

**Comment by IndrajeetPatil** [comment]
Speaking of appropriate effect size and their confidence intervals, what do you think would be an appropriate effect size for `ggpiestats` when only the proportion test is run?

- **For two levels**- this is straightforward with the `stats` package
It provides estimate and its confidence intervals.

``` r
# ggstatsplot
ggstatsplot::ggpiestats(mtcars, am)
```

![](https://i.imgur.com/sETJssD.png)

``` r

# confidence intervals from stats package
broom::tidy(stats::prop.test(table(mtcars$am), correct = FALSE))
#> # A tibble: 1 x 8
#>   estimate statistic p.value parameter conf.low conf.high method
#>      <dbl>     <dbl>   <dbl>     <int>    <dbl>     <dbl> <chr> 
#> 1    0.594      1.12   0.289         1    0.423     0.745 1-sam~
#> # ... with 1 more variable: alternative <chr>
```
- **For more than two levels** - not supported in `stats` package
```r
# ggstatsplot
ggstatsplot::ggpiestats(mtcars, cyl)
```
![](https://i.imgur.com/WLvWsJ1.png)

``` r

# confidence intervals from stats package
broom::tidy(stats::prop.test(table(mtcars$cyl), correct = FALSE))
#> Error in stats::prop.test(table(mtcars$cyl), correct = FALSE): table 'x' should have 2 entries
```

<sup>Created on 2019-02-11 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
