### ISSUE TITLE
Tibble package error

### ISSUE THREAD

**Issue by rbratslaver** [IndrajeetPatil/ggstatsplot#136]
Hi - have you come across this error related to the tibble package? I've tried updating it, removing and re-installing tibble, tidyverse, and ggstatsplot and this error persists. 

--
Error: package or namespace load failed for ‘ggstatsplot’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 namespace ‘tibble’ 1.4.2 is already loaded, but >= 2.0.0 is required
In addition: Warning message:
package ‘ggstatsplot’ was built under R version 3.5.2 
--

**Comment by IndrajeetPatil** [comment]
Yes, `ggstatsplot 0.0.8` now relies on new version of `tibble` package (`2.0.0`), which is available on CRAN-
https://cran.r-project.org/web/packages/tibble/index.html

![image](https://user-images.githubusercontent.com/11330453/50979711-1742cf00-151d-11e9-9826-d890f887ec6e.png)

Once you update, you should no longer get this error.
