### ISSUE TITLE
Package Dependencies

### ISSUE THREAD

**Issue by rbratslaver** [IndrajeetPatil/ggstatsplot#139]
Hi - I'm geting this error related to the rgl package: 

configure: error: missing required header GL/gl.h
ERROR: configuration failed for package ‘rgl’
* removing ‘/R_Data/packages/rgl’

Wondering if you had any suggestions to resolve this, I've tried removing and re-installing rgl with its dependencies and that doesn't seem to help. 

Thanks for your time.

**Comment by IndrajeetPatil** [comment]
Can you provide a [reprex](https://github.com/tidyverse/reprex) (along with session information)? It's hard to know what's the issue without knowing more details about the system you are working on, etc.

**Comment by rbratslaver** [comment]
Hi - you can close this as I found out this is an issue my server admin
team has to resolve. Thanks.
