### ISSUE TITLE
`ggstatsplot` fails to load with new version of package `skimr`

### ISSUE THREAD

**Issue by GegznaV** [IndrajeetPatil/ggstatsplot#141]
Version 2 of `skimr` package is going to be released soon (as I understand, it should happen this month: [link](https://github.com/ropensci/skimr/issues/341#issuecomment-451752348)). If  `skimr` v2 is installed, `ggstatsplot` fails to load with the error:

```r
library(ggstatsplot)
# Error: package or namespace load failed for ‘ggstatsplot’:
# object ‘skim_to_wide’ is not exported by 'namespace:skimr'
```
You can download the new version of `skimr` using this code:
```r
devtools::install_github("ropenscilabs/skimr", ref = "v2")
```

I think, `ggstatsplot` should prepare for the new version of `skimr` as soon as possible.

**Comment by IndrajeetPatil** [comment]
Sweet lord. Thanks for letting me know!

**Comment by elinw** [comment]
Can you try testing using v2 with skim instead of skim_to_wide?

**Comment by IndrajeetPatil** [comment]
Thanks, I have fixed this. 

@GegznaV Can you download the GitHub development version of `groupedstats` (https://github.com/IndrajeetPatil/groupedstats) and try to see if `ggstatsplot` works with `skimr` v2?

**Comment by GegznaV** [comment]
I can confirm, that the new patch of `ggstatsplot` makes the package compatible with `skimr` v2 (the initial issue disappeared).
Thank's for the quick response.
