### ISSUE TITLE
converting percentages in `gghistostats` to integers

### ISSUE THREAD

**Issue by IndrajeetPatil** [IndrajeetPatil/ggstatsplot#142]
- `bar.measure = "proportion"`
``` r
ggstatsplot::gghistostats(data = iris,
                          x = Sepal.Length,
                          bar.measure = "proportion",
                          results.subtitle = FALSE,
                          messages = FALSE)
```

![](https://i.imgur.com/T5YkN19.png)

- `bar.measure = "mix"`
``` r
ggstatsplot::gghistostats(data = iris,
                          x = Sepal.Length,
                          bar.measure = "mix",
                          results.subtitle = FALSE,
                          messages = FALSE)
```

![](https://i.imgur.com/yGCGm5u.png)

<sup>Created on 2019-01-23 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by IndrajeetPatil** [comment]
@ibecav Do you want to take a stab at this? You have done a similar thing for `ggbarstats` where percentages don't have a decimal point.

**Comment by ibecav** [comment]
Sure I’ll take a look tomorrow

**Comment by ibecav** [comment]
Done.  I'll put in a PR.  Could make it user selectable but I can't imagine a distribution so flat that it would actually matter.  Good news is unbeknownst to me the `scales` package has a variant `percent_format` where you can specify what they call `accuracy` which was all that was needed.
