### ISSUE TITLE
FYI

### ISSUE THREAD

**Issue by ibecav** [IndrajeetPatil/ggstatsplot#147]
You can delete this as soon as you like since it's not an issue or needed long term.  Just a heads up I emailled you a real world example of `ggbarstats` and `purrr::map2` that I think you'll like

**Comment by IndrajeetPatil** [comment]
Thanks. Unfortunately, for some reason, gmail is blocking me from downloading the HTML file. :(

If you publish it in public domain, lemme know and I'll be happy to have a look.
