### ISSUE TITLE
Add ggstatsplot to ggplot2 extensions page

### ISSUE THREAD

**Issue by jl5000** [IndrajeetPatil/ggstatsplot#151]
Not strictly a code issue, but it would be good if this was registered here:

https://www.ggplot2-exts.org/

**Comment by IndrajeetPatil** [comment]
I had made a pull request in the respective repo a long time ago, but it was never accepted. So I stopped trying. I don't think that repo is being actively maintained by anyone. 

I will try to have another shot at it and see if it works.

**Comment by jl5000** [comment]
Ah I see. Apologies.
