### ISSUE TITLE
sort coef order 

### ISSUE THREAD

**Issue by xieguagua** [IndrajeetPatil/ggstatsplot#154]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

Brief description of the problem
Could ggcoefstats sort the coef according to the formula order instead by the  alphabet order？ 
like：

Sex
Age

It should be very helpful to social science research.Thanks！
```r
ggstatsplot::ggcoefstats(
  x = lme4::glmer(
    formula = Survived ~ Sex + Age + (Sex + Age | Class),
    # select 20% of the sample to reduce the time of execution
    data = dplyr::sample_frac(tbl = ggstatsplot::Titanic_full, size = 0.2),
    family = stats::binomial(link = "logit"),
    control = lme4::glmerControl(
      optimizer = "Nelder_Mead",
      calc.derivs = FALSE,
      boundary.tol = 1e-7
    )
  ),
  title = "generalized linear mixed-effects model",
  exponentiate = TRUE,
  stats.label.color = "black"
)
```

**Comment by ibecav** [comment]
What version are you using?  There is already a `sort` option that does what I believe you are asking for.

Important to `set.seed` in the reprex if you want to get the same results consistently since you are pulling a 20% sample

``` r
library(ggstatsplot)
set.seed(123)
ggstatsplot::ggcoefstats(
  x = lme4::glmer(
    formula = Survived ~ Sex + Age + (Sex + Age | Class),
    # select 20% of the sample to reduce the time of execution
    data = dplyr::sample_frac(tbl = ggstatsplot::Titanic_full, size = 0.2),
    family = stats::binomial(link = "logit"),
    control = lme4::glmerControl(
      optimizer = "Nelder_Mead",
      calc.derivs = FALSE,
      boundary.tol = 1e-7
    )
  ),
  title = "generalized linear mixed-effects model",
  exponentiate = TRUE,
  stats.label.color = "black"
)
```

![](https://i.imgur.com/ZfHvixs.png)

``` r
set.seed(123)
ggstatsplot::ggcoefstats(
  x = lme4::glmer(
    formula = Survived ~ Sex + Age + (Sex + Age | Class),
    # select 20% of the sample to reduce the time of execution
    data = dplyr::sample_frac(tbl = ggstatsplot::Titanic_full, size = 0.2),
    family = stats::binomial(link = "logit"),
    control = lme4::glmerControl(
      optimizer = "Nelder_Mead",
      calc.derivs = FALSE,
      boundary.tol = 1e-7
    )
  ),
  title = "generalized linear mixed-effects model",
  exponentiate = TRUE,
  stats.label.color = "black",
  sort = "descending"
)
```

![](https://i.imgur.com/BdTgpRm.png)

<sup>Created on 2019-02-01 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by IndrajeetPatil** [comment]
`ggcoefstats` doesn't sort the terms alphabetically. If `sort` is set to `"none"`, it will display the terms in order in which they were provided by the underlying model. The other options are to sort the terms by their **magnitude** (and not by **names**).

Here is an example-
``` r

set.seed(123)

mod <- stats::lm(
  formula = rating ~ mpaa * genre,
  data = ggstatsplot::movies_long
)

# no sorting
ggstatsplot::ggcoefstats(x = mod, exponentiate = TRUE, sort = "none", stats.labels = FALSE)
```

![](https://i.imgur.com/lx8XYaZ.png)

``` r

# increasing magnitude of estimate
ggstatsplot::ggcoefstats(x = mod, exponentiate = TRUE, sort = "ascending", stats.labels = FALSE)
```

![](https://i.imgur.com/zd86zCL.png)

``` r

# decreasing magnitude of estimate
ggstatsplot::ggcoefstats(x = mod, exponentiate = TRUE, sort = "descending", stats.labels = FALSE)
```

![](https://i.imgur.com/zXgB8v0.png)

**Comment by xieguagua** [comment]
If We run:

polr.mod <- MASS::polr(formula = Sat ~ Infl + Type + Cont, 
                       weights = Freq, 
                       data = housing)


> summary(polr.mod )

Re-fitting to get Hessian

Call:
MASS::polr(formula = Sat ~ Infl + Type + Cont, data = housing, 
    weights = Freq)

Coefficients:
                Value Std. Error t value
InflMedium     0.5664    0.10465   5.412
InflHigh       1.2888    0.12716  10.136
TypeApartment -0.5724    0.11924  -4.800
TypeAtrium    -0.3662    0.15517  -2.360
TypeTerrace   -1.0910    0.15149  -7.202
ContHigh       0.3603    0.09554   3.771

Intercepts:
            Value   Std. Error t value
Low|Medium  -0.4961  0.1248    -3.9739
Medium|High  0.6907  0.1255     5.5049

Residual Deviance: 3479.149 
AIC: 3495.149 

then  plot ,
the Coefficients order is not as same as in "summary",confusing
![image](https://user-images.githubusercontent.com/31589570/52165617-0bbe7e80-273e-11e9-8124-3817f3accfb6.png)

**Comment by IndrajeetPatil** [comment]
I don't think this has anything to do with `ggcoefstats` function, but rather stems from how `broom` (at least the `CRAN` version) tidier for `polr` class objects: https://github.com/tidymodels/broom/issues/420

Here is an example with `lm` object. As you can see, the term order is preserved-
``` r

# setup
set.seed(123)

# model
mod <- stats::lm(formula = wt ~ am * cyl, data = mtcars)

# summary of the model
coef(summary(mod))
#>                Estimate Std. Error    t value     Pr(>|t|)
#> (Intercept)  1.65820588 0.58714925  2.8241642 0.0086365378
#> am          -0.95618461 0.79273245 -1.2061883 0.2378382515
#> cyl          0.30381127 0.08260183  3.6780209 0.0009892218
#> am:cyl       0.03280575 0.13020948  0.2519459 0.8029230279

# plot
ggstatsplot::ggcoefstats(mod)
```

![](https://i.imgur.com/nNQoxE1.png)

<sup>Created on 2019-02-06 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
