### ISSUE TITLE
Can not adjust bin width for violin in ggbetweenstats

### ISSUE THREAD

**Issue by ethulin** [IndrajeetPatil/ggstatsplot#158]
ggbetweenstats uses the default bin width of geom_density. I am hoping to be able to pass parameters to geom_density (in this case, specifically bw to adjust bin width).

The particular use case this is coming up with is that I have a discrete measure of a continuous variable, and would like to increase the smoothing factor to reflect that the bumps in the density are rather arbitrary, and therefore should not be the focus of the graphic.

**Comment by IndrajeetPatil** [comment]
@ibecav Wanna take a crack at this?

**Comment by ibecav** [comment]
No thank you.

**Comment by IndrajeetPatil** [comment]
I think continuously adding new arguments to support every aesthetic of a geom is not a sustainable solution, so I am going to close this issue. I have some ideas on how to get around this problem but none of them are going to be backward-compatible. 

For now, please prepare a custom plot and use `statsExpressions` to display test results:
https://cran.r-project.org/web/packages/statsExpressions/readme/README.html
