### ISSUE TITLE
`subtitle_mann_nonparametric` gives different results based on wide/long format data

### ISSUE THREAD

**Issue by IndrajeetPatil** [IndrajeetPatil/ggstatsplot#162]
@ibecav Again, I'll highly recommend not supporting wide format data to avoid such issues.
``` r
set.seed(123)
library(ggstatsplot)

# made up data
Input <- ("
              Bird   Typical  Odd
              A     -0.255   -0.324
              B     -0.213   -0.185
              C     -0.190   -0.299
              D     -0.185   -0.144
              E     -0.045   -0.027
              F     -0.025   -0.039
              G     -0.015   -0.264
              H      0.003   -0.077
              I      0.015   -0.017
              J      0.020   -0.169
              K      0.023   -0.096
              L      0.040   -0.330
              M      0.040   -0.346
              N      0.050   -0.191
              O      0.055   -0.128
              P      0.058   -0.182
              ")

# creating a dataframe
df_bird <- read.table(textConnection(Input), header = TRUE)

# wide format dataframe
df_bird_wide <- tibble::as_tibble(df_bird)

# converting to long format
df_bird_long <- 
  df_bird %>%
  tibble::as_tibble(x = .) %>%
  tidyr::gather(
    data = .,
    key = "type",
    value = "length",
    Typical:Odd
  )

# checking if the wide and long format are equivalent

# long format means
df_bird_long %>%
  dplyr::group_by(.data = ., type) %>%
  dplyr::summarise(.data = ., mean = mean(length))
#> # A tibble: 2 x 2
#>   type      mean
#>   <chr>    <dbl>
#> 1 Odd     -0.176
#> 2 Typical -0.039

# wide format means
mean(df_bird_wide$Typical)
#> [1] -0.039
mean(df_bird_wide$Odd)
#> [1] -0.176125

# yes!

# wide format
ggstatsplot::subtitle_mann_nonparametric(
  data = df_bird_wide,
  x = Typical,
  y = Odd,
  k = 3,
  conf.level = 0.90,
  paired = TRUE,
  messages = FALSE
)
#> Warning in cor(x, y, use = use, method = method): the standard deviation is
#> zero
#> paste(NULL, "log"["e"](italic("V")), " = ", "4.836", ", ", italic("p"), 
#>     " = ", "0.003", ", ", italic(r)["Spearman"], " = ", "NA", 
#>     ", CI"["90%"], " [", "NA", ", ", "NA", "]", ", ", italic("n"), 
#>     " = ", 16L)

# long format
ggstatsplot::subtitle_mann_nonparametric(
  data = df_bird_long,
  x = type,
  y = length,
  k = 3,
  conf.level = 0.90,
  paired = TRUE,
  messages = FALSE
)
#> paste(NULL, "log"["e"](italic("V")), " = ", "2.303", ", ", italic("p"), 
#>     " = ", "0.003", ", ", italic(r)["Spearman"], " = ", "0.559", 
#>     ", CI"["90%"], " [", "0.314", ", ", "0.733", "]", ", ", italic("n"), 
#>     " = ", 16)
```

<sup>Created on 2019-02-13 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by IndrajeetPatil** [comment]
Here is another example. This shouldn't work, but it does because this is treated as a wide format data!

``` r
# categorical data?
table(mtcars$am, mtcars$cyl)
    
#>      4  6  8
#>   0  3  4 12
#>   1  8  3  2

# use in the function
ggstatsplot::subtitle_mann_nonparametric(
  data = mtcars,
  x = am,
  y = cyl,
  k = 3,
  conf.level = 0.90,
  paired = TRUE,
  messages = FALSE
)

#> paste(NULL, "log"["e"](italic("V")), " = ", "-Inf", ", ", italic("p"), 
#>     " = ", "< 0.001", ", ", italic(r)["Spearman"], " = ", "-0.522", 
#>     ", CI"["90%"], " [", "-0.709", ", ", "-0.267", "]", ", ", 
#>     italic("n"), " = ", 32L)
```

<sup>Created on 2019-02-13 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by IndrajeetPatil** [comment]
If you agree, I will remove the wide format component of this function. We either add support for wide format data for all dozen subtitle helper functions, or don't provide that support for any of them.

I vote for the latter. Nobody who is coming to `ggplot` framework, which this package is part of, doesn't have their data in non-tidy format. So this shouldn't be a big headache for the users since they will already have data in the tidy form.

**Comment by ibecav** [comment]
Please don't yank them.  Happy to have a longer discussion.  It is a huge headache for me (as in a deal breaker).  As to this specific issue, simple mistake on my part, but very germane.  I'll make a PR but the short answer is `corr.test` will only work with two variables both of which are numbers.  So for the long format I have to do `as.integer` to the factor.  But if I'm not careful as here then converting real numbers to integers may lose me the variance I need.

**Comment by IndrajeetPatil** [comment]
Okay, let's retain the wide format support for now. Can you add tests in the PR itself to cover cases like the ones shown in this thread? 

In the future, I think we should adopt a policy to include tests in the PR itself and not add them once the changes are already merged in the master and then discovering bugs while writing tests for the master branch. I've been doing this with all new additions; I immediately write tests for any new lines of code I add. We've constantly maintained our code coverage at 99.83% for a few months now!

**Comment by ibecav** [comment]
BTW to your mtcars example above with `am` by `cyl` it's not technically incorrect to run that test and the reported results are 100% accurate `W = 0, p-value = 1.78e-12` the W = 0 is an artifact of all the ties and the fact we're claiming paired.  But the effect is actually quite strongly negative the number of cylinders 4,6,8 is quite related to whether or not it's automatic 0,1 the real problem is they were lazy in coding a factor as an integer.  BTW no way this is `paired = TRUE` these are independent observations...  A better reprex...  Not the test I would choose but not _**wrong**_ either

``` r
library(ggstatsplot)
mtcarsx <- mtcars
mtcarsx$am <- factor(mtcarsx$am)
ggstatsplot::subtitle_mann_nonparametric(
  data = mtcarsx,
  x = am,
  y = cyl,
  k = 3,
  conf.level = 0.90,
  paired = FALSE,
  messages = FALSE
)
#> paste(NULL, "log"["e"](italic("W")), " = ", "5.268", ", ", italic("p"), 
#>     " = ", "0.004", ", ", italic(r)["Spearman"], " = ", "-0.522", 
#>     ", CI"["90%"], " [", "-0.709", ", ", "-0.267", "]", ", ", 
#>     italic("n"), " = ", 32L)
 
# and

ggstatsplot::ggbetweenstats(
  data = mtcarsx,
  x = am,
  y = cyl,
  k = 3,
  conf.level = 0.90,
  type = "np",
  messages = FALSE
)
```

![](https://i.imgur.com/qRI6wRQ.png)

<sup>Created on 2019-02-15 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by IndrajeetPatil** [comment]
Sure, but even with the changes you made to `subtitle_mann_parametric` in the recent PR, the first issue in this thread continues to be there. Exactly same data gives different results depending on whether it's in wide or long format-
![image](https://user-images.githubusercontent.com/11330453/52878107-dfd1ce80-3129-11e9-9916-262900b12181.png)

**Comment by ibecav** [comment]
Issue acknowledged.  The problem is in wilcox.test where you actually get different answers.  More tomorrow.

**Comment by ibecav** [comment]
Figured this out.  `wilcox.test` is weird, see reprex.  Near term when you're ready I'll add a note in the doco.  Could rewrite it but really don't want to for this.  The Spearman difference is just sloppiness on my part I'll fix it.

``` r
set.seed(123)
library(ggstatsplot)

# Using your made up data
Input <- ("
              Bird   Typical  Odd
              A     -0.255   -0.324
              B     -0.213   -0.185
              C     -0.190   -0.299
              D     -0.185   -0.144
              E     -0.045   -0.027
              F     -0.025   -0.039
              G     -0.015   -0.264
              H      0.003   -0.077
              I      0.015   -0.017
              J      0.020   -0.169
              K      0.023   -0.096
              L      0.040   -0.330
              M      0.040   -0.346
              N      0.050   -0.191
              O      0.055   -0.128
              P      0.058   -0.182
              ")

# creating a dataframe
df_bird <- read.table(textConnection(Input), header = TRUE)

# wide format dataframe
df_bird_wide <- tibble::as_tibble(df_bird)

# converting to long format
df_bird_long <- 
  df_bird %>%
  tibble::as_tibble(x = .) %>%
  tidyr::gather(
    data = .,
    key = "type",
    value = "length",
    Typical:Odd
  )


# wide format
ggstatsplot::subtitle_mann_nonparametric(
  data = df_bird_wide,
  x = Typical,
  y = Odd,
  k = 5,
  conf.level = 0.90,
  paired = TRUE,
  messages = FALSE
)
#> paste(NULL, "log"["e"](italic("V")), " = ", "4.83628", ", ", 
#>     italic("p"), " = ", "0.00295", ", ", italic(r)["Spearman"], 
#>     " = ", "-0.02502", ", CI"["90%"], " [", "-0.44722", ", ", 
#>     "0.40630", "]", ", ", italic("n"), " = ", 16L)

# long format
ggstatsplot::subtitle_mann_nonparametric(
  data = df_bird_long,
  x = type,
  y = length,
  k = 5,
  conf.level = 0.90,
  paired = TRUE,
  messages = FALSE
)
#> paste(NULL, "log"["e"](italic("V")), " = ", "2.30259", ", ", 
#>     italic("p"), " = ", "0.00295", ", ", italic(r)["Spearman"], 
#>     " = ", "0.55856", ", CI"["90%"], " [", "0.31428", ", ", "0.73346", 
#>     "]", ", ", italic("n"), " = ", 16)

#### The discrepancy in the V statistic has nothing to do with
#### long versus wide format and everything to do with how
#### wilcox.test runs in R.  The order of the `type` factor in
#### the long format actually matters sigh... Rather than doing 
#### what most people would do and what t.test does they don't 
#### simply reverse the sigh of the statistic they compute a whole
#### different number.  I've tested it extensively and it's the 
#### wilcox.test not our code

#### If I reverse the factor manually from the default alphabetic
#### odd before typical then look what happens...

df_bird_long$type <- factor(df_bird_long$type, levels = c("Typical", "Odd"))
# long format
ggstatsplot::subtitle_mann_nonparametric(
  data = df_bird_long,
  x = type,
  y = length,
  k = 5,
  conf.level = 0.90,
  paired = TRUE,
  messages = FALSE
)
#> paste(NULL, "log"["e"](italic("V")), " = ", "4.83628", ", ", 
#>     italic("p"), " = ", "0.00295", ", ", italic(r)["Spearman"], 
#>     " = ", "-0.55856", ", CI"["90%"], " [", "-0.73346", ", ", 
#>     "-0.31428", "]", ", ", italic("n"), " = ", 16)

#### Ironically the p value remains the same even the though
#### the test statistic changes an order of magnitude from 10 to 126
```

<sup>Created on 2019-02-18 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by ibecav** [comment]
No need to reopen but just for clarity and my sanity.  It kept bugging me that `wilcox.test` didn't do what I expected.  So I kept digging.  Found a cross-validated answer that got me on the right path.  Will tweak the doco a bit more on another day but...  Also answers an earlier question you had about the difference between **_W_** & **_V_**.

[Cross-validated](https://stats.stackexchange.com/questions/229760/wilcoxon-signed-rank-test-in-r/393267#393267)
