### ISSUE TITLE
`effsize_t_parametric` produces identical CIs for d and g for one sample tests

### ISSUE THREAD

**Issue by IndrajeetPatil** [IndrajeetPatil/ggstatsplot#166]
@ibecav A couple of things to note here- 
1. The _d_ and _g_ don't change depending on whether `noncentral` is set to `TRUE` or `FALSE` (but maybe that's expected?)
2. The confidence intervals are **identical** for _d_ and _g_ although values of _d_ and _g_ are not the same. Not sure how the estimate can change but not its CIs.

``` r
library(ggstatsplot)

purrr::pmap_dfr(
  .l = list(
    data = list(mtcars),
    formula = list(~ wt),
    mu = list(3),
    hedges.correction = list(FALSE, TRUE, FALSE, TRUE),
    noncentral = list(FALSE, FALSE, TRUE, TRUE),
    conf.level = list(0.95)
  ),
  .f = ggstatsplot::effsize_t_parametric
) %>%
  dplyr::select(.data = ., -c(alternative, paired, var.equal))

#> # A tibble: 4 x 6
#>   method     estimate conf.low conf.high conf.level noncentral
#>   <chr>         <dbl>    <dbl>     <dbl>      <dbl> <lgl>     
#> 1 Cohen's d     0.222   -0.501     0.945       0.95 FALSE     
#> 2 Hedges's g    0.216   -0.501     0.945       0.95 FALSE     
#> 3 Cohen's d     0.222   -0.133     0.580       0.95 TRUE      
#> 4 Hedges's g    0.216   -0.133     0.580       0.95 TRUE
```

<sup>Created on 2019-02-14 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by ibecav** [comment]
Yeah I need to go through the one sample piece carefully.  Honestly I wasn't expecting you to make it visible quite so quickly.  Since `effsize::cohend` didn't cover one sample I just included it for completeness.  I'm sure the d and g are correct not so sure about the CI's but don't want to make this a high pri yet

**Comment by IndrajeetPatil** [comment]
We are **not** using `effsize_t_parametric` in the context of one-sample tests yet. We still rely on `psych` package to get CI for *d*. But I still wanted to check everything nonetheless, even for internal functions that users won't be exposed to.

**Comment by ibecav** [comment]
I agree it needs more work just not going to make it a priority for this release...

**Comment by IndrajeetPatil** [comment]
But we do need to make it a priority to have _r_ (Spearman) effect size for **one-sample** Wilcoxon test. Because, otherwise, we will have _r_ for two-sample while LHS estimator one-sample test as the measure of effect size. 

Do you want to instead prioritize that?

**Comment by ibecav** [comment]
Just to be clear because sometimes I get sloppy with my lingo do you mean one sample as in "paired" or one sample as in one independent sample compared to a `mu`?  The former case is addressed in `subtitle_mann_nonparametric`and works see reprex below.  If you mean against a mu or test where have you been handling that in the past?

``` r
library(ggstatsplot)
pre  <- c(100, 122, 97, 25, 274) # a pre-treatment measure for 5 cases
post <- c(104, 125, 99, 29, 277) # the post-treatment measure for the same 5 cases
exams2 <- data.frame(pre, post)
ggstatsplot::subtitle_mann_nonparametric(
  data = exams2,
  x = pre,
  y = post,
  k = 3,
  conf.level = 0.70,
  paired = TRUE,
  messages = FALSE
)
#> paste(NULL, "log"["e"](italic("V")), " = ", "-Inf", ", ", italic("p"), 
#>     " = ", "0.057", ", ", italic(r)["Spearman"], " = ", "1.000", 
#>     ", CI"["70%"], " [", "1.000", ", ", "1.000", "]", ", ", italic("n"), 
#>     " = ", 5L)
```

<sup>Created on 2019-02-15 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by IndrajeetPatil** [comment]
Yes, I meant it against `mu`. Here is an example of what this output currently looks like-
``` r
ggstatsplot::gghistostats(
  data = mtcars,
  x = wt,
  test.value = 3,
  type = "np",
  messages = FALSE
)
```

![](https://i.imgur.com/uY7NZNV.png)

<sup>Created on 2019-02-15 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by IndrajeetPatil** [comment]
Ideally, we would want to have something like this, but using Spearman's rho rather than a rank-biserial correlation-

![image](https://user-images.githubusercontent.com/11330453/52880547-3e9a4680-3130-11e9-9817-1478e81a3c97.png)

**Comment by ibecav** [comment]
Ah, sorry didn't mean to be dense.  Good news, bad news.  I'm not at all uncomfortable for reporting HLS in this case since it is readily reported.  It's not really an effect as is commonly regarded and this is an excellent example.  The results say the point estimate for the pseudo median is 3.19 with the CI's shown which means we can't reject the null for location shift.  100% correct but not what is classically thought of as an effect a la `d` or `g`.

Problem is we can't use `spearman` because there is nothing to compare with.  We could do median - pseudo median (like d does mean - mu) but what's the denominator?  Maybe the MAD?

I don't understand what they're doing but I'll look later spearman has to take the form `cor(x,y,"Spearman)` we know what x is are they perhaps making `y` just a constant vector of mu?

DUnno.  Meantime leave HLS there, no work required.

**Comment by ibecav** [comment]
I did dig on this a little more and I can find nowhere where rank biserial correlation can be used against mu.  See for example https://stats.stackexchange.com/questions/89119/difference-between-point-biserial-and-rank-biserial-correlations

``` r
library(ggstatsplot)
library(psych)
psych::describe(mtcars$wt)
#>    vars  n mean   sd median trimmed  mad  min  max range skew kurtosis
#> X1    1 32 3.22 0.98   3.33    3.15 0.77 1.51 5.42  3.91 0.42    -0.02
#>      se
#> X1 0.17
# Manually calculate d mean - mu / sd
(3.22 - 3.00)/0.98
#> [1] 0.2244898
# traditional confidence interval is about 2 * se on either side so looks reasonable
ggstatsplot::gghistostats(
  data = mtcars,
  x = wt,
  test.value = 3,
  type = "p",
  messages = FALSE
)
```

![](https://i.imgur.com/B29KOzu.png)

``` r
# looks about right
# now compare our pseudo nedian to mu
# first using sd
(3.18865 - 3.00)/0.98
#> [1] 0.1925
# or perhaps mad
(3.18865 - 3.00)/0.77
#> [1] 0.245
# which produce values on either side of the parametric d but close
ggstatsplot::gghistostats(
  data = mtcars,
  x = wt,
  test.value = 3,
  type = "np",
  messages = FALSE
)
```

![](https://i.imgur.com/Gmw15F8.png)

<sup>Created on 2019-02-15 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by ibecav** [comment]
See pull request #176 for parametric

**Comment by IndrajeetPatil** [comment]
Thanks, merged the PR. But, before I close this issue, I just wanted to double-check with you if this is the output you'd expect for one-sample test (using the example above)-

``` r
library(ggstatsplot)
options(pillar.sigfig = 5)

# toobject
x <- stats::t.test(x = mtcars$wt, mu = 3)

# all options
purrr::pmap_dfr(
  .l = list(
    data = list(mtcars),
    formula = list(~ wt),
    mu = list(3),
    hedges.correction = list(FALSE, TRUE, FALSE, TRUE),
    noncentral = list(FALSE, FALSE, TRUE, TRUE),
    conf.level = list(0.95),
    tobject = list(x)
  ),
  .f = ggstatsplot:::effsize_t_parametric
) %>%
  dplyr::select(.data = ., -c(alternative, paired, var.equal))

#> # A tibble: 4 x 6
#>   method     estimate conf.low conf.high conf.level noncentral
#>   <chr>         <dbl>    <dbl>     <dbl>      <dbl> <lgl>     
#> 1 Cohen's d   0.22203 -0.50126   0.94533       0.95 FALSE     
#> 2 Hedges's g  0.21644 -0.50686   0.93973       0.95 FALSE     
#> 3 Cohen's d   0.22203 -0.13262   0.58025       0.95 TRUE      
#> 4 Hedges's g  0.21644 -0.13262   0.58025       0.95 TRUE
```

Note that the confidence intervals are again identical for both _d_ and _g_ when noncentral CIs are used.

![image](https://user-images.githubusercontent.com/11330453/53115503-5dc01c00-3514-11e9-9da3-cab1cad405a8.png)

**Comment by ibecav** [comment]
Yes that's correct.  What I was trying to say in numbered point #2 above.  In noncentral calculations the effect size itself does not matter.  If you look at the calculations in that section of code `d/g` appears not at all, and the formulas make use of the t statistic from the test, the df from the test, and the confidence interval from the test.  Hedge's correction never enters the picture.

**Comment by IndrajeetPatil** [comment]
Okay, perfect. 

Do you want to implement this new function to compute Cohen's _d_ for one-sample _t_-test (used in `ggstatsplot::subtitle_t_onesample()`)? Currently we are using `psych`-
https://github.com/IndrajeetPatil/ggstatsplot/blob/3c89ad2d293bd0336c4d6115e2c50089c838a454/R/helpers_gghistostats_subtitles.R#L100-L107

Maybe we can now also support Hedge's _g_, like in `ggbetweenstats`?

**Comment by ibecav** [comment]
Sure I'd be happy to take a look.  Do me a favor and can you make this an "issue" in github?  You're even welcome to assign it to me.  There's a few others there I consider mine as well.

Parenthetically I'll be slow through next Tuesday.  Personal time visiting grand daughter in Georgia assuming flight out of Hartford doesn't get snow bound.  Certainly answering email but not doing any new serious coding.

**Comment by IndrajeetPatil** [comment]
Cool, sounds good. No hurry at all. This is a low priority anyway.

I think the checklist in #164 is going to be the best way for you to keep track of which issues you can take care of.

**Comment by ibecav** [comment]
BTW if you look at the table you generated

1 Cohen's d   0.22203 -0.50126   0.94533       0.95 FALSE     
2 Hedges's g  0.21644 -0.50686   0.93973       0.95 FALSE     
3 Cohen's d   0.22203 -0.13262   0.58025       0.95 TRUE      
4 Hedges's g  0.21644 -0.13262   0.58025       0.95 TRUE      

One thing that is testable... the absolute diff between high and low conf will be identical (w/i rounding) for matched pairs by method regardless of hedges or cohen

`
> abs(0.94533 - -0.50126)
[1] 1.44659
> abs(0.93973 - -0.50686)
[1] 1.44659
`
It's pretty obvious for ncp but not so obvios for centreal
