### ISSUE TITLE
effect size (+ CI) for proportion test

### ISSUE THREAD

**Issue by IndrajeetPatil** [IndrajeetPatil/ggstatsplot#169]
What would be an appropriate effect size for `ggpiestats` when only the one-sample proportion test is run?

- **For two levels**- this is straightforward with the `stats` package
It provides estimate and its confidence intervals.

``` r
# ggstatsplot
ggstatsplot::ggpiestats(mtcars, am)
```

![](https://i.imgur.com/sETJssD.png)

``` r

# confidence intervals from stats package
broom::tidy(stats::prop.test(table(mtcars$am), correct = FALSE))
#> # A tibble: 1 x 8
#>   estimate statistic p.value parameter conf.low conf.high method
#>      <dbl>     <dbl>   <dbl>     <int>    <dbl>     <dbl> <chr> 
#> 1    0.594      1.12   0.289         1    0.423     0.745 1-sam~
#> # ... with 1 more variable: alternative <chr>
```
- **For more than two levels** - not supported in `stats` package
```r
# ggstatsplot
ggstatsplot::ggpiestats(mtcars, cyl)
```
![](https://i.imgur.com/WLvWsJ1.png)

``` r

# confidence intervals from stats package
broom::tidy(stats::prop.test(table(mtcars$cyl), correct = FALSE))
#> Error in stats::prop.test(table(mtcars$cyl), correct = FALSE): table 'x' should have 2 entries
```

<sup>Created on 2019-02-11 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by IndrajeetPatil** [comment]
@ibecav Any thoughts on this?

**Comment by ibecav** [comment]
Sorry at another campus this week for an accreditation team visit, unlikely to work on any code this week.

**Comment by IndrajeetPatil** [comment]
@ibecav Tagging you again in this to see if you know of any such effect size.

**Comment by ibecav** [comment]
The "right" effect is Cramer's V (range 0 to 1).  Took some time chasing down how best to get the CI.  `prop.test` is definitely **NOT**  what you want.  Easiest to grab the required function `DescTools::CramerV`

reprex below

``` r
chisq.test(table(mtcars$am), correct = FALSE)
#> 
#>  Chi-squared test for given probabilities
#> 
#> data:  table(mtcars$am)
#> X-squared = 1.125, df = 1, p-value = 0.2888
DescTools::CramerV(table(mtcars$am), conf.level = .95, method = "ncchisq")
#>  Cramer V    lwr.ci    upr.ci 
#> 0.1875000 0.0000000 0.5338788
chisq.test(table(mtcars$cyl), correct = FALSE)
#> 
#>  Chi-squared test for given probabilities
#> 
#> data:  table(mtcars$cyl)
#> X-squared = 2.3125, df = 2, p-value = 0.3147
DescTools::CramerV(table(mtcars$cyl), conf.level = .95, method = "ncchisq")
#>  Cramer V    lwr.ci    upr.ci 
#> 0.1900863 0.0000000 0.4065023
lsr::cramersV(table(mtcars$am))
#> [1] 0.1875
lsr::cramersV(table(mtcars$cyl))
#> [1] 0.1900863
```

<sup>Created on 2019-06-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
