### ISSUE TITLE
CRAN version failing with tibble pull request

### ISSUE THREAD

**Issue by krlmlr** [IndrajeetPatil/ggstatsplot#183]
tibble is changing the name repair strategy again, due to unforeseen circumstances: https://github.com/tidyverse/tibble/pull/584. We have seen check failures with _ggstatsplot_, perhaps because it relies on output names after name repair: 

https://github.com/tidyverse/tibble/blob/7067a9ff4e1a60d717734c1b07bbd6acfbd0529b/revdep/new-problems.md#ggstatsplot.

Could you please install the PR with 

```r
devtools::install_github("tidyverse/tibble#584")
```

and confirm?

Thanks, and sorry for the disruption.

**Comment by IndrajeetPatil** [comment]
Thanks for letting me know!

I have fixed this issue and will push a new version of `ggstatsplot` to `CRAN` as soon as I see the new version of `tibble`.

**Comment by krlmlr** [comment]
Thanks for the quick fix! In this particular case you could also use `.name_repair = "universal"` which works with both _tibble_ 2.0.1 and the PR. This removes the need for version check.
