### ISSUE TITLE
adding support for repeated measures design to `subtitle_anova_parametric`

### ISSUE THREAD

**Issue by IndrajeetPatil** [IndrajeetPatil/ggstatsplot#187]
@ibecav Can you work on adding support for repeated measures design for this function?

I have added a new function `ggwithinstats` that will need this (https://indrajeetpatil.github.io/ggstatsplot/reference/ggwithinstats.html).

``` r
set.seed(123)
library(ggstatsplot)

#-------------------------------------- t-test -------------------------------------------------

# between-subjects
subtitle_t_parametric(mtcars, am, wt, paired = FALSE)
#> paste(NULL, italic("t"), "(", "29.23", ") = ", "5.49", ", ", 
#>     italic("p"), " = ", "< 0.001", ", ", italic("g"), " = ", 
#>     "1.89", ", CI"["95%"], " [", "1.10", ", ", "2.83", "]", ", ", 
#>     italic("n"), " = ", 32L)

# within-subjects
subtitle_t_parametric(VR_dilemma, modality, score, paired = TRUE)
#> paste(NULL, italic("t"), "(", "33", ") = ", "-3.96", ", ", italic("p"), 
#>     " = ", "< 0.001", ", ", italic("g"), " = ", "-0.66", ", CI"["95%"], 
#>     " [", "-1.07", ", ", "-0.31", "]", ", ", italic("n"), " = ", 
#>     34L)

#-------------------------------------- anova -------------------------------------------------

# between-subjects
subtitle_anova_parametric(mtcars, cyl, wt, paired = FALSE)
#> Note: 95% CI for effect size estimate was computed with 100 bootstrap samples.
#> 
#> paste(NULL, italic("F"), "(", "2", ",", "18.97", ") = ", "20.25", 
#>     ", ", italic("p"), " = ", "< 0.001", ", ", omega["p"]^2, 
#>     " = ", "0.58", ", CI"["95%"], " [", "0.42", ", ", "0.74", 
#>     "]", ", ", italic("n"), " = ", 32L)
```

<sup>Created on 2019-03-12 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by ibecav** [comment]
Just to be clear you'd like me to investigate the best way to handle repeated measure one way ANOVA parametric?  That is for example a group of subjects who were measured for an outcome on more than two occasions (since two occasions is simply paired t-test)?

**Comment by IndrajeetPatil** [comment]
Yes, that’s exactly what I meant!

Note that this is already supported for *non-parametric* and *robust* tests. Only their parametric and Bayes Factor equivalents are missing.

**Comment by IndrajeetPatil** [comment]
Also, this same function should support both independent and repeated measures design with the argument paired, just to be consistent with how this has been implemented for the t-test.

**Comment by ibecav** [comment]
Okay.  I'm a little bit worried that `paired` will begin to confuse people as the designs get more complex but we can deal with that later...

Are you still going to eventually include more complex factorial ANOVA model designs?  I ask because native `aov` and `car::Anova` are a pain for manipulating complex models and as you know don't typically include effect sizes (which get even more complex when you add in repeated measures).  

The `ez` package has `ezANOVA` which will solve many problems as the model gets more complex, to include properly handling the `type` of sums of squares (aov doesn't) as well as producing an effect size estimate that generalizes to both between and within subjects designs. (see (Bakeman, 2005, https://link.springer.com/content/pdf/10.3758%2FBF03192707.pdf))

Once we have generalized eta squared and the anova table we can calculate CI's around it based off work from `MBESS` without even importing the whole package.

It's like worth it if we're expanding ANOVA support but may not be if we're not.

**Comment by IndrajeetPatil** [comment]
Ah, no. 
I should have been more specific: both `ggbetweenstats` and `ggwithinstats` will always support **only** one-way (repeated measures) ANOVA. 

For more complex designs, I expect people to use `ggcoefstats` which supports all kinds of designs:
https://indrajeetpatil.github.io/ggstatsplot/articles/web_only/ggcoefstats.html

So, we don't have to worry about this. But, I completely agree with you that supporting the RM designs are much more challenging than their independent design cousins.

**Comment by ibecav** [comment]
Ugh, not the answer I wanted to hear (lol so **_you_** don't have to worry about it).  Oh well.  If you don't mind i'm still going to initially design it using `ezAnova` since it is far less painful all around.

**Comment by ibecav** [comment]
Okay so I have the work successfully done to run the test and report the results (actually about 5 different ways).  I can get eta or omega.  BUT all attempts to generate CIs around the effect seem to generate non sensical lower interval (as in lower interval is greater than the estimate) in some data whether I use MBESS or sjsstats.  I'll keep researching

**Comment by ibecav** [comment]
Did the best I could with the time I have.  Happily I'm now 1005 sure it's not just a sill mistake on my part.  Both `MBESS` and `sjsstats` use ncp algorithms to compute the CI's around the effect size.  In other words they use the F Values and not the actual estimate.  Can't get sjsstats to give me boot-strapped intervals I know you've worked with him before.

I'm using your bugs example for the doo even though that data is actually a 2x2 that you are collapsing to 4 flat levels.  doesn't really matter since the results are the same when I used repeated measures data I have like [Nolen-Hoeksema and Morrow (1991)](https://www.uvm.edu/~dhowell/StatPages/R/NolenHoeksema.dat) 

PR on the way.  Sadly I still can't do testing but It think it's in decent shape

**Comment by IndrajeetPatil** [comment]
Can you show what the output looks like from this function? I couldn't find any reprex in the PR either.

For example, using the following example-
```r
subtitle_anova_parametric_repeated(
  data = iris_long,
  x = condition,
  y = value,
  id.variable = id
)
```

**Comment by ibecav** [comment]
Per your request a reprex with iris_long and bugs_long

``` r
library(ggstatsplot)
library(jmv)
data("bugs", package = "jmv")

# converting to long format
data_bugs <- bugs %>%
  dplyr::filter(., !is.na(LDHF) & !is.na(LDLF) & !is.na(HDLF)  & !is.na(HDHF)) %>%
  tibble::as_tibble(.) %>%
  tidyr::gather(., key, value, LDLF:HDHF)

# minimum call
subtitle_anova_parametric_repeated(
  data = data_bugs,
  x = key,
  y = value,
  id.variable = Subject
)
#> paste(NULL, italic("F"), "(", "3", ",", "261", ") = ", "20.59", 
#>     ", ", italic("p"), " = ", "< 0.001", ", ", omega^2, " = ", 
#>     "0.08", ", CI"["95%"], " [", "0.08", ", ", "0.21", "]", ", ", 
#>     italic("n"), " = ", 88)

# changing effect type and confidence
subtitle_anova_parametric_repeated(
  data = data_bugs,
  x = key,
  y = value,
  id.variable = Subject,
  effsize.type = "biased",
  conf.level = .99
)
#> paste(NULL, italic("F"), "(", "3", ",", "261", ") = ", "20.59", 
#>     ", ", italic("p"), " = ", "< 0.001", ", ", eta["p"]^2, " = ", 
#>     "0.19", ", CI"["99%"], " [", "0.09", ", ", "0.29", "]", ", ", 
#>     italic("n"), " = ", 88)

# before I remove the changes to ggwithinstats
ggstatsplot:::ggwithinstats(data_bugs, 
                            key, 
                            value, 
                            id.variable = Subject, 
                            effsize.type = "biased", 
                            pairwise.comparisons = TRUE, 
                            p.adjust.method = "bonferroni", 
                            conf.level = .99, 
                            bf.message = TRUE,
                            path.point = FALSE)
#> Note: 99% CI for effect size estimate was computed with 100 bootstrap samples.
#> 
#> # A tibble: 6 x 8
#>   group1 group2 mean.difference conf.low conf.high  p.value significance
#>   <chr>  <chr>            <dbl>    <dbl>     <dbl>    <dbl> <chr>       
#> 1 HDLF   HDHF            -1.15    -2.21    -0.0883 3.18e- 3 **          
#> 2 LDHF   HDHF            -0.472   -1.53     0.588  4.21e- 1 ns          
#> 3 LDLF   HDHF            -2.16    -3.22    -1.11   3.95e-12 ***         
#> 4 LDHF   HDLF             0.676   -0.383    1.74   3.37e- 1 ns          
#> 5 LDLF   HDLF            -1.02    -2.08     0.0424 7.94e- 3 **          
#> 6 LDLF   LDHF            -1.69    -2.75    -0.634  1.33e- 8 ***         
#> # … with 1 more variable: p.value.label <chr>
#> Note: Shapiro-Wilk Normality Test for value : p-value = < 0.001
#> 
#> Note: Bartlett's test for homogeneity of variances for factor key : p-value = 0.112
#> 
```

![](https://i.imgur.com/byYrPQ4.png)

``` r

# your request for iris_long
subtitle_anova_parametric_repeated(
  data = iris_long,
  x = condition,
  y = value,
  id.variable = id
)
#> paste(NULL, italic("F"), "(", "3", ",", "447", ") = ", "776.32", 
#>     ", ", italic("p"), " = ", "< 0.001", ", ", omega^2, " = ", 
#>     "0.71", ", CI"["95%"], " [", "0.77", ", ", "0.82", "]", ", ", 
#>     italic("n"), " = ", 150)

ggstatsplot:::ggwithinstats(data = iris_long, 
                            x = condition, 
                            y = value, 
                            id.variable = id, 
                            effsize.type = "unbiased", 
                            pairwise.comparisons = TRUE, 
                            p.adjust.method = "bonferroni", 
                            bf.message = TRUE,
                            path.point = FALSE)
#> Note: 95% CI for effect size estimate was computed with 100 bootstrap samples.
#> 
#> # A tibble: 6 x 8
#>   group1 group2 mean.difference conf.low conf.high   p.value significance
#>   <chr>  <chr>            <dbl>    <dbl>     <dbl>     <dbl> <chr>       
#> 1 Petal… Petal…          -2.56     -2.88    -2.24  7.20e- 64 ***         
#> 2 Sepal… Petal…           2.09      1.77     2.40  1.08e- 49 ***         
#> 3 Sepal… Petal…          -0.701    -1.02    -0.383 1.78e-  4 ***         
#> 4 Sepal… Petal…           4.64      4.33     4.96  4.93e-148 ***         
#> 5 Sepal… Petal…           1.86      1.54     2.18  3.28e- 49 ***         
#> 6 Sepal… Sepal…          -2.79     -3.10    -2.47  1.11e- 72 ***         
#> # … with 1 more variable: p.value.label <chr>
#> Note: Shapiro-Wilk Normality Test for value : p-value = < 0.001
#> 
#> Note: Bartlett's test for homogeneity of variances for factor condition : p-value = < 0.001
#> 
```

![](https://i.imgur.com/bhdcbLZ.png)

<sup>Created on 2019-03-14 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
