### ISSUE TITLE
kendall's W inaccurate?

### ISSUE THREAD

**Issue by IndrajeetPatil** [IndrajeetPatil/ggstatsplot#195]
Currently, we are computing Kendall's _W_ using this formula. 
http://www.tss.awf.poznan.pl/files/3_Trends_Vol21_2014__no1_20.pdf
But the value we get seems to be inaccurate.

Here is an example with the beloved bugs dataset.
``` r
# setup
set.seed(123)
library(jmv)
library(ggstatsplot)
data("bugs", package = "jmv")

# converting to long format
data_bugs <- bugs %>%
  tibble::as_tibble(.) %>%
  tidyr::gather(., key, value, LDLF:HDHF)

# plot
ggstatsplot::ggwithinstats(data_bugs,
                           key,
                           value,
                           pairwise.comparisons = TRUE,
                           type = "np")
#> # A tibble: 6 x 6
#>   group1 group2 statistic  p.value significance p.value.label
#>   <chr>  <chr>      <dbl>    <dbl> <chr>        <chr>        
#> 1 LDLF   HDLF        3.23 4.13e- 3 **           p = 0.004    
#> 2 LDLF   LDHF        5.57 3.15e- 7 ***          p <= 0.001   
#> 3 LDLF   HDHF        8.01 2.22e-13 ***          p <= 0.001   
#> 4 HDLF   LDHF        2.34 3.04e- 2 *            p = 0.030    
#> 5 HDLF   HDHF        4.78 1.17e- 5 ***          p <= 0.001   
#> 6 LDHF   HDHF        2.44 3.04e- 2 *            p = 0.030    
#> Note: Shapiro-Wilk Normality Test for value : p-value = < 0.001
#> 
#> Note: Bartlett's test for homogeneity of variances for factor key : p-value = 0.112
#> 
```

![](https://i.imgur.com/BDlokPZ.png)

Here are results from JASP for comparison. Although details from _post hoc_ tests and the test statistic, parameters, and p-values line up, the effect size is wildly different. 

![image](https://user-images.githubusercontent.com/11330453/54797845-3c923e80-4c2c-11e9-8f60-788e48ca18e3.png)

Not sure if this is what they are using in the background, but `DescTools` agrees:
``` r
set.seed(123)
library(jmv)
data("bugs", package = "jmv")

DescTools::KendallW(x = as.matrix(dplyr::select(bugs, LDLF:HDHF)),
                    correct = TRUE)
#> [1] 0.6147828
```

**Comment by IndrajeetPatil** [comment]
This seems to be the essence of the function, but not sure how to compute CI now since this doesn't depend on chi-squared value.
``` r
# function
kendall_w <- function(x) {
  ratings <- as.matrix(na.omit(x))
  ns <- nrow(ratings)
  nr <- ncol(ratings)
  ratings.rank <- apply(ratings, 2, rank)
  Tj <- 0
  for (i in 1:nr) {
    rater <- table(ratings.rank[, i])
    ties <- rater[rater > 1]
    l <- as.numeric(ties)
    Tj <- Tj + sum(l^3 - l)
  }
  coeff <- (12 * var(apply(ratings.rank, 1, sum)) * (ns -
    1)) / (nr^2 * (ns^3 - ns) - nr * Tj)

  return(coeff)
}

# using the function
set.seed(123)
library(jmv)
data("bugs", package = "jmv")
kendall_w(dplyr::select(bugs, LDLF:HDHF))
#> [1] 0.6147828
```

**Comment by ibecav** [comment]
Not a lot of time to look at this and **none** to work on it but yes if you think DescTools::KendallW is the right answer based upon JASP versus the article then yes the good news is there's no checking built in to look for unique subject id's so you should be able to build a straight up boot object using this function and then compute a confidence interval.

Did you have a chance to think about the 2WayAnova issue?

**Comment by IndrajeetPatil** [comment]
By "the 2WayAnova issue", you mean supporting these designs in `ggstatsplot`? In new functions or in the existing functions (`ggbetweenstats` and `ggwithinstats`)?

This is not a priority for me right now. I want to finalize all existing functions (esp. `ggwithinstats`), release version `1.0.0` and change the lifecycle to `stable`. This is going to involve a massive refactoring of `ggcoefstats` function and I'll be working on that in the next few weeks.

Only then we can start thinking of adding support for more complicated designs.

**Comment by ibecav** [comment]
I'd recommend a separate function but that's not important right now.  

All I need to know for certain right now is whether you will allow it at some future point.  For my own needs I need to work on it extensively for the next couple of weeks.  I can do that with an eye on future inclusion (which requires a little more short term work for me with a long term pay-off) or forge ahead knowing I have only myself to please (less near term work).

I'll check in late next week.  Oblivious to all coding for the next week or so while I'm offsite elsewhere. Good luck.
