### ISSUE TITLE
ggwithinstats - notch not working

### ISSUE THREAD

**Issue by xmarti6** [IndrajeetPatil/ggstatsplot#210]
Hi, congrats for the package, I believe the "notch" option is not working in "ggwithinstats" to me. I don't know if this feature is in development stage yet:
```r
ggstatsplot::ggwithinstats(
  data = WRS2::WineTasting,
  x = Wine,
  y = Taste,
  sort = "descending", # ordering groups along the x-axis based on
  sort.fun = median, # values of `y` variable
  pairwise.comparisons = TRUE,
  pairwise.display = "s",
  pairwise.annotation = "p",
  title = "Wine tasting",
  caption = "Source: `WRS2` R package",
  ggtheme = ggthemes::theme_fivethirtyeight(),
  ggstatsplot.layer = FALSE,
  messages = FALSE,
**notch=T**
)
```

**Comment by IndrajeetPatil** [comment]
@ibecav Do you want to take this one?

**Comment by ibecav** [comment]
Hmmmmm, you didn't implement plot.type in ggwithinstats.  But simply adding back the functionality for notches in box plots was trivial.  PR follows all tests pass no change to doco or dependencies
