### ISSUE TITLE
Confidence Intervals and sign of the effect size (non-parametric ggwithinstats)

### ISSUE THREAD

**Issue by Pedr0M** [IndrajeetPatil/ggstatsplot#216]
Hi

Thank you very much for all the effort on the production of this very useful package.

I've been using the ggwithinstats function to compute the effect-size (r) for a non-parametric within-groups' comparisons. 

The calculation of the 95% CI (with bootstap) for some of the variables is higher than 1.

In addition, the r coefficient is always returning positive values, irrespectively of the values on the second condition are higher or lower than of those on the first condition.

![UOSAP4N6](https://user-images.githubusercontent.com/22108746/58091785-6df2a080-7bc2-11e9-81b2-ba2c32e84140.jpg)
![MNrQRbw-](https://user-images.githubusercontent.com/22108746/58091790-6f23cd80-7bc2-11e9-8ffb-dc5a207bbad3.jpg)

Best,
Pedro

**Comment by ibecav** [comment]
Hi Pedro,

Yes the boostrap method doesn't "know" that r is constrained between -1 and +1, at some point I guess we can look at some conditional logic to apply a constraint in the display.

We're currently reporting all effect sizes as a positive value since the sign is purely a function of the order of the grouping factors and we make no assumptions about their order.

**Comment by IndrajeetPatil** [comment]
All of this has been resolved with the release of a new version of `rcompanion` package.

- Effect sizes now reflect the direction of mean differences between groups.
- If you use `conf.type = "perc"` or `conf.type = "boot"`, the values will not go above or below the absolute value of 1.
- In addition to this, the documentation also reflects when the confidence intervals can or can't be used for inferential purposes.

**Comment by marcora** [comment]
Just started with ggstatsplot and effect sizes do not reflect the direction of mean differences between groups. Is it possible to specify the behavior one way or another?
