### ISSUE TITLE
README plots are perhaps a tad large

### ISSUE THREAD

**Issue by jonathon-love** [IndrajeetPatil/ggstatsplot#25]
are the plots in the README on CRAN, perhaps a bit large?:

https://youtu.be/FvFVk7QbNsA

:P

jonathon

**Comment by IndrajeetPatil** [comment]
@jonathon-love Holy cow! 

Thanks for bringing this to my attention. They look so good on GitHub; not completely sure what's going on with the CRAN version. Will have a look at this now.

**Comment by IndrajeetPatil** [comment]
This is fixed in the new release:
https://cran.r-project.org/web/packages/ggstatsplot/README.html

**Comment by jonathon-love** [comment]
cool. btw you should make this into a jamovi module. :)

**Comment by IndrajeetPatil** [comment]
@jonathon-love That would be great!! Thanks for considering this package.

I will wait a bit though. I want to add a lot more functionality, plots, and unit tests. After that, it will be ready for proper mass consumption ;)
