### ISSUE TITLE
gghistostats CI interpretation

### ISSUE THREAD

**Issue by rbratslaver** [IndrajeetPatil/ggstatsplot#283]
Hi - I have a pretty basic question: if I run `t.test(mtcars$mpg,mu=25)`, I get a 95% CI of
 `17.91768, 22.26357`.  This code for gghistostats reports the CI as `[-1.21, -.41]`. Could you help me understand how to interpret this properly and how it relates to the CI generated by `t.test`? Thanks.

`gghistostats(data=mtcars,
             x=mpg,
             test.value = 25,
             test.value.line = T)`

**Comment by IndrajeetPatil** [comment]
Maybe this vignette will help?
https://indrajeetpatil.github.io/ggstatsplot/articles/web_only/gghistostats.html#summary-of-tests

![image](https://user-images.githubusercontent.com/11330453/62510901-fe627980-b7de-11e9-9b5f-9bb724b2ba0a.png)

`stats::t.test` reports CI for mean, while `gghistostats` reports CI for the effect size measure.

**Comment by rbratslaver** [comment]
Got it, thanks for this clarification. How can I see the formula that's calculating the effect size CI behind the scenes?
