### ISSUE TITLE
It seems that dose response model derived using drc is not supported yet. 

### ISSUE THREAD

**Issue by zhenglei-gao** [IndrajeetPatil/ggstatsplot#302]
If running the piece of code below, I got an error just as shown in [here](https://indrajeetpatil.github.io/ggstatsplot/articles/web_only/ggcoefstats.html#dose-response-curves-drc). Looking at `broomExtra::tidy(mod)`, NULL was returned. 

```
# setup
set.seed(123)
library(drc)

# model
mod <- drc::drm(
  formula = dead / total ~ conc,
  curveid = type,
  weights = total,
  data = selenium,
  fct = LL.2(),
  type = "binomial"
)

# plot
ggstatsplot::ggcoefstats(
  x = mod,
  conf.level = 0.99,
  title = "Dose-Response Curves"
)
#> Error: All elements in the column `term` should be unique.
```

**Comment by IndrajeetPatil** [comment]
Make sure to use the development version of `broom` package and this should work:
https://github.com/tidymodels/broom/tree/master/R

Here is a working example now:
https://indrajeetpatil.github.io/ggstatsplot/articles/web_only/ggcoefstats.html#dose-response-curves-drc

![image](https://user-images.githubusercontent.com/11330453/64264792-29e99880-cf32-11e9-9a7b-538490c59884.png)

**Comment by zhenglei-gao** [comment]
Thanks! Did not know it is supported in the development version.

**Comment by IndrajeetPatil** [comment]
You will also need the development version of ggstatsplot.
