### ISSUE TITLE
Missing images in the documentation?

### ISSUE THREAD

**Issue by Jonas-Sch** [IndrajeetPatil/ggstatsplot#31]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

Hi Indrajeet Patil,

it seems as if the images of the documentation here oh GitHub went missing - they won't load (at least using firefox).

Best,
Jonas

```r
# insert reprex here
```

**Comment by IndrajeetPatil** [comment]
@Jonas-Sch If you are referring to the GitHub README document, then I can't reproduce this issue. Checked with Firefox and I can see all the images. Maybe it was a temporary glitch?

But if you are referring to the website dedicated to the package (https://indrajeetpatil.github.io/ggstatsplot/), then- yes, the README document images are indeed not getting displayed irrespective of the web browser used.
