### ISSUE TITLE
Use geom_line to connect samples with same specified ID

### ISSUE THREAD

**Issue by wipperman** [IndrajeetPatil/ggstatsplot#319]
Hello,

Thank you for the wonderful package. I have a simple question that would apply to most of the functions within the ggstatsplot package. Is there an easy way to connect dots from the same sample, by specifying specifically the column that contains the sample ID variable? With my own data, I have tried adding geom_line() after the ggwithinstats() argument, but this didn't seem to work. 

For example, I see in this example from the tutorial the dotted lines produced presumably between the 'subject' column header in the input table. Sometimes this header is called something else, so just allowing a user to specify the variable used to connect two (or more) points from the same "subject" would be a nice feature. Also, allowing for "missing" data, in the sense that it's often the case that some data is missing, so even if most subjects from two or more groups (i.e., several timepoints from a longitudinal study) are grouped and could be connected with a line, some datapoints from a particular subject might be missing. Perhaps this is a feature and I just can't find it, but I think it would be helpful to the overall use of the package. 

Thanks so much! 
Matt

```
# common setup
set.seed(123)

# getting data in tidy format
data_bugs <- ggstatsplot::bugs_long %>%
  dplyr::filter(.data = ., region %in% c("Europe", "North America"))

# plot
ggstatsplot::grouped_ggwithinstats(
  data = dplyr::filter(data_bugs, condition %in% c("LDLF", "LDHF")),
  x = condition,
  y = desire,
  xlab = "Condition",
  ylab = "Desire to kill an artrhopod",
  grouping.var = region,
  outlier.tagging = TRUE,
  outlier.label = education,
  ggtheme = hrbrthemes::theme_ipsum_tw(),
  ggstatsplot.layer = FALSE,
  messages = FALSE
)
```

**Comment by fmmattioni** [comment]
I would love to see that too!

**Comment by handrigg** [comment]
I agree, this feature would be useful.

**Comment by IndrajeetPatil** [comment]
Closing in favor of #483

Hopefully this will be implemented in the next scheduled release 🤞
