### ISSUE TITLE
Compatibility with skimr 2.0

### ISSUE THREAD

**Issue by fmmattioni** [IndrajeetPatil/ggstatsplot#323]
I am not quite sure the cause of this problem, but one of the recent commits of `rlang` caused `skimr` to break. If I try to:

`devtools::install_github("ropensci/skimr")`

I will get the following error:

```
> devtools::install_github("ropensci/skimr")
Downloading GitHub repo ropensci/skimr@master
✔  checking for file ‘/tmp/RtmpvwoCcq/remotes4f53add2705/ropensci-skimr-4a7a024/DESCRIPTION’ (415ms)
─  preparing ‘skimr’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘skimr_1.0.7.tar.gz’
   
Installing package into ‘/home/felipe/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package ‘skimr’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘skimr’:
 .onLoad failed in loadNamespace() for 'skimr', details:
  call: NULL
  error: Internal error: Expected call in `quo_invert()`
Error: loading failed
Execution halted
```
To solve this issue, I have installed `skimr 2.0` with:

`devtools::install_github("ropensci/skimr", ref = "v2")`

However, when I try to run `ggstatsplot::grouped_ggwithinstats()` I get the following error:

```
This package is currently not compatible with `skimr 2.0` package.
Error in groupedstats::grouped_summary(data = data, grouping.vars = { : 
```

<details><summary>Session Info</summary>
 setting  value                       
 version  R version 3.6.1 (2019-07-05)
 os       Ubuntu 19.04                
 system   x86_64, linux-gnu           
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       Europe/Berlin               
 date     2019-10-10                  

─ Packages ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 package             * version      date       lib source                                             
 abind                 1.4-5        2016-07-21 [3] CRAN (R 3.5.0)                                     
 assertthat            0.2.1        2019-03-21 [1] CRAN (R 3.6.0)                                     
 backports             1.1.5        2019-10-02 [1] CRAN (R 3.6.1)                                     
 base64enc             0.1-3        2015-07-28 [3] CRAN (R 3.5.0)                                     
 BayesFactor           0.9.12-4.2   2018-05-19 [1] CRAN (R 3.6.0)                                     
 bayestestR            0.3.3        2019-10-10 [1] Github (easystats/bayestestR@594a2e7)              
 boot                  1.3-22       2019-04-26 [1] CRAN (R 3.6.0)                                     
 bridgesampling        0.7-2        2019-07-21 [1] CRAN (R 3.6.1)                                     
 Brobdingnag           1.2-6        2018-08-13 [1] CRAN (R 3.6.1)                                     
 broom                 0.5.2        2019-04-07 [1] CRAN (R 3.6.0)                                     
 broom.mixed           0.2.4        2019-02-21 [1] CRAN (R 3.6.0)                                     
 broomExtra            0.0.5        2019-08-19 [1] CRAN (R 3.6.1)                                     
 callr                 3.3.2        2019-09-22 [1] CRAN (R 3.6.1)                                     
 car                   3.0-3        2019-05-27 [1] CRAN (R 3.6.0)                                     
 carData               3.0-2        2018-09-30 [1] CRAN (R 3.6.0)                                     
 cellranger            1.1.0        2016-07-27 [1] CRAN (R 3.6.0)                                     
 cli                   1.1.0        2019-03-19 [1] CRAN (R 3.6.0)                                     
 clipr                 0.7.0        2019-07-23 [1] CRAN (R 3.6.1)                                     
 cluster               2.1.0        2019-06-19 [4] CRAN (R 3.6.1)                                     
 coda                  0.19-3       2019-07-05 [1] CRAN (R 3.6.1)                                     
 codetools             0.2-16       2018-12-24 [4] CRAN (R 3.6.0)                                     
 coin                  1.3-1        2019-08-28 [1] CRAN (R 3.6.1)                                     
 colorspace            1.4-1        2019-03-18 [1] CRAN (R 3.6.0)                                     
 cowplot               1.0.0        2019-07-11 [1] CRAN (R 3.6.1)                                     
 crayon                1.3.4        2017-09-16 [3] CRAN (R 3.5.0)                                     
 curl                  4.2          2019-09-24 [1] CRAN (R 3.6.1)                                     
 data.table            1.12.4       2019-10-03 [1] CRAN (R 3.6.1)                                     
 DEoptimR              1.0-8        2016-11-19 [1] CRAN (R 3.6.0)                                     
 desc                  1.2.0        2018-05-01 [3] CRAN (R 3.5.0)                                     
 DescTools             0.99.29      2019-09-26 [1] CRAN (R 3.6.1)                                     
 devtools              2.2.1        2019-09-24 [1] CRAN (R 3.6.1)                                     
 digest                0.6.21       2019-09-20 [1] CRAN (R 3.6.1)                                     
 dplyr               * 0.8.3.9000   2019-10-10 [1] Github (tidyverse/dplyr@dcfc1d1)                   
 ellipsis              0.3.0        2019-09-20 [1] CRAN (R 3.6.1)                                     
 emmeans               1.4.1.009004 2019-10-08 [1] Github (rvlenth/emmeans@2852064)                   
 EMT                   1.1          2013-01-29 [1] CRAN (R 3.6.0)                                     
 estimability          1.3          2018-02-11 [1] CRAN (R 3.6.0)                                     
 expm                  0.999-4      2019-03-21 [1] CRAN (R 3.6.0)                                     
 ez                    4.4-0        2016-11-02 [1] CRAN (R 3.6.0)                                     
 fansi                 0.4.0        2018-10-05 [3] CRAN (R 3.5.1)                                     
 fit.models            0.5-14       2017-04-06 [1] CRAN (R 3.6.0)                                     
 forcats             * 0.4.0        2019-02-17 [1] CRAN (R 3.6.0)                                     
 foreign               0.8-72       2019-08-02 [4] CRAN (R 3.6.1)                                     
 fs                    1.3.1        2019-05-06 [1] CRAN (R 3.6.0)                                     
 furrr                 0.1.0        2018-05-16 [1] CRAN (R 3.6.1)                                     
 future                1.14.0       2019-07-02 [1] CRAN (R 3.6.0)                                     
 generics              0.0.2        2018-11-29 [1] CRAN (R 3.6.0)                                     
 ggcorrplot            0.1.3        2019-05-19 [1] CRAN (R 3.6.0)                                     
 ggExtra               0.9          2019-08-27 [1] CRAN (R 3.6.1)                                     
 ggplot2             * 3.2.1        2019-08-10 [1] CRAN (R 3.6.1)                                     
 ggrepel               0.8.1        2019-05-07 [1] CRAN (R 3.6.0)                                     
 ggsignif              0.6.0        2019-08-08 [1] CRAN (R 3.6.1)                                     
 ggstatsplot           0.1.2.9000   2019-10-08 [1] Github (IndrajeetPatil/ggstatsplot@499222d)        
 globals               0.12.4       2018-10-11 [1] CRAN (R 3.6.0)                                     
 glue                  1.3.1        2019-03-12 [1] CRAN (R 3.6.0)                                     
 gridExtra             2.3          2017-09-09 [1] CRAN (R 3.6.0)                                     
 groupedstats          0.0.9        2019-08-28 [1] CRAN (R 3.6.1)                                     
 gtable                0.3.0        2019-03-25 [1] CRAN (R 3.6.0)                                     
 gtools                3.8.1        2018-06-26 [1] CRAN (R 3.6.0)                                     
 haven                 2.1.1        2019-07-04 [1] CRAN (R 3.6.1)                                     
 hms                   0.5.1        2019-08-23 [1] CRAN (R 3.6.1)                                     
 htmltools             0.4.0        2019-10-04 [1] CRAN (R 3.6.1)                                     
 httpuv                1.5.2.9000   2019-10-06 [1] Github (rstudio/httpuv@57e1d71)                    
 httr                  1.4.1        2019-08-05 [1] CRAN (R 3.6.1)                                     
 inline                0.3.15       2018-05-18 [1] CRAN (R 3.6.1)                                     
 insight               0.5.0.9000   2019-10-06 [1] Github (easystats/insight@b806966)                 
 jmv                   0.9.6.1      2019-04-22 [1] CRAN (R 3.6.0)                                     
 jmvcore               1.0.0        2019-05-28 [1] CRAN (R 3.6.0)                                     
 jsonlite              1.6          2018-12-07 [3] CRAN (R 3.5.1)                                     
 knitr                 1.25         2019-09-18 [1] CRAN (R 3.6.1)                                     
 LaplacesDemon         16.1.1       2018-06-30 [1] CRAN (R 3.6.0)                                     
 later                 1.0.0        2019-10-04 [1] CRAN (R 3.6.1)                                     
 lattice               0.20-38      2018-11-04 [4] CRAN (R 3.6.0)                                     
 lazyeval              0.2.2        2019-03-15 [1] CRAN (R 3.6.0)                                     
 libcoin               1.0-5        2019-08-27 [1] CRAN (R 3.6.1)                                     
 lifecycle             0.1.0        2019-08-01 [1] CRAN (R 3.6.1)                                     
 listenv               0.7.0        2018-01-21 [1] CRAN (R 3.6.0)                                     
 lme4                  1.1-21       2019-03-05 [1] CRAN (R 3.6.0)                                     
 lmtest                0.9-37       2019-04-30 [1] CRAN (R 3.6.0)                                     
 logspline             2.1.14       2019-10-04 [1] CRAN (R 3.6.1)                                     
 loo                   2.1.0        2019-03-13 [1] CRAN (R 3.6.1)                                     
 lubridate             1.7.4        2018-04-11 [3] CRAN (R 3.5.1)                                     
 magrittr              1.5          2014-11-22 [3] CRAN (R 3.5.0)                                     
 MASS                  7.3-51.4     2019-04-26 [4] CRAN (R 3.6.1)                                     
 Matrix                1.2-17       2019-03-22 [4] CRAN (R 3.6.1)                                     
 MatrixModels          0.4-1        2015-08-22 [1] CRAN (R 3.6.0)                                     
 matrixStats           0.55.0       2019-09-07 [1] CRAN (R 3.6.1)                                     
 mc2d                  0.1-18       2017-03-06 [1] CRAN (R 3.6.0)                                     
 mcmc                  0.9-6        2019-03-10 [1] CRAN (R 3.6.0)                                     
 MCMCpack              1.4-4        2018-09-14 [1] CRAN (R 3.6.0)                                     
 memoise               1.1.0        2017-04-21 [3] CRAN (R 3.5.0)                                     
 metaBMA               0.6.2        2019-09-16 [1] CRAN (R 3.6.1)                                     
 metafor               2.1-0        2019-05-14 [1] CRAN (R 3.6.0)                                     
 mgcv                  1.8-29       2019-09-20 [4] CRAN (R 3.6.1)                                     
 mime                  0.7          2019-06-11 [1] CRAN (R 3.6.0)                                     
 miniUI                0.1.1.1      2018-05-18 [3] CRAN (R 3.5.0)                                     
 minpack.lm            1.2-1        2016-11-20 [1] CRAN (R 3.6.0)                                     
 minqa                 1.2.4        2014-10-09 [1] CRAN (R 3.6.0)                                     
 mnormt                1.5-5        2016-10-15 [1] CRAN (R 3.6.0)                                     
 modelr                0.1.5        2019-08-08 [1] CRAN (R 3.6.1)                                     
 modeltools            0.2-22       2018-07-16 [1] CRAN (R 3.6.0)                                     
 multcomp              1.4-10       2019-03-05 [1] CRAN (R 3.6.0)                                     
 multcompView          0.1-7        2015-07-31 [1] CRAN (R 3.6.0)                                     
 munsell               0.5.0        2018-06-12 [3] CRAN (R 3.5.0)                                     
 mvtnorm               1.0-11       2019-06-19 [1] CRAN (R 3.6.0)                                     
 nlme                  3.1-141      2019-08-01 [4] CRAN (R 3.6.1)                                     
 nloptr                1.2.1        2018-10-03 [1] CRAN (R 3.6.0)                                     
 nortest               1.0-4        2015-07-30 [1] CRAN (R 3.6.0)                                     
 openxlsx              4.1.0.1      2019-05-28 [1] CRAN (R 3.6.0)                                     
 packrat               0.5.0        2018-11-14 [1] CRAN (R 3.6.0)                                     
 pairwiseComparisons   0.1.1.9000   2019-10-06 [1] Github (IndrajeetPatil/pairwiseComparisons@7cf8e0e)
 paletteer             0.2.1        2019-02-13 [1] CRAN (R 3.6.0)                                     
 parameters            0.2.1        2019-10-10 [1] Github (easystats/parameters@34bd9bf)              
 pbapply               1.4-2        2019-08-31 [1] CRAN (R 3.6.1)                                     
 pcaPP                 1.9-73       2018-01-14 [1] CRAN (R 3.6.0)                                     
 performance           0.3.0.9000   2019-10-07 [1] Github (easystats/performance@fc1a19f)             
 pillar                1.4.2        2019-06-29 [1] CRAN (R 3.6.0)                                     
 pkgbuild              1.0.6        2019-10-09 [1] CRAN (R 3.6.1)                                     
 pkgconfig             2.0.3        2019-09-22 [1] CRAN (R 3.6.1)                                     
 pkgload               1.0.2        2018-10-29 [1] CRAN (R 3.6.0)                                     
 plyr                  1.8.4        2016-06-08 [3] CRAN (R 3.5.0)                                     
 prettyunits           1.0.2        2015-07-13 [3] CRAN (R 3.5.0)                                     
 processx              3.4.1        2019-07-18 [1] CRAN (R 3.6.1)                                     
 promises              1.1.0.9000   2019-10-06 [1] Github (rstudio/promises@8222809)                  
 ps                    1.3.0        2018-12-21 [1] CRAN (R 3.6.0)                                     
 psych                 1.8.12       2019-01-12 [1] CRAN (R 3.6.0)                                     
 purrr               * 0.3.2        2019-03-15 [1] CRAN (R 3.6.0)                                     
 quantreg              5.51         2019-08-07 [1] CRAN (R 3.6.1)                                     
 R6                    2.4.0        2019-02-14 [3] CRAN (R 3.5.2)                                     
 rap                   0.0.0.9001   2019-06-06 [1] Github (romainfrancois/rap@ff8d735)                
 rcompanion            2.3.7        2019-09-29 [1] CRAN (R 3.6.1)                                     
 Rcpp                  1.0.2        2019-07-25 [1] CRAN (R 3.6.1)                                     
 readr               * 1.3.1        2018-12-21 [1] CRAN (R 3.6.0)                                     
 readxl                1.3.1        2019-03-13 [1] CRAN (R 3.6.0)                                     
 remotes               2.1.0        2019-06-24 [1] CRAN (R 3.6.0)                                     
 repr                  1.0.1        2019-05-14 [1] CRAN (R 3.6.1)                                     
 reshape               0.8.8        2018-10-23 [1] CRAN (R 3.6.0)                                     
 reshape2              1.4.3        2017-12-11 [3] CRAN (R 3.5.0)                                     
 rio                   0.5.16       2018-11-26 [1] CRAN (R 3.6.0)                                     
 rjson                 0.2.20       2018-06-08 [1] CRAN (R 3.6.0)                                     
 rlang                 0.4.0.9004   2019-10-10 [1] Github (r-lib/rlang@a7d8177)                       
 robust                0.4-18.1     2019-07-02 [1] CRAN (R 3.6.0)                                     
 robustbase            0.93-5       2019-05-12 [1] CRAN (R 3.6.0)                                     
 rprojroot             1.3-2        2018-01-03 [3] CRAN (R 3.5.0)                                     
 rrcov                 1.4-7        2018-11-15 [1] CRAN (R 3.6.0)                                     
 rsample               0.0.5        2019-07-12 [1] CRAN (R 3.6.1)                                     
 rstan                 2.19.2       2019-07-09 [1] CRAN (R 3.6.1)                                     
 rstantools            2.0.0        2019-09-15 [1] CRAN (R 3.6.1)                                     
 rstudioapi            0.10.0-9002  2019-10-10 [1] Github (rstudio/rstudioapi@6e340b4)                
 rvest                 0.3.4        2019-05-15 [1] CRAN (R 3.6.0)                                     
 sandwich              2.5-1        2019-04-06 [1] CRAN (R 3.6.0)                                     
 scales                1.0.0        2018-08-09 [3] CRAN (R 3.5.1)                                     
 segmented             1.0-0        2019-06-17 [1] CRAN (R 3.6.0)                                     
 sessioninfo         * 1.1.1        2018-11-05 [1] CRAN (R 3.6.0)                                     
 shiny                 1.3.2        2019-04-22 [1] CRAN (R 3.6.0)                                     
 sjlabelled            1.1.1        2019-09-13 [1] CRAN (R 3.6.1)                                     
 sjmisc                2.8.2        2019-09-24 [1] CRAN (R 3.6.1)                                     
 sjstats               0.17.6       2019-09-08 [1] CRAN (R 3.6.1)                                     
 skimr                 2.0          2019-10-10 [1] Github (ropensci/skimr@a41b971)                    
 SparseM               1.77         2017-04-23 [1] CRAN (R 3.6.0)                                     
 StanHeaders           2.19.0       2019-09-07 [1] CRAN (R 3.6.1)                                     
 statsExpressions      0.1.1        2019-08-28 [1] CRAN (R 3.6.1)                                     
 stringi               1.4.3        2019-03-12 [1] CRAN (R 3.6.0)                                     
 stringr             * 1.4.0        2019-02-10 [3] CRAN (R 3.5.2)                                     
 survival              2.44-1.1     2019-04-01 [4] CRAN (R 3.6.1)                                     
 testthat              2.2.1        2019-07-25 [1] CRAN (R 3.6.1)                                     
 TH.data               1.0-10       2019-01-21 [1] CRAN (R 3.6.0)                                     
 tibble              * 2.1.3        2019-06-06 [1] CRAN (R 3.6.0)                                     
 tidyr               * 1.0.0        2019-09-11 [1] CRAN (R 3.6.1)                                     
 tidyselect            0.2.5        2018-10-11 [3] CRAN (R 3.5.1)                                     
 tidyverse           * 1.2.1        2017-11-14 [1] CRAN (R 3.6.0)                                     
 TMB                   1.7.15       2018-11-09 [1] CRAN (R 3.6.0)                                     
 usethis               1.5.1        2019-07-04 [1] CRAN (R 3.6.1)                                     
 utf8                  1.1.4        2018-05-24 [3] CRAN (R 3.5.0)                                     
 vctrs                 0.2.0.9005   2019-10-10 [1] Github (r-lib/vctrs@1a96680)                       
 withr                 2.1.2        2018-03-15 [3] CRAN (R 3.5.0)                                     
 WRS2                  1.0-0        2019-06-06 [1] CRAN (R 3.6.0)                                     
 xfun                  0.10         2019-10-01 [1] CRAN (R 3.6.1)                                     
 xml2                  1.2.2        2019-08-09 [1] CRAN (R 3.6.1)                                     
 xtable                1.8-4        2019-04-21 [1] CRAN (R 3.6.0)                                     
 zeallot               0.1.0        2018-01-28 [1] CRAN (R 3.6.0)                                     
 zip                   2.0.4        2019-09-01 [1] CRAN (R 3.6.1)                                     
 zoo                   1.8-6        2019-05-28 [1] CRAN (R 3.6.0)                                     
</details>

**Comment by IndrajeetPatil** [comment]
Yes, `ggstatsplot` currently doesn't work with the development version of `skimr`. For a while, I tried to keep it in sync with the changes being made to `skimr`, but got tired of it after a while. 

Your current options are-
Use CRAN version of `skimr`
or
set `mean.plotting = FALSE` when you use `ggbetweenstats` or `ggwithinstats` functions.

**Comment by fmmattioni** [comment]
Sounds good! Thank you!!
