### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by montenegrina** [IndrajeetPatil/ggstatsplot#326]
I was trying to install this package locally via:
module load compilers/r-3.6.1
R

```r
remotes::install_github( repo = "IndrajeetPatil/ggstatsplot", # package path on GitHub dependencies = TRUE, # installs packages which ggstatsplot depends on upgrade_dependencies = TRUE # updates any out of date dependencies )
```
and I got:
```r
─  building ‘ggstatsplot_0.1.2.9000.tar.gz’
   Warning: invalid uid value replaced by that for user 'nobody'
   Warning: invalid gid value replaced by that for user 'nobody'
   
Installing package into ‘/home/anamaria/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package ‘ggstatsplot’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace ‘purrr’ 0.3.2 is already loaded, but >= 0.3.3 is required
Calls: <Anonymous> ... namespaceImportFrom -> asNamespace -> loadNamespace
Execution halted
ERROR: lazy loading failed for package ‘ggstatsplot’
* removing ‘/home/anamaria/R/x86_64-pc-linux-gnu-library/3.6/ggstatsplot’
Error: Failed to install 'ggstatsplot' from GitHub:
  (converted from warning) installation of package ‘/tmp/RtmptgkZVs/file11a0c6dae3611/ggstatsplot_0.1.2.9000.tar.gz’ had non-zero exit status
```
Can you please advise, thanks!
Ana

**Comment by IndrajeetPatil** [comment]
You just need to update the `purrr` (https://cran.r-project.org/web/packages/purrr/index.html) version to `0.3.3` and this should work. 

```r
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace ‘purrr’ 0.3.2 is already loaded, but >= 0.3.3 is required
```

**Comment by montenegrina** [comment]
HI,

that worked! Thank you!

Can you please tell me which method was used to calculate this p value on
this plot I made with ggwithinstats()
I have non parametric data, so was this the right function for me?

Cheers,
Ana

**Comment by IndrajeetPatil** [comment]
Great. You can have a look at the vignette online to see which test was carried out:
https://indrajeetpatil.github.io/ggstatsplot/articles/web_only/ggwithinstats.html

![image](https://user-images.githubusercontent.com/11330453/67622608-03522a80-f81c-11e9-84da-4769c2389e54.png)

**Comment by montenegrina** [comment]
ok, yes I did read that but I am still unsure did I choose the right
function. So this is what I have:
in ALL Genes I have around 30000 entries with EQTL counts for all of those
in RG Genes I have 103 genes and their EQTL counts. Also these 103 genes
are the subgroup of All Genes.
Does this function make sense in that data I have?

**Comment by montenegrina** [comment]
if I do just regular wilcox.test(a$number_of_eqtles_per_gene, y =
b$number_of_eqtles_per_gene,paired = FALSE)
where my ALL genes are in "a" and RG genes are in "b"
> head(a)
            gene_id number_of_eqtles_per_gene
1 ENSG00000237683.5                         5
2 ENSG00000225972.1                       267
3 ENSG00000225630.1                        97

I am getting a very different p value than with your function:

Wilcoxon rank sum test with continuity correction

data:  a$number_of_eqtles_per_gene and b$number_of_eqtles_per_gene
W = 1371200, p-value = 0.007768
alternative hypothesis: true location shift is not equal to 0

with your function it is: 0.308 see attach

**Comment by IndrajeetPatil** [comment]
If you have a between-subjects Design (paired = False), you should Instead use gg betweenstats

**Comment by montenegrina** [comment]
let me please reiterate this again:
I have:
All Genes: with 30000 entries
RG Genes: with 103 entries
so yes they are different length and that is why I used in Wilcox paired=False

on another hand those 103 entries are in All Genes group as well.

So knowing that do you still think that gg betweenstats is the right
method for me to use here?

I am guessing you referred to this one:

# Mann-Whitney U test (nonparametric t) and violin plot
p2 <- ggstatsplot::ggbetweenstats(
  data = df_year,
  x = year,
  y = lifeExp,
  xlab = "Year",
  ylab = "Life expectancy",
  plot.type = "violin",
  type = "np",
  conf.level = 0.99,
  title = "Non-parametric Test (violin plot)",
  package = "ggsci",
  palette = "uniform_startrek",
  k = 2,
  messages = FALSE
)


I would like to include this in my manuscript

**Comment by montenegrina** [comment]
Hi,

sorry to bother you again, I did use this function to create attached plot.
ggstatsplot::ggbetweenstats(
Can you please tell me what would be interpretation of the plot given
my context:
in ALL Genes I have around 30000 entries with EQTL counts for all of those
in RG Genes I have 103 genes and their EQTL counts. Also these 103
genes are the subgroup of All Genes.

Thanks
Ana

**Comment by montenegrina** [comment]
Can you please get back to me about this? I would like to include this
in my manuscript

**Comment by montenegrina** [comment]
does this function ggbetweenstats takes pairing in account?
because one of my distributions has 103 elements and another one around 30000
