### ISSUE TITLE
`ggwithinstats` - change color and connecting path should start after the point

### ISSUE THREAD

**Issue by IndrajeetPatil** [IndrajeetPatil/ggstatsplot#334]
![image](https://user-images.githubusercontent.com/11330453/69238747-04674500-0b99-11ea-968f-c196a0b1cc4a.png)

**Comment by GegznaV** [comment]
The order of layers should be changed:

1) as you stated, lines should be behind dots.
2) and labels should be in front of lines and dots (indicated by violet arrow)

![image](https://user-images.githubusercontent.com/12725868/80101089-94128480-8579-11ea-9e10-10aa154eb489.png)

The code to reproduce the plot:
```r
# setup
set.seed(123)
library(ggstatsplot)

# two groups (*t*-test)
ggstatsplot::ggwithinstats(
  data = iris,
  x = Species,
  y = Petal.Length,
  var.equal = TRUE
)
```
