### ISSUE TITLE
Breaking changes to paletteer

### ISSUE THREAD

**Issue by EmilHvitfeldt** [IndrajeetPatil/ggstatsplot#340]
Hello @IndrajeetPatil! 

Wonderful package you have going here. [paletteer](https://github.com/EmilHvitfeldt/paletteer) is going through some last stages of development before a big release, planned to happen before December 17th.

The main difference for this package is that the under-interface has had an overhaul. 

Previously the structure was

```r
paletteer_c(package = "nord", palette = "frost")
```

where both package and palette could be strings or symbols, but now a palette is specified by

```r
paletteer_c(palette = "nord::frost")
```

where only strings are accepted. I can help you with the RP to fix the damages on your end but I see two different approaches to fix this problem.

1. change your user interface to just have palette argument where the user supplies "nord::frost".
2. Keep your user interface and paste the arguments together internally. + manually write roxygen for the arguments since they would be different than the paletteer package.

Let me know what you think and I'll get working on a PR.

**Comment by EmilHvitfeldt** [comment]
Hello @IndrajeetPatil,

any news on this issue? My offer still stands, just tell me how you want the issue fixed and I'll implement it :)

**Comment by IndrajeetPatil** [comment]
Dear @EmilHvitfeldt, Sincere apologies for not getting back sooner! 

I would really appreciate a PR with the second option since that will be backward-compatible.
