### ISSUE TITLE
[Feaure request] ggcorrmat return = "ci"

### ISSUE THREAD

**Issue by GegznaV** [IndrajeetPatil/ggstatsplot#342]
From the documentation of `ggcorrmat`:

```r
# getting the confidence intervals for correlations
ggstatsplot::ggcorrmat(
  data = ggplot2::msleep,
  cor.vars = sleep_total:bodywt,
  corr.method = "p", # parametric
  return = "ci", # confidence intervals
  p.adjust.method = "holm"
)
#> Note: In the correlation matrix,
#> the upper triangle: p-values adjusted for multiple comparisons
#> the lower triangle: unadjusted p-values.
#> # A tibble: 15 x 7
#>    pair                      r    lower    upper          p lower.adj  upper.adj
#>    <chr>                 <dbl>    <dbl>    <dbl>      <dbl>     <dbl>      <dbl>
#>  1 sleep_total-sleep_~  0.7518  0.6167   0.8438  2.916e- 12  0.5402     8.740e-1
#>  2 sleep_total-sleep_~ -0.4737 -0.7058  -0.1498  6.169e-  3 -0.7738     7.215e-5

# / output truncated/
```

There are my thoughts on how this could be improved:

1) What is the meaning of messages "Note: In the correlation matrix," and "the upper triangle: p-values adjusted for multiple comparisons". Where is the upper triangle in this output? Maybe the messages should be **removed/modified** for this type of output?
2) Is there a description, that do the columns  `lower`, `upper`,  `p`,  `lower.adj`,  `upper.adj` really mean? I expect this description in the `Values` (`#' @return`) part of the function so that I do not need to read all vignettes other parts of documentation when I do not have much time.
    a. Are all p values corrected or not in the output? Are just a fraction of them are corrected and others are not (as "the upper triangle: p-values adjusted for multiple comparisons")?
    b. How are the `lower.adj`,  `upper.adj` calculated? Could any references to the methods be included?
3) Can **both (regular) p values and adjusted p values** be included in the output table? It would give more clarity as well as it would be more convenient for the user.
4) Can an additional column with **sample sizes** be included? It would be a more convenient version of the output.

**Comment by IndrajeetPatil** [comment]
Yeah, sorry about that. The original intent behind `ggcorrmat` was only to display the plot; all the other outputs were kind of add-ons and so were never really paid enough attention. 

Here is what the output is going to look like for now:
``` r
ggstatsplot::ggcorrmat(
  data = ggplot2::msleep,
  cor.vars = sleep_total:bodywt,
  output = "ci"
)

#> # A tibble: 15 x 5
#>    pair                      lower      r   upper         p
#>    <chr>                     <dbl>  <dbl>   <dbl>     <dbl>
#>  1 sleep_total-sleep_rem    0.617   0.752  0.844  2.92e- 12
#>  2 sleep_total-sleep_cycle -0.706  -0.474 -0.150  6.17e-  3
#>  3 sleep_total-awake       -1.00   -1.00  -1.00   2.42e-226
#>  4 sleep_total-brainwt     -0.569  -0.360 -0.108  6.35e-  3
#>  5 sleep_total-bodywt      -0.494  -0.312 -0.103  4.09e-  3
#>  6 sleep_rem-sleep_cycle   -0.614  -0.338  0.0120 5.84e-  2
#>  7 sleep_rem-awake         -0.844  -0.752 -0.617  2.91e- 12
#>  8 sleep_rem-brainwt       -0.476  -0.221  0.0670 1.31e-  1
#>  9 sleep_rem-bodywt        -0.535  -0.328 -0.0826 9.95e-  3
#> 10 sleep_cycle-awake        0.150   0.474  0.706  6.17e-  3
#> 11 sleep_cycle-brainwt      0.709   0.852  0.927  2.42e-  9
#> 12 sleep_cycle-bodywt       0.0809  0.418  0.669  1.73e-  2
#> 13 awake-brainwt            0.108   0.360  0.569  6.35e-  3
#> 14 awake-bodywt             0.103   0.312  0.494  4.09e-  3
#> 15 brainwt-bodywt           0.889   0.934  0.961  9.16e- 26
```

To address your specific concerns:
1. That warning was not supposed to be displayed in this context. It's fixed now.
2. The `lower.adj` and `upper.adj`columns are no longer included because `psych::corr.test` itself has no documentation on what they correspond to. The other columns are rather straightforward to interpret. 
3. (see 4.)
4. The long-term goal is to rely on `correlation` [package](https://github.com/easystats/correlation) (once it makes to `CRAN`) and stop relying on `psych`. That package does return the details you are talking about.

**Comment by IndrajeetPatil** [comment]
Partially addressed in https://github.com/IndrajeetPatil/ggstatsplot/commit/270304b91e8883010f0e62cabe9662713b724ebc
