### ISSUE TITLE
displaying a different centrality measure depending on the `type` argument

### ISSUE THREAD

**Issue by IndrajeetPatil** [IndrajeetPatil/ggstatsplot#350]
For discussion, see https://github.com/IndrajeetPatil/ggstatsplot/issues/333#issuecomment-569938325

**Comment by chantelanuit** [comment]
Hello Indra,

What do you think would be the most relevant information to display on the plot when an inference about a trimmed mean is done ?

- the whole dataset
- the trimmed dataset
- the whole dataset, but with a display of the observations that are trimmed out in a different colour (to emphasize the observations that are set apart).
- other ?

I did not find a discussion about this in the literature (https://www.pnas.org/content/116/6/1857). That pertains to data visualization literacy.

Michael

“Most of us need to listen to the music to understand how beautiful it is. But often that’s how we present statistics: we just show the notes, we don’t play the music.”
— Hans Rosling (1948-2017)

**Comment by IndrajeetPatil** [comment]
Related request from another user:

> Given that the test methods are automatically detected: parametric vs nonparametric, I was just wondering if you could automate the mean_labeller to also have something like median_labeller since that will be more relevant in the case of nonparametric tests.

**Comment by IndrajeetPatil** [comment]
@chantelanuit I would display the whole dataset but the **label** would make it clear that the mean is based on trimmed dataset.

**Comment by IndrajeetPatil** [comment]
Brain dump:
- [ ] rename `mean.plotting` to something like `centrality.plotting`
- [ ] parametric -> mean (current implementation)
- [ ] non-paramrtric -> median
- [ ] robust -> trimmed mean
- [ ] Bayes -> MAP?

**Comment by IndrajeetPatil** [comment]
``` r
library(ggplot2)

d <- ggplot(mtcars, aes(cyl, mpg)) + geom_point(na.rm = TRUE)

d + stat_summary(fun = base::mean, colour = "red", size = 1)
#> Warning: Removed 3 rows containing missing values (geom_segment).
```

![](https://i.imgur.com/D5RbBQk.png)

``` r
d + stat_summary(fun = stats::median, colour = "red", size = 1)
#> Warning: Removed 3 rows containing missing values (geom_segment).
```

![](https://i.imgur.com/IZZS76D.png)

``` r
d + stat_summary(fun = WRS2::winmean, colour = "red", size = 1)
#> Warning: Removed 3 rows containing missing values (geom_segment).
```

![](https://i.imgur.com/8RzNYFZ.png)

``` r
d + stat_summary(fun = bayestestR::map_estimate, colour = "red", size = 1)
#> Warning: Removed 3 rows containing missing values (geom_segment).
```

![](https://i.imgur.com/tEcGiut.png)

<sup>Created on 2020-12-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by IndrajeetPatil** [comment]
Currently, all measures are supported in `parameters`-devel version:

```r
library(parameters)

standardize_names(as.data.frame(describe_distribution(iris$Sepal.Length, "mean")), "broom")
#>   estimate   std.dev iqr min max skewness  kurtosis   n n.missing
#> 1 5.843333 0.8280661 1.3 4.3 7.9 0.314911 -0.552064 150         0

standardize_names(as.data.frame(describe_distribution(iris$Sepal.Length, "median")), "broom")
#>   estimate     mad iqr min max skewness  kurtosis   n n.missing
#> 1      5.8 1.03782 1.3 4.3 7.9 0.314911 -0.552064 150         0

standardize_names(as.data.frame(describe_distribution(iris$Sepal.Length, "trimmed", threshold = 0.1)), "broom")
#>   trimmed.mean   std.dev iqr min max skewness  kurtosis   n n.missing
#> 1     5.808333 0.8280661 1.3 4.3 7.9 0.314911 -0.552064 150         0

standardize_names(as.data.frame(describe_distribution(iris$Sepal.Length, "MAP")), "broom")
#>   estimate iqr min max skewness  kurtosis   n n.missing
#> 1 5.746334 1.3 4.3 7.9 0.314911 -0.552064 150         0
```
