### ISSUE TITLE
Feature request: Interaction plots

### ISSUE THREAD

**Issue by steenharsted** [IndrajeetPatil/ggstatsplot#362]
Hi,
I am a big fan of ggstatsplots! I wish however that there was a function to visualize the effect of interaction terms from regression models.

Thank you for ggstatsplot

**Comment by IndrajeetPatil** [comment]
I would highly recommend that you check out `interactions`: https://interactions.jacob-long.com/

Currently, there are no plans to add support for interactions in `ggstatsplot` because there is already a package that does an excellent job of visualizing these.
