### ISSUE TITLE
ggbarstats p-value

### ISSUE THREAD

**Issue by sbalci** [IndrajeetPatil/ggstatsplot#383]
Hi,

I would like to ask a question. In the ggbarstats output table there are p-values. But I assume they do not represent the Chi-square test p-value. Would you please inform me what they refer to.

p.value
2.25e-33 
3.64e-47

Reprex below

Best regards

``` r
mydata <- tibble::tribble(
~Operation,          ~Diagnosis,   ~n,
  "Type1",         "A",   58L,
  "Type2",         "A",  349L,
  "Type1", "B",   52L,
  "Type2", "B",  267L
  )


ggstatsplot::ggbarstats(data = mydata, Operation, Diagnosis, counts = n)
#> Registered S3 methods overwritten by 'broom.mixed':
#>   method         from 
#>   augment.lme    broom
#>   augment.merMod broom
#>   glance.lme     broom
#>   glance.merMod  broom
#>   glance.stanreg broom
#>   tidy.brmsfit   broom
#>   tidy.gamlss    broom
#>   tidy.lme       broom
#>   tidy.merMod    broom
#>   tidy.rjags     broom
#>   tidy.stanfit   broom
#>   tidy.stanreg   broom
#> Registered S3 methods overwritten by 'car':
#>   method                          from
#>   influence.merMod                lme4
#>   cooks.distance.influence.merMod lme4
#>   dfbeta.influence.merMod         lme4
#>   dfbetas.influence.merMod        lme4
#> Note: 95% CI for effect size estimate was computed with 100 bootstrap samples.
#> 
#> # A tibble: 2 x 11
#>   Diagnosis counts  perc N     Type1 Type2 statistic  p.value parameter method
#>   <fct>      <int> <dbl> <chr> <chr> <chr>     <dbl>    <dbl>     <dbl> <chr> 
#> 1 B            319  43.9 (n =… 16.3… 83.7…      145. 2.25e-33         1 Chi-s…
#> 2 A            407  56.1 (n =… 14.2… 85.7…      208. 3.64e-47         1 Chi-s…
#> # … with 1 more variable: significance <chr>
```

![](https://i.imgur.com/r3oIlcW.png)

<sup>Created on 2020-02-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by IndrajeetPatil** [comment]
Those are _p_-values from one-sample goodness of fit tests (or proportion tests). The asterisks above bars `***` correspond to those _p_-values.

![Screenshot 2020-02-27 08 26 10](https://user-images.githubusercontent.com/11330453/75421578-dd0fd900-593a-11ea-8e8c-d1e98891b4f8.png)

You can also have a look at this presentation, although it is not up-to-date:
https://indrajeetpatil.github.io/ggstatsplot_slides/slides/ggstatsplot_presentation.html#76
