### ISSUE TITLE
Does v0.3.0 ggcorrmat deprecate the "insig = 'blank'"? 

### ISSUE THREAD

**Issue by icupsy** [IndrajeetPatil/ggstatsplot#389]

**Comment by IndrajeetPatil** [comment]
Yes, the syntax for `ggstatsplot` functions has changed significantly for this release.

For reasons, see here: https://indrajeetpatil.github.io/ggstatsplot/news/index.html#ggstatsplot-030

Now you can do something like the following:

``` r
library(ggstatsplot)

ggcorrmat(
  ggplot2::msleep,
  ggcorrplot.args = list(outline.color = "black", insig = 'blank')
)
```

![](https://i.imgur.com/b2BO2p1.png)

<sup>Created on 2020-03-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by icupsy** [comment]
Great! Thanks!
