### ISSUE TITLE
color control

### ISSUE THREAD

**Issue by devonorourke** [IndrajeetPatil/ggstatsplot#39]
Terrific package. 
I'm using `ggstatsplot::ggbetweenstats` and couldn't find any function that might control for the fill color of the points that are created in the violin plot that is produced.
Similar to how you have `xfill` and `yfill` arguments for the `ggscatterstats` script, is there an option within `ggbetweenstats` that could function where you pass in a vector of colors associated with each group?
I'd like to use a 2 hue, 2 color system where light/dark represents one variable, and the other color (say yellow/purple) represents a different variable. 
In your [between stats](https://indrajeetpatil.github.io/ggstatsplot/articles/combine_plots.html) example combining plots, I can get half way there because the same scheme is used for each subplot, but I don't want to split my 4 groups apart. 

Here's the plot I have so far:

![image](https://user-images.githubusercontent.com/11182172/44993469-b56bca80-af68-11e8-89dd-ae0568736163.png)

What I'd like is to have something that allows me to substitute those four colors with the four hex-code specified colors I want, which would ultimately produce something where the first two groups are yellow (light yellow, dark yellow) and the last two groups are purple (light purple, dark purple).

Apologies if this already exists and I can't find it in the function descriptions!

Thanks

**Comment by IndrajeetPatil** [comment]
You can do this using `scale_color_manual` function from `ggplot2`.

**Example-1**

``` r
ggstatsplot::ggbetweenstats(data = iris, x = Species, y = Sepal.Length) +
  ggplot2::scale_color_manual(values = c("#999999", "#E69F00", "#56B4E9"))
#> Note: 95% CI for partial omega-squared was computed with 100 bootstrap samples.
#> 
#> Note:  Shapiro-Wilk Normality Test for Sepal.Length : p-value =  0.010
#> 
#> Note:  Bartlett's test for homogeneity of variances for factor Species : p-value =  < 0.001
#> 
#> Scale for 'colour' is already present. Adding another scale for
#> 'colour', which will replace the existing scale.
```

![](https://i.imgur.com/TcHX4tl.png)

**Example-2**

``` r
ggstatsplot::ggbetweenstats(data = mtcars, x = am, y = wt) +
  ggplot2::scale_color_manual(values = c("#0072B2", "#CC79A7"))
#> Note:  Shapiro-Wilk Normality Test for wt : p-value =  0.093
#> 
#> Note:  Bartlett's test for homogeneity of variances for factor am : p-value =  0.398
#> 
#> Scale for 'colour' is already present. Adding another scale for
#> 'colour', which will replace the existing scale.
```

![](https://i.imgur.com/3P8NMev.png)

Additionally, the next release of `ggstatsplot` will give all functions two new arguments (`palette` and `package`) to choose any palette you want from the existing palette packages. For example,

``` r
ggstatsplot::ggbetweenstats(
  data = iris,
  x = Species,
  y = Sepal.Length,
  package = "wesanderson",
  palette = "Royal1"
)
#> Note: 95% CI for partial omega-squared was computed with 100 bootstrap samples.
#> 
#> Note:  Shapiro-Wilk Normality Test for Sepal.Length : p-value =  0.010
#> 
#> Note:  Bartlett's test for homogeneity of variances for factor Species : p-value =  < 0.001
#> 
```

![](https://i.imgur.com/VtkJe89.png)

**Comment by devonorourke** [comment]
Thanks very much for the detailed response.
Curiously, your second example with `mtcars` works just fine, yet the moment your first example returns this:
```
> ggstatsplot::ggbetweenstats(data = iris, x = Species, y = Sepal.Length) +
+   ggplot2::scale_color_manual(values = c("#999999", "#E69F00", "#56B4E9"))
Reference:  Welch's ANOVA is used as a default. (Delacre, Leys, Mora, & Lakens, PsyArXiv, 2018).
Note:  Shapiro-Wilk Normality Test for Sepal.Length : p-value =  0.010
Note:  Bartlett's test for homogeneity of variances for factor Species : p-value =  < 0.001
Scale for 'colour' is already present. Adding another scale for 'colour', which will replace the
existing scale.
Error in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y,  : 
  polygon edge not found
```

I'm interested in the error because I get the same one with my dataset.
```
ggstatsplot::ggbetweenstats(data = allImiss, x=group, y=rateMiss) +
  ggplot2::scale_fill_manual(values = c("#9ecae1", "#3182bd", "#addd8e", "#31a354"))
```

As a sanity check:
```
> class(allImiss$group)
[1] "character"
> class(allImiss$rateMiss)
[1] "numeric"
```

Apologies if I'm missing something really obvious here.

**Comment by devonorourke** [comment]
Appreciate all the help.

I did the install once more. I put together this little example:
```
set.seed(10)
group1 <- data.frame(runif(10,1,100))
colnames(group1) <- "value"
group1$group <- "group1"

group2 <- data.frame(runif(10,1,100))
colnames(group2) <- "value"
group2$group <- "group2"

group3 <- data.frame(runif(10,1,100))
colnames(group3) <- "value"
group3$group <- "group3"

group4 <- data.frame(runif(10,1,100))
colnames(group4) <- "value"
group4$group <- "group4"

df <- rbind(group1, group2, group3, group4)

ggstatsplot::ggbetweenstats(data = df, x = group, y = value) +
  ggplot2::scale_color_manual(values = c("red", "blue", "green", "brown"))
```

Of course, this works just fine, haha!
Still unclear why my own data set isn't working, but it's clearly something about how the data is organized. I'll keep digging.

Thanks again for your help (and a wonderful R package).
