### ISSUE TITLE
Feature Request: Specification Curves

### ISSUE THREAD

**Issue by DeFilippis** [IndrajeetPatil/ggstatsplot#390]
Would be very nice to have an aesthetically-pleasing specification curve in `ggstatsplot` a la [Simonsohn (2015)](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2694998).  

Some implementations of it can be found here:
1. https://dcosme.github.io/2019/06/28/specification-curve-analysis-sca-tutorial/
2. http://philippmasur.de/blog/2020/01/02/how-to-do-specification-curve-analyses-in-r-introducing-specr/
3. https://econometria.wordpress.com/2019/12/10/from-one-regression-to-hundreds-within-seconds-a-shiny-specification-curve-r-bloggers/

**Comment by IndrajeetPatil** [comment]
This package (on `CRAN`) is pretty comprehensive when it comes to specification curves, and I am not sure if I can add anything more to it via `ggstatsplot`:  https://masurp.github.io/specr/

Please reopen the issue if you think `ggstatsplot` can shimmy over this package and add some stats details that might typically be useful.
