### ISSUE TITLE
Feature Idea: Alluvial Diagrams for McNemar instead of bar graphs

### ISSUE THREAD

**Issue by sbalci** [IndrajeetPatil/ggstatsplot#394]
**Describe the solution you'd like**
Alluvial Diagrams for McNemar instead of bar graphs.
I use repeated measures of categorical variables in my research. A marker positive in tumor may be positive or negative in metastasis. In alluvial diagrams I like to see the change as a flow. I think it is visually more informative.  

**How could we do it?**
similarly `alluvial`, `ggalluvial` packages

**Comment by IndrajeetPatil** [comment]
Closing in favor of #500
