### ISSUE TITLE
Factor Re-leveling supported?

### ISSUE THREAD

**Issue by rbratslaver** [IndrajeetPatil/ggstatsplot#40]
Hi - thank you so much for this package, it's my absolute favorite thing. I'm not sure if this is an issue so I apologize if I'm posting in the wrong place, but I was wondering if there's a way to re-order levels so that each grouping would be sorted in the same order; see below - is it possible to re-sort the 'Sepal.Width' grouping in ascending order so it looks like the other groups or is each group sorted independently by design? Thank you! 

![image](https://user-images.githubusercontent.com/32785182/45249201-fa398d80-b2e9-11e8-8faf-3b5b795f8b8f.png)

```
melt <- melt(iris)

grouped_ggbetweenstats(melt, Species, value, grouping.var = variable, messages = F )
```

**Comment by IndrajeetPatil** [comment]
As I show in this vignette (https://cran.r-project.org/web/packages/ggstatsplot/vignettes/ggbetweenstats.html), if you want to customize plots from `grouped_` variants of all functions, you will instead have to use the `purrr` package. 

Here is how you can get what you need-

``` r
# loading needed libraries
library(tidyverse)

# converting to long format
melt <- reshape2::melt(iris) %>%
  tibble::as.tibble(.)
#> Using Species as id variables

# changing the factor levels based on means
iris.list <- melt %>% # create a list
  base::split(x = .,
              f = .$variable,
              drop = TRUE) %>% # run operation for each element of the list
  purrr::map(
    .x = .,
    .f = ~ dplyr::mutate(
      .data = .,
      Species = forcats::fct_reorder(.f = Species, .x = value, .fun = mean)
    )
  )

# creating a list of plots
plot_list <- purrr::pmap(
  .l = list(
    data = iris.list,
    x = "Species",
    y = "value",
    messages = FALSE
  ),
  .f = ggstatsplot::ggbetweenstats
)

# combining the list of plots
ggstatsplot::combine_plots(plotlist = plot_list)
```

![](https://i.imgur.com/VQzQFsM.png)

**Comment by rbratslaver** [comment]
Got it, thank you!. One follow up question - is there an option to
suppress/hide the results of the statistical tests? I love the design of
the visuals though have
found that some audiences would be better off not seeing the statistics
altogether. Thanks again.

**Comment by IndrajeetPatil** [comment]
Sure, here is the modified answer-

``` r
# loading needed libraries
library(tidyverse)

# converting to long format
melt <- reshape2::melt(iris) %>%
  tibble::as.tibble(.)
#> Using Species as id variables
# > Using Species as id variables

# changing the factor levels based on means
iris.list <- melt %>% # create a list
  base::split(
    x = .,
    f = .$variable,
    drop = TRUE
  ) %>% # run operation for each element of the list
  purrr::map(
    .x = .,
    .f = ~dplyr::mutate(
      .data = .,
      Species = forcats::fct_reorder(.f = Species, .x = value, .fun = mean)
    )
  )

# creating a list of plots
plot_list <- purrr::pmap(
  .l = list(
    data = iris.list,
    x = "Species",
    y = "value",
    messages = FALSE
  ),
  .f = ggstatsplot::ggbetweenstats
) %>% # removing subtitles
  purrr::map(
    .x = .,
    .f = ~.x + ggplot2::labs(subtitle = NULL)
  )

# combining the list of plots
ggstatsplot::combine_plots(plotlist = plot_list)
```

![](https://i.imgur.com/QtkUnJV.png)

Created on 2018-09-08 by the [reprex package](https://reprex.tidyverse.org) (v0.2.0.9000).
