### ISSUE TITLE
Warning in install.packages :   installation of package 'ggstatsplot' had non-zero exit status

### ISSUE THREAD

**Issue by Pamei** [IndrajeetPatil/ggstatsplot#402]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

Unable to install 'ggstatsplot' despite repeated attempts 
Brief description of the problem

```r
# insert reprex here
```
installing the source package 'ggstatsplot'

trying URL 'https://cran.rstudio.com/src/contrib/ggstatsplot_0.3.1.tar.gz'
Content type 'application/x-gzip' length 2998784 bytes (2.9 MB)
==================================================
downloaded 2.9 MB

During startup - Warning messages:
1: Setting LC_CTYPE failed, using "C" 
2: Setting LC_TIME failed, using "C" 
3: Setting LC_MESSAGES failed, using "C" 
4: Setting LC_MONETARY failed, using "C" 
* installing *source* package 'ggstatsplot' ...
** package 'ggstatsplot' successfully unpacked and MD5 sums checked
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace 'ggplot2' 3.2.1 is being loaded, but >= 3.3.0 is required
ERROR: lazy loading failed for package 'ggstatsplot'
* removing '/Users/gairanpamei/Library/R/3.5/library/ggstatsplot'
Warning in install.packages :
  installation of package 'ggstatsplot' had non-zero exit status

**Comment by IndrajeetPatil** [comment]
This the source of the problem.
```r
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) :
namespace 'ggplot2' 3.2.1 is being loaded, but >= 3.3.0 is required
```

Please update `ggplot2` to `3.3.0` (current version on CRAN) and then this should work fine.

**Comment by Pamei** [comment]
Thank you, Indrajeet.
