### ISSUE TITLE
Possible to display the statistical test results of ggstatsplot in plotly?

### ISSUE THREAD

**Issue by cheriewpq** [IndrajeetPatil/ggstatsplot#403]
Saw this example of converting ggstatsplot to a plotly object (https://indrajeetpatil.github.io/ggstatsplot/articles/web_only/faq.html), would it be possible to display the statistical test results after converting to a plotly object?

**Comment by IndrajeetPatil** [comment]
This is not a `ggstatsplot` issue but rather `ggplot2` issue.

Note that you don't get the subtitle in `ggplot2` plots as well:

```r
# for reproducibility
set.seed(123)
library(ggplot2)
library(plotly)

# creating ggplot object with ggplot2
p <- ggplot(mtcars, aes(wt, mpg)) + geom_point() +
  labs(subtitle = "this subtitle doesn't appear in plotly")

# converting to plotly object
plotly::ggplotly(p, width = 480, height = 480)
```

![image](https://user-images.githubusercontent.com/11330453/77585283-84554100-6ee4-11ea-8cfa-e7e85be0fdd1.png)
