### ISSUE TITLE
ggbarstats error

### ISSUE THREAD

**Issue by benjaminwnelson** [IndrajeetPatil/ggstatsplot#408]
Thank you for making such a great package!

I was able to use the, ggpiestats function, but I got this error when using the ggbarstats function using the same data. Any ideas?

```r
Error in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : polygon edge not found
```

**Comment by IndrajeetPatil** [comment]
This is actually not related to `ggbarstats`, or even `ggstatsplot`, but rather with RStudio. 

Have a look at this: 
https://stackoverflow.com/questions/10581440/error-in-grid-calll-textbounds-as-graphicsannotxlabel-xx-xy-polygon
