### ISSUE TITLE
Correlation coefficients/p-values text size

### ISSUE THREAD

**Issue by lucavd** [IndrajeetPatil/ggstatsplot#419]
For large correlation matrix, it would be helpful to make the text reporting coefficients smaller (if needed)

![Rplot](https://user-images.githubusercontent.com/7904152/80291386-55352800-874d-11ea-8c2e-e2d46ee62987.png)

**Comment by IndrajeetPatil** [comment]
You can use the `ggcorrplot.args` argument to specify `lab_size` (https://rdrr.io/cran/ggcorrplot/man/ggcorrplot.html)

![image](https://user-images.githubusercontent.com/11330453/80300286-96542900-879b-11ea-9485-42ea2c47e492.png)

Another option is to save the plot with larger values for `width` and `height` when you save the plot with `ggplot2::ggsave()`.

**Comment by lucavd** [comment]
Thank you for the reply and thank you for your wonderful package (I recommended it to all of my colleagues at the University of Padova, Italy)

**Comment by rb643** [comment]
Is there a similar way to leave text in the cells out altogether?

**Comment by IndrajeetPatil** [comment]
@rb643 Here is a workaround.

``` r
library(ggstatsplot)
p <- ggcorrmat(iris)

# removing labels
p <- gginnards::delete_layers(p, "GeomText")

# removing crosses
gginnards::delete_layers(p, "GeomPoint")
```

![](https://i.imgur.com/IVaAwzJ.png)

But if you want to not display correlation coefficients, you can just use `ggcorrplot::ggcorrplot` function.
