### ISSUE TITLE
Bug in gghistostats

### ISSUE THREAD

**Issue by ibecav** [IndrajeetPatil/ggstatsplot#42]
Hi,

Love this package.  Forked to learn and study more.  Encountered a bug in gghistostats that generates:

Error in as.list.environment(x, all.names = TRUE) : 
  object 'len' not found 

For what should be identical behavior between non dataframe format.  I tried on both the CRAN and GitHub versions of the code.  I'll put some sleuthing into it but I only just started looking at your code which is quite complex.

Thank you.  Chuck
---

```r
# insert reprex here
library(ggstatsplot)
# Minimum reproducible example
gghistostats(
  x = ToothGrowth$len,
  xlab = "Tooth length",
  bar.measure = "mix"
)
gghistostats(
  data = ToothGrowth,
  x = len, 
  xlab = "Tooth length",
  bar.measure = "mix"
)
gghistostats(
  data = ToothGrowth,
  x = len, 
  xlab = "Tooth length"
)

```

**Comment by IndrajeetPatil** [comment]
@ibecav Thanks.

To use `bar.measure = "mix"` option, you will need to get the development version of `ggplot2` from GitHub 

```
devtools::install_github(repo = "tidyverse/ggplot2", dependencies = FALSE)
```

And then try again. Lemme know if it still doesn't work.

**Comment by ibecav** [comment]
Thank you that solved it.
