### ISSUE TITLE
user question: how to increase all font sizes for output plots

### ISSUE THREAD

**Issue by IndrajeetPatil** [IndrajeetPatil/ggstatsplot#424]
The output objects from this package are `ggplot`, so they can be modified using functions from `ggplot2`:

``` r
library(ggstatsplot)
library(ggplot2)

ggbarstats(mtcars, am, cyl, messages = FALSE) + 
  theme(text = element_text(size = 20),
        plot.subtitle = element_text(size = 15),
        legend.title = element_text(size = 20),
        legend.text = element_text(size = 20)) 
#> Warning in stats::chisq.test(x = x_arg, correct = FALSE): Chi-squared
#> approximation may be incorrect
#> Warning in stats::chisq.test(xtab): Chi-squared approximation may be incorrect
```

![](https://i.imgur.com/y7mraNW.png)

<sup>Created on 2020-05-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by Lillyakasiken** [comment]
But how to change the size of (n = 11) in above example?

**Comment by ran525** [comment]
I also would like to ask how to change the size of (n=1 and 27%) these lables ?

I tried mant methods, did not work
