### ISSUE TITLE
remove percentage label from bar chart

### ISSUE THREAD

**Issue by PeterGilles** [IndrajeetPatil/ggstatsplot#427]
As bar charts may become crowded, is it possible to remove the label inside of each bar segment indicating the percentage?
![image](https://user-images.githubusercontent.com/3244485/81502737-07d5c080-92e0-11ea-8123-90719796a1ad.png)

**Comment by IndrajeetPatil** [comment]
I am hesitant to add argument to remove labels. But this is something you can easily do outside of `ggstatsplot`:

``` r
library(gginnards)
library(ggstatsplot)

p <- ggbarstats(mtcars, am, cyl, messages = FALSE, results.subtitle = FALSE)

delete_layers(p, "GeomLabel")
```

![](https://i.imgur.com/wQBgKmv.png)

<sup>Created on 2020-05-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by asierFernandezP** [comment]
Hi! About this issue, is it possible to remove or hide only the labels or 1 of the 2 levels (1 or 0)?
