### ISSUE TITLE
Mean Label Overlaps Data Points By Default

### ISSUE THREAD

**Issue by DarioS** [IndrajeetPatil/ggstatsplot#429]
Looking at the various examples, the position of the mean label overlaps the box outline and some dots. There is also a lot of white space between adjacent box plots. Could the placement of the mean label by default be in the blank area next to the box, so that all of the data points and box boundary lines are visible? I suppose it's possible to get the desired result by trial and error change of `mean.point.args` but I wonder if it could be better by default.

**Comment by IndrajeetPatil** [comment]
Note to self: Maybe use the curved segment feature introduced in `ggrepel 0.9.0`?
https://ggrepel.slowkow.com/articles/examples.html#make-curved-line-segments-or-arrows-1

![Uploading image.png…]()

**Comment by IndrajeetPatil** [comment]
Relevant change:

```r
  # attach the labels with means to the plot
  plot <- plot +
    rlang::exec(
      .fn = ggrepel::geom_label_repel,
      data = mean_df,
      mapping = ggplot2::aes(x = {{ x }}, y = {{ y }}, label = label),
      show.legend = FALSE,
      min.segment.length = 0,
      inherit.aes = FALSE,
      parse = TRUE,
      na.rm = TRUE,
      nudge_x = .25,
      box.padding = 0.5,
      nudge_y = 1,
      segment.curvature = -0.4,
      segment.ncp = 3,
      segment.angle = 30,
      !!!mean.label.args
    )
```
