### ISSUE TITLE
Accommodate survey weights 

### ISSUE THREAD

**Issue by 55Mitch** [IndrajeetPatil/ggstatsplot#430]
Would is be possible to allow for survey weights in ggbetweenstats and other non-model ggstatsplot procedures?  I see it is possible in model reporting by using the R survey package.

**Comment by IndrajeetPatil** [comment]
Can you please post an example where this kind of analysis is relevant or useful? 
I am personally not well-informed about this.

**Comment by 55Mitch** [comment]
Weighting procedures are used to generalize results from a survey to populations of theoretical and substantive interest.  There are two common approaches, design weights, and post-stratification weights.  Design weights are used to compensate for over- or under-sampling of specific cases or for disproportionate stratification in sample design.  Samples that are underrepresented and/or overrepresented based on demographic subgroups can introduce bias that distorts both the accuracy and the inferences made about the results.  Poststratification weights offer a valuable technique for correcting bias from overrepresented and underrepresented samples. The method can also help discern the degree to which bias exists by comparing weighted versus unweighted results. The definitive guide for R, particularly in the case of complex samples is Lumley, Thomas S. Complex Surveys: a Guide to Analysis Using R. John Wiley &amp; Sons Inc, 2016.
