### ISSUE TITLE
Subtitle adjustment

### ISSUE THREAD

**Issue by dax44** [IndrajeetPatil/ggstatsplot#438]
Is any possibility to adjust the subtitle of ggstatsplot functions. As I know we cannot choose which parts of caption will be plotted. Tell me if I wrong.

**Comment by IndrajeetPatil** [comment]
No, it's not possible to adjust the contents of the subtitle expressions. These are auto-generated in a specified template and prepared by the following function:
https://indrajeetpatil.github.io/statsExpressions/reference/expr_template.html

**Comment by dax44** [comment]
It's a shame, because in grouped_gg... plots some texts are cutted off :(

**Comment by IndrajeetPatil** [comment]
You can always save the plot with higher `width` and `height` using `ggplot2::ggsave` call so that they are not cut off.
