### ISSUE TITLE
Preparing for 0.0.6 release

### ISSUE THREAD

**Issue by IndrajeetPatil** [IndrajeetPatil/ggstatsplot#44]
To do:

- [ ] Check font size for `theme_ggstatsplot` function and if you wanna change it
- [ ] Clean up Rmd using `gramr` package 
- [x] Change `merMod` tidiers as soon as `broom.mixed` is on `CRAN`.
- [x] Attempt to reduce size of vignettes to prevent `R CMD CRAN` from producing a `NOTE`.
- [ ] Add tests for all the new functions being exported to prepare text subtitles for results.
- [x] Change how the `bf.message` is currently implemented.
- [x] Add `warning` message to every `grouped_` function that they can't be further modified.

**Comment by ibecav** [comment]
If you don't mind, I'll take on the two following tasks and submit a PR (one at a time) in the order stated.

1.  Cleanup all the warning messages generated in a full CRAN build, e.g. "Warning: @description [/Users/cpowell/Documents/RProjects/ggstatsplot/R/helpers_ggbetween_subtitles.R#1]: requires a value" which are simply about blank comment lines in some places.

2.  I'll take a look at the vignettes to see what I can find to make them smaller and more performant.

Chuck

**Comment by IndrajeetPatil** [comment]
Hi Chuck,

1. Sure, you can have a look at this. But this is not really a problem because `R CMD CHECK` doesn't have any problems with these (you'll see that if you run `devtools::check()`). This seems to be associated with `#'` in `roxygen2` documentation with trailing white spaces when `devtools::document(roclets=c('rd', 'collate', 'namespace'))` is used (https://github.com/klutometis/roxygen/issues/710). 
2. Yes, but I think it will not be prudent to downsize vignettes without adding more tests in `testthat`. That's why I haven't really made it a priority for the next release (`0.0.6`). `CRAN` is a bit more lenient with the size of the package (> 5MB) if you can justify it. But, yes, as a long-term goal, I do want to reduce their size. Do you also want to have a look at the tests and see if you can add more tests?

**Comment by IndrajeetPatil** [comment]
Hi Chuck,

I have added you as a contributor to the package. Also, I will be pushing the new version (`0.0.6`) of the package to `CRAN` on the 26th. There is a lot of new functionality I had added since `0.0.5` that I no longer want to postpone from pushing to `CRAN`. 

So if you wanted to add something new, you can create a PR, but depending on when the package makes it to CRAN, it will either be part of the next release (`0.0.6`) or next to next (`0.0.7`).

**Comment by IndrajeetPatil** [comment]
@ibecav Unfortunately, the package was rejected by `CRAN` because the size is larger than 5 MB and the vignette build-up time is ~ 10 minutes (and they need it to be around 5 minutes). 
So I think is something that needs to be resolved before next submission. 

Do you mind having a look at the vignette for `ggpiestats`? I think it can use some fine-tuning.

I will be removing `plot_design` vignette, which wasn't really supposed to be included anyway. I plan to publish it somewhere else (like a blog post).

**Comment by ibecav** [comment]
Happy to look this aft.  My favorite place to post is Rbloggers see for
example
https://www.r-bloggers.com/announcing-another-slopegraph-plotting-function-june-14-2018/

I haven't pinned it down completely yet but I think a lot of the issue with
the vignettes is just that ggplot objects tend to be big even if the
dataset isn't huge.

**Comment by ibecav** [comment]
A quick update.  I've managed to cut the file size in about half so far and hopefully also make things clearer but won't be able to finish until tomorrow.

**Comment by IndrajeetPatil** [comment]
In addition to the vignette changes you have made, I've also tidied up the `README` file a bit and also reduced `dpi` for all vignettes to `200`, which should reduce the size of figures to some degree. The vignette build time has now been reduced (~ 5 min). But the size the package is slightly above limit (6.3 MB). I think `CRAN` will accept it, but we should still attempt to reduce a bit further.

I was thinking of re-submitting the package on the 30th. 

If you get time, do you also mind having a look at `ggbetweenstats` (or `purrr_examples`) vignette? They are the largest and most time-consuming vignettes right now.

**Comment by ibecav** [comment]
Absolutely I’ll get to those Monday, my plan is to go through all of them but I’ll start with those. Good idea on 200 dpi

**Comment by IndrajeetPatil** [comment]
ggstatsplot `0.0.6` is now on `CRAN`:
https://cran.r-project.org/web/packages/ggstatsplot/index.html

**Comment by ibecav** [comment]
Congratulations!
