### ISSUE TITLE
Not enough observations

### ISSUE THREAD

**Issue by pavlo888** [IndrajeetPatil/ggstatsplot#442]
I have a problem to plot my data. When I try to run the following commands: 
ggstatsplot::ggbetweenstats(
  data = fert,
  x = lote,
  y = urea,
  title = "Rendimiento"
)

I obtain this error 
```r
 x callr subprocess failed: <text>:19:10: unexpected '='
18: ggstatsplot::ggbetweenstats(
19: +   data =
             ^ 

 Process 12940:
 17. (function (input)  ...
 18. rmarkdown::render(input, quiet = TRUE, envir = globalenv())
 19. knitr::spin(spin_input, knit = FALSE, envir = envir, format = "Rmd")
 20. utils:::getParseData(parse(text = x, keep.source = TRUE))
 21. base:::parse(text = x, keep.source = TRUE)
 22. base:::.handleSimpleError(function (e)  ...
 23. h(simpleError(msg, call))

 x <text>:19:10: unexpected '='
18: ggstatsplot::ggbetweenstats(
19: +   data =
             ^ 
```

Could you please help me out to solve this issue? 

Cheers, 
Pablo

**Comment by IndrajeetPatil** [comment]
Hmm, hard to see what the problem is without a reproducible example. 

I see that the error is generated in RMarkdown document. What happens if you run the same code in a script?

**Comment by pavlo888** [comment]
Hi Indrajeet, 

It was an error in my dataset. I have fixed it now. 

Thanks!
