### ISSUE TITLE
expand color palette

### ISSUE THREAD

**Issue by pavlo888** [IndrajeetPatil/ggstatsplot#443]
Hi, 

First off, great package!!!! It is super useful and aesthetically pleasing. 

I am trying to expand the color palette of my graph but I don't know how to do it. 

I am using the following command: 

`ggbetweenstats(
  data = shannon,
  x = GH,
  y = shannon,
  type = "np", # <<
  mean.ci = FALSE, # <<
  pairwise.comparisons = TRUE, # <<
  pairwise.display = "s", # <<
  p.adjust.method = "fdr", # <<
  messages = FALSE
)`

I have 15 boxplots and I would like them to each have a color. 

Could you please recommend me a way to do this? 

Cheers, 
Pablo

**Comment by IndrajeetPatil** [comment]
In the future, please don't use GitHub issues to ask questions. GitHub issues are meant mostly to point out bugs or other documentation-related inconsistencies. You can instead raise issue on StackOverflow, where I or someone else will promptly respond to your question. See: https://yihui.org/en/2017/08/so-gh-email/ 

As for your question, you can use an appropriate color palette from a package of your choosing. For available number of palettes from different packages, see

```r
View(paletteer::palettes_d_names)
```

and sort by `length`-

![image](https://user-images.githubusercontent.com/11330453/86609236-f7725700-bfab-11ea-94fa-e9aaac885247.png)
