### ISSUE TITLE
Customisation of Y-Axis Allowing Logarithmic Scales

### ISSUE THREAD

**Issue by DarioS** [IndrajeetPatil/ggstatsplot#444]
**Describe the solution you'd like**
Could there be an easy way to represent the y-axis scale of a box plot on a logarithmic scale? Also, how about ordered instead of jittered points? It's clearer if there are many data points than jitter. For example, a popular kind of [bioinformatics plot](https://www.nature.com/articles/nature12477/figures/1) is:

![image](https://user-images.githubusercontent.com/631218/86669912-6e086680-c037-11ea-8c23-343f8c8afc0f.png)

**How could we do it?**
Coding in R

**Comment by IndrajeetPatil** [comment]
Hmm, this is not easy to implement currently with everything that `ggbetweenstats` displays. That said, there is a way to tweak it to achieve what you want-

``` r

# setup
set.seed(123)
library(ggstatsplot)
library(ggplot2)

# making dataframe
df <-
  dplyr::mutate(msleep,
    brainwt = log10(brainwt),
    vore = forcats::fct_reorder(vore, brainwt, .fun = mean, na.rm = TRUE)
  )

# plot
ggbetweenstats(
  data = df,
  x = vore,
  y = brainwt,
  point.args = list(
    position = ggplot2::position_jitterdodge(dodge.width = 0, jitter.width = 0),
    alpha
    = 0.4,
    size = 3,
    stroke = 0
  ), 
  ylab = "brainwt (logarithmic scale)"
) +
  scale_y_continuous(labels = scales::comma)
```

![](https://i.imgur.com/pWCs8ol.png)

<sup>Created on 2020-07-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
