### ISSUE TITLE
CI issue

### ISSUE THREAD

**Issue by dax44** [IndrajeetPatil/ggstatsplot#445]
I have an issue with confidence interval for effect size. When the effect size is quite big and confidence interval should be narrow, there an error "All values of t are equal to  0.87 \n Cannot calculate confidence intervals" appear. 
This is the example

`data %>% 
    ggwithinstats(x = grouping_var,
                  y = dep_var,
                  type = "np",
                  bf.message = F,
                  messages = F)`

it gives me an error. When I do parametric test error doesn't appear. I thing the problem is with accuracy of CI calculation, because when I took k=3 and I execute the code many times, sometimes I've got the plot.

**Comment by IndrajeetPatil** [comment]
Can you please post a reproducible example? I have no idea what your data is.

**Comment by IndrajeetPatil** [comment]
Closing this for now. Will reoopen if this can be reproduced.
