### ISSUE TITLE
Possibility to combine ggstatsplots with ggforce::geom_sina instead of default scatter.

### ISSUE THREAD

**Issue by Midnighter** [IndrajeetPatil/ggstatsplot#446]
**Describe the solution you'd like**

I am very fond of the Sina plots offered, for example, by the ggforce package (https://ggforce.data-imaginist.com/reference/geom_sina.html). So ideally I would be able to first draw a geom_sina layer, disable the raw scatter and violin of ggstatsplot, and then add other customization.

**How could we do it?**

Maybe this is already possible? I would mainly need to disable the default raw scatter. And it seems kind of awkward to pass a data frame both into `ggplot`, as well as into the ggstatsplot directly.

**Comment by IndrajeetPatil** [comment]
I will suggest just creating a custom plot and then using `statsExpressions` to display results rather than trying to hack `ggstatsplot`.

``` r
# setup
set.seed(123)
library(ggplot2)
library(ggforce)
library(statsExpressions)

# plot using `ggforce` and subtitle using `statsExpressions`
ggplot(midwest, aes(state, area)) +
  geom_violin() +
  geom_sina() +
  labs(subtitle = expr_anova_parametric(midwest, state, area))
```

![](https://i.imgur.com/NmkQmBO.png)

<sup>Created on 2020-07-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Midnighter** [comment]
Of course it lacks a lot of the bells and whistles that you've added (pairwise comparisons, mean values, null hypothesis caption) but that's fair enough.
