### ISSUE TITLE
colorpallette and axis customisation

### ISSUE THREAD

**Issue by rb643** [IndrajeetPatil/ggstatsplot#448]
Is there a straightforward way to integrate viridis and/or scico colorpallette for discrete maps into ggbetweenstats?

Is there a straightforward way to rotate axis labels?

**Comment by IndrajeetPatil** [comment]
There is no straightforward way to integrate these palettes because they are **sequential** palettes while `ggbetweenstats` needs **discrete** palettes. But there is a way around it: You can manually enter the colors you require and the color codes can be extracted using `paletteer`.

```r    
# needed libraries
    library(ggstatsplot)
    library(paletteer)
    library(ggplot2)

    # plot
    ggbetweenstats(mtcars, cyl, wt) + 
      # modify further with `ggplot2` functions
      scale_color_manual(values = paletteer::paletteer_c("viridis::viridis", 3)) +
      scale_x_discrete(guide = guide_axis(angle = 90))
    #> Scale for 'colour' is already present. Adding another scale for 'colour',
    #> which will replace the existing scale.
    #> Scale for 'x' is already present. Adding another scale for 'x', which will
    #> replace the existing scale.
```
![](https://i.imgur.com/Y5aWYk6.png)

**Comment by rb643** [comment]
Unfortunately that doesn't seem to quite work for my little snippet..  Neither axes are rotated in this nor the colour is changed.. Any chance I missed something? The main reason I want to change the palette is because I have around 12-14 difference factors and with the default palettes the last ones end up just empty. Side note: viridis has the option to set the colorscale to discrete so perhaps there is a way to integrate it directly.

`ggstatsplot::grouped_ggbetweenstats(
  data = data.dx,
  grouping.var = sex,
  pairwise.comparisons = TRUE, # display results from pairwise comparisons
  pairwise.display = "significant", # display only significant pairwise comparisons
  p.adjust.method = "fdr", 
  x = dx,
  y = quantile,
  nboot = 10,
  messages = FALSE
) +
  scale_color_manual(values = paletteer::paletteer_c("viridis::viridis", 3)) +
  scale_x_discrete(guide = guide_axis(angle = 90))`

**Comment by IndrajeetPatil** [comment]
Do you mean that if you copy-paste the exact code I posted above and run it, you don't see the same output?

As for the empty the colours, you can just change the `package` and `palette` arguments for `ggbetweenstats` and select a combination which has length > 12.

Here are all the available palettes which meet this requirement:

``` r
library(tidyverse)

paletteer::palettes_d_names %>%
  arrange(desc(length)) %>%
  as_tibble()
#> # A tibble: 1,711 x 4
#>    package      palette  length type      
#>    <chr>        <chr>     <int> <chr>     
#>  1 palettesForR Named       448 sequential
#>  2 palettesForR Inkscape    431 sequential
#>  3 palettesForR Visibone    336 sequential
#>  4 palettesForR Bears       256 sequential
#>  5 palettesForR Bgold       256 sequential
#>  6 palettesForR Blues       256 sequential
#>  7 palettesForR Borders     256 sequential
#>  8 palettesForR Caramel     256 sequential
#>  9 palettesForR Cascade     256 sequential
#> 10 palettesForR China       256 sequential
#> # … with 1,701 more rows
```

**Comment by rb643** [comment]
Your code works and I can reproduce the same thing. When I apply it to my data however using the grouped version of ggbetweenstats and having more factors it doesn't..

E.g. this does not result in a plot with scaled axes and all factor with a viridis colorscale...
`ggstatsplot::grouped_ggbetweenstats(
  data = data.dx,
  grouping.var = sex,
  pairwise.comparisons = TRUE, # display results from pairwise comparisons
  pairwise.display = "significant", # display only significant pairwise comparisons
  p.adjust.method = "fdr", 
  x = dx,
  y = quantile,
  nboot = 10,
  messages = FALSE
) +
  scale_color_manual(values = paletteer::paletteer_c("viridis::viridis", nlevels(data.dx$dx))) +
  scale_x_discrete(guide = guide_axis(angle = 90))`

**Comment by IndrajeetPatil** [comment]
But in the original question you said `ggbetweenstats` and not `grouped_ggbetweenstats`.

What if you run the following:

```r
ggstatsplot::grouped_ggbetweenstats(
  data = data.dx,
  grouping.var = sex,
  pairwise.comparisons = TRUE,
  pairwise.display = "significant",
  p.adjust.method = "fdr",
  x = dx,
  y = quantile,
  nboot = 10,
  messages = FALSE,
  package = "khroma",
  palette = "discrete_rainbow	",
  ggplot.component = list(ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 90)))
) 
```

**Comment by rb643** [comment]
My apologies, I should have been clearer on that.. With that code I at least get a new error:

```
ggstatsplot::grouped_ggbetweenstats(
+     data = data.dx,
+     grouping.var = sex,
+     pairwise.comparisons = TRUE,
+     pairwise.display = "significant",
+     p.adjust.method = "fdr",
+     x = dx,
+     y = quantile,
+     nboot = 10,
+     messages = FALSE,
+     package = "khroma",
+     palette = "discrete_rainbow",
+     ggplot.component = list(ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 90)))
+ ) 
Error in grid.Call(C_convert, x, as.integer(whatfrom), as.integer(whatto),  : 
  Viewport has zero dimension(s)
```

**Comment by IndrajeetPatil** [comment]
Cool, this is no longer `ggstatsplot` issue, but `RStudio` on `MacOS` issue. Have a look at this:
https://github.com/IndrajeetPatil/ggstatsplot/issues/178#issuecomment-465833778

You can also Google that error and will find multiple posts on `StackOverflow`, which will help you.
