### ISSUE TITLE
Not working for binomial family in robustbase::glmrob

### ISSUE THREAD

**Issue by sebastianf101** [IndrajeetPatil/ggstatsplot#455]
First, I appreciate your excellent work on this comprehensive package.
Next, I give the issue's reprex.

From robustbase's documentation, the following example returns:

> Error in if (model_info(x)$family %in% g.t.mods) { : 
>   argument is of length zero
> In addition: Warning messages:
> 1: Could not access model information.

```r
library(robustbase)
data(vaso)
mod_rob_ex <- glmrob(Y ~ log(Volume) + log(Rate), family=binomial, data=vaso, method= "BY")
ggcoefstats(mod_rob_ex, title = "Example of glmrob in robustbase documentation")
```
Maybe the binomial familiy hasn't been implemented yet?

**Comment by IndrajeetPatil** [comment]
Closed in favor of https://github.com/easystats/insight/issues/225
