### ISSUE TITLE
Download issue: rstan

### ISSUE THREAD

**Issue by ryanoc7** [IndrajeetPatil/ggstatsplot#456]
There is an issue with downloading and using this package. I run on a MacBook. There seems to be an issue with the rstan package

```r
library(ggstatsplot)
Error: package or namespace load failed for ‘ggstatsplot’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘rstan’
```

**Comment by IndrajeetPatil** [comment]
This has nothing to do with `ggstatsplot`. You don't have `rstan` installed.

Please see instructions to install it here:
https://mc-stan.org/users/interfaces/rstan
