### ISSUE TITLE
Summary table?

### ISSUE THREAD

**Issue by Nilafhiosagam** [IndrajeetPatil/ggstatsplot#461]
Hi, perhaps it's just me, but does the package have a way to output all the calculations done under the hood in a tidy format rather than as part of the ggplot?

There's a wealth of information displayed on the plots but I can't see how I extract the p values, CIs, etc in a df

**Comment by IndrajeetPatil** [comment]
From the next release, this will indeed be possible:
https://indrajeetpatil.github.io/ggstatsplot/articles/web_only/faq.html#how-can-i-extract-dataframe-containing-results-from-ggstatsplot-
