### ISSUE TITLE
Format p-value in subtitle to avoid scientific notation

### ISSUE THREAD

**Issue by fmmattioni** [IndrajeetPatil/ggstatsplot#466]
Hi @IndrajeetPatil,

I was wondering if I could somehow format the p-value in the subtitle to avoid the scientific notation? Perhaps I way that I could use `parameters::format_p()`?

reprex with subtitle in scientific notation:

``` r
# for reproducibility
set.seed(123)
library(ggstatsplot)

# plot
ggstatsplot::ggbetweenstats(
  data = iris,
  x = Species,
  y = Sepal.Length,
  title = "Distribution of sepal length across Iris species"
)
```

![](https://i.imgur.com/OEt460d.png)

<sup>Created on 2020-10-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by IndrajeetPatil** [comment]
Previous versions of `ggstatsplot` did not use the scientific notation, but I couldn't see any way of avoiding it anymore to simplify some aspects of the code. 

Current workaround is:

``` r
# for reproducibility
set.seed(123)
library(ggplot2)
library(ggstatsplot)

set.seed(123)
(sub <-
  statsExpressions::expr_anova_parametric(
    data = iris,
    x = Species,
    y = Sepal.Length
  ))
#> paste(italic("F")["Welch"], "(", "2", ",", "92.21", ") = ", "138.91", 
#>     ", ", italic("p"), " = ", "1.51e-28", ", ", widehat(omega["p"]^2), 
#>     " = ", "0.61", ", CI"["95%"], " [", "0.52", ", ", "0.68", 
#>     "]", ", ", italic("n")["obs"], " = ", 150L)

parameters::format_p(1.51e-28)
#> [1] "p < .001"

# plot
ggstatsplot::ggbetweenstats(
  data = iris,
  x = Species,
  y = Sepal.Length,
  results.subtitle = FALSE,
  title = "Distribution of sepal length across Iris species"
) +
  labs(subtitle = ggplot2::expr(paste(
    italic("F")["Welch"], "(", "2",
    ",", "92.21", ") = ", "138.91", ", ",
    italic("p"), " < ", ".001", ", ",
    widehat(omega["p"]^2), " = ", "0.61", ", CI"["95%"],
    " [", "0.52", ", ", "0.68", "]",
    ", ", italic("n")["obs"], " = ",
    150L
  )))
```

![](https://i.imgur.com/Ernaa05.png)

<sup>Created on 2020-10-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

If you also want to avoid scientific notation in pairwise comparisons, you can similarly modify using custom labels.
e.g., https://indrajeetpatil.github.io/ggstatsplot/articles/web_only/faq.html#can-you-customize-which-pairs-are-shown-in-pairwise-comparisons-

**Comment by fmmattioni** [comment]
This is great!! Thank you very much for the quick reply!

**Comment by brianmsm** [comment]
Could an argument be added specifying the format of the desired p-value?

**Comment by IndrajeetPatil** [comment]
In general, I am a bit hesitant to provide arguments to change the format of the expressions, since this will inevitable lead to an explosion of arguments for the `ggstatsplot` functions.

I would much rather have the users customize the expressions further themselves to their own liking. As shown in the example above, this is very easy to do since `ggstatsplot` can also just return the full expression.

**Comment by brianmsm** [comment]
If there are more requests to customize regular expressions, perhaps a function could be created that could function as a template. 
Regarding the p-value, the request was because the APA guidelines state that any value less than 0.001 should be indicated as "p < .001". I originally thought I could create a wrapper function for personal use, but I decided to comment it out first.

**Comment by IndrajeetPatil** [comment]
Yeah, I see what you mean. But I personally feel people shouldn't follow the APA guidelines as religiously as they do. This is why, although `ggstatsplot` package tries to follow these guidelines as much as possible, it also diverges from them when necessary. Showing exact _p_-values is more informative and consistent than arbitrary cut-offs (< .05, < .01, < .001) APA guidelines have adopted.

Btw, I also have written papers containing `ggstatsplot` plots with the _p_-values in scientific notation and the reviewers did not seem to be bothered by it in the least. So I don't think this should be that big of a deal also during the peer review process.

**Comment by brianmsm** [comment]
I understand what you mean, although the current APA standards do not indicate cut-off points in the p-value, they only talk about values less than 0.001. 
Thank you for your answer.
