### ISSUE TITLE
ggcoefstats: support for np.anova and nparLD

### ISSUE THREAD

**Issue by M-Colley** [IndrajeetPatil/ggstatsplot#469]
Dr. Lüpsen provides provides functions for non-parametric ANOVAs [(Link](http://www.uni-koeln.de/~luepsen/R/)). 

Additionally, there is the package [nparLD](https://cran.r-project.org/web/packages/nparLD/nparLD.pdf) that also provides functionality for non-parametric ANOVAs with a betwee-subject factor. 

Would it be possible to support these in ggcoefstats?

Kind regards

**Comment by IndrajeetPatil** [comment]
I am not really familiar with these models. 

What information from here do you expect should be plotted as estimates in the `ggcoefstats` output?

``` r
set.seed(123)
library(nparLD)
#> Loading required package: MASS
data(panic)

ex.f1.np <-
  nparLD(resp ~ time,
    data = panic,
    subject = "subject",
    description = FALSE
  )
#>  LD F1 Model 
#>  ----------------------- 
#>  Check that the order of the time level is correct.
#>  Time level:   0 2 4 6 8 
#>  If the order is not correct, specify the correct order in time.order.

class(ex.f1.np)
#> [1] "nparLD"

summary(ex.f1.np)
#> Model: 
#> LD F1 Model 
#>  
#> Call: 
#> resp ~ time
#> 
#> Relative Treatment Effect (RTE):
#>       RankMeans Nobs       RTE
#> time0  66.09375   16 0.8199219
#> time2  50.50000   16 0.6250000
#> time4  41.28125   16 0.5097656
#> time6  25.62500   16 0.3140625
#> time8  19.00000   16 0.2312500
#> 
#> Wald-Type Statistc (WTS):
#>      Statistic df    p-value
#> time  126.6946  4 1.9822e-26
#> 
#> ANOVA-Type Statistc (ATS):
#>      Statistic       df      p-value
#> time  36.93664 2.234135 1.975781e-18
```

<sup>Created on 2020-11-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by IndrajeetPatil** [comment]
Will reopen after receiving a response.
