### ISSUE TITLE
Add ibecav as contributor?

### ISSUE THREAD

**Issue by ibecav** [IndrajeetPatil/ggstatsplot#47]
One of the issues I'm having is staying synched with your changes to master.  If you're willing...

https://help.github.com/articles/inviting-collaborators-to-a-personal-repository/

I'm not interested in writing to "master" happy to read and write to devel branches and let you do the merging

Meantime I just blew away my fork and reforked to synch up

**Comment by ibecav** [comment]
Thank you

**Comment by IndrajeetPatil** [comment]
I have added you as a collaborator. 

Yeah, I do commit pretty frequently and a lot of them can be stylistic changes (like using `styler` package to format code in tidyverse style or using `pkgdown` to updated the website). 

And, yes, please always push your changes to the `development` branch and I can merge them with `master` branch. 

Thanks.

**Comment by ibecav** [comment]
Okay thanks.
