### ISSUE TITLE
Adding color/shape to jitter

### ISSUE THREAD

**Issue by pavlo888** [IndrajeetPatil/ggstatsplot#471]
Hi @IndrajeetPatil,

First of all, GREAT PACKAGE!!!! This package has been really useful for me. 

However, I was wondering if there is any way to add another level of information to my plot. Let me give an example. 

I have this figure below. I would like the jitter to be colored/shaped according to different sampling times I made. Normally, I would do it with facetting but since the number of samples is not balanced, I cannot use the function grouped_ggbetweenstats. 

Thanks in advance for your help! 
Cheers, 
Pablo 

![image](https://user-images.githubusercontent.com/45701394/98446632-17af4f80-211f-11eb-93e9-fb19885a2b06.png)

**Comment by IndrajeetPatil** [comment]
Dear Pablo,

Need to think about this. But, at the first look, it seems to me that using `purrr` might be the way to go here?
https://indrajeetpatil.github.io/ggstatsplot/articles/web_only/purrr_examples.html#ggbetweenstats-1

Does that help?
