### ISSUE TITLE
allow custom pairwise comparisons display

### ISSUE THREAD

**Issue by rb643** [IndrajeetPatil/ggstatsplot#479]
Is there a way to change/control the spacing between the lines and text showing the pairwise comparisons in (groupped)_ggbetweenstats.

At the moment I have a lot of significant pairs and the lines cross through the text quite often while there is still whitespace within the plot (e.g. I've for example set the `ylims` very liberal)

**Comment by IndrajeetPatil** [comment]
Isn't this just a matter of the aspect ratio? 
If you are saving the plot using `ggplot2::ggsave`, you can not just change the `height` and `width` arguments.
If this is an `RMarkdown` chunk, you can change `fig.height` and `fig.width`.

**Comment by rb643** [comment]
playing around with that improves things slightly, but it still leaves a lot of white-space and the annotated p-values and lines still overlap. But maybe this is more of a future feature request.

**Comment by IndrajeetPatil** [comment]
Can you please post a picture of what the figure looks like? I am grasping in blind here and don't understand what the issue.

**Comment by rb643** [comment]
See below. This is already with pretty generous aspect ratio's and I've fixed the ylim to ensure consistency. You can see in both panel the lines and annotation pretty much overlap despite there being ample space...
![Figure_2 (2)](https://user-images.githubusercontent.com/10026949/100362033-ce9e3d00-2ff2-11eb-9e2a-9a6042206fde.png)

As a side note another solution would be if I could restrict the comparison set manually (in this case I am actually mainly interested in the pairwise comparisons between the first factor and all the others (but not between the others so much, though I'd still conduct the tests for all and correct for all, for visualisation only references to the first would be needed)

**Comment by IndrajeetPatil** [comment]
I see. In that case, I would suggest doing a custom `pairwiseComparisons` + `ggsignif` combination:
https://indrajeetpatil.github.io/pairwiseComparisons/

For example, although there are three comparisons here, I am choosing to display only 1. So you can do something similar for your plot.

``` r
# needed libraries
library(ggplot2)
library(pairwiseComparisons)
library(ggsignif)

# converting to factor
mtcars$cyl <- as.factor(mtcars$cyl)

# creating a basic plot
p <- ggplot(mtcars, aes(cyl, wt)) + geom_boxplot()

# using `pairwiseComparisons` package to create a dataframe with results
set.seed(123)
(df <-
    pairwise_comparisons(mtcars, cyl, wt, messages = FALSE) %>%
    dplyr::mutate(.data = ., groups = purrr::pmap(.l = list(group1, group2), .f = c)) %>%
    dplyr::arrange(.data = ., group1))
#> # A tibble: 3 x 9
#>   group1 group2 statistic p.value significance test.details p.value.adjustm…
#>   <chr>  <chr>      <dbl>   <dbl> <chr>        <chr>        <chr>           
#> 1 4      6           5.39 8.31e-3 **           Games-Howel… Holm            
#> 2 4      8           9.11 1.24e-5 ***          Games-Howel… Holm            
#> 3 6      8           5.12 8.31e-3 **           Games-Howel… Holm            
#> # … with 2 more variables: label <chr>, groups <list>

# using `geom_signif` to display results
p +
  ggsignif::geom_signif(
    comparisons = list(df$groups[[1]]),
    annotations = df$label[[1]],
    test = NULL,
    na.rm = TRUE,
    parse = TRUE
  )
```

![](https://i.imgur.com/iN5QjgW.png)

<sup>Created on 2020-11-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Note to self: Add this to FAQ.

**Comment by IndrajeetPatil** [comment]
Although this is going to be a headache to do for `grouped_` function. Currently, you can either show all comparisons, only significant ones, or only non-significant ones, but not only selective few. I need to think how can I allow users to do this.

**Comment by IndrajeetPatil** [comment]
Can't think of any way to support this right now. Might revisit this in the future (after `1.0` release, i.e.).
