### ISSUE TITLE
Larger font for statistical reporting and mean vlaues

### ISSUE THREAD

**Issue by pavlo888** [IndrajeetPatil/ggstatsplot#480]
Hi, 

I was wondering if there was a way to make the statistical report font a bit larger and also the mean values displayed? See the highlighted features in light blue. 

Thanks! 

Cheers, 
Pablo 

![InkedRplot01-2_LI](https://user-images.githubusercontent.com/45701394/100358283-402bba80-2ff6-11eb-87c3-aecf391b9dac.jpg)

**Comment by IndrajeetPatil** [comment]
``` r
library(ggstatsplot)
library(ggplot2)

ggbetweenstats(mtcars, am, wt, mean.label.args = list(size = 7)) + 
  theme(plot.subtitle = element_text(size = 15))
```

![](https://i.imgur.com/VAT5tNe.png)

<sup>Created on 2020-11-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
