### ISSUE TITLE
ggscatterstats margin = true fails to generate the plot

### ISSUE THREAD

**Issue by LenaLapidot** [IndrajeetPatil/ggstatsplot#490]
Hello,
First, I would like to thank you for this awesome r package!

I am using ggscatterstats to plot person correlation between 2 continuous variables. I want to create a plot with margins, however, the plot appears only if I use margins = false. If I try to use margins=true, the plot does not appear. 

Do you have any suggestions for this issue?

Thank you.
Best,
Lena

**Comment by IndrajeetPatil** [comment]
The argument you are looking for is `marginal`, and not `margins`.
https://indrajeetpatil.github.io/ggstatsplot/reference/ggscatterstats.html

![image](https://user-images.githubusercontent.com/11330453/102333146-4fff4480-3f8d-11eb-8154-da9d84c198ce.png)

**Comment by LenaLapidot** [comment]
Hi, thank you for your answer. This is the command I'm trying to run, and it doesn't produce a plot. However, if I change marginal to FALSE, the plot is produced (without margins).

ggstatsplot::ggscatterstats(
  data = Map,
  x = ses, 
  y = FSIQ, 
  xlab = "Socioeconomic status scores", 
  ylab = "Full scale IQ scores", 
  point.alpha = 0.7,
  point.size = 4,
  point.color = "grey50",
  marginal = TRUE, 
  marginal.type = "densigram",
  centrality.parameter = "mean", 
  margins = "both", 
  xfill = "#CC79A7", 
  yfill = "#009E73", 
  type = "p",
  title = "Relationship between participants' socioeconomic status and full scale IQ scores",
  messages = FALSE
)

**Comment by IndrajeetPatil** [comment]
I can't run that command since I don't have access to the data you are using. 
So here I am using `mtcars` dataset to demonstrate that I can't reproduce the issue you are facing. 

Have you tried updating your packages and running this command? 
Maybe you have some out of date packages that causing the isssue.

``` r
ggstatsplot::ggscatterstats(
  data = mtcars,
  x = wt,
  y = mpg,
  xlab = "Socioeconomic status scores",
  ylab = "Full scale IQ scores",
  point.alpha = 0.7,
  point.size = 4,
  point.color = "grey50",
  marginal = TRUE,
  marginal.type = "densigram",
  centrality.parameter = "mean",
  margins = "both",
  xfill = "#CC79A7",
  yfill = "#009E73",
  type = "p",
  title = "Relationship between participants' socioeconomic status and full scale IQ scores",
  messages = FALSE
)
```

![](https://i.imgur.com/Lg2LBWI.png)

<sup>Created on 2020-12-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>
