### ISSUE TITLE
Tied ranks adjustment for np tests

### ISSUE THREAD

**Issue by whclaw** [IndrajeetPatil/ggstatsplot#497]
Hi Indra,

Thanks for the great package.

I wonder if there is a way to display the tied ranks adjusted non-parametric between-subject statistics (e.g.  Kruskal-Wallis and Mann-Whitney tests) in the plots. 

I'm asking this as my data seems to be very skewed with lots of tied ranks.

Best Wishes,
Crystal

**Comment by IndrajeetPatil** [comment]
Yes, all the non-parametric tests you mention are already supported. Just set `type = "np"` in `ggstatsplot` functions.
Have  a look at the `README` to see what tests are currently supported:
https://cran.r-project.org/web/packages/ggstatsplot/readme/README.html

<img width="739" alt="Screenshot 2020-12-20 at 08 27 01" src="https://user-images.githubusercontent.com/11330453/102707656-29971d00-429d-11eb-89b0-ffc38f27f2cf.png">

**Comment by whclaw** [comment]
Hi thanks for such quick reply :)  Do you mean that the np statistics values displayed in the plots now are all "tied ranks adjusted" already?

**Comment by IndrajeetPatil** [comment]
Oh, I see.

My hunch is that `stats::kruskal.test` does this adjustment by default. But I actually can't seem to find any documentation on this. Will get back to you.

**Comment by IndrajeetPatil** [comment]
Investigating

``` r

# raw data 
# example from https://www.dataanalytics.org.uk/adjustment-for-tied-ranks-in-the-kruskal-wallis-test/
df <-
  tibble::tribble(
    ~Upper, ~Mid, ~Lower,
    3, 4, 11,
    4, 3, 12,
    5, 7, 9,
    9, 9, 10,
    8, 11, 11,
    10, NA, NA,
    9, NA, NA
  )

# get it in long format
df <- tidyr::gather(df, "g", "x")

# using `stats`
set.seed(123)
stats::kruskal.test(x ~ g, df)
#> 
#>  Kruskal-Wallis rank sum test
#> 
#> data:  x by g
#> Kruskal-Wallis chi-squared = 6.5396, df = 2, p-value = 0.03801

# using `PMCMRplus`
set.seed(123)
PMCMRplus::kruskalTest(x ~ g, df, dist = "KruskalWallis")
#> Error in kruskalTest.default(c(3, 4, 5, 9, 8, 10, 9, 4, 3, 7, 9, 11, 11, : all group levels must be finite
```

<sup>Created on 2020-12-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by whclaw** [comment]
Hi Indra,
Thanks so much for such quick replies and support :)
