### ISSUE TITLE
implementation of Dunnett's test

### ISSUE THREAD

**Issue by marioniepel** [IndrajeetPatil/ggstatsplot#499]
In grouped experiments, the ggbetweenstats perform a comparison of every group against every other group. However, in many biological experiments the only relevant comparison is between a single control and all other treatments individually (which I believe would be the Dunnett's test). It would be great to be able to perform this with ggstatsplots since it would be much a much less cluttered and more informative outout that either ggbetweenstats or having to split up every single larger group into individual pairs and then call an analysis.

[Illustration](https://i.stack.imgur.com/wE6uv.png)

In this example more than a dozen 'significant' differences are reported. Yet, the only relevant comparisons are between the positive control and the 5 other groups. The negative control to show there is a measurable effect and then treatment A through D to show which (if any) treatments had an affect on the control condition (positive control in this case).

**Comment by IndrajeetPatil** [comment]
Yeah, I completely relate to this feature request and this issue has been raised in the past. I see no way to support it currently, but I do plan to come back to it some time by the end of the next year 

Closing in favor of #500
