### ISSUE TITLE
Non-parametric Between Subject Interaction Effect

### ISSUE THREAD

**Issue by whclaw** [IndrajeetPatil/ggstatsplot#501]
Hi Indra,
Thanks for creating ggstatsplot and the always helpful responses to questions.

I know that the ggbetweenstats function can perform non-parametric Oneway ANOVA analysis,
now I wonder is there a way to use it to examine the **interaction effect** (a two-way nonparametric ANOVA)?

Best Wishes,
Crystal

**Comment by IndrajeetPatil** [comment]
Closing in favor of #500
