### ISSUE TITLE
  C++14 standard requested but CXX14 is not defined

### ISSUE THREAD

**Issue by krushnach80** [IndrajeetPatil/ggstatsplot#503]
Im trying to install the library using this 

```
remotes::install_github(
  repo = "IndrajeetPatil/ggstatsplot", # package path on GitHub
  dependencies = TRUE, # installs packages which ggstatsplot depends on
  upgrade_dependencies = TRUE # updates any out of date dependencies
)
```

This is the error Im getting 
```
Error in .shlib_internal(args) : 
  C++14 standard requested but CXX14 is not defined
* removing ‘/usr/lib64/R/library/rstan’
Error: Failed to install 'ggstatsplot' from GitHub:
  Failed to install 'tidyBF' from GitHub:
  (converted from warning) installation of package ‘rstan’ had non-zero exit status

```
My R version
R version 3.6.0 (2019-04-26) -- "Planting of a Tree"

This is my OS version.

CentOS Linux release 7.9.2009 (Core)

How do i get around this? the above issue

**Comment by IndrajeetPatil** [comment]
The problem is that you seem to be having trouble installing `rstan` package:

```r
Failed to install 'tidyBF' from GitHub:
  (converted from warning) installation of package ‘rstan’ had non-zero exit status
```

So this has nothing to do with `ggstatsplot`.

Have a look at this: https://github.com/stan-dev/rstan/issues/569

If that doesn't solve the issue, raise another issue on `rstan` repository.
