### ISSUE TITLE
problem loading ggstatsplot 0.6.6

### ISSUE THREAD

**Issue by tomateba** [IndrajeetPatil/ggstatsplot#505]
_Hi, I recently updated tidyverse packages and ggstatsplot and I cannot load it anymore, 
this is the message I get:_

```r
library(ggstatsplot)

Registered S3 method overwritten by 'broom.mixed':
  method      from 
  tidy.gamlss broom
Error: package or namespace load failed for ‘ggstatsplot’:
 object ‘easystats_to_tidy_names’ is not exported by 'namespace:broomExtra'`
```

**I have broomExtra 4.1.0, broom.mixed 0.2.6 and ggstatsplot 0.6.6 installed**

_Would you please help me to address this issue?_

**Comment by IndrajeetPatil** [comment]
Can you please update **all** of your packages, restart the `RStudio` session, and then try again?
