### ISSUE TITLE
Loading additional palettes doesn't seem to work

### ISSUE THREAD

**Issue by jonmjachimowicz** [IndrajeetPatil/ggstatsplot#51]
I'm trying to load additional palettes in to help me plot a variable with more than 8 categories. However, when I do that, I get the following error:

Error in ggstatsplot::ggbetweenstats(data = sums_inc, x = AnnualIncome,  : 
  unused arguments (ggstatsplot.layer = FALSE, package = "wesanderson")

Any advice/insights on what to do?

ggstatsplot::ggbetweenstats(
  data = sums_inc,                                    
  x = AnnualIncome,
  y = negative_affect.z,
  mean.plotting = F,
  mean.label.size = 3.5,
  k = 2,
  xlab = "Annual Income",
  ylab = "Negative Affect",
  title = "Income and Negative Affect",
  plot.type = "boxviolin", 
  type = F,
  ggtheme = ggthemes::theme_fivethirtyeight(),
  messages = FALSE, 
  ggstatsplot.layer = FALSE,  
  package = "wesanderson",
  palette = "Darjeeling1")

**Comment by jonmjachimowicz** [comment]
Hi,

Thanks for the response! I updated ggstatsplot and now get the following error:

Error in ggplot2::labs(x = xlab, y = ylab, title = title, subtitle = subtitle,  : 
  object 'subtitle' not found

Any idea what’s going on?

Jon

**Comment by IndrajeetPatil** [comment]
You are setting `type` argument to `F`, but that's not an allowed value.

```

type: Type of statistic expected ("parametric" or "nonparametric" or "robust" or "bayes").
Corresponding abbreviations are also accepted: "p" (for parametric), "np" (nonparametric), 
"r" (robust), or "bf" resp.
```

See if it works if you change that.

**Comment by jonmjachimowicz** [comment]
That worked like a charm, thanks so much! is there a way to turn off the type of statistic at all?

**Comment by IndrajeetPatil** [comment]
Yes!

For example-

``` r
ggstatsplot::ggbetweenstats(data = iris, x = Species, y = Sepal.Length, messages = FALSE) +
  ggplot2::labs(subtitle = NULL)
```

![](https://i.imgur.com/LLnk2pK.png)

<sup>Created on 2018-09-21 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
