### ISSUE TITLE
ggscatterstats - change color of geom_points according to a variable of interest

### ISSUE THREAD

**Issue by LenaLapidot** [IndrajeetPatil/ggstatsplot#510]
Hello,
I would like to color the geom_points according to a third variable (which is not the x and y variables). Is this possible?

Thank you,
Best,
Lena

**Comment by IndrajeetPatil** [comment]
Unfortunately, not. The best `ggstatsplot` has to offer is an expression you can use to show in your custom plot:

``` r
library(ggplot2)
library(ggstatsplot)

expr <- ggbetweenstats(msleep, vore, brainwt, output = "subtitle")

ggplot(msleep, aes(vore, brainwt, color = conservation)) +
  geom_point() +
  labs(subtitle = expr)
#> Warning: Removed 27 rows containing missing values (geom_point).
```

![](https://i.imgur.com/OBZdFa5.png)

<sup>Created on 2021-01-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
