### ISSUE TITLE
Option to remove the "Pairwise test: ...; Comparisons shown: ..." caption

### ISSUE THREAD

**Issue by brianhillFR** [IndrajeetPatil/ggstatsplot#511]
Hi,

First, thanks of the development of ggstatsplot: it's great!

Is there a way to remove the "Pairwise test: ...; Comparisons shown: ..." caption appearing appearing at the bottom of `ggstatsplot::ggwithinstats` and `ggstatsplot::ggwithinstats` plots when pairwise comparisons are on? 

If not, I'd suggestion developing an option. This would helpful when displaying multiple plots -- say, a grid 2 x 4 of 8 plots -- each with the same pairwise comparisons inside the plots. In such cases, repeating  "Pairwise test: ...; Comparisons shown: ..." below every plot is space-consuming (and ugly), and it would be nice to remove these captions and add a single caption at the bottom of the grid.

Thanks!

**Comment by IndrajeetPatil** [comment]
There is no need to add a new option just to do this. You can just do this in the function call itself.

``` r
library(ggstatsplot)

ggstatsplot::grouped_ggwithinstats(
  data = VR_dilemma,
  x = modality,
  y = score,
  grouping.var = order,
  ggplot.component = ggplot2::labs(caption = NULL)
)
```

![](https://i.imgur.com/q8VwFLs.png)

<sup>Created on 2021-01-28 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

The issue of duplicated captions is valid though. Will work on fixing that in the future.

**Comment by brianhillFR** [comment]
Thanks. The suggestion concerned the duplication of captions. I was aware of the grouping function, which, apart from the caption duplication, works great.
Thanks again.
