### ISSUE TITLE
Overlapping combine_plots for coeftest 

### ISSUE THREAD

**Issue by IsadoraBM** [IndrajeetPatil/ggstatsplot#521]
The `--vcovHC`–function estimates three heteroskedasticity-consistent covariance estimators with additional options. 
```r
fixed <-plm(y ~ x1, data=Panel, index=c("country", "year"), model="within")
```

`ggstatsplot::ggcoefstats` **CAN** currently plot `coeftest(fixed)` [No heteriskedasticity control]
and `coeftest(fixed, vcovHC(fixed, method = "arellano"))` (for example)  [With Arellano control]

Feature idea:
`combine_plots` could be extended to support a graph with a shared y-axis and x-axis scale that both models' dot-whisker plots overlap, with an additional `hline.args` to specify each model's color to quickly visualize comparisons just like with `point.args`

![Idea combine_plots](https://user-images.githubusercontent.com/26873609/107295662-d3915b00-6a3d-11eb-89b1-3ec801a94cbd.jpg)

**Comment by IndrajeetPatil** [comment]
Note that `combine_plots` is designed to only create a grid of already prepared plots. It will not be able to support any analysis _within_ a given plot.

`ggcoefstats` is designed to plot results only from a single model at a given time, so it will not be able to support your feature request. Sorry.

I would recommend that you instead use `dotwhisker` package, which does allow such multi-model comparisons:
https://cran.r-project.org/web/packages/dotwhisker/vignettes/dotwhisker-vignette.html

**Comment by IsadoraBM** [comment]
Thanks for the recommendation!
________________________________
