### ISSUE TITLE
Feature idea: choosable mean or median via parameter

### ISSUE THREAD

**Issue by M-Colley** [IndrajeetPatil/ggstatsplot#524]
Hey, I followed the updates you made regarding displaying the mean or median in the charts and understand why you did this.

However, for my use cases it would be sometimes great to show the mean when ggstatsplot actually shows the median. 
Therefore, I would suggest making this choosable via a parameter while the default is chosen as you implemented it.

Thank you for your consideration and the great package!

**Comment by IndrajeetPatil** [comment]
``` r
library(ggstatsplot)

ggbetweenstats(mtcars, am, wt, type = "np", centrality.type = "p")
```

![](https://i.imgur.com/feu7Nn7.png)

<sup>Created on 2021-02-11 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>
