### ISSUE TITLE
Warning message in ggstatsplot::combine_plots : In as_grob.default(plot) :  Cannot convert object of class list into a grob

### ISSUE THREAD

**Issue by gaelhammer** [IndrajeetPatil/ggstatsplot#526]
Hello,
I'm discovering your ggstastplot package which looks extremely interesting for what I'm doing.

I tried to run your very first example from this page: "[using ggstatsplot with the purrr package](https://indrajeetpatil.github.io/ggstatsplot/articles/web_only/purrr_examples.html)", where `ggstatsplot::combine_plots()` generates an error message.
`Warning messages:
1: In as_grob.default(plot) :
  Cannot convert object of class list into a grob.
2: In as_grob.default(plot) :
  Cannot convert object of class list into a grob.`

Each single plot is OK, but calling `combine_plots()` - even only one single plot - generates this error. I hope it's easy to fix!

Keep up the good work!

![Rplot](https://user-images.githubusercontent.com/23336353/107664496-c1f1c280-6c8c-11eb-8d61-f855143f6112.png)

**Comment by IndrajeetPatil** [comment]
When you use `ggstatsplot::combine_plots()`, do you use the `plotlist` argument to provide plots as a `list`?

Like in the article you link to?

```
# combining all individual plots from the list into a single plot using combine_plots function
ggstatsplot::combine_plots(
  plotlist = plot_list,
  annotation.args = list(title = "Changes in life expectancy across continents (1967-2007)"),
  plotgrid.args = list(ncol = 1)
)
```

Can you please update all of your packages and then provide a reproducible example? 
Without that, it's hard for me to say what's going on.

**Comment by IndrajeetPatil** [comment]
Will re-open once `reprex` is provided.

**Comment by gaelhammer** [comment]
Thanks for the quick reply! All my packages are up to date. 
Here's the reprex with the incriminated warning bout `as_grob.default(plot)` at the end.

>``` r
# using ggstatsplot with the purrr package
# Indrajeet Patil
# 2021-02-10
# Source: vignettes/web_only/purrr_examples.Rmd
# https://indrajeetpatil.github.io/ggstatsplot/articles/web_only/purrr_examples.html

# install.packages("ggstatsplot")

# for reproducibility
library(ggstatsplot)
#> Registered S3 methods overwritten by 'lme4':
#>   method                          from
#>   cooks.distance.influence.merMod car 
#>   influence.merMod                car 
#>   dfbeta.influence.merMod         car 
#>   dfbetas.influence.merMod        car
#> In case you would like cite this package, cite it as:
#>      Patil, I. (2018). ggstatsplot: "ggplot2" Based Plots with Statistical Details. CRAN.
#>      Retrieved from https://cran.r-project.org/web/packages/ggstatsplot/index.html
set.seed(123)

# let's split the dataframe and create a list by years of interest
year_list <-
  gapminder::gapminder %>%
  dplyr::filter(.data = ., year %in% c(1967, 1987, 2007), continent != "Oceania") %>%
  split(x = ., f = .$year, drop = TRUE)

# checking the length of the list and the names of each element
length(year_list)
#> [1] 3
names(year_list)
#> [1] "1967" "1987" "2007"
str(year_list)
#> List of 3
#>  $ 1967: tibble [140 x 6] (S3: tbl_df/tbl/data.frame)
#>   ..$ country  : Factor w/ 142 levels "Afghanistan",..: 1 2 3 4 5 7 8 9 10 11 ...
#>   ..$ continent: Factor w/ 5 levels "Africa","Americas",..: 3 4 1 1 2 4 3 3 4 1 ...
#>   ..$ year     : int [1:140] 1967 1967 1967 1967 1967 1967 1967 1967 1967 1967 ...
#>   ..$ lifeExp  : num [1:140] 34 66.2 51.4 36 65.6 ...
#>   ..$ pop      : int [1:140] 11537966 1984060 12760499 5247469 22934225 7376998 202182 62821884 9556500 2427334 ...
#>   ..$ gdpPercap: num [1:140] 836 2760 3247 5523 8053 ...
#>  $ 1987: tibble [140 x 6] (S3: tbl_df/tbl/data.frame)
#>   ..$ country  : Factor w/ 142 levels "Afghanistan",..: 1 2 3 4 5 7 8 9 10 11 ...
#>   ..$ continent: Factor w/ 5 levels "Africa","Americas",..: 3 4 1 1 2 4 3 3 4 1 ...
#>   ..$ year     : int [1:140] 1987 1987 1987 1987 1987 1987 1987 1987 1987 1987 ...
#>   ..$ lifeExp  : num [1:140] 40.8 72 65.8 39.9 70.8 ...
#>   ..$ pop      : int [1:140] 13867957 3075321 23254956 7874230 31620918 7578903 454612 103764241 9870200 4243788 ...
#>   ..$ gdpPercap: num [1:140] 852 3739 5681 2430 9140 ...
#>  $ 2007: tibble [140 x 6] (S3: tbl_df/tbl/data.frame)
#>   ..$ country  : Factor w/ 142 levels "Afghanistan",..: 1 2 3 4 5 7 8 9 10 11 ...
#>   ..$ continent: Factor w/ 5 levels "Africa","Americas",..: 3 4 1 1 2 4 3 3 4 1 ...
#>   ..$ year     : int [1:140] 2007 2007 2007 2007 2007 2007 2007 2007 2007 2007 ...
#>   ..$ lifeExp  : num [1:140] 43.8 76.4 72.3 42.7 75.3 ...
#>   ..$ pop      : int [1:140] 31889923 3600523 33333216 12420476 40301927 8199783 708573 150448339 10392226 8078314 ...
#>   ..$ gdpPercap: num [1:140] 975 5937 6223 4797 12779 ...

# Now that we have the data divided into the three relevant years in a list
# we'll turn to purrr::pmap to create a list of ggplot objects that we'll make
# use of stored in plot_list. When you look at the documentation for ?pmap it
# will accept .l which is a list of lists. The length of .l determines the
# number of arguments that .f will be called with. List names will be used if
# present. .f is the function we want to apply (here, .f =
# ggstatsplot::ggbetweenstats).

# creating a list of plots
plot_list <-
  purrr::pmap(
    .l = list(
      data = year_list,
      x = "continent",
      y = "lifeExp",
      outlier.tagging = TRUE,
      outlier.label = "country",
      outlier.label.args = list(
        list(size = 3, color = "#56B4E9"),
        list(size = 2.5, color = "#009E73"),
        list(size = 3.5, color = "#F0E442")
      ),
      xlab = "Continent",
      ylab = "Life expectancy",
      title = list(
        "Year: 1967",
        "Year: 1987",
        "Year: 2007"
      ),
      type = list("r", "bf", "np"),
      pairwise.display = list("s", "ns", "all"),
      p.adjust.method = list("hommel", "bonferroni", "BH"),
      conf.level = list(0.99, 0.95, 0.90),
      k = list(1, 2, 3),
      effsize.type = list(
        NULL,
        "partial_omega",
        "partial_eta"
      ),
      plot.type = list("box", "boxviolin", "violin"),
      package = list("nord", "ochRe", "awtools"),
      palette = list("aurora", "parliament", "bpalette"),
      ggtheme = list(
        ggthemes::theme_stata(),
        ggplot2::theme_classic(),
        ggthemes::theme_fivethirtyeight()
      ),
      ggstatsplot.layer = list(FALSE, FALSE, TRUE)
    ),
    .f = ggstatsplot::ggbetweenstats
  )

# The final step is to pass the plot_list object we just created to the
# combine_plots function. While each of the 3 plots already has labeling
# information combine_plots gives us an opportunity to add additional details to
# the merged plots and specify the layout in rows and columns.

# combining all individual plots from the list into a single plot using combine_plots function
ggstatsplot::combine_plots(
  plotlist = plot_list,
  annotation.args = list(title = "Changes in life expectancy across continents (1967-2007)"),
  plotgrid.args = list(ncol = 1)
)
#> Warning in as_grob.default(plot): Cannot convert object of class list into a
#> grob.

#> Warning in as_grob.default(plot): Cannot convert object of class list into a
#> grob.
```

![](https://i.imgur.com/8HqQwRo.png)

<sup>Created on 2021-02-12 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

<details style="margin-bottom:10px;">
<summary>
Standard output and standard error
</summary>

``` sh
-- nothing to show --
```

</details>

**Comment by IndrajeetPatil** [comment]
Can you download the GitHub version of `ggstatsplot` and see if you can reproduce this behavior?

So run-

```r
remotes::install_github(
  repo = "IndrajeetPatil/ggstatsplot", 
  dependencies = TRUE, 
  upgrade_dependencies = TRUE
)
```
