### ISSUE TITLE
student t and correlation statistic not displaying in subtitle for ggscatterstats

### ISSUE THREAD

**Issue by DanSimonet** [IndrajeetPatil/ggstatsplot#528]
This is relatively minor but the t-student and pearson r prefix in the results subtitle for the `ggscatterstats` function is not displaying. I've tried removing plots, resizing, and trying on alternative machines but the subtitle always begins with just the df and has omitted the correlation statistic label. 

```r
ggscatterstats(cars,speed,dist)
```
The resulting image is

![image](https://user-images.githubusercontent.com/19256412/108125503-87b26780-7076-11eb-9c47-a319e0042a44.png)

**Comment by IndrajeetPatil** [comment]
What do you see if you run `remotes::install_github("easystats/parameters")`, and then restart the R session and run the same command again?

**Comment by DanSimonet** [comment]
Tried the reinstallation and rerun in a new R session and still produces the subtitle with the statistical tests omitted. Other functions do not encounter the same issue. For instance:

```r
ggbetweenstats(ToothGrowth, supp, len)
```
Produces the following

![image](https://user-images.githubusercontent.com/19256412/108127008-9a2da080-7078-11eb-8b49-85b5719e8151.png)

**Comment by IndrajeetPatil** [comment]
What do you see if you run 

```r
remotes::install_github("IndrajeetPatil/statsExpressions")
```

restart the R session, and then redo the same analysis?

**Comment by DanSimonet** [comment]
That solved the issue (see shot below)! Thank you very much. I really like the idea and output behind this package. 

![image](https://user-images.githubusercontent.com/19256412/108238827-50e05e00-7117-11eb-9a16-c03bee123bab.png)
