### ISSUE TITLE
name of variable x is ptinted instead of statistics

### ISSUE THREAD

**Issue by teindor** [IndrajeetPatil/ggstatsplot#531]
Hi,
I'm using this code:

```r
ggstatsplot::ggscatterstats(
  type = "p",
  data = d.p2, # dataframe from which variables are taken
  x = sex_comm_CM, # predictor/independent variable
  y = csb, # dependent variable
  xlab = "Quality of communication about sex with mothers", # label for the x-axis
  ylab = "CSBD", # label for the y-axis
  marginal.type = "density", # type of plot for marginal distribution
  xfill = "#42EADDFF",
  yfill = "#CDB599FF" # fill for marginals on the y-axis
)
```

It prints the name of the X variable and not the expected statistics. 
I updated `statsExpressions` using this code, with no help:

```r
remotes::install_github(
  repo = "IndrajeetPatil/statsExpressions", # package path on GitHub
  dependencies = TRUE, # installs packages which statsExpressions depends on
  upgrade_dependencies = TRUE,
force = TRUE # updates any out of date dependencies
)
```

![plot](https://user-images.githubusercontent.com/79282034/109191880-453c0980-779f-11eb-9337-f615890a1f13.png)

**Comment by IndrajeetPatil** [comment]
Hmm, hard to diagnoze this without [a reproducible example](https://reprex.tidyverse.org/). Can you post your data so that I can reproduce this?

**Comment by teindor** [comment]
same issue with this code:
ggscatterstats(
  data = ggplot2::msleep,
  x = sleep_rem,
  y = awake,
  xlab = "REM sleep (in hours)",
  ylab = "Amount of time spent awake (in hours)",
  title = "Understanding mammalian sleep",
  results.subtitle = T
)
![same issue with generic data](https://user-images.githubusercontent.com/79282034/109192739-491c5b80-77a0-11eb-9863-685fa1195c11.png)

**Comment by IndrajeetPatil** [comment]
Can update all your package, refresh R session, and then  post output for the following?

```r
library(ggstatsplot)
sessioninfo::sessioninfo()
```

**Comment by teindor** [comment]
I used a slightly different code as it made an error: sessioninfo::session_info()

- Session info -------------------------------------------------------
 setting  value                       
 version  R version 4.0.4 (2021-02-15)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  Hebrew_Israel.1255          
 ctype    Hebrew_Israel.1255          
 tz       Asia/Jerusalem              
 date     2021-02-25                  

- Packages -----------------------------------------------------------
 package              * version    date       lib
 abind                  1.4-5      2016-07-21 [1]
 afex                   0.28-1     2021-01-12 [1]
 AnnotationDbi        * 1.52.0     2020-10-27 [1]
 AnnotationFilter       1.14.0     2020-10-27 [1]
 askpass                1.1        2019-01-13 [1]
 assertthat             0.2.1      2019-03-21 [1]
 backports              1.2.1      2020-12-09 [1]
 base64enc              0.1-3      2015-07-28 [1]
 BayesFactor            0.9.12-4.3 2021-02-25 [1]
 bayestestR             0.8.2      2021-01-26 [1]
 Biobase              * 2.50.0     2020-10-27 [1]
 BiocFileCache          1.14.0     2020-10-27 [1]
 BiocGenerics         * 0.36.0     2020-10-27 [1]
 BiocManager            1.30.10    2019-11-16 [1]
 BiocParallel           1.24.1     2020-11-06 [1]
 biomaRt                2.46.3     2021-02-09 [1]
 Biostrings             2.58.0     2020-10-27 [1]
 biovizBase             1.38.0     2020-10-27 [1]
 bit                    4.0.4      2020-08-04 [1]
 bit64                  4.0.5      2020-08-30 [1]
 bitops                 1.0-6      2013-08-17 [1]
 blob                   1.2.1      2020-01-20 [1]
 boot                   1.3-27     2021-02-12 [1]
 BSgenome               1.58.0     2020-10-27 [1]
 BWStest                0.2.2      2018-10-18 [1]
 cachem                 1.0.4      2021-02-13 [1]
 car                    3.0-10     2020-09-29 [1]
 carData                3.0-4      2020-05-22 [1]
 cellranger             1.1.0      2016-07-27 [1]
 checkmate              2.0.0      2020-02-06 [1]
 cli                    2.3.1      2021-02-23 [1]
 cluster                2.1.1      2021-02-14 [1]
 coda                   0.19-4     2020-09-30 [1]
 codetools              0.2-18     2020-11-04 [1]
 colorspace             2.0-0      2020-11-11 [1]
 correlation            0.6.0      2021-02-12 [1]
 cowplot                1.1.1      2020-12-30 [1]
 crayon                 1.4.1      2021-02-08 [1]
 curl                   4.3        2019-12-02 [1]
 data.table             1.14.0     2021-02-21 [1]
 DBI                    1.1.1      2021-01-15 [1]
 dbplyr                 2.1.0      2021-02-03 [1]
 DelayedArray           0.16.1     2021-01-22 [1]
 dichromat              2.0-0      2013-01-24 [1]
 digest                 0.6.27     2020-10-24 [1]
 dplyr                  1.0.4      2021-02-02 [1]
 effectsize             0.4.3      2021-01-18 [1]
 ellipsis               0.3.1      2020-05-15 [1]
 emmeans              * 1.5.4      2021-02-03 [1]
 ensembldb              2.14.0     2020-10-27 [1]
 estimability           1.3        2018-02-11 [1]
 fansi                  0.4.2      2021-01-15 [1]
 fastmap                1.1.0      2021-01-25 [1]
 forcats                0.5.1      2021-01-27 [1]
 foreign                0.8-81     2020-12-22 [1]
 Formula                1.2-4      2020-10-16 [1]
 generics               0.1.0      2020-10-31 [1]
 GenomeInfoDb         * 1.26.2     2020-12-08 [1]
 GenomeInfoDbData       1.2.4      2021-02-18 [1]
 GenomicAlignments      1.26.0     2020-10-27 [1]
 GenomicFeatures      * 1.42.1     2020-11-13 [1]
 GenomicRanges        * 1.42.0     2020-10-27 [1]
 ggcorrplot             0.1.3      2019-05-19 [1]
 ggExtra                0.9        2019-08-27 [1]
 ggplot2                3.3.3      2020-12-30 [1]
 ggrepel                0.9.1      2021-01-15 [1]
 ggsignif               0.6.1      2021-02-23 [1]
 ggstatsplot          * 0.7.0      2021-02-19 [1]
 glue                   1.4.2      2020-08-27 [1]
 gmp                    0.6-2      2021-01-07 [1]
 graph                  1.68.0     2020-10-27 [1]
 gridExtra              2.3        2017-09-09 [1]
 gtable                 0.3.0      2019-03-25 [1]
 gtools                 3.8.2      2020-03-31 [1]
 Gviz                 * 1.34.0     2020-10-27 [1]
 haven                  2.3.1      2020-06-01 [1]
 Hmisc                  4.4-2      2020-11-29 [1]
 hms                    1.0.0      2021-01-13 [1]
 htmlTable              2.1.0      2020-09-16 [1]
 htmltools              0.5.1.1    2021-01-22 [1]
 htmlwidgets            1.5.3      2020-12-10 [1]
 httpuv                 1.5.5      2021-01-13 [1]
 httr                   1.4.2      2020-07-20 [1]
 insight                0.13.1     2021-02-22 [1]
 ipmisc                 6.0.0      2021-02-13 [1]
 IRanges              * 2.24.1     2020-12-12 [1]
 jpeg                   0.1-8.1    2019-10-24 [1]
 knitr                  1.31       2021-01-27 [1]
 kSamples               1.2-9      2019-05-20 [1]
 later                  1.1.0.1    2020-06-05 [1]
 lattice                0.20-41    2020-04-02 [1]
 latticeExtra           0.6-29     2019-12-19 [1]
 lavaan                 0.6-7      2020-07-31 [1]
 lazyeval               0.2.2      2019-03-15 [1]
 lifecycle              1.0.0      2021-02-15 [1]
 lme4                   1.1-26     2020-12-01 [1]
 lmerTest               3.1-3      2020-10-23 [1]
 magrittr               2.0.1      2020-11-17 [1]
 MASS                   7.3-53.1   2021-02-12 [1]
 Matrix                 1.3-2      2021-01-06 [1]
 MatrixGenerics         1.2.1      2021-01-30 [1]
 MatrixModels           0.4-1      2015-08-22 [1]
 matrixStats            0.58.0     2021-01-29 [1]
 mc2d                   0.1-18     2017-03-06 [1]
 memoise                2.0.0      2021-01-26 [1]
 mime                   0.10       2021-02-13 [1]
 miniUI                 0.1.1.1    2018-05-18 [1]
 minqa                  1.2.4      2014-10-09 [1]
 mnormt                 2.0.2      2020-09-01 [1]
 multcomp               1.4-16     2021-02-08 [1]
 multcompView           0.1-8      2019-12-19 [1]
 munsell                0.5.0      2018-06-12 [1]
 mvtnorm                1.1-1      2020-06-09 [1]
 nlme                   3.1-152    2021-02-04 [1]
 nloptr                 1.2.2.2    2020-07-02 [1]
 nnet                   7.3-15     2021-01-24 [1]
 numDeriv               2016.8-1.1 2019-06-06 [1]
 openssl                1.4.3      2020-09-18 [1]
 openxlsx               4.2.3      2020-10-27 [1]
 OrganismDbi          * 1.32.0     2020-10-27 [1]
 pairwiseComparisons    3.1.3      2021-02-03 [1]
 paletteer              1.3.0      2021-01-06 [1]
 parameters             0.12.0.1   2021-02-25 [1]
 patchwork              1.1.1      2020-12-17 [1]
 pbapply                1.4-3      2020-08-18 [1]
 pbivnorm               0.6.0      2015-01-23 [1]
 performance            0.7.0      2021-02-03 [1]
 pillar                 1.5.0      2021-02-22 [1]
 pkgconfig              2.0.3      2019-09-22 [1]
 plyr                   1.8.6      2020-03-03 [1]
 PMCMRplus              1.9.0      2021-01-15 [1]
 png                    0.1-7      2013-12-03 [1]
 prettyunits            1.1.1      2020-01-24 [1]
 progress               1.2.2      2019-05-16 [1]
 promises               1.2.0.1    2021-02-11 [1]
 ProtGenerics           1.22.0     2020-10-27 [1]
 purrr                  0.3.4      2020-04-17 [1]
 R6                     2.5.0      2020-10-28 [1]
 rappdirs               0.3.3      2021-01-31 [1]
 RBGL                   1.66.0     2020-10-27 [1]
 RColorBrewer           1.1-2      2014-12-07 [1]
 Rcpp                   1.0.6      2021-01-15 [1]
 RCurl                  1.98-1.2   2020-04-18 [1]
 readxl                 1.3.1      2019-03-13 [1]
 rematch2               2.1.2      2020-05-01 [1]
 reshape                0.8.8      2018-10-23 [1]
 reshape2               1.4.4      2020-04-09 [1]
 rio                    0.5.16     2018-11-26 [1]
 rlang                  0.4.10     2020-12-30 [1]
 Rmpfr                  0.8-2      2020-11-11 [1]
 rpart                  4.1-15     2019-04-12 [1]
 Rsamtools              2.6.0      2020-10-27 [1]
 RSQLite                2.2.3      2021-01-24 [1]
 rstudioapi             0.13       2020-11-12 [1]
 rtracklayer            1.50.0     2020-10-27 [1]
 S4Vectors            * 0.28.1     2020-12-09 [1]
 sandwich               3.0-0      2020-10-02 [1]
 scales                 1.1.1      2020-05-11 [1]
 sessioninfo            1.1.1      2018-11-05 [1]
 shiny                  1.6.0      2021-01-25 [1]
 statmod                1.4.35     2020-10-19 [1]
 statsExpressions       1.0.0.9000 2021-02-25 [1]
 stringi                1.5.3      2020-09-09 [1]
 stringr                1.4.0      2019-02-10 [1]
 SummarizedExperiment   1.20.0     2020-10-28 [1]
 SuppDists              1.1-9.5    2020-01-18 [1]
 survival               3.2-7      2020-09-28 [2]
 TH.data                1.0-10     2019-01-21 [1]
 tibble                 3.0.6      2021-01-29 [1]
 tidyr                  1.1.2      2020-08-27 [1]
 tidyselect             1.1.0      2020-05-11 [1]
 tinytex                0.29       2021-01-21 [1]
 tmvnsim                1.0-2      2016-12-15 [1]
 utf8                   1.1.4      2018-05-24 [1]
 VariantAnnotation      1.36.0     2020-10-28 [1]
 vctrs                  0.3.6      2020-12-17 [1]
 withr                  2.4.1      2021-01-26 [1]
 WRS2                   1.1-1      2021-02-15 [1]
 xfun                   0.21       2021-02-10 [1]
 XML                    3.99-0.5   2020-07-23 [1]
 xml2                   1.3.2      2020-04-23 [1]
 xtable                 1.8-4      2019-04-21 [1]
 XVector                0.30.0     2020-10-28 [1]
 yaml                   2.2.1      2020-02-01 [1]
 zeallot                0.1.0      2018-01-28 [1]
 zip                    2.1.1      2020-08-27 [1]
 zlibbioc               1.36.0     2020-10-28 [1]
 zoo                    1.8-8      2020-05-02 [1]
 source                                          
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 Bioconductor                                    
 Bioconductor                                    
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 Github (richarddmorey/BayesFactor@4526244)      
 CRAN (R 4.0.3)                                  
 Bioconductor                                    
 Bioconductor                                    
 Bioconductor                                    
 CRAN (R 4.0.3)                                  
 Bioconductor                                    
 Bioconductor                                    
 Bioconductor                                    
 Bioconductor                                    
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 Bioconductor                                    
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.4)                                  
 CRAN (R 4.0.4)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.4)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 Bioconductor                                    
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 Bioconductor                                    
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 Bioconductor                                    
 Bioconductor                                    
 Bioconductor                                    
 Bioconductor                                    
 Bioconductor                                    
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.4)                                  
 CRAN (R 4.0.4)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 Bioconductor                                    
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 Bioconductor                                    
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.4)                                  
 CRAN (R 4.0.3)                                  
 Bioconductor                                    
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.4)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 Bioconductor                                    
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 Bioconductor                                    
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 Github (easystats/parameters@606066e)           
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.4)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 Bioconductor                                    
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 Bioconductor                                    
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 Bioconductor                                    
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 Bioconductor                                    
 Bioconductor                                    
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 Github (IndrajeetPatil/statsExpressions@0c3c1fd)
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 Bioconductor                                    
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.4)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 Bioconductor                                    
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.4)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 Bioconductor                                    
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 CRAN (R 4.0.3)                                  
 Bioconductor                                    
 CRAN (R 4.0.3)                                  

[1] C:/Users/teind/OneDrive/Documents/R/win-library/4.0
[2] C:/Program Files/R/R-4.0.4/library

**Comment by IndrajeetPatil** [comment]
Can you actually download the GitHub version of `ggstatspot` and see if the issue persists?

**Comment by IndrajeetPatil** [comment]
`statsExpressions` on `GitHub` is not compatible with `CRAN` version of `ggstatsplot`, and I think that's why this is not working for you.

**Comment by teindor** [comment]
I'm used this code:

remotes::install_github(
  repo = "IndrajeetPatil/ggstatsplot", # package path on GitHub
  dependencies = TRUE, # installs packages which ggstatsplot depends on
  upgrade_dependencies = TRUE ,
  force = TRUE# updates any out of date dependencies
)

Now it works perfectly !
Thank you 
![correct plot](https://user-images.githubusercontent.com/79282034/109196497-710dbe00-77a4-11eb-8782-6ce8ddf077b5.png)
