### ISSUE TITLE
sample.size.label removal in ggbarstats

### ISSUE THREAD

**Issue by Eduardo-Auer** [IndrajeetPatil/ggstatsplot#538]
I want to remove sample.size.label in a plot created by ggbarstats. I  could not found any argument in ggbarstats to remove sample.size.label. Is it possible to remove it?

**Comment by IndrajeetPatil** [comment]
You can simply delete the layer corresponding to the sample size labels:

``` r
library(ggstatsplot)
#> In case you would like cite this package, cite it as:
#>      Patil, I. (2018). ggstatsplot: "ggplot2" Based Plots with Statistical Details. CRAN.
#>      Retrieved from https://cran.r-project.org/web/packages/ggstatsplot/index.html
library(gginnards)
#> Loading required package: ggplot2

p <- ggbarstats(mtcars, am, cyl)
#> Warning in (function (x, y = NULL, correct = TRUE, p = rep(1/length(x), : Chi-
#> squared approximation may be incorrect

delete_layers(p, "GeomText")
```

![](https://i.imgur.com/L4Wq6G5.png)

<sup>Created on 2021-03-13 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>
