### ISSUE TITLE
Setting significance level for ggstatsplot::ggwithinstats

### ISSUE THREAD

**Issue by as116** [IndrajeetPatil/ggstatsplot#541]
Hey, 
is it possible to change the significance level for ggstatsplot:ggwithinstats?  
I've seen that the confidence level can be set. But the alpha value is not adjusted accordingly.

Thanks!

**Comment by IndrajeetPatil** [comment]
Unfortunately, no, the alpha can't be adjusted for any of the tests supported in this package, except for `ggcorrmat`.

I would suggest reporting the alpha separately to draw the reader's attention to the significance level used.
