### ISSUE TITLE
Question: Alpha Level Correction

### ISSUE THREAD

**Issue by M-Colley** [IndrajeetPatil/ggstatsplot#542]
Hey there, I have a study in which we have a 2 factorial design ( 6 x 3 within-subjects design; thus 18 conditions). We want to do a Friedman's test for each of the 6 levels of the first factor, thus, always comparing three means. 

I believe that for this, I have to adjust my alpha level to 0.05 / 6 (because of the 6 levels of the first factor). However, I would love to still use your great ggwithinstats-function. Is there a way to adjust the alpha level? I sadly did not find this option. Otherwise, this might be an interesting idea to be changeable?

Kind regards!

**Comment by IndrajeetPatil** [comment]
Hmm, same as https://github.com/IndrajeetPatil/ggstatsplot/issues/541. 

No, there is no way to adjust alpha if you use `grouped_` functions (e.g., `grouped_ggwithinstats`). You will have to just report in the paper/article/report, what your adjusted alpha is.

So, for example, in the example below 2 test are being carried out, so the alpha is going to be `0.05/2 = 0.025`. So, when you describe the _Methods_ section, you can mention that only those tests should be considered significant where `p < 0.025`. Or you can even mention this in the caption.

<img width="878" alt="Screenshot 2021-03-17 at 19 51 42" src="https://user-images.githubusercontent.com/11330453/111522171-4b982280-875a-11eb-9ccc-6ff1b1c31423.png">
