### ISSUE TITLE
Mismatch in correlation coeff obtained through ggcorrmat and ggscatterstats

### ISSUE THREAD

**Issue by tspriyan** [IndrajeetPatil/ggstatsplot#543]
I used "ggcorrmat" function to obtain the correlation matrix between variables and I used the "ggscatterstats" to visualize the correlation between two variables. There is a mismatch between the correlation coeff and P value displayed in  "ggcorrmat" function and the coeff obtained through "ggscatterstats"

A reproducible example:

Step1: The correlation matrix was obtained using "ggcorrmat" function

```r
set.seed(123)

  ggstatsplot:: ggcorrmat(
  data = ggplot2::msleep,
  type = 'robust',
  colors = c("#B2182B", "white", "#4D4D4D"),
  title = "Correlalogram for mammals sleep dataset",
  subtitle = "sleep units: hours; weight units: kilograms",
  p.adjust.method = "none",
)
```

Step2: In the correlation matrix, the correlation coeff b/w sleep_rem and bodywt is -0.35 and it is not significant at 0.05 level. But if we scatter plot these variables through "ggscatterstats" we obtain: r = -0.37 and P = 0.003. 

```r
set.seed(123)

  ggstatsplot:: ggscatterstats(
    data = ggplot2::msleep,
    x = bodywt,
    y = sleep_rem,
    xlab = "Brain Weight",
    ylab = "Sleep REM",
    title = "Correlation b/w brain weight and sleep REM",
    bf.message = FALSE,
    type = "robust"
  )
```

Similarly,
Step3:In the correlation matrix, the correlation coeff b/w awake and  sleep_rem is -0.56 and it is significant at 0.05 level. But if we scatter plot these variables through "ggscatterstats" we obtain: r = -0.72 and P < 0.001.

```r
set.seed(123)

  ggstatsplot:: ggscatterstats(
    data = ggplot2::msleep,
    x = awake,
    y = sleep_rem,
    xlab = "awake",
    ylab = "sleep_rem",
    title = "Correlation b/w awake and sleep_rem",
    bf.message = FALSE,
    type = "robust",
    
  )
```

Similarly,
Step4:In the correlation matrix, the correlation coeff b/w awake and  sleep_cycle is 0.56 and it is significant at 0.05 level. But if we scatter plot these variables through "ggscatterstats" we obtain: r = 0.45 and P < 0.011.

```r
set.seed(123)

  ggstatsplot:: ggscatterstats(
    data = ggplot2::msleep,
    x = awake,
    y = sleep_cycle,
    xlab = "awake",
    ylab = "sleep_cycle",
    title = "Correlation b/w awake and sleep_cycle",
    bf.message = FALSE,
    type = "robust",
    
  )
```
The issue was obtained with "Winsorized Pearson correlation coefficient" method. 

Other details:
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.7 LTS

ggstatsplot version:  ggstatsplot_0.7.0

**Comment by IndrajeetPatil** [comment]
``` r
library(ggstatsplot)
#> In case you would like cite this package, cite it as:
#>      Patil, I. (2018). ggstatsplot: "ggplot2" Based Plots with Statistical Details. CRAN.
#>      Retrieved from https://cran.r-project.org/web/packages/ggstatsplot/index.html

set.seed(123)
ggcorrmat(
  data = ggplot2::msleep,
  type = "robust",
  p.adjust.method = "none"
)
```

![](https://i.imgur.com/LykuC56.png)

``` r
set.seed(123)
ggscatterstats(
  data = ggplot2::msleep,
  x = bodywt,
  y = sleep_rem,
  type = "robust",
  output = "subtitle"
)
#> paste(italic("t")["Student"], "(", "59", ") = ", "-3.10", ", ", 
#>     italic("p"), " = ", "0.003", ", ", widehat(italic("r"))["Winsorized"], 
#>     " = ", "-0.37", ", CI"["95%"], " [", "-0.57", ", ", "-0.14", 
#>     "]", ", ", italic("n")["pairs"], " = ", "61")

set.seed(123)
ggscatterstats(
  data = ggplot2::msleep,
  x = awake,
  y = sleep_rem,
  type = "robust",
  output = "subtitle"
)
#> paste(italic("t")["Student"], "(", "59", ") = ", "-7.87", ", ", 
#>     italic("p"), " = ", "9.12e-11", ", ", widehat(italic("r"))["Winsorized"], 
#>     " = ", "-0.72", ", CI"["95%"], " [", "-0.82", ", ", "-0.57", 
#>     "]", ", ", italic("n")["pairs"], " = ", "61")

set.seed(123)
ggscatterstats(
  data = ggplot2::msleep,
  x = awake,
  y = sleep_cycle,
  type = "robust",
  output = "subtitle"
)
#> paste(italic("t")["Student"], "(", "30", ") = ", "2.72", ", ", 
#>     italic("p"), " = ", "0.011", ", ", widehat(italic("r"))["Winsorized"], 
#>     " = ", "0.45", ", CI"["95%"], " [", "0.11", ", ", "0.69", 
#>     "]", ", ", italic("n")["pairs"], " = ", "32")
```

<sup>Created on 2021-03-18 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by IndrajeetPatil** [comment]
Thanks, will have a closer look later.

**Comment by IndrajeetPatil** [comment]
Trace to https://github.com/easystats/correlation/issues/151.

Closing in favor of that issue.

**Comment by IndrajeetPatil** [comment]
Can you please install GitHub version of `correlation` package and see that this has been resolved?

```r
remotes::install_github("easystats/correlation")
```

**Comment by tspriyan** [comment]
@IndrajeetPatil I installed the GitHub version of correlation package and the issue is solved now.
Was the difference due to how NAs are omitted? My data did have many NAs.
Thanks for this speedy bug fix.

**Comment by IndrajeetPatil** [comment]
Yepp, exactly. It was doing `NA` omission for all data, instead of for each pair.
