### ISSUE TITLE
Setting `map_signif_level` in `ggsignif.args`

### ISSUE THREAD

**Issue by kulbhushanchand** [IndrajeetPatil/ggstatsplot#544]
Hi,

Is there any way I can pass `map_signif_level` in `ggsignif.args`?

As per the documentation, I tried passing the argument as 
`ggsignif.args = list(map_signif_level = c("***"=0.001, "**"=0.01, "*"=0.05))`

and error is
`formal argument "map_signif_level" matched by multiple actual arguments`

**Comment by IndrajeetPatil** [comment]
Yes, this is because `ggstatsplot` defaults to displaying exact p-values or logged Bayes Factor values for pairwise comparisons. But what if you wish to adopt a different annotation labels? For example, showing asterisks in your case.

You will have to customize them using `pairwiseComparisons` and `ggsignif:`

``` r
# needed libraries
set.seed(123)
library(ggplot2)
library(pairwiseComparisons)
library(ggsignif)
library(ggstatsplot)

# converting to factor
mtcars$cyl <- as.factor(mtcars$cyl)

# creating a basic plot
p <- ggbetweenstats(mtcars, cyl, wt, pairwise.comparisons = FALSE)

# using `pairwiseComparisons` package to create a dataframe with results
set.seed(123)
(df <-
    pairwise_comparisons(mtcars, cyl, wt) %>%
    dplyr::mutate(groups = purrr::pmap(.l = list(group1, group2), .f = c)) %>%
    dplyr::arrange(group1) %>%
    dplyr::mutate(asterisk_label = c("**", "***", "**")))
#> # A tibble: 3 x 13
#>   group1 group2 statistic  p.value alternative method  distribution p.adjustment
#>   <chr>  <chr>      <dbl>    <dbl> <chr>       <chr>   <chr>        <chr>       
#> 1 4      6           5.39  8.31e-3 two.sided   Games-… q            none        
#> 2 4      8           9.11  1.24e-5 two.sided   Games-… q            none        
#> 3 6      8           5.12  8.31e-3 two.sided   Games-… q            none        
#> # … with 5 more variables: test.details <chr>, p.value.adjustment <chr>,
#> #   label <chr>, groups <list>, asterisk_label <chr>

# adding pairwise comparisons using `ggsignif`
p +
  ggsignif::geom_signif(
    comparisons = df$groups,
    map_signif_level = TRUE,
    annotations = df$asterisk_label,
    y_position = c(5.5, 5.75, 6.0),
    test = NULL,
    na.rm = TRUE
  )
```

![](https://i.imgur.com/rKCP3Kj.png)

<sup>Created on 2021-03-22 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by kulbhushanchand** [comment]
You have showed the straightforward path. 
Also, in the meantime, I browsed the source of `ggstatplot` and replicated the basic `ggplot` layers to achieve the desired results.
Thanks for the help.

**Comment by zhakota** [comment]
Hello!
Is there no simpler code for ggsignif.args?
