### ISSUE TITLE
updating scales for `gghistostats` removes centrality annotation and secondary y-axis

### ISSUE THREAD

**Issue by IndrajeetPatil** [IndrajeetPatil/ggstatsplot#546]
``` r
set.seed(123)
library(ggstatsplot)

# plot
gghistostats(
  data = iris,
  x = Sepal.Length,
  test.value = 5,
  ggplot.component = list(
    ggplot2::scale_x_continuous(breaks = seq(3, 9, 1), limits = (c(3, 9))),
    ggplot2::scale_y_continuous(breaks = seq(0, 25, 5), limits = (c(0, 25)))
  )
)
#> Scale for 'x' is already present. Adding another scale for 'x', which will
#> replace the existing scale.
#> Scale for 'y' is already present. Adding another scale for 'y', which will
#> replace the existing scale.
#> Warning: Removed 2 rows containing missing values (geom_bar).
```

![](https://i.imgur.com/F7oFmii.png)

<sup>Created on 2021-03-23 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by IndrajeetPatil** [comment]
Oh, this is to be expected! Both the secondary `x`-axis and `y`-axis are transformations of the primary axes. 
So if the primary axes change, the secondary axes will also refresh and will remove the prior information (breaks and labels).

This is something that is often needed in `grouped_` context, and needs to be supported.

**Comment by paulHasselkuss** [comment]
Thank you for your efforts on this package!

Unfortunately, I'm encountering the same issue once again as of version 0.12.2. Is there a way to update the scales while retaining annotations and the right y-scale, or was this issue never resolved?
