### ISSUE TITLE
Expand/Use manual color palette

### ISSUE THREAD

**Issue by Rokis1990** [IndrajeetPatil/ggstatsplot#547]
First of all, thank you for this great package!

The area to improve, in my opinion, would be to add more colors to the color palette. I was testing out the `ggbarstats()` function with some survey responses and found that when there are more than 8 levels in either the `x` or `y` variable, I get white areas in the stacked bar chart.

Now, I see in the help file of the `ggbarstats()` function, that I can specify a `palette` from the `RColorBrewer` package. However, sometimes we need to use custom color palettes. When I tried pasting in a custom list of HEX color codes, I got an error message:

```r
ggbarstats(data_exp, Q019_1_lik, D5_dim, palette = cbbPalette) + coord_flip()
Error in palette_df$length[[1]] : subscript out of bounds
In addition: Warning messages:
1: In (function (x, y = NULL, correct = TRUE, p = rep(1/length(x),  :
  Chi-squared approximation may be incorrect
2: In palette == c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442",  :
  longer object length is not a multiple of shorter object length
```

Is this a known issue, or am I doing something wrong?
If It is possible, it would be nice to have the ability to add a manual color palette, just like in a regular ggplot.

**Comment by IndrajeetPatil** [comment]
Yes, you can manually change the colors using `ggplot2` functions, and not using the `palette` argument:

``` r
# needed libraries
set.seed(123)
library(ggstatsplot)
library(ggplot2)

ggbarstats(mtcars, am, cyl, results.subtitle = FALSE) +
  scale_fill_manual(values = c("#E7298A", "#66A61E"))
#> Scale for 'fill' is already present. Adding another scale for 'fill', which
#> will replace the existing scale.
```

![](https://i.imgur.com/QygbOgP.png)

<sup>Created on 2021-03-25 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

If you read the docs, you will notice that the `palette` is taken from the given `package` in which that palette lies. This is why your call fails.

<img width="846" alt="Screenshot 2021-03-25 at 16 37 48" src="https://user-images.githubusercontent.com/11330453/112500261-84528000-8d88-11eb-8574-36cc18051a7a.png">
