### ISSUE TITLE
Correct way to rearrange x variable

### ISSUE THREAD

**Issue by kulbhushanchand** [IndrajeetPatil/ggstatsplot#551]
I've also posted the [question on stackoverflow](https://stackoverflow.com/questions/66866635/correct-way-to-rearrange-x-variable-for-multiple-ggplot-layer-in-ggstatsplot-p), but I thought, here is the best place to ask.

I tried to rearrange the x variable in the custom order as `Wine B`, `Wine A` and `Wine C`, instead of default order.
**Problem** is that the ggline/ggpath (another layer of ggplot) connecting the means, doesn't arranged in the given order.

```
library(WRS2)
ggstatsplot::ggwithinstats(
  data = WineTasting,
  x = Wine,
  y = Taste,
  type = "np", # non-parametric test
  pairwise.comparisons = TRUE,
  ggplot.component = list(scale_x_discrete(limits=c("Wine B", "Wine A", "Wine C")))
)
```
In the cropped output below, you can see that the red line connecting means, starts from `Wine A`, instead of the provided order.

![image](https://user-images.githubusercontent.com/17742733/112952618-4ffd0c00-915a-11eb-93cc-b062b27401f8.png)

**Workaround** -
Currently, the workaround I'm using, is to manually name the columns in the data frame, in ascending order , before passing to the `ggwithinstats`, i.e. `1.Wine B`, `2.Wine A` and `3.Wine C`. This looks silly, but works.
Can you guide the correct wat to do this in `ggstatsplot`?

Thanks

**Comment by kulbhushanchand** [comment]
Solved at stackoverflow. I just have to relevel the factors.

```
WineTasting$Wine <- factor(WineTasting$Wine, levels = c("Wine C", "Wine A", "Wine B"))
ggwithinstats(
  data = WineTasting,
  x = Wine,
  y = Taste,
  type = "np", # non-parametric test
  pairwise.comparisons = TRUE
)
```

Apologies for being hasty to file the issue.

**Comment by IndrajeetPatil** [comment]
No worries. I am glad it got resolved!
