### ISSUE TITLE
Error: grouping factor must have exactly 2 levels

### ISSUE THREAD

**Issue by ShixiangWang** [IndrajeetPatil/ggstatsplot#559]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

----

When using `grouped_ggbetweenstats`, I always encount errors due to limited samples in splitted groups. For example, the following example shows an error "grouping factor must have exactly 2 levels".

The statistical test in this tool seems could not be disabled. Based on my use, I want the program more intelligent, i.e. when the sample size is enough for a category A in the group, the statistical test is performed, while if the sample size is not enough for a category B in the group, don't perform the test and just show the plot.

```r
library(ggstatsplot)

df <- data.frame(
  x = c(rep(1, 50), rep(2, 40), rep(3, 10)),
  y = rnorm(100),
  g = c(rep("a", 49), rep("b", 51))
)

grouped_ggbetweenstats(
  data = df,
  x = x,
  y = y,
  grouping.var = g
)

```

Best,

Shixiang

**Comment by IndrajeetPatil** [comment]
Thanks for the bug report.

In general, the statistical analysis can be turned off by setting `results.subtitle = FALSE`.

But, I agree, that it is rather painful to run into this error in the `grouped_` context and to then track down which grouping level is causing the issue.

Now the functions are more robust to such contexts and just return empty subtitle/caption.

``` r
library(ggstatsplot)

df <- data.frame(
  x = c(rep(1, 50), rep(2, 40), rep(3, 10)),
  y = rnorm(100),
  g = c(rep("a", 49), rep("b", 51))
)

grouped_ggbetweenstats(
  data = df,
  x = x,
  y = y,
  grouping.var = g
)
```

![](https://i.imgur.com/oAk3SRO.png)

<sup>Created on 2021-04-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by ShixiangWang** [comment]
@IndrajeetPatil Great work, thanks :)
