### ISSUE TITLE
`theme_wsj()` doesn't work with ggstatsplot layer

### ISSUE THREAD

**Issue by IndrajeetPatil** [IndrajeetPatil/ggstatsplot#56]
``` r
# doesn't work
ggstatsplot::ggscatterstats(
  data = iris,
  x = Sepal.Length,
  y = Petal.Width,
  ggtheme = ggthemes::theme_wsj(),
  ggstatsplot.layer = TRUE
)
#> Error in unit(rep(just$hjust, n), "npc"): 'x' and 'units' must have length > 0

# works
ggstatsplot::ggscatterstats(
  data = iris,
  x = Sepal.Length,
  y = Petal.Width,
  ggtheme = ggthemes::theme_wsj(),
  ggstatsplot.layer = FALSE
)
#> Warning: The plot is not a `ggplot` object and therefore can't be further modified with `ggplot2` functions.
#> 
```

![](https://i.imgur.com/PbEE1jO.png)

<sup>Created on 2018-09-25 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by ibecav** [comment]
Sorry, this one is beyond me.  Almost every other theme I try seems to work just fine.

Only suggestion I can make is to insert the following error-trapping code...

`  if (isTRUE(ggstatsplot.layer) && deparse(substitute(ggtheme)) == "ggthemes::theme_wsj()") { stop("Sorry, at this point you can not combine the WSJ theme with ggstatplot.layer")}
`
like so in theme_ggstatsplot.R

`
theme_ggstatsplot <- function(ggtheme = ggplot2::theme_bw(), ggstatsplot.layer = TRUE) {

      if (isTRUE(ggstatsplot.layer) && deparse(substitute(ggtheme)) == "ggthemes::theme_wsj()") { stop("Sorry, at this point you can not combine the WSJ theme with ggstatplot.layer")}
      if (isTRUE(ggstatsplot.layer)) {

    ggtheme +
`

**Comment by IndrajeetPatil** [comment]
This should be resolved on the `ggthemes` front soon-
https://github.com/jrnold/ggthemes/issues/101

**Comment by IndrajeetPatil** [comment]
Not `ggstatsplot` issue, so gonna close this.
