### ISSUE TITLE
Yates' correction on ggbarstats

### ISSUE THREAD

**Issue by Eduardo-Auer** [IndrajeetPatil/ggstatsplot#560]
Is there a way to use Yates' correction in χ2 square test from the `ggbarstats `function?

**Comment by IndrajeetPatil** [comment]
Hi,

No, the chi-squared tests do not allow Yates' correction. There are good reasons to now apply this correction. You can find references in this video: https://www.youtube.com/watch?v=UrHq1a59j1Y&ab_channel=how2stats
