### ISSUE TITLE
Error: package or namespace load failed for ‘ggstatsplot’:  object ‘specify_decimal_p’ is not exported by 'namespace:ipmisc'

### ISSUE THREAD

**Issue by martynagalazka** [IndrajeetPatil/ggstatsplot#561]
Hi, 

I'm getting the following error when uploading the ggstatsplot package. 
I installed groupedstats but the problem persists. 

Error: package or namespace load failed for ‘ggstatsplot’:
 object ‘specify_decimal_p’ is not exported by 'namespace:ipmisc'

Thanks

**Comment by IndrajeetPatil** [comment]
Hi,

You just need to update *all* of your packages. This error is due to some dependencies being out of date.
