### ISSUE TITLE
JOSS review: gghistostats

### ISSUE THREAD

**Issue by kevinrue** [IndrajeetPatil/ggstatsplot#577]
I'm running into an error running some code from the README.

Namely

```r
gghistostats(
  data = ggplot2::msleep, # dataframe from which variable is to be taken
  x = awake, # numeric variable whose distribution is of interest
  title = "Amount of time spent awake", # title for the plot
  caption = substitute(paste(italic("Source: "), "Mammalian sleep data set")),
  test.value = 12, # default value is 0
  binwidth = 1, # binwidth value (experiment)
  ggtheme = hrbrthemes::theme_ipsum_tw(), # choosing a different theme
  ggstatsplot.layer = FALSE # turn off ggstatsplot theme layer
)
```

The error is 

```
Error in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y,  : 
  polygon edge not found
In addition: Warning messages:
1: In min(x) : no non-missing arguments to min; returning Inf
2: In max(x) : no non-missing arguments to max; returning -Inf
3: In grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y,  :
  no font could be found for family "Titillium Web"
```

I'm not sure yet whether the error relates to the polygon edge, the font that cannot be found, or both.

****

For https://github.com/openjournals/joss-reviews/issues/3167

**Comment by kevinrue** [comment]
I solved it by installing the font from https://fonts.google.com/specimen/Titillium+Web

**Comment by kevinrue** [comment]
I'll let you decide whether this should be documented anywhere, or whether it's OK to close the issue as it is.

**Comment by IndrajeetPatil** [comment]
FAQ 3: https://indrajeetpatil.github.io/ggstatsplot/articles/web_only/faq.html#3-i-am-getting-error-in-grid-call-error

This is one of the most common error encountered while using `ggplot2` on `MacOS` and has nothing to do with `ggstatsplot` _per se_.

For example,
- https://stackoverflow.com/questions/10581440/error-in-grid-calll-textbounds-as-graphicsannotxlabel-xx-xy-polygon
- https://community.rstudio.com/t/comeback-of-the-infamous-error-in-grid-call-c-textbounds-as-graphicsannot-x-label-x-x-x-y-polygon-edge-not-found-bug/54555
- https://community.rstudio.com/t/still-fighting-with-grid-call-c-textbounds-as-graphicsannot-x-label-x-x-x-y-polygon-edge-not-found-error/65559
- https://github.com/tidyverse/ggplot2/issues/2252
and the list goes on.

Not always clear where it is coming from, so I have no instructions about this error.

**Comment by kevinrue** [comment]
Noted - hopefully this threads and the links that you provided will give other users good places to start looking for answers.

I came back to this thread because I just ran into a similar error again, because of another font missing on my computer

```r
ggscatterstats(
  data = dplyr::filter(movies_long, genre == "Action"),
  x = budget,
  y = rating,
  type = "robust", # type of test that needs to be run
  xlab = "Movie budget (in million/ US$)", # label for x axis
  ylab = "IMDB rating", # label for y axis
  label.var = title, # variable for labeling data points
  label.expression = rating < 5 & budget > 100, # expression that decides which points to label
  title = "Movie budget and IMDB rating (action)", # title text for the plot
  caption = expression(paste(italic("Note"), ": IMDB stands for Internet Movie DataBase")),
  ggtheme = hrbrthemes::theme_ipsum_ps(), # choosing a different theme
  ggstatsplot.layer = FALSE, # turn off `ggstatsplot` theme layer
  marginal.type = "boxplot", # type of marginal distribution to be displayed
  xfill = "pink", # color fill for x-axis marginal distribution
  yfill = "#009E73" # color fill for y-axis marginal distribution
)
```

```
  no font could be found for family "IBMPlexSans"
```

Also, speaking about RStudio, from past experience, I noticed that resizing the "Plots" pane often helps, especially increasing the size of the pane, so that RStudio gets as much space as possible to fits margins.

**Comment by kevinrue** [comment]
Also: users should make sure that they restart RStudio after installing new fonts.

**Comment by IndrajeetPatil** [comment]
> Also, speaking about RStudio, from past experience, I noticed that resizing the "Plots" pane often helps, especially increasing the size of the pane, so that RStudio gets as much space as possible to fits margins.

That's a helpful tip, thanks!
