### ISSUE TITLE
Boxplot with frequency table

### ISSUE THREAD

**Issue by iago-pssjd** [IndrajeetPatil/ggstatsplot#578]
Hi!
Today I came to this package to see if it had implemented the next: it would be a boxplot with the `n` and `%` of observations in each group of the boxplot, so how many observations are between the minimum and Q1-1.5IQR?, how many between Q1-1.5IQR and Q1, between Q1 and the median and so on. It could be also printed second level groups, as how many observations are between the minimum and Q1, or between Q1 and Q3, etc.... I have not found any similar to this so I suggest here as a Feature idea.

**Update**

1.If there is more than 1 boxplot (let's say if `y` is the continuous variable and `x` the discrete variable), there would be this data for each `x`-boxplot.
2. In some place would appear also the missing observations

Thank you!

**Comment by IndrajeetPatil** [comment]
Hey!

Thanks for the suggestion.

This seems like a very niche visualization. Have you seen an example of such a plot in the wild? If yes, can you please post it here for reference?

**Comment by iago-pssjd** [comment]
I am sorry I have no example for this (and I was looking for before searching in your package), I just imagine it with the numbers being placed in the lateral of each boxplot or otherwise as data outside the graphic (in a table?), but any form will be good for sure.

**Comment by IndrajeetPatil** [comment]
I think this is going to be too niche of a visualization for the current package. In terms of visualizations I would like to support in the future, something like this ranks pretty low. So closing this for now, but might revisit after `1.0` release.
