### ISSUE TITLE
Warning in install.packages :   package ‘ggcoefstats’ is not available (for R version 4.0.2)

### ISSUE THREAD

**Issue by blueja5** [IndrajeetPatil/ggstatsplot#580]
Hello, your package looks excellent and looks recently updated however I am unable to use with my current R version, am I missing something? It looks like it should run on anything above 3.6?

**Comment by IndrajeetPatil** [comment]
> package ‘ggcoefstats’ is not available 

The name of the package is `ggstatsplot`, and `ggcoefstats` is a function from this package.

**Comment by blueja5** [comment]
Thanks! I'm a wally. Works fine now
