### ISSUE TITLE
how to connect items/subjects in ggbetweenstats

### ISSUE THREAD

**Issue by danielemarinazzo** [IndrajeetPatil/ggstatsplot#583]
Hi

going through the example and the vignette I don't seem to find how to connect the same subjects across measures (like in the third example of the vignette and in the second example of the readme).

thanks!

**Comment by IndrajeetPatil** [comment]
The connecting of items/subjects is only available in `ggwithinstats` function, and not `ggbetweenstats` function.
https://indrajeetpatil.github.io/ggstatsplot/reference/ggwithinstats.html#examples

`ggbetweenstats` always handles between-subjects design, so I don't think it makes sense to connect unrelated measurements. This is why it doesn't allow this behavior.

**Comment by danielemarinazzo** [comment]
sorry I meant ggwithinstats
