### ISSUE TITLE
Problem loading ggstatsplot to use ggscatterstats

### ISSUE THREAD

**Issue by Jeleel2020** [IndrajeetPatil/ggstatsplot#585]
Hi IndrajeetPatil

I have problem using using ggscatterstats in a function. Any time I source the function. I get this error message..
Error in ggscatterstats(data = data, x = { : could not find function "ggscatterstats"
I realised it has to do with the installation and loading of required package. I successfully installed ggstatsplot, but anly time I try to load it. I am getting this error. 
> Error in library(ggstatsplot) : there is no package called ‘ggstatsplot’

Please what do you think I am doing wrong?

Kind regards,
Jeleel.

**Comment by M-Colley** [comment]
could you please provide a minimal reproducible example or your code?

which R version do you have?

**Comment by Jeleel2020** [comment]
Thanks for your quick response.

I should say that I am just learning to use R. Please don't be offended if some of my question sounds off. I am using R. 4.02. This is part of the function I am planning to use it for.

p <- ggscatterstats(data = data,
                          x = {{x}}, 
                          y = {{y}},
                          type = type, # type of test that needs to be run
                          conf.level = conf_level, # confidence level
                          xlab = xlab, # label for x axis
                          ylab = ylab, # label for y axis
                          title = title, # plot title
                          results.subtitle = FALSE, # turn off stats
                          point.args = list(color = "white"), # make it easy for coloring points by geom_point()
                          k = 3, # no. of decimal places in the results
                          marginal = FALSE, # whether show ggExtra::ggMarginal() plots or not
                          messages = FALSE)

**Comment by M-Colley** [comment]
hmm can you use some of the built-in data to try it? first try one of the provided examples such as 


`ggscatterstats(
  data = ggplot2::msleep,
  x = sleep_rem,
  y = awake,
  xlab = "REM sleep (in hours)",
  ylab = "Amount of time spent awake (in hours)",
  title = "Understanding mammalian sleep"
)`

does this work?

**Comment by Jeleel2020** [comment]
But my problem is I can't even load library(ggstatsplot)  or isn't that a problem in itself?

**Comment by IndrajeetPatil** [comment]
Have you actually installed the package?

The error you reported says that you have not installed this package. So you can't use a function from a package that is not even installed yet.

> Error in library(ggstatsplot) : there is no package called ‘ggstatsplot’

**Comment by Jeleel2020** [comment]
Hi,

I did install the package. I have the message at the end of the installation. Do you think the installation isn't successful.
configure: error: GNU MP not found, or not 4.1.4 or up, see http://gmplib.org
ERROR: configuration failed for package ‘gmp’
* removing ‘/net/fs-1/home01/jeag/R/library-4.0/gmp’
Warning in install.packages :
  installation of package ‘gmp’ had non-zero exit status
ERROR: dependency ‘gmp’ is not available for package ‘Rmpfr’
* removing ‘/net/fs-1/home01/jeag/R/library-4.0/Rmpfr’
Warning in install.packages :
  installation of package ‘Rmpfr’ had non-zero exit status
ERROR: dependencies ‘gmp’, ‘Rmpfr’ are not available for package ‘PMCMRplus’
* removing ‘/net/fs-1/home01/jeag/R/library-4.0/PMCMRplus’
Warning in install.packages :
  installation of package ‘PMCMRplus’ had non-zero exit status
ERROR: dependency ‘PMCMRplus’ is not available for package ‘pairwiseComparisons’
* removing ‘/net/fs-1/home01/jeag/R/library-4.0/pairwiseComparisons’
Warning in install.packages :
  installation of package ‘pairwiseComparisons’ had non-zero exit status
ERROR: dependency ‘pairwiseComparisons’ is not available for package ‘ggstatsplot’
* removing ‘/net/fs-1/home01/jeag/R/library-4.0/ggstatsplot’
Warning in install.packages :
  installation of package ‘ggstatsplot’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/Rtmp8XQZfY/downloaded_packages’

**Comment by IndrajeetPatil** [comment]
Yes, indeed.

The problem is `PMCMRplus` installation wasn't successful because `Rmpfr` installation wasn't successful.

This is a common problem and the `README` for `PMCMRplus` has detailed instructions about what to do:

https://cran.r-project.org/web/packages/PMCMRplus/readme/README.html

**Comment by Jeleel2020** [comment]
Thank you, I will work on this. Thanks both of you for your quick reply.

**Comment by elia427** [comment]
Hi,

We followed the instructions here https://cran.r-project.org/web/packages/PMCMRplus/readme/README.html
```
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)
```

Both gmp-devel and mpfr-devel are installed.

```
$ rpm -qa |grep gmp
gmp-devel-6.0.0-15.el7.x86_64
gmp-6.0.0-15.el7.x86_64

$ rpm -qa |grep mpfr
mpfr-devel-3.1.1-4.el7.x86_64
mpfr-3.1.1-4.el7.x86_64
```

However, we couldn't install it. 
```
install.packages("PMCMRplus")
configure: error: GNU MP not found, or not 4.1.4 or up, see http://gmplib.org
ERROR: configuration failed for package ‘gmp’
* removing ‘/net/fs-1/home01/jeag/R/library-4.0/gmp’
```

Thanks for the help.

**Comment by IndrajeetPatil** [comment]
See this:

https://stackoverflow.com/questions/22277440/in-r-using-ubuntu-try-to-install-a-lib-depending-on-gmp-c-lib-it-wont-find-g

**Comment by elia427** [comment]
Thanks, I saw that. That is for Ubuntu/Debian. As you can see, we have CentOS 7. Only gmp-devel is available for CentOS.

**Comment by IndrajeetPatil** [comment]
Actually, there is nothing I can do here, since this is not a `ggstatsplot` issue _per se_.

You will just have to write to the maintainer of `Rmpfr` (maechler@stat.math.ethz.ch) and seek guidance about how to proceed.

**Comment by IndrajeetPatil** [comment]
Btw, the comment on the StackOverflow [answer](https://stackoverflow.com/a/26451979/7973626) also says

> If you are using CentOS, it will work with `sudo yum install gmp-devel`

Might work for you.

**Comment by elia427** [comment]
We already have that. I posted this earlier. Didn't you see it?
```
$ rpm -qa |grep gmp
gmp-devel-6.0.0-15.el7.x86_64
gmp-6.0.0-15.el7.x86_64

$ rpm -qa |grep mpfr
mpfr-devel-3.1.1-4.el7.x86_64
mpfr-3.1.1-4.el7.x86_64
```

**Comment by IndrajeetPatil** [comment]
Okay, then I can't help you any further.
