### ISSUE TITLE
ggsignif_adder ggsignif_args map_signif_level = TRUE doesn't work

### ISSUE THREAD

**Issue by hermidalc** [IndrajeetPatil/ggstatsplot#587]
If I run the example here https://indrajeetpatil.github.io/ggstatsplot//reference/ggsignif_adder.html and add the `ggsignif_args` param with `map_signif_level = TRUE` arg it doesn't display asterisks.  I tried also passing a vector too and that also didn't work. I ran a simple ggsignif example using geom_signif directly and it works, so not sure where the bug is if it's in ggstatsplot or ggsignif.

```r
set.seed(123)
library(ggplot2)

# plot
p <- ggplot(iris, aes(Species, Sepal.Length)) +
  geom_boxplot()

# dataframe with pairwise comparison test results
df_pair <-
  pairwiseComparisons::pairwise_comparisons(
    data = iris,
    x = Species,
    y = Sepal.Length
  )

# adding a geom for pairwise comparisons
ggstatsplot:::ggsignif_adder(
  plot = p,
  data = iris,
  x = Species,
  y = Sepal.Length,
  df_pairwise = df_pair
  ggsignif_args = list(map_signif_level = TRUE)
)
```

**Comment by IndrajeetPatil** [comment]
Please don't use `ggstatsplot:::ggsignif_adder`; it's only for internal use. This is not an exported function (thus `:::` and not `::`), and might even be completely removed in the future.

If you want to customize pairwise comparisons further, have a look at FAQ-13 for an example:
https://indrajeetpatil.github.io/ggstatsplot/articles/web_only/faq.html

Also have a look at my response here:
https://github.com/IndrajeetPatil/ggstatsplot/issues/544
