### ISSUE TITLE
Apply normalisation functions to the data before ggstatsplot

### ISSUE THREAD

**Issue by lucolotto** [IndrajeetPatil/ggstatsplot#588]
Hi! First of all thanks for the excellent library, very useful!
I have a dataset which is not normally distributed. In order to be able to run parametric tests instead of non-parametric ones I would like to normalize the data before giving it as input to ggstatsplot. To do so I am using the library `bestNormalize`. The library transforms the data, and this transformation can then be visualised in ggplot by specifying a new scale via the `scales::trans_new` parameter (see: https://cran.r-project.org/web/packages/bestNormalize/vignettes/bestNormalize.html#visualizing-transformations-in-ggplot2-with-scales-package). I think it would be nice if we could feed the normalised data to ggstatsplot and then visualise the plot using the original scale, cause it would keep the original units of measure instead of having them transformed. Do you think it would be possible?

Thanks a lot
Luca

**Comment by IndrajeetPatil** [comment]
Hi,

This is already possible to do via `ggplot.component` argument present in all functions. 

Here is the example you had linked to:

``` r
library(ggplot2)
library(bestNormalize)

x <- rgamma(1000, 1, .1)
bn <- bestNormalize(x)
y <- bn$x.t * 1 + rnorm(1000)
df <- data.frame(x = x, y = y)


library(ggstatsplot)

ggscatterstats(df, x, y,
  ggplot.component = list(scale_x_continuous(trans = "log", breaks = scales::log_breaks()))
)
#> Loading required namespace: ggExtra
```

![](https://i.imgur.com/Oofq5sw.png)

<sup>Created on 2021-05-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by lucolotto** [comment]
Thanks! However what you showed is not quite what I wanted. It's my fault, I explained myself in an unclear way.
What I would like to have is to have the normalised data (i.e. the `y` or `var2` from your example) to perform the statistics (with ggstatsplot). I would then like to plot `var2` with your package but I would like to have, as scale for the y-axis, the un-normalised values (e.g. the original `x` values). Is it possible?

Thanks
Luca

**Comment by IndrajeetPatil** [comment]
Uh, no.

In that case, I would recommend you prepare a custom plot to your liking and then use `statsExpressions` to display results from statistical analysis in the subtitle. For more, see example here: https://github.com/IndrajeetPatil/statsExpressions

**Comment by lucolotto** [comment]
Thanks! I'll have a look at this package. 
You are super helpful, thanks a lot man!
Luca
