### ISSUE TITLE
Controlling Boxplot from "ggbetweenstats"

### ISSUE THREAD

**Issue by vivek-verma202** [IndrajeetPatil/ggstatsplot#592]
Hi Indrajeet! Thank you for ggstatsplot. 
I am planning to use ```ggbetweenstats``` for one of my paper, however, we are interested only the boxplot with thicker boundaries.
I expect something like this (with all the bells and whistles from ggstatsplot):
![image](https://user-images.githubusercontent.com/33168572/117731570-5b613f80-b1bc-11eb-965a-a4d7b6a0759c.png)

However, the best I was able to achieve was:
```
ggbetweenstats(data = df,x = group, y = mean_pc_ULBP_SEP,
                     plot.type = "box",
                     pairwise.display = "all",
                     title = "A: mean % of ULBP+ SEP",
                     ggtheme = ggplot2::theme_classic(),
                     xlab = "", ylab = "", results.subtitle = F,
                     ggsignif.args = list(textsize = 3.5,
                                          tip_length = 0.02,
                                          lwd = 1),
                     point.args = list(alpha = 1, size = 4,
                                       position = ggplot2::position_jitterdodge(dodge.width = 0.8))) +
  ggplot2::scale_color_manual(values = c("#4BB269","#FFA500","#BC3A3A")) +
  ggplot2::theme(
    plot.title = element_text(color = "black",size = 20),
    axis.text  = element_text(color = "black",size = 15))
```
![image](https://user-images.githubusercontent.com/33168572/117732072-33bea700-b1bd-11eb-995d-b28267863ff3.png)

I have the following questions for you:
1. Is there a way to increase the ```lwd``` of the boxplots?
2. Can I ```fill``` the boxplots with colors of my choice?
3. Lastly, Is there a way to get rid of the text in the end (highlighted in yellow)?

Thanks a lot!

**Comment by IndrajeetPatil** [comment]
> Is there a way to increase the lwd of the boxplots?

Currently, no. But I am considering adding a new `boxplot.args` argument to specify additional arguments like these to the underlying `geom` (https://github.com/IndrajeetPatil/ggstatsplot/issues/593).

> Can I fill the boxplots with colors of my choice?

No, this is not possible and will not be possible.

> Lastly, Is there a way to get rid of the text in the end (highlighted in yellow)?

Yes, just add `labs(caption = NULL)` like in this example:

``` r
library(ggstatsplot)
library(ggplot2)

ggbetweenstats(mtcars, cyl, wt) + labs(caption = NULL)
```

![](https://i.imgur.com/fa4VCwR.png)

<sup>Created on 2021-05-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by IndrajeetPatil** [comment]
Btw, if you really want to customize a plot, I would suggest just preparing your own plot and then use something like `statsExpressions` to display stats in the plot:
https://indrajeetpatil.github.io/statsExpressions/
