### ISSUE TITLE
Title parameter for grouped_ggwithinstats?

### ISSUE THREAD

**Issue by andreifoldes** [IndrajeetPatil/ggstatsplot#595]
I think it would be useful to able to add titles for grouped_ggwithinstats too somehow; 

When running the code below, I get:
Error in .f(data = .l[[1L]][[i]], title = .l[[2L]][[i]], ...) : 
  formal argument "title" matched by multiple actual arguments

```r
grouped_ggwithinstats(
  data = VR_dilemma,
  x = modality,
  y = score,
  grouping.var = order,
  title = "Some title",
  type = "np", # non-parametric test
  # additional modifications for **each** plot using `ggplot2` functions
  ggplot.component = ggplot2::scale_y_continuous(
    breaks = seq(0, 1, 0.1),
    limits = c(0, 1)
  )
)
```

**Comment by IndrajeetPatil** [comment]
You can add annotations for the **entire plot**, but not for the individual panels. I hope that's what you are looking for.

``` r
library(ggstatsplot)

grouped_ggwithinstats(
  data = VR_dilemma,
  x = modality,
  y = score,
  grouping.var = order,
  annotation.args = list(title = "Some title", subtitle = "Some subtitle"),
  type = "np", # non-parametric test
  # additional modifications for **each** plot using `ggplot2` functions
  ggplot.component = ggplot2::scale_y_continuous(
    breaks = seq(0, 1, 0.1),
    limits = c(0, 1)
  )
)
```

![](https://i.imgur.com/AhVpC5p.png)

<sup>Created on 2021-05-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
