### ISSUE TITLE
JOSS Review: Benefits/Software implementation

### ISSUE THREAD

**Issue by njtierney** [IndrajeetPatil/ggstatsplot#598]
In the paper, in the benefits section, it states that `ggstatsplot`:

> "increases reproducibility of statistical reporting"

I am not sure I agree with this fully, as while the package does an incredible job at presenting a high quality, readable graphics, it is not possible to replicate the statistical analysis separately.

As far as I can tell, the output is a graphic, and to reproduce just the analysis, not the graphic, would require inspecting either the source code of the functions, or manually reading and copying the details to a statistical test, which I think is prone to human error. 

I think that the best way around this would be to either provide separate functions that the user could call, or for the plotting functions to perhaps provide an option where the statistical summary objects are provided as a list.

Cross linking to the review: https://github.com/openjournals/joss-reviews/issues/3167

**Comment by IndrajeetPatil** [comment]
> As far as I can tell, the output is a graphic, and to reproduce just the analysis, not the graphic, would require inspecting either the source code of the functions, or manually reading and copying the details to a statistical test, which I think is prone to human error.

This is true. 

The `ggstatsplot` package is actually just a graphics package, while all the statistical analysis is carried out by the backend `statsExpressions` package (https://joss.theoj.org/papers/10.21105/joss.03236).

So, any statistical analysis in `ggstatsplot` can be reproduced with `statsExpressions` package:

``` r
options(tibble.width = Inf) # to see all columns

suppressPackageStartupMessages(library(ggstatsplot))
set.seed(123)
ggbetweenstats(mtcars, am, wt)
```

![](https://i.imgur.com/YZ3LpLw.png)

``` r
library(statsExpressions)
set.seed(123)
two_sample_test(mtcars, am, wt)
#> # A tibble: 1 x 16
#>   term  group mean.group1 mean.group2 statistic df.error    p.value
#>   <chr> <chr>       <dbl>       <dbl>     <dbl>    <dbl>      <dbl>
#> 1 wt    am           3.77        2.41      5.49     29.2 0.00000627
#>   method                  estimate conf.level conf.low conf.high effectsize
#>   <chr>                      <dbl>      <dbl>    <dbl>     <dbl> <chr>     
#> 1 Welch Two Sample t-test     1.88       0.95     1.05      2.70 Hedges' g 
#>   conf.method conf.distribution expression
#>   <chr>       <chr>             <list>    
#> 1 ncp         t                 <language>

two_sample_test(mtcars, am, wt, type = "bayesian")
#> # A tibble: 2 x 13
#>   term       estimate conf.level conf.low conf.high    pd rope.percentage
#>   <chr>         <dbl>      <dbl>    <dbl>     <dbl> <dbl>           <dbl>
#> 1 Difference    -1.26       0.95   -1.79     -0.722     1               0
#> 2 Cohens_d       1.72       0.95    0.831     2.56      1               0
#>   prior.distribution prior.location prior.scale  bf10 method          expression
#>   <chr>                       <dbl>       <dbl> <dbl> <chr>           <list>    
#> 1 cauchy                          0       0.707 1383. Bayesian t-test <language>
#> 2 cauchy                          0       0.707 1383. Bayesian t-test <language>
```

<sup>Created on 2021-05-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

Additionally, the user can always access dataframes containing all the statistical analyses from the plot environment, although this is definitely not a beginner-friendly solution:

``` r
options(tibble.width = Inf) # to see all columns

suppressPackageStartupMessages(library(ggstatsplot))
set.seed(123)
p <- ggbetweenstats(mtcars, am, wt)

p$plot_env$subtitle_df
#> # A tibble: 1 x 16
#>   term  group mean.group1 mean.group2 statistic df.error    p.value
#>   <chr> <chr>       <dbl>       <dbl>     <dbl>    <dbl>      <dbl>
#> 1 wt    am           3.77        2.41      5.49     29.2 0.00000627
#>   method                  estimate conf.level conf.low conf.high effectsize
#>   <chr>                      <dbl>      <dbl>    <dbl>     <dbl> <chr>     
#> 1 Welch Two Sample t-test     1.88       0.95     1.05      2.70 Hedges' g 
#>   conf.method conf.distribution expression
#>   <chr>       <chr>             <list>    
#> 1 ncp         t                 <language>

p$plot_env$caption_df
#> # A tibble: 2 x 13
#>   term       estimate conf.level conf.low conf.high    pd rope.percentage
#>   <chr>         <dbl>      <dbl>    <dbl>     <dbl> <dbl>           <dbl>
#> 1 Difference    -1.26       0.95   -1.79     -0.722     1               0
#> 2 Cohens_d       1.72       0.95    0.831     2.56      1               0
#>   prior.distribution prior.location prior.scale  bf10 method          expression
#>   <chr>                       <dbl>       <dbl> <dbl> <chr>           <list>    
#> 1 cauchy                          0       0.707 1383. Bayesian t-test <language>
#> 2 cauchy                          0       0.707 1383. Bayesian t-test <language>
```

<sup>Created on 2021-05-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

Do you advise that I be more explicit about `statsExpressions`'s role in statistical analysis? 
Or would you much rather have me just remove the sentence in question?

**Comment by njtierney** [comment]
This is great information. What do you think about a wrapper function like, `extract_ggstats_method()` or similar, to help extract this information from a plot?, which could do something like the following:

```r
extract_ggstats_method <- function(x, ...){
  stopifnot(inherits("gg"), "input must be a ggplot")
  list(substitle_info = x$plot_env$subtitle_df, caption_info = x$plot_env$caption_df)
}
```

With the documentation describing how to understand which test to run from `statsExpressions` based on this information, or cross linking to another page where you outline which tests are conducted in which functions.

**Comment by IndrajeetPatil** [comment]
Thanks for the great suggestion!

I have implemented this function now: https://indrajeetpatil.github.io/ggstatsplot/reference/extract_stats.html

Example:

```r
set.seed(123)
library(ggstatsplot)
p <- ggbetweenstats(mtcars, am, mpg)
extract_stats(p)
#> $subtitle_data
#> # A tibble: 1 x 16
#>   term  group mean.group1 mean.group2 statistic df.error p.value
#>   <chr> <chr>       <dbl>       <dbl>     <dbl>    <dbl>   <dbl>
#> 1 mpg   am           17.1        24.4     -3.77     18.3 0.00137
#>   method                  estimate conf.level conf.low conf.high effectsize
#>   <chr>                      <dbl>      <dbl>    <dbl>     <dbl> <chr>     
#> 1 Welch Two Sample t-test    -1.35       0.95    -2.17    -0.512 Hedges' g 
#>   conf.method conf.distribution expression
#>   <chr>       <chr>             <list>    
#> 1 ncp         t                 <language>
#> 
#> $caption_data
#> # A tibble: 2 x 13
#>   term       estimate conf.level conf.low conf.high    pd rope.percentage
#>   <chr>         <dbl>      <dbl>    <dbl>     <dbl> <dbl>           <dbl>
#> 1 Difference     6.44       0.95     2.68    10.0   0.999               0
#> 2 Cohens_d      -1.30       0.95    -2.11    -0.519 0.999               0
#>   prior.distribution prior.location prior.scale  bf10 method          expression
#>   <chr>                       <dbl>       <dbl> <dbl> <chr>           <list>    
#> 1 cauchy                          0       0.707  86.6 Bayesian t-test <language>
#> 2 cauchy                          0       0.707  86.6 Bayesian t-test <language>
#> 
```

Let me know if you want me to make any other changes.

**Comment by njtierney** [comment]
That looks great to me, all I could think to suggest would be to add examples to the README and add tests, but I see you've already done that! Thanks for integrating the changes so quickly!
