### ISSUE TITLE
Possibility of leaving as a blank instead of a cross in insignificant p-values on ggcorrmat

### ISSUE THREAD

**Issue by Eduardo-Auer** [IndrajeetPatil/ggstatsplot#607]
I would like to know if there is a way to leave as a blank space the correlations insignificant after FDR correction instead of a cross. Would that be possible?

Below there is an example of the script:

```
library(ggplot2)

ggstatsplot::ggcorrmat(
  data = mtcars,
  output = "plot",
  matrix.type = "lower",
  type = "nonparametric",
  sig.level = 0.05,
  p.adjust.method = "fdr",
  insig = "cross")+
  theme(text = element_text(size=11, colour = "black"), axis.text.x = element_text(size = 11, colour = "black"), axis.text = element_text(size = 11, colour = "black"), axis.text.y = element_text(size = 11, colour = "black"), plot.caption = element_text(size = 11, colour = "black"), plot.subtitle = element_text(size = 11, colour = "black"))

```
![image](https://user-images.githubusercontent.com/79405348/120379493-38770680-c2f6-11eb-9bd6-f96db9f3678f.png)

**Comment by IndrajeetPatil** [comment]
Yes, you can pass additional arugments to `ggcorrplot` to do this:

``` r
library(ggstatsplot)

ggcorrmat(
  data = mtcars,
  ggcorrplot.args = list(
    method = "square",       # default
    outline.color = "black", # default
    insig = "blank"          # change
  )
)
```

![](https://i.imgur.com/W6VGe1H.png)

<sup>Created on 2021-06-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by Eduardo-Auer** [comment]
> Yes, you can pass additional arugments to `ggcorrplot` to do this:
> 
> ```r
> library(ggstatsplot)
> 
> ggcorrmat(
>   data = mtcars,
>   ggcorrplot.args = list(
>     method = "square",       # default
>     outline.color = "black", # default
>     insig = "blank"          # change
>   )
> )
> ```
> 
> ![](https://camo.githubusercontent.com/ab5b0a240f8cadac195b61495c48e59a0826fd95c9a20c343dcc82f82e8202f9/68747470733a2f2f692e696d6775722e636f6d2f573656476531482e706e67)
> 
> Created on 2021-06-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)

Thank you!
