### ISSUE TITLE
Error in ggstatsplot

### ISSUE THREAD

**Issue by malvikarajeev** [IndrajeetPatil/ggstatsplot#608]
Hi, when I try to load ggstatsplot I get in RStudio:

Error: package or namespace load failed for ‘ggstatsplot’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 **there is no package called ‘pairwiseComparisons’**

I tried to install  ‘pairwiseComparisons’ but:

ERROR: lazy loading failed for package ‘pairwiseComparisons’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/pairwiseComparisons’
Warning in install.packages :
  installation of package ‘pairwiseComparisons’ had non-zero exit status

**Comment by IndrajeetPatil** [comment]
> there is no package called ‘pairwiseComparisons’

Run the following and see if that solves the issue:

```r
install.packages("pairwiseComparisons")
```

Are you on Linux by any chance?

**Comment by IndrajeetPatil** [comment]
Also have a look at the installation instructions from home page: https://indrajeetpatil.github.io/ggstatsplot/

![image](https://user-images.githubusercontent.com/11330453/121212763-edbd3780-c87d-11eb-993c-db5ebfab3254.png)
