### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by skytguuu** [IndrajeetPatil/ggstatsplot#609]
Hi,

I tried to install ggstatsplot and it succeed installed in Rstudio. However, when I library(ggstatsplot), it reported the following error:

```r
Error: package or namespace load failed for ‘ggstatsplot’:
 'namespace:ipmisc' has no ‘format_num’
```
Any help?

Thanks!
Garen

**Comment by IndrajeetPatil** [comment]
Hi, 

You just need to update `ipmisc` package to the latest version.

So do, `install.packages("ipmisc")` and then try again to install `ggstatsplot`.
