### ISSUE TITLE
Feature request ggpiestats

### ISSUE THREAD

**Issue by ibecav** [IndrajeetPatil/ggstatsplot#61]
Like to suggest we add to ggpiestats something similar to `test.k` for gghistostats that is a way to change the number of decimal places show for the labels on the pie slices.  Right not it just displays a rounded integer.

**Comment by IndrajeetPatil** [comment]
`ggpiestats` has gained `perc.k` argument to handle this:

``` r
# for reproducibility
set.seed(123)

# simple function call with the defaults (without condition)
ggstatsplot::ggpiestats(
  data = ggplot2::msleep,
  main = vore,
  perc.k = 1,
  k = 2
)
```

![](https://i.imgur.com/92aWtPa.png)

<sup>Created on 2018-09-29 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
