### ISSUE TITLE
Kindly include York Regression.

### ISSUE THREAD

**Issue by Aswin2271993** [IndrajeetPatil/ggstatsplot#613]
**Describe the solution you'd like**
Please try to include regression in which you have uncertainty in x and y axis. Commonly called York regression. In the result you may show the confidence interval band, slope and intercept with uncertainties and also a feature to predict a Y value for a given X with associated uncertainty.
**How could we do it?**
You may refer to R package "Bfsl" or IsoplotR.

**Comment by IndrajeetPatil** [comment]
Closing in favor of https://github.com/easystats/parameters/issues/530

Once it is implemented in `parameters` package, it will also work with `ggcoefstats` function in `ggstatsplot`.
