### ISSUE TITLE
ggbetweenstats - enable removal of median (or other data) labels

### ISSUE THREAD

**Issue by alanstenhouse** [IndrajeetPatil/ggstatsplot#618]
Would it be possible to allow removal of median labels from ggbetweenstats plots?

eg. using a setting like 
showMedian = FALSE or TRUE
or similar?

**Comment by IndrajeetPatil** [comment]
You can already do this via `centrality.plotting` argument:

``` r
library(ggstatsplot)

ggbetweenstats(mtcars, am, wt, centrality.plotting = FALSE)
```

![](https://i.imgur.com/Iq2yYNM.png)

<sup>Created on 2021-06-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

Please have a look at the documentation:
https://indrajeetpatil.github.io/ggstatsplot/reference/ggbetweenstats.html

**Comment by alanstenhouse** [comment]
Ah very sorry, don't know how I missed this! Thanks!!

**Comment by alanstenhouse** [comment]
Actually, I do want to plot the median point, but not to display the label showing the value. How can I suppress those?

**Comment by IndrajeetPatil** [comment]
But the boxplot itself shows the median, so no need to plot the median again as a point.

**Comment by alanstenhouse** [comment]
Ok, so if I also want to plot the mean point, without the label?

**Comment by alanstenhouse** [comment]
Using something like these options gets what I was intending, sorry that I did not work this out earlier! Thanks for the great package!

centrality.plotting = TRUE, 
centrality.type = "parameteric",  # to get mean point
centrality.label.args = list(alpha=0) # to make label fully transparent

**Comment by IndrajeetPatil** [comment]
That's a clever workaround! Thanks for letting me know :)
