### ISSUE TITLE
Change display of pairwise comparison to compact letter display

### ISSUE THREAD

**Issue by IndrajeetPatil** [IndrajeetPatil/ggstatsplot#621]
### Discussed in https://github.com/IndrajeetPatil/ggstatsplot/discussions/620

<div type='discussions-op-text'>

<sup>Originally posted by **Kpulidoc** July  2, 2021</sup>
Hi, 
I would like to know how can I change the significance comparison display to a compact letter display because I have 14 groups to compare and the plot seems too crowded. I am using **ggbetweenstats** to calculate Kruskal-Wallis and Dunn's test. 
Thank you. 
![Captura](https://user-images.githubusercontent.com/86808829/124201123-7b83ef80-dad7-11eb-950e-76b4b1bbad1a.PNG)

</div>

**Comment by IndrajeetPatil** [comment]
Please have a look at the documentation for this function, which provides an argument to suppress the default display of all significant pairwise comparisons: https://indrajeetpatil.github.io/ggstatsplot/reference/ggbetweenstats.html

<img width="1385" alt="Screenshot 2021-07-02 at 09 14 10" src="https://user-images.githubusercontent.com/11330453/124235785-f9ff8200-db15-11eb-8409-adb114ca6ca1.png">

If you further want to customize them, have a look at FAQ-11 and FAQ-13 here:
https://indrajeetpatil.github.io/ggstatsplot/articles/web_only/faq.html

**Comment by lucolotto** [comment]
Hi,
I know you already answered to this question. I looked at the FAQ you mentioned but I could not find a way to plot the statistical significance in the form of a compact letter display (like in this plot: https://community-cdn.rstudio.com/uploads/default/original/2X/d/de0319f0cb638c3c5ef9565cd127de79b45caa33.jpg). Can you please provide an example of how to do it?

Maybe starting from a dummy example like: 
```# converting to factor
mtcars$cyl <- as.factor(mtcars$cyl)

p <- ggplot(mtcars, aes(cyl, wt)) +
  geom_boxplot()

p
```
Thanks a lot in advance
All the best
Luca
