### ISSUE TITLE
Mean tagging in plot but just the value of mean, not Mu="value".

### ISSUE THREAD

**Issue by latifizadehhabib** [IndrajeetPatil/ggstatsplot#624]
Hi there, 
I'm going to change the way of displaying mean tagging in the plot by "ggbetweenstats" function but I just want to annotate the value of mean, not Mu="value". Would you please help me out in this regard? 

Thank you

**Comment by IndrajeetPatil** [comment]
Hi,

Unfortunately, this kind of customization is not supported, nor will it be supported in the future. You will just need to prepare a custom plot.

Sorry.
