### ISSUE TITLE
Sponsor link - no info

### ISSUE THREAD

**Issue by RickPack** [IndrajeetPatil/ggstatsplot#627]
Indrajeet, I saw this Tweet about the lack of papers using your work also including the proper citation. How can we support you financially? Clicking Sponsor on the front of this Github page does not provide information.
[Indrajeet Patil's Tweet regarding lack or wrong citation of ggstatsplot](https://twitter.com/patilindrajeets/status/1414126675684728835?s=20)

**Comment by IndrajeetPatil** [comment]
Dear Rick,

Thank you so much for your response and your support. 

To be clear, I was just venting my frustration about people not citing the software properly and not really expecting any financial support. That said, if you _do_ wish to donate money in my name to a charity of my choice (https://www.againstmalaria.com/Default.aspx), I will never decline that offer. 😉
