### ISSUE TITLE
Saving output in good resolution with ggsave

### ISSUE THREAD

**Issue by javierfs** [IndrajeetPatil/ggstatsplot#630]
I know is written in the docs that the output is not a modifiable object for ggplot2. So I was wondering how can I save the plot as a .png with good resolution. It seems If I export the image from the Rstudio window the quality of the image is very bad. Anyone knows?

**Comment by IndrajeetPatil** [comment]
Hi,

> I know is written in the docs that the output is not a modifiable object for ggplot2. 

No, except for `ggscatterstats`, all outputs **are modifiable** with `ggplot2` functions.

> So I was wondering how can I save the plot as a .png with good resolution.

You can just use `ggasve` function: 
https://ggplot2.tidyverse.org/reference/ggsave.html

**Comment by javierfs** [comment]
I meant this regarding `ggscatterstats`. I finally got the best resolution it by using:

```
png(here('eda_plots/',paste0('my_plot','.png')), 
     width= 10, 
     height= 6, 
     units="in", 
     res=300)
     
rest of the code including the `ggscatterstats`

# Close device
dev.off()
```

but as I said, ggsave does not work with `ggscatterstats`

**Comment by IndrajeetPatil** [comment]
So you are saying, if you run the following command, it produces an error?

```r
library(ggplot2)
library(ggstatsplot)

ggsave(
  filename = "myplot.png",
  plot = ggscatterstats(mtcars, wt, mpg),
  dpi = 600
)
```

**Comment by javierfs** [comment]
Oh my bad, I had a couple of variables bad referenced. I checked and now it works. thanks anyways :D

**Comment by IndrajeetPatil** [comment]
`+ ggsave` is not supported in `ggplot2` itself:

https://www.tidyverse.org/blog/2021/06/off-label-uses-in-ggplot2/

**Comment by javierfs** [comment]
I would probably run this over an older version, but still `+ ggsave` worked when I use the function `ggbetweenstats`
