### ISSUE TITLE
 ggbetweenstats without plotting points

### ISSUE THREAD

**Issue by emantzo** [IndrajeetPatil/ggstatsplot#636]
Hi.
I would like to make comparisons on a large dataset, and I do not have enough memory.
Is it possible to use  ggbetweenstats with boxplots, but without plotting the points?
Thank you!

**Comment by IndrajeetPatil** [comment]
Hi,

No, it's not possible to plot without the points.

In such cases, I would actually recommend preparing your own graphics and then using `statsExpressions` package to display the statistical details using: https://indrajeetpatil.github.io/statsExpressions/

The `ggstatsplot` package plots might be an overkill for large datasets.
