### ISSUE TITLE
Is there a way to plot the grouping factor in the y-axis and the numerical variable in the x-axis?

### ISSUE THREAD

**Issue by javierfs** [IndrajeetPatil/ggstatsplot#637]
I have a variable with many categories that I think it will be better displayed in the Y-axis rather in the X-axis: 

![lead_genre_monthlystreams_listenters](https://user-images.githubusercontent.com/13203962/126152043-d0c51e14-b9ce-4ca8-be67-0c0693686ecf.png)

Is there a way to revert the display of this? This is the code I am using to display this: 

```
data_cleaned %>% 
  select(monthly_stream30_followers, genre_1) %>% 
  ggbetweenstats(
  x = genre_1,
  y = monthly_stream30_followers,
  xlab = "Lead Genre", # label for the x-axis
  ylab = "Monthly Listeners Streams >30s", # label for the y-axis
  title = "",
  ggplot.component =
    # modify further with `ggplot2` functions
  list(
    scale_color_manual(values = paletteer::paletteer_c("ggthemes::Green-Blue Diverging",colourCount_genre_1)),
    theme(axis.text.x = element_text(angle = 0)))
  ) + 
  scale_y_continuous(limits = c(0,7500)) +
  scale_x_discrete(guide=guide_axis(n.dodge=2))+
  ggsave(here('eda_graphs/',paste0('lead_genre_monthlystreams_listenters','.png')),
               height = 8, 
               width = 12,
         device = "png")
```

**Comment by IndrajeetPatil** [comment]
You can just use `coord_flip` from `ggplot2`, but there is a price to pay: you can no longer display pairwise comparisons.

``` r
library(ggstatsplot)
library(ggplot2)

ggbetweenstats(
  iris, Species, Sepal.Length,
  pairwise.comparisons = FALSE
) + 
  coord_flip()
```

![](https://i.imgur.com/xoJ9BF3.png)

<sup>Created on 2021-07-19 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by IndrajeetPatil** [comment]
If you are wondering why pairwise comparison display needs to be turned off, it's for this reason:
https://github.com/const-ae/ggsignif/issues/44
