### ISSUE TITLE
Request: extending bife support for get_APEs for marginal effects visualizations

### ISSUE THREAD

**Issue by IsadoraBM** [IndrajeetPatil/ggstatsplot#639]
Request to implement effects visualization for summary.bifeAPEs  from `get_APEs()` function since 
https://strengejacke.github.io/ggeffects/index.html and https://cran.r-project.org/web/packages/ggiraphExtra/vignettes/ggPredict.html do not support bife, but ggstatsplot already supports model estimate visualizations. Since binary choice models' effects cannot be directly interpreted, average partial (aka) marginal effects are the way in which models are discussed and interpreted. 

```
library(bife)
test <- iris%>% mutate(LengthDummy= if_else(Sepal.Length>5, "Long", "Short") %>% as_factor(.)) %>%  
                 bife(LengthDummy~ Sepal.Width+ Petal.Length+Petal.Width
                      | Species, data = ., "logit")
APEsIris <- summary(get_APEs(test))
str(APEsIris)
```

**Comment by IndrajeetPatil** [comment]
Hi, `ggcoefstats` will work with this object once it's supported in `parameters`.

I have created an issue on that repo: https://github.com/easystats/parameters/issues/566

So closing the current issue in favor of it.

**Comment by IndrajeetPatil** [comment]
If you download the GitHub versions of `insight` and `parameters` packages, this should work now:

``` r
library(tidyverse)
library(bife)
library(ggstatsplot)
#> You can cite this package as:
#>      Patil, I. (2021). Visualizations with statistical details: The 'ggstatsplot' approach.
#>      Journal of Open Source Software, 6(61), 3167, doi:10.21105/joss.03167

test <- iris%>% mutate(LengthDummy= if_else(Sepal.Length>5, "Long", "Short") %>% as_factor(.)) %>%  
  bife(LengthDummy~ Sepal.Width+ Petal.Length+Petal.Width
       | Species, data = ., "logit")
APEsIris <- get_APEs(test)

ggcoefstats(APEsIris)
#> Warning: Could not access model information.
#> Warning in nobs.default(object, use.fallback = use.fallback): no 'nobs' method
#> is available
#> Warning: Could not access model information.
```

![](https://i.imgur.com/dL12FhJ.png)

<sup>Created on 2021-07-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
