### ISSUE TITLE
Is there a pre-processing feature to normalise very skewed data for applying parametric tests? 

### ISSUE THREAD

**Issue by javierfs** [IndrajeetPatil/ggstatsplot#640]
I was wondering if there is a way to log transform the data to make it as similar to a normal distribution as possible for very skewed data. 

This is the how the data looks like (limited by upper boundaries values around 5000 because there is values up to 40million)
![nmr_moods_genres_monthlystreams](https://user-images.githubusercontent.com/13203962/126544396-932f5e43-5d5c-48f1-a6bf-6be37495e8a0.png)

In order to normalise the data I use `scales::trans_breaks` and `scales::trans_format`. This is the code I use to get the chart (number of genres, left plot shown above):

```
data_cleaned %>% 
  mutate(number_genres = factor(number_genres, ordered = T, c("0", "1", "2", "3"))) %>% 
  ggbetweenstats(
  x = number_genres,
  y = monthly_stream30_followers,
  xlab = "Number of Genres", # label for the x-axis
  ylab = "Monthly Listeners Streams >30s", # label for the y-axis
  title = "",
  pairwise.comparisons = FALSE,
  ggplot.component = list(scale_color_manual(values = paletteer::paletteer_c("ggthemes::Green-Blue Diverging",4)),
                          scale_y_log10(breaks = scales::trans_breaks("log10", function(x) 10^x),
                                        labels = scales::trans_format("log10", scales::math_format(10^.x))))
                ) + 
  ggsave(here('eda_graphs/',paste0('nmr_genres_monthlystreams','.png')),
                 height = 8, 
                 width = 12,
           device = "png")
```

![nmr_genres_monthlystreams](https://user-images.githubusercontent.com/13203962/126544959-f6ca64ba-5232-4323-bb82-44709c747107.png)

The data looks more normal, but all the statistical results are the same as before even though the data changed. My question is, the parametric tests are performed before or after the transformation of the data, and if it is before: is there a way to perform the tests after the transformations? Thanks for the great effort on this package!

**Comment by IndrajeetPatil** [comment]
> My question is, the parametric tests are performed before or after the transformation of the data, and if it is before: is there a way to perform the tests after the transformations?

The tests are all performed on whatever data you enter in `data` argument to `ggbetweenstats`, that's it. 
Statistical analysis will **not** be affected by any scale transformations you perform afterwards.

If you want statistical analysis to work with transformed data, you will have to _enter_ transformed data into the function. That is, instead of `ggbetweenstats(data, ...)`, you will have to enter  `ggbetweenstats(mutate(data, x = log(x)), ...)`, etc.

**Comment by IndrajeetPatil** [comment]
If you are worried about violation of test assumptions, you can always use robust statistics by setting `type = "robust"`.

**Comment by javierfs** [comment]
Perfect! Now I understand better. I modified it in this way and the statistical results make more sense now: 

```
data_cleaned %>% 
  mutate(number_genres = factor(number_moods, ordered = T, c("0", "1", "2", "3")),
         log_monthly_streams = log10(monthly_stream30_followers)) %>% 
  ggbetweenstats(
  x = number_moods,
  y = log_monthly_streams,
  xlab = "Number of Moods", # label for the x-axis
  ylab = "(Log scale) \n Monthly Listeners Streams >30s", # label for the y-axis
  title = "",
  ggplot.component = list(scale_color_manual(values = paletteer::paletteer_c("ggthemes::Green-Blue Diverging",4)),
                          scale_y_continuous(labels = scales::math_format(10^.x)))
                ) + 
  ggsave(here('eda_graphs/',paste0('nmr_moods_monthlystreams_log_labels','.png')),
                 height = 8, 
                 width = 12,
           device = "png")
```

![nmr_moods_monthlystreams_log_labels](https://user-images.githubusercontent.com/13203962/126633178-33e82a5a-cdcc-4741-a911-ef9672c83c78.png)

I am wondering: is there a way to change the format of the categorical means? i.e., if mu_hat = 2, then 10^2. That's adding
` scales::math_format(10^.x)`  @IndrajeetPatil ?
