### ISSUE TITLE
(potential?) bug with ggbetweenstats  outlier.shape = NA argument

### ISSUE THREAD

**Issue by TriageDr** [IndrajeetPatil/ggstatsplot#643]
Hello, 

First off - love this package. 

Below is some code to generate boxplot comparisons. I was hoping to utilize the outlier.shape = NA argument to omit the clear outlier in the lower left hand corner (red) boxplot. 

Question: is ggbetweenstats behaving as expected and removing the outlier from the lower left hand corner (red) boxplot? 

```r
ggbetweenstats(
  data,
  x = data_x,
  y = data_y,
  plot.type = "box",
  palette = "default_nejm",
  package = "ggsci",
  type = "np",
  pairwise.display = "significant",
  outlier.shape = NA,
  p.adjust.method = "bonferroni")

```
<img width="1484" alt="Screen Shot 2021-07-28 at 5 39 53 PM" src="https://user-images.githubusercontent.com/44305158/127405392-698f2dea-f36a-4e9b-a551-bc678927e6d3.png">

**Comment by IndrajeetPatil** [comment]
> I was hoping to utilize the outlier.shape = NA argument to omit the clear outlier in the lower left hand corner (red) boxplot.

Actually, this is not going to achieve what you want. You just need to filter the data _before_ entering it into the function (`dplyr::filter(data, data_y < 10000)`).

`outlier.shape` will not actually remove the data point. Also, that argument is relevant only if you have set `outlier.tagging = TRUE`.

<img width="1261" alt="Screenshot 2021-07-29 at 16 19 16" src="https://user-images.githubusercontent.com/11330453/127508834-d5454dd3-bf1a-46c5-8d27-bc400a299b6c.png">
