### ISSUE TITLE
Removing white space between boxplots in ggwithinstats and ggbetweenstats

### ISSUE THREAD

**Issue by TriageDr** [IndrajeetPatil/ggstatsplot#644]
Hello again! Thank you for your quick reply to my last question regarding outlier tagging. 

Question:
How do you remove white position space between boxplots/violin plots using the ggwithinstats and ggbetweenstats functions? 

I've been playing with the  violin.args  argument of the function to no avail!    Is it perhaps a theme element passed after the function output? 

![image](https://user-images.githubusercontent.com/44305158/127565710-be45e5a7-9240-4fd1-a6a0-c7cf5e97df37.png)

```r

  ggwithinstats(
...
violin.args = list(
         width = 0.25, 
         alpha = 0, 
         position = position_dodge(width=0.1))
...
)
 



```

**Comment by IndrajeetPatil** [comment]
Unfortunately, this is not at all straightforward to do from `ggstatsplot` itself, but here is a workaround with a `ggplot2` function:

``` r
library(ggstatsplot)
library(ggplot2)

# before
ggbetweenstats(mtcars, cyl, wt)
```

![](https://i.imgur.com/nNiThWr.png)

``` r
# after
ggbetweenstats(mtcars, cyl, wt) +
  expand_limits(x = seq(-1, 5))
```

![](https://i.imgur.com/tEoTZ85.png)

<sup>Created on 2021-07-31 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
