### ISSUE TITLE
Trouble Running ggstatplot library

### ISSUE THREAD

**Issue by christineng1** [IndrajeetPatil/ggstatsplot#646]
I installed both ggstatplot and easystats but having trouble running the packages:

Error: package or namespace load failed for ‘ggstatsplot’:
 object ‘check_heterogeneity_bias’ is not exported by 'namespace:performance'

R version is 4.10

thanks

**Comment by IndrajeetPatil** [comment]
You can run the following command, refresh R session, and then it should work:

```r
install.packages('easystats', repos = 'https://easystats.r-universe.dev')
```

**Comment by christineng1** [comment]
Thanks! I did do it and it still the same issue. thanks

**Comment by IndrajeetPatil** [comment]
Can you please open a new issue here?
https://github.com/easystats/easystats/issues

Because this has less to do with `ggstatsplot`, and more to do with `easystats` package installation.
