### ISSUE TITLE
ggstatsplot::ggwithinstats error

### ISSUE THREAD

**Issue by kathrynfox** [IndrajeetPatil/ggstatsplot#648]
I'm currently running the code (pasted below), and the figure is not providing me with the statistical details for the primary fishers test, only with the posthoc stats. Any tips to get the stat test to appear again? This issue arose when I updated my R version today. An important note: when I run the nonparametric version (same code just change type), the stat details show up. @IndrajeetPatil - could you please help with this issue?

```r
Comparing_Disclosure_SITBs_parametric2<-ggstatsplot::grouped_ggwithinstats(
  data = degree_disclosure_sitb,
  x = person,
  y = value,
  grouping.var = behavior,
  xlab = "Key Person Disclosed To",  
  ylab = "Frequency of Disclosure", 
  type = "parametric",  
  pairwise.comparisons = TRUE,  
  p.adjust.method = "holm", 
  notch = FALSE,
  k = 3,
  mean.ci = TRUE,
  results.subtitle = TRUE,
  title.prefix = "Specific Thought/Behavior",
  title.text = "Frequency of SITB Disclosure Across Key People",
  plotgrid.args = list(ncol = 2)
)
```

**Comment by IndrajeetPatil** [comment]
Hi Kathryn,

If the figure is generated and the plot does not contain statistical analysis, it means the underlying statistical analysis failed for some reason and an empty subtitle is shown.

More often than not, this happens because when you used `grouped_`, there might not be enough data for the respective test at that level of the grouping variable.

That's my guess. Hard to say anything else without looking at the data itself.

**Comment by kathrynfox** [comment]
Hi! Thanks so much for your reply -- got it. For some reason it is able to calculate when I try nonparametric, but not parametric, so it seems not to be a data specific issue? It may be helpful to share: We have between 500-900 participants. depending on the group.

**Comment by IndrajeetPatil** [comment]
> For some reason it is able to calculate when I try nonparametric, but not parametric, so it seems not to be a data specific issue?

Well, parametric and non-parametric tests are different in terms of their data expectations. So if one runs successfully, it doesn’t mean the other will run as well. 

You can isolate the level of the grouping variable that is causing problem and then share that data with me.

**Comment by kathrynfox** [comment]
Ah, yes that's true! 

I ended up solving the issue by downloading the base package for the anova tests -- afex!! Now everything is running properly. I am guessing most people don't run into this issue, but helpful to know that can be a fix sometimes!

**Comment by kathrynfox** [comment]
Thank you so much for your help @IndrajeetPatil

**Comment by IndrajeetPatil** [comment]
You're welcome!
