### ISSUE TITLE
p values as annotations only in grouped plots?

### ISSUE THREAD

**Issue by jaydoc** [IndrajeetPatil/ggstatsplot#652]
Hi

 I have a grouped plot with 4 variable levels per plot and the resulting plot looks cluttered when there are significant differences between every group and the p-values run up to 8 or 10 digits long. 

So, is there a way to show significance values as annotations (like *, ** etc) only in plots generated using grouped_ggstatsplot functions?

**Comment by IndrajeetPatil** [comment]
Hi,

Please have a look at this vignette to see how you can modify the appearance of each of the small multiples when you are plotting across levels of a grouping variable:
https://indrajeetpatil.github.io/ggstatsplot/articles/web_only/purrr_examples.html

``` r
library(ggstatsplot)
library(purrr)

# creating list by grouping variable
year_list <-
  gapminder::gapminder %>%
  dplyr::filter(year %in% c(1967, 1987, 2007), continent != "Oceania") %>%
  split(f = .$year, drop = TRUE)

# creating a list of plots
plot_list <-
  purrr::pmap(
    .l = list(
      data = year_list,
      x = "continent",
      y = list("lifeExp"),
      results.subtitle = FALSE,
      pairwise.comparisons = FALSE,
      subtitle = list("***", "***", "**")
    ),
    .f = ggstatsplot::ggbetweenstats
  )

# combining individual plots together
ggstatsplot::combine_plots(
  plotlist = plot_list,
  annotation.args = list(title = "Changes in life expectancy across continents (1967-2007)"),
  plotgrid.args = list(nrow = 1)
)
```

![](https://i.imgur.com/wMccdDX.png)

<sup>Created on 2021-10-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
