### ISSUE TITLE
[Bug] Failure to load ggstatsplot after update to R 4.1.1

### ISSUE THREAD

**Issue by M-Colley** [IndrajeetPatil/ggstatsplot#653]
Hello, 

after the update to R Version 4.1.1 the following error occurs:

Error: retrieving namespace for ‘ggstatsplot’: failed
 Objekt ‘check_heterogeneity_bias’ is not exported by 'namespace:performance' 

ggstatsplot in Version 0.8.0 and performance in version 0.7.3 is installed.

This is especially weird as the package "performance" here clearly exports the function: https://github.com/easystats/performance/blob/master/R/check_heterogeneity_bias.R

To reproduce, you only need to use:

`library(ggstatsplot)`

Kind regards

**Comment by IndrajeetPatil** [comment]
Nothing to do with `{ggstatsplot}`, it's `{easystats}` issue: https://github.com/easystats/easystats/issues/166

**Comment by M-Colley** [comment]
oh okay thanks!

**Comment by IndrajeetPatil** [comment]
https://github.com/easystats/modelbased/issues/140#issuecomment-901029581

**Comment by M-Colley** [comment]
For future reference: simply uninstalling all easystats packages and only installing the necessary packages via install.packages works as well.
