### ISSUE TITLE
Ranking Differences in Scatterplots

### ISSUE THREAD

**Issue by flachboard** [IndrajeetPatil/ggstatsplot#663]
[ggstatsexample.csv](https://github.com/IndrajeetPatil/ggstatsplot/files/7332458/ggstatsexample.csv)

Hello, I've attached a sample dataset. For each group in group1, I'm looking to compare the values between ALL and HCC in group2. Ultimately, I want to rank the group1 groups by how different the values (val1 and val2) are between ALL and HCC in group2. Is there an easy way to do this? Sorry if I'm missing it. I was researching the ggscatterstats function, but I'm not quite seeing what I'm looking for. Thanks for this wonderful package!

**Comment by IndrajeetPatil** [comment]
Hi, 

Unfortunately, this falls outside the current scope of the package, and will not be supported.
