### ISSUE TITLE
Pairwise comparison label is missing for two groups

### ISSUE THREAD

**Issue by ShixiangWang** [IndrajeetPatil/ggstatsplot#676]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

Brief description of the problem

```r
## for reproducibility
set.seed(123)
library(ggstatsplot)

ggbetweenstats(
  data = iris,
  x = Species,
  y = Sepal.Length,
  title = "Distribution of sepal length across Iris species",
  bf.message = FALSE,
  results.subtitle = FALSE
)


ggbetweenstats(
  data = iris %>% dplyr::filter(Species != "setosa"),
  x = Species,
  y = Sepal.Length,
  title = "Distribution of sepal length across Iris species",
  bf.message = FALSE,
  results.subtitle = FALSE
)

```

![image](https://user-images.githubusercontent.com/25057508/142961831-9c211a39-2a97-4241-87a6-10480e555fc1.png)

![image](https://user-images.githubusercontent.com/25057508/142961845-32a3e980-f61d-4ac5-ae90-d046a378573a.png)

Is it possible to show the pairwise comparison for two groups and corresponding p value?

**Comment by AntoineSoetewey** [comment]
There is no need to do a pairwise comparison when there are only two groups. Pairwise comparisons are intended for 3 groups or more.

For 2 groups, the p-value of the student’s t-test (or the non-parametric version) can be displayed if you change `results.subtitle` to `TRUE`

**Comment by ShixiangWang** [comment]
I want to use consistent format to present the comparison when group number >= 2.
Besides, the default subtitle showed many details, it may be suitable for a single plot, but not proper for multiple plots (>= 10). I have seen an issue posted to talk about shortening the subtile, so I did not mention above.

**Comment by AntoineSoetewey** [comment]
Are you referring to this issue : https://github.com/IndrajeetPatil/ggstatsplot/issues/669 ?

I agree with you, there are many details.

**Comment by ShixiangWang** [comment]
Yeah.

**Comment by IndrajeetPatil** [comment]
Thanks for creating the issue.

In addition to what Antoine has already mentioned, the omnibus and pairwise tests are completely different. 

E.g., if we just focus on between-subjects design (and equal variances are not assumed), the tests look like the following:

| no. of groups | omnibus test | pairwise test |
| ----------- | ----------- | ----------- |
| > 2 | Welch's ANOVA | Games-Howell test |
| 2 | Welch's _t_-test | - |

If I start displaying Games-Howell test results when there are just 2 groups (which is possible), then there might sometimes be inconsistency between the test shown in the subtitle and the one shown in pairwise geom. Additionally, I am not even sure if it statistically makes sense to use a pairwise test as an omnibus test.

So, I guess this boils down to #669, and I will close this issue in favor of it.
