### ISSUE TITLE
adding group percentage under group count

### ISSUE THREAD

**Issue by ralikwen** [IndrajeetPatil/ggstatsplot#677]
Now group count appears under each category. I would also like to have the relative percentage of that group displayed under the group count. And than I wouldn't need to make a separate table for that.

**How could we do it?**
Where it is - label=n() 
it could be - label=paste0(n(),'\n',round(n/sum(n)*100),'%')

**Comment by IndrajeetPatil** [comment]
Which function are you referring to?

**Comment by ralikwen** [comment]
Sorry->ggbetweenstats

**Comment by IndrajeetPatil** [comment]
Although this would be easy to implement, after giving this some thought, I have decided that it's not the best idea to add more information to the default plots in `{ggstatsplot}`, which are already overflowing with details.

![image](https://user-images.githubusercontent.com/11330453/151763199-5b5da4e3-5e87-4927-8cc1-2ce14d4c1552.png)

I would much prefer that the users do this themselves using `{ggplot}`, outside `{ggstatsplot}`.
