### ISSUE TITLE
Package version for R 3.6.3

### ISSUE THREAD

**Issue by carlosmag** [IndrajeetPatil/ggstatsplot#683]
Hi!,
What is the latest version of the package that can be used under R 3.6.3?

**Comment by IndrajeetPatil** [comment]
The previous release, so `0.8.0`.

You can download it as follows:

```r
require(devtools)
install_version("ggstatsplot", version = "0.8.0", repos = "http://cran.us.r-project.org")
```

**Comment by carlosmag** [comment]
I have an error during installation:

`ERROR: dependencies ‘ipmisc’, ‘pairwiseComparisons’, ‘statsExpressions’ are not available for package ‘ggstatsplot’`

**Comment by IndrajeetPatil** [comment]
Ah, yes, I have removed them now. 

So you will need to do the following:

```r
require(devtools)
install_version("ipmisc", version = "6.0.2", repos = "http://cran.us.r-project.org")
install_version("statsExpressions", version = "1.1.0", repos = "http://cran.us.r-project.org")
install_version("pairwiseComparisons", version = "3.2.0", repos = "http://cran.us.r-project.org")
install_version("ggstatsplot", version = "0.8.0", repos = "http://cran.us.r-project.org")
```

**Comment by carlosmag** [comment]
It seems "pairwiseComparisons" package version is not compatible with R 3.6.3. Is there another one that can work with "ggstatsplot" ?

`ERROR: this R is version 3.6.3, package 'pairwiseComparisons' requires  R >= 4.0`

**Comment by IndrajeetPatil** [comment]
Try 

install_version("pairwiseComparisons", version = "3.1.6", repos = "http://cran.us.r-project.org")

**Comment by carlosmag** [comment]
It worked! Thanks!

**Comment by IndrajeetPatil** [comment]
Out of curiosity; why are you unable to update to R >= 4.0?

**Comment by carlosmag** [comment]
I still did not update R, in fear it would break some projects I've been
involved with...

A sexta, 10/12/2021, 19:03, Indrajeet Patil ***@***.***>
escreveu:

**Comment by vsteiger** [comment]
The installation according to the  instructions above worked fine.

Although, I'm getting an error specifically for ggbetweenstats():

```
library(ggstatsplot)
library(tidyverse)
library(palmerpenguins)

penguins %>% ggbetweenstats(x = species, y = bill_depth_mm)
```
Full error message:

```
Error in `dplyr::mutate()`:
! Problem while computing `n_label = paste0(species, "\n(n = ",
  .prettyNum(n), ")")`.
Caused by error in `vapply()`:
! values must be length 1,
 but FUN(X[[1]]) result is length 3
---
Backtrace:
  1. penguins %>% ggbetweenstats(x = species, y = bill_depth_mm)
 14. ggstatsplot:::.prettyNum(n)
 15. base::prettyNum(x, big.mark = ",", scientific = FALSE)
 16. base::vapply(...)
```

Session Info:
```
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: SUSE Linux Enterprise Server 15 SP3

Matrix products: default
BLAS/LAPACK: /usr/lib64/libopenblas_pthreads.so.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] palmerpenguins_0.1.1 ggstatsplot_0.8.0    forcats_0.5.2        stringr_1.4.1       
 [5] dplyr_1.0.10         purrr_0.3.5          readr_2.1.3          tidyr_1.2.1         
 [9] tibble_3.1.8         ggplot2_3.4.0        tidyverse_1.3.2     

```

**Comment by IndrajeetPatil** [comment]
@vsteiger This is the same issue as https://github.com/IndrajeetPatil/ggstatsplot/issues/749. I guess you also need to install the specific version of `{insight}` that works for this old version of `{ggstatsplot}`.

May I know why you can't upgrade to `R 4.0`?

**Comment by vsteiger** [comment]
> @vsteiger This is the same issue as #749. I guess you also need to install the specific version of `{insight}` that works for this old version of `{ggstatsplot}`.
> 
> May I know why you can't upgrade to `R 4.0`?

@IndrajeetPatil Thanks for clarifying and sorry for the double entry.
Which version of the insight package, should be compatible with the 0.8.0 version of ggstatsplot?
