### ISSUE TITLE
Saved output of ggbetweenstats appears to have missing fonts

### ISSUE THREAD

**Issue by brianmsm** [IndrajeetPatil/ggstatsplot#685]
When I generate the plot with `ggbetweenstats`, I can see it correctly in the Rstudio viewer. However, when I save the image, a square appears next to the average that looks as if some source is missing.

``` r
library(ggstatsplot)
#> You can cite this package as:
#>      Patil, I. (2021). Visualizations with statistical details: The 'ggstatsplot' approach.
#>      Journal of Open Source Software, 6(61), 3167, doi:10.21105/joss.03167
library(ggplot2)

ggsave(
  filename = "myplot.png",
  plot = ggbetweenstats(mtcars, am, mpg),
  dpi = 400,
  height = 5,
  width = 7
)
```

<sup>Created on 2021-12-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

![myplot](https://user-images.githubusercontent.com/28207224/146844886-d767e604-0f62-4baa-9e65-a0e4a0a0a059.png)

```
sessioninfo::platform_info()
## setting  value
## version  R version 4.1.2 (2021-11-01)
## os       Manjaro Linux
## system   x86_64, linux-gnu
## ui       RStudio
## language (EN)
## collate  es_PE.UTF-8
## ctype    es_PE.UTF-8
## tz       America/Lima
## date     2021-12-20
## rstudio  2021.09.1+372 Ghost Orchid (desktop)
## pandoc   2.14.0.3 @ /usr/lib/rstudio/bin/pandoc/ (via rmarkdown)
```

**Comment by IndrajeetPatil** [comment]
Interesting. 

Are you using the CRAN version of the package or the GitHub version?

**Comment by brianmsm** [comment]
I'm sorry. I just saw your answer.

Version of package is 0.9.0 (CRAN).

**Comment by IndrajeetPatil** [comment]
What do you see if you run the following?

```r
library(ggplot2)

ggplot() +
  labs(subtitle = parse(text = "mu==2"))
```

**Comment by IndrajeetPatil** [comment]
Closing in favor of https://github.com/tidyverse/ggplot2/issues/4706
