### ISSUE TITLE
When using games-howell pwc

### ISSUE THREAD

**Issue by Bryan-Hutchinson** [IndrajeetPatil/ggstatsplot#689]
Lovely package Indrajeet

I suggest automatically setting additional p-value corrections to "none" when using games-howell, took me some time to realize Holm correction was added to result additionally which was throwing off my result.

"The test is based on Welch’s degrees of freedom correction and uses Tukey’s studentized range distribution for computing the p-values. The test compares the difference between each pair of means with appropriate adjustment for the multiple testing. So there is no need to apply additional p-value corrections."

**Comment by IndrajeetPatil** [comment]
> "The test is based on Welch’s degrees of freedom correction and uses Tukey’s studentized range distribution for computing the p-values. The test compares the difference between each pair of means with appropriate adjustment for the multiple testing. So there is no need to apply additional p-value corrections."

What's the source of this quote?!

At any rate, I prefer not to change the default argument only for one type of test in order to keep the API consistent across parametric, non-parametric, and robust statistics, where adjustment is applied by default.

**Comment by Bryan-Hutchinson** [comment]
Indrajeet

Thanks for your prompt reply.

The quote is from, I think, rstatix.

Please note that I have since come across the following stackexchange query. With regards to the userfriendlyscience' package. See in particular the end where they changed the default from "holm" to "none" .

https://stats.stackexchange.com/questions/83941/games-howell-post-hoc-test-in-r


I understand your logic in not changing the default – but I think that, at least, it should be mentioned in the documentation.

Regards
