### ISSUE TITLE
Question: Possible to remove density line?

### ISSUE THREAD

**Issue by M-Colley** [IndrajeetPatil/ggstatsplot#696]
Hey, is there the possibility to remove the density curve from the plots?

I really love the package but with a higher number of conditions, the plots tend to become "crowded", therefore, one way to "ease" the "heavyness" of the plot would be to only display boxplots and the points or boxplot and the density curve. 

To achieve only the boxplot + density curve, one could do the following:

```r
ggstatsplot::ggbetweenstats(data = iris, x = Species, y = Sepal.Length, violin.args = list(width = 0.5, alpha = 0.2), point.args = list(alpha = 0.01))
```
However, I found no way to keep the points + boxplot but no density curve. 

Thank you!

**Comment by IndrajeetPatil** [comment]
It's true. Currently, there is no way to display only box plots and points.

You can use the `plot.type` argument to only display a boxplot:

``` r
ggstatsplot::ggbetweenstats(
  data = iris,
  x = Species,
  y = Sepal.Length,
  violin.args = list(width = 0.5, alpha = 0.2),
  point.args = list(alpha = 0.01),
  plot.type = "box"
)
```

![](https://i.imgur.com/D6lT62X.png)

<sup>Created on 2022-01-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

I will try to implement this soon.

**Comment by M-Colley** [comment]
Hey, actually, I played around a bit and if i take your code and simply remove 

```r  point.args = list(alpha = 0.01),
``` 

then it works:

![image](https://user-images.githubusercontent.com/39366189/149635748-1e53a4cc-384e-4f13-acf4-96cc4de7c828.png)

**Comment by IndrajeetPatil** [comment]
Thanks for figuring it out!

I will still need to document this somewhere since it's not straightforward.

**Comment by allaway** [comment]
Hi there - just leaving this note for posterity in case someone stumbles across this issue later. For some reason, even when setting the param `plot.type = "box"`, the violin plots remain on the plot. A workaround that was able to fix this for me was to add `violin.args = list(width = 0)`.
