### ISSUE TITLE
Mean value display arguments not working

### ISSUE THREAD

**Issue by Abhishek-Kar** [IndrajeetPatil/ggstatsplot#702]
mean.color & mean.size not working

packageVersion("ggstatsplot")

[1] ‘0.9.1’

```r

ggbetweenstats(
  data = dplyr::filter(gapminder::gapminder, year == 2007, continent != "Oceania"),
  x = continent,
  mean.color= "black",
  y = lifeExp
)

```

**Comment by IndrajeetPatil** [comment]
Hi,

The argument you are looking for is `centrality.point.args`. If you wanted to change the aesthetics of the label instead, the argument would be `centrality.label.args`: https://indrajeetpatil.github.io/ggstatsplot/reference/ggbetweenstats.html

``` r
library(ggstatsplot)

ggbetweenstats(
  data = dplyr::filter(gapminder::gapminder, year == 2007, continent != "Oceania"),
  x = continent,
  y = lifeExp,
  centrality.point.args = list(color = "black", size = 5)
)
```

![](https://i.imgur.com/y2u0cQC.png)

<sup>Created on 2022-01-31 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by Abhishek-Kar** [comment]
Thank you so much! Much appreciated.

Warm regards,
Abhishek
