### ISSUE TITLE
Extract conf.level values of ggwithinstats

### ISSUE THREAD

**Issue by RS-eco** [IndrajeetPatil/ggstatsplot#704]
Is there a way to extract the confidence level values (min, max) of the individual violin plots produced with ggwithinstats, as shown in #467?

**Comment by IndrajeetPatil** [comment]
Do you mean confidence intervals for centrality measures?

You can use https://easystats.github.io/datawizard/reference/describe_distribution.html.

``` r
library(datawizard)
describe_distribution(rnorm(100), ci = 0.95)
#> Mean |   SD |  IQR |        95% CI |         Range | Skewness | Kurtosis |   n | n_Missing
#> ------------------------------------------------------------------------------------------
#> 0.06 | 1.03 | 1.33 | [-0.15, 0.22] | [-2.65, 2.46] |    -0.31 |     0.32 | 100 |         0
```

<sup>Created on 2022-03-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
