### ISSUE TITLE
Add plot of points on top of bars in ggbarstats

### ISSUE THREAD

**Issue by hermidalc** [IndrajeetPatil/ggstatsplot#712]
Add ability to easily enable plot of underlying points used to make bars in ggbarstats, similar to how `ggpubr` `ggbarplot` does it https://rpkgs.datanovia.com/ggpubr/reference/ggbarplot.html (scroll down to bottom to see the examples), but with `ggstatsplot` (IMO much better) looks and aesthetics.

**Comment by IndrajeetPatil** [comment]
Note that `ggbarstats()` and `ggbarplot()` are quite different:
The former is designed to work only with categorical/qualitative data, while the latter is designed to work with continuous data.

So plotting underlying points is irrelevant for `ggbarstats()`.
