### ISSUE TITLE
ggscatterstats - color data points using a different variable

### ISSUE THREAD

**Issue by StephanieRodrigues** [IndrajeetPatil/ggstatsplot#713]
Hi, 
I'd like to know if there is the possibility to color the data points using a different variable. 
I know that I can chose a variable to label the dots, using label.var argument but I don't if I can set up different colors in my dots using a third variable. Id there a way to do this?

Thank you in advance.

**Comment by IndrajeetPatil** [comment]
No, this is not possible with _ggstatsplot_, and this won't be supported in the future either.

You can just make a custom plot and use _statsExpressions_ to display results instead:

``` r
library(ggplot2)
library(statsExpressions)

results_expr <- corr_test(mtcars, wt, mpg)$expression[[1]]

ggplot(mtcars, aes(wt, mpg, color = as.factor(cyl))) + 
  geom_point() + 
  labs(subtitle = results_expr)
```

![](https://i.imgur.com/ahJaoSj.png)

<sup>Created on 2022-03-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
