### ISSUE TITLE
error on pairwise_comparisons

### ISSUE THREAD

**Issue by rvalieris** [IndrajeetPatil/ggstatsplot#718]
Hello, I'm getting an error with the pairwise_comparions function in the following case:

```r
tibble(case=c("z","z","y","y"), cond=c("a","b","a","b"), value=c(4,1423,1,23)) %>% 
pairwise_comparisons(x=cond, y=value, subject.id=case, type='parametric')
```

<details>
  <summary>Error in data.frame(..., check.names = FALSE): arguments imply differing number of rows: 0, 1</summary>
<pre>
Traceback:

1. tibble(case = c("z", "z", "y", "y"), cond = c("a", "b", "a", 
 .     "b"), value = c(4, 1423, 1, 23)) %>% pairwise_comparisons(x = cond, 
 .     y = value, subject.id = case, type = "parametric")
2. pairwise_comparisons(., x = cond, y = value, subject.id = case, 
 .     type = "parametric")
3. suppressWarnings(exec(.fn = .f, x = y_vec, g = x_vec, groups = x_vec, 
 .     blocks = g_vec, paired = paired, p.adjust.method = "none", 
 .     !!!.f.args)) %>% tidy_model_parameters(.) %>% rename(group2 = group1, 
 .     group1 = group2)
4. rename(., group2 = group1, group1 = group2)
5. tidy_model_parameters(.)
6. model_parameters(model, verbose = FALSE, ...) %>% select(where(~!all(is.na(.x))), 
 .     -matches("Difference")) %>% standardize_names(style = "broom") %>% 
 .     rename_all(~gsub("cramers.", "", .x)) %>% rename_all(.funs = recode, 
 .     bayes.factor = "bf10") %>% tidyr::fill(matches("^prior|^bf"), 
 .     .direction = "updown") %>% mutate(across(matches("bf10"), 
 .     ~log(.x), .names = "log_e_{.col}"))
7. mutate(., across(matches("bf10"), ~log(.x), .names = "log_e_{.col}"))
8. tidyr::fill(., matches("^prior|^bf"), .direction = "updown")
9. rename_all(., .funs = recode, bayes.factor = "bf10")
10. tbl_vars(.tbl)
11. new_sel_vars(tbl_vars_dispatch(x), group_vars(x))
12. structure(vars, groups = group_vars, class = c("dplyr_sel_vars", 
  .     "character"))
13. tbl_vars_dispatch(x)
14. rename_all(., ~gsub("cramers.", "", .x))
15. tbl_vars(.tbl)
16. new_sel_vars(tbl_vars_dispatch(x), group_vars(x))
17. structure(vars, groups = group_vars, class = c("dplyr_sel_vars", 
  .     "character"))
18. tbl_vars_dispatch(x)
19. standardize_names(., style = "broom")
20. select(., where(~!all(is.na(.x))), -matches("Difference"))
21. model_parameters(model, verbose = FALSE, ...)
22. model_parameters.PMCMR(model, verbose = FALSE, ...)
23. PMCMRplus::toTidy(model)
24. cbind(merge(x = matrix_to_tidy(mod$statistic, col_name = "statistic"), 
  .     y = matrix_to_tidy(mod$p.value, col_name = "p.value"), by = c("group1", 
  .         "group2")), data.frame(alternative = ifelse(is.null(mod$alternative), 
  .     "two.sided", mod$alternative)), data.frame(method = METH), 
  .     data.frame(distribution = mod$dist), data.frame(p.adjust.method = mod$p.adjust.method))
25. cbind(deparse.level, ...)
26. data.frame(..., check.names = FALSE)
27. stop(gettextf("arguments imply differing number of rows: %s", 
  .     paste(unique(nrows), collapse = ", ")), domain = NA)
</pre>
</details>

am I doing something wrong ?
also, worth mentioning, if `type="nonparametric"` the error does not happen.

ggstatsplot version: 0.9.1

**Comment by IndrajeetPatil** [comment]
Can reproduce. Let me have a look.

``` r
library(ggstatsplot)

df <- tibble(
    case = c("z", "z", "y", "y"),
    cond = c("a", "b", "a", "b"),
    value = c(4, 1423, 1, 23)
  )

pairwise_comparisons(
  df,
  x = cond,
  y = value,
  subject.id = case,
  type = "parametric"
)
#> Error in data.frame(..., check.names = FALSE): arguments imply differing number of rows: 0, 1
```

<sup>Created on 2022-03-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

Traceback:

```r
27: stop(gettextf("arguments imply differing number of rows: %s", 
        paste(unique(nrows), collapse = ", ")), domain = NA)
26: data.frame(..., check.names = FALSE)
25: cbind(deparse.level, ...)
24: cbind(merge(x = matrix_to_tidy(mod$statistic, col_name = "statistic"), 
        y = matrix_to_tidy(mod$p.value, col_name = "p.value"), by = c("group1", 
            "group2")), data.frame(alternative = ifelse(is.null(mod$alternative), 
        "two.sided", mod$alternative)), data.frame(method = METH), 
        data.frame(distribution = mod$dist), data.frame(p.adjust.method = mod$p.adjust.method))
23: PMCMRplus::toTidy(model)
22: model_parameters.PMCMR(model, verbose = FALSE, ...)
21: model_parameters(model, verbose = FALSE, ...)
20: select(., where(~!all(is.na(.x))), -matches("Difference"))
19: standardize_names(., style = "broom")
18: tbl_vars_dispatch(x)
17: structure(vars, groups = group_vars, class = c("dplyr_sel_vars", 
        "character"))
16: new_sel_vars(tbl_vars_dispatch(x), group_vars(x))
15: tbl_vars(.tbl)
14: rename_all(., ~gsub("cramers.", "", .x))
13: tbl_vars_dispatch(x)
12: structure(vars, groups = group_vars, class = c("dplyr_sel_vars", 
        "character"))
11: new_sel_vars(tbl_vars_dispatch(x), group_vars(x))
10: tbl_vars(.tbl)
9: rename_all(., .funs = recode, bayes.factor = "bf10")
8: tidyr::fill(., matches("^prior|^bf"), .direction = "updown")
7: mutate(., across(matches("bf10"), ~log(.x), .names = "log_e_{.col}"))
6: model_parameters(model, verbose = FALSE, ...) %>% select(where(~!all(is.na(.x))), 
       -matches("Difference")) %>% standardize_names(style = "broom") %>% 
       rename_all(~gsub("cramers.", "", .x)) %>% rename_all(.funs = recode, 
       bayes.factor = "bf10") %>% tidyr::fill(matches("^prior|^bf"), 
       .direction = "updown") %>% mutate(across(matches("bf10"), 
       ~log(.x), .names = "log_e_{.col}")) at helpers_easystats.R#12
5: tidy_model_parameters(.)
4: rename(., group2 = group1, group1 = group2)
3: suppressWarnings(exec(.fn = .f, x = y_vec, g = x_vec, groups = x_vec, 
       blocks = g_vec, paired = paired, p.adjust.method = "none", 
       !!!.f.args)) %>% tidy_model_parameters(.) %>% rename(group2 = group1, 
       group1 = group2)
2: pairwise_comparisons(., x = cond, y = value, subject.id = case, 
       type = "parametric")
1: tibble(case = c("z", "z", "y", "y"), cond = c("a", "b", "a", 
       "b"), value = c(4, 1423, 1, 23)) %>% pairwise_comparisons(x = cond, 
       y = value, subject.id = case, type = "parametric")
```

**Comment by IndrajeetPatil** [comment]
Sorry, just got around to work on this package.

Turns out, you just forgot to use `paired = TRUE` for the within-subjects design, and so the wrong test was being run:

``` r
library(ggstatsplot)

df <- tibble(
  case = c("z", "z", "y", "y"),
  cond = c("a", "b", "a", "b"),
  value = c(4, 1423, 1, 23)
)

pairwise_comparisons(
  df,
  x = cond,
  y = value,
  paired = TRUE,
  subject.id = case,
  type = "parametric"
)
#> # A tibble: 1 × 6
#>   group1 group2 p.value test.details     p.value.adjustment label               
#>   <chr>  <chr>    <dbl> <chr>            <chr>              <chr>               
#> 1 a      b        0.490 Student's t-test Holm               list(~italic(p)[Hol…
```

<sup>Created on 2022-03-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
