### ISSUE TITLE
feature request: 2D density plot in ggscatterstats

### ISSUE THREAD

**Issue by XiaoyuZeng** [IndrajeetPatil/ggstatsplot#722]
Hi all,

Thanks for developing such an excellent package. I have a request to integrate a 2D density plot in the ggscatterstats function. This feature will nicely solve the problem that the number of data points is obscure, which is frequently seen in datasets with large number of data points.

example:
![image](https://user-images.githubusercontent.com/38243112/159877116-2473f28e-01a2-4665-ba1a-6c59cacee717.png)

another R package that have implemented this function and may provide insights:
https://github.com/LKremer/ggpointdensity

Best regards,
Xiaoyu

**Comment by IndrajeetPatil** [comment]
Unfortunately, I don't plan to support any other plots in _ggstatsplot_ at the moment.

You can just make a custom plot and use _statsExpressions_ to display the results instead:

``` r
library(ggplot2)
library(dplyr)
library(viridis)
#> Loading required package: viridisLite
library(ggpointdensity)

dat <- bind_rows(
  tibble(x = rnorm(7000, sd = 1),
         y = rnorm(7000, sd = 10),
         group = "foo"),
  tibble(x = rnorm(3000, mean = 1, sd = .5),
         y = rnorm(3000, mean = 7, sd = 5),
         group = "bar"))

library(statsExpressions)
results_expr <- corr_test(dat, x, y, type = "robust")$expression[[1]]

ggplot(data = dat, mapping = aes(x = x, y = y)) +
  geom_pointdensity() +
  scale_color_viridis() + 
  labs(subtitle = results_expr)
```

![](https://i.imgur.com/gKIfFAT.png)

<sup>Created on 2022-03-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
