### ISSUE TITLE
Mean box removal.

### ISSUE THREAD

**Issue by MFS2020** [IndrajeetPatil/ggstatsplot#734]
Hello,

I have a small issue and I keep correcting it in paint, I need the "mean = 23" box that poitns at the mean red circle to disappear from the figures in the **ggbetweenstats** I have tried multiple mean commands set to FALSE and nothing has so far worked.

I would also like to remove the statistics on the bottom that are generated, I really love the graphical representation, but the details beyond the p=value are not necessary for my case, still they are lesser of an issue since quick paint can fix it, but not the mean, mean box usually generates on top of the violin plot.

Best,
MS

**Comment by IndrajeetPatil** [comment]
You mean like this?

``` r
library(ggstatsplot)
set.seed(123)

ggbetweenstats(mtcars, am, wt,
  centrality.plotting = FALSE
)
```

![](https://i.imgur.com/5WK5kKp.png)

<sup>Created on 2022-04-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by MFS2020** [comment]
omg what a response time, yes precisely, but is it possible to keep the red dot? I love the visual representation it gives

**Comment by arunvv90** [comment]
Wow, I was trying the same thing and this answer saved me too. That was quick. Again, I would like to keep the red dot too.
![Rplot](https://user-images.githubusercontent.com/41168645/164531997-f188a00f-b54b-416e-8bc4-598f91f98359.png)
 I still want to keep the mean values if possible. In my case, it is crowded. Is it possible to cheng ethe location of the mean title, something like ggrepel?

**Comment by IndrajeetPatil** [comment]
To keep the mean, but to remove the labels:

``` r
library(ggstatsplot)
set.seed(123)

ggbetweenstats(mtcars, am, wt,
               centrality.label.args = list(alpha = 0),
)
```

![](https://i.imgur.com/hpyRv1i.png)

<sup>Created on 2022-04-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by arunvv90** [comment]
Here is my code and plot. In your case, I guess that you have three different groups. There is no space to add the entire equation in the top for all three groups. So it is splitting between top and bottom I guess
![Rplot03](https://user-images.githubusercontent.com/41168645/164533154-e6124816-6abf-4341-9031-f3037be80011.png)
m

**Comment by IndrajeetPatil** [comment]
> I still want to keep the mean values if possible. In my case, it is crowded. Is it possible to change the location of the mean title, something like ggrepel?

@arunvv90 _ggstatsplot_ already uses _ggrepel_ internally to display these labels. You can use `centrality.label.args` parameter to specify further customizations for these labels.

**Comment by IndrajeetPatil** [comment]
> how did you get rid of the statistics on the bottom? 

Setting `bf.message = FALSE` will get rid of it:

``` r
library(ggstatsplot)
set.seed(123)

ggbetweenstats(mtcars, am, wt,
               bf.message = FALSE
)
```

![](https://i.imgur.com/aiZmH1j.png)

<sup>Created on 2022-04-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by IndrajeetPatil** [comment]
For more, please have a look at the documentation for this function:
Manual: https://indrajeetpatil.github.io/ggstatsplot/reference/ggbetweenstats.html
Vignette: https://indrajeetpatil.github.io/ggstatsplot/articles/web_only/ggbetweenstats.html

**Comment by MFS2020** [comment]
thank you!!!

**Comment by arunvv90** [comment]
Thank you for the quick support
