### ISSUE TITLE
Is there a way to show latex expressions in the caption of the ggplot?

### ISSUE THREAD

**Issue by javierfs** [IndrajeetPatil/ggstatsplot#737]
I'd like to add a description of the thresholds of the robust effect size suggested by Algina, Keselman, Penfield Psych Methods, 2005, 317-328 (the same delta AKP sub r that's plotted on the subtitle of ggbetweenstats() output). Something like |d| = 0.2, 0.5, and 0.8 correspond to small, medium, and large effects but with the proper delta symbol

**Comment by IndrajeetPatil** [comment]
For general questions like these, please use https://stackoverflow.com/ in the future. 
GitHub's issues are only for bug reports or feature requests.

Here is how you can include expressions in the plot:

``` r
library(ggstatsplot)
library(ggplot2)

p <- ggbetweenstats(mtcars, am, wt, type = "r")

p +
  labs(caption = parse(text = "list(delta == 0.2: small, delta == 0.5: medium, delta == 0.8: large)"))
```

![](https://i.imgur.com/Ha3Whtk.png)

<sup>Created on 2022-04-26 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>
