### ISSUE TITLE
Best way to vary dot size for overlapping dots

### ISSUE THREAD

**Issue by jsibley2** [IndrajeetPatil/ggstatsplot#741]
Hello,

Is there a way to show or represent the count of how many dots overlap, similar to geom_count?

Thank you.

**Comment by IndrajeetPatil** [comment]
No, this is not possible in _ggstatsplot_.

You can prepare a custom plot and then use _statsExpressions_ to show the stats in the plot:

``` r
library(statsExpressions)
library(ggplot2)

df <- corr_test(mpg, cty, hwy)

library(ggside)

ggplot(mpg, aes(cty, hwy)) +
  geom_count() +
  geom_xsidehistogram() +
  geom_ysidehistogram() +
  labs(subtitle = df$expression[[1]])
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
```

![](https://i.imgur.com/R9vBJFR.png)

<sup>Created on 2022-04-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
