### ISSUE TITLE
Statistical reporting not visible in ggwithinstats

### ISSUE THREAD

**Issue by Ydv-aakash** [IndrajeetPatil/ggstatsplot#745]
Hi, I am using ggwithinstats to plot my data. I require wilcoxon signed rank test but the pvalues are not showing up in the plot. Am I missing something? 

```r
ggwithinstats(
data=plotting_dataframe,
y     = compo_avg_seven,
x     = labels_2.0_bound,
type ="nonparametric",
xlab = " ",
ylab="Feature 1",
point.path = FALSE,
)

```

![image](https://user-images.githubusercontent.com/97742887/167700557-b7c956af-7f8e-4f45-98e5-cd38218d4b68.png)

**Comment by IndrajeetPatil** [comment]
I can't help without looking at the data. 

If you can't share data, try running the following and see what you get:

```r
statsExpressions::oneway_anova(
  data = plotting_dataframe,
  y = compo_avg_seven,
  x = labels_2.0_bound,
  type = "nonparametric",
  paired = TRUE
)

```
