### ISSUE TITLE
P-value formatting

### ISSUE THREAD

**Issue by Andrzej-Andrzej** [IndrajeetPatil/ggstatsplot#746]
**Describe the solution you'd like**
I would like to ask if after some corrections have been done, is it possible to turn off scientific notation and in a consistent way 
round p-values decimal places to 4 like 0.0000 in eg. ggbetweenstats function and others ?

**Comment by AntoineSoetewey** [comment]
I also would like to use this formatting instead of the scientific notation.

However, if this is implemented, I think it’s more correct to write p < 0.001 instead of 0.0000.

**Comment by IndrajeetPatil** [comment]
Hi both,

This is something that I plan to support in the future, but, for now, FAQ#2 is your best shot here:
https://indrajeetpatil.github.io/ggstatsplot/articles/web_only/faq.html#how-can-i-customize-the-details-contained-in-the-subtitle

This is the same issue as #720, so closing in favour of that.

**Comment by RainRam** [comment]
> I also would like to use this formatting instead of the scientific notation.
> 
> However, if this is implemented, I think it’s more correct to write p < 0.001 for all p-values below 0.001, instead of 0.0000.

did you get your expected formatting, how to achieve that goal, 
if you made it, could I get some supports from you?

**Comment by AntoineSoetewey** [comment]
> did you get your expected formatting, how to achieve that goal, if you made it, could I get some supports from you?

Here is an example with the Fisher's exact test:

```
p_val <- fisher.test(table(dat$x, dat$y))$p.value
ggbarstats(data = dat,
           x = x,
           y = y,
           proportion.test = FALSE,
           results.subtitle = FALSE) +
  labs(caption = NULL,
       subtitle = paste0("Fisher's exact test, p ", ifelse(p_val < 0.001, "< 0.001", paste0("= ", round(p_val, 3)))))
```

But this is not optimal because I need to compute it manually and it removes all other information.

**Comment by RainRam** [comment]
> > did you get your expected formatting, how to achieve that goal, if you made it, could I get some supports from you?
> 
> Here is an example with the Fisher's exact test:
> 
> ```
> p_val <- fisher.test(table(dat$x, dat$y))$p.value
> ggbarstats(data = dat,
>            x = x,
>            y = y,
>            proportion.test = FALSE,
>            results.subtitle = FALSE) +
>   labs(caption = NULL,
>        subtitle = paste0("Fisher's exact test, p ", ifelse(p_val < 0.001, "< 0.001", paste0("= ", round(p_val, 3)))))
> ```
> 
> But this is not optimal because I need to compute it manually and it removes all other information.

Though I am now still confused
Thanks a lot
