### ISSUE TITLE
`ggbetweenstats()` fails with new version of `{insight}` package

### ISSUE THREAD

**Issue by robby81** [IndrajeetPatil/ggstatsplot#749]
Here the error message:

Quitting from lines 1312-1352 (ImVHong_Analysis.Rmd) 
Error in `mutate()`:
! Problem while computing `n_label = paste0(studycohort, "\n(n = ", .prettyNum(n), ")")`.
Caused by error in `vapply()`:
! values must be length 1,
 but FUN(X[[1]]) result is length 3
Backtrace:
  1. ggstatsplot::grouped_ggbetweenstats(...)
 17. statsExpressions:::.prettyNum(n)
 18. base::prettyNum(x, big.mark = ",", scientific = FALSE)
 19. base::vapply(...)

my session-info:
> sessioninfo::session_info(include_base = TRUE)
─ Session info ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.2.0 (2022-04-22)
 os       openSUSE Tumbleweed
 system   x86_64, linux-gnu
 ui       X11
 language
 collate  de_DE.UTF-8
 ctype    en_US.UTF-8
 tz       Europe/Berlin
 date     2022-05-16
 pandoc   2.17.1.1 @ /usr/bin/ (via rmarkdown)

─ Packages ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 package          * version    date (UTC) lib source
 assertthat         0.2.1      2019-03-21 [1] CRAN (R 4.2.0)
 backports          1.4.1      2021-12-13 [1] CRAN (R 4.2.0)
 base             * 4.2.0      2022-05-15 [2] local
 BayesFactor        0.9.12-4.3 2021-12-13 [1] CRAN (R 4.2.0)
 bayestestR         0.12.1     2022-05-02 [1] CRAN (R 4.2.0)
 beeswarm           0.4.0      2021-06-01 [1] CRAN (R 4.2.0)
 bit                4.0.4      2020-08-04 [1] CRAN (R 4.2.0)
 bit64              4.0.5      2020-08-30 [1] CRAN (R 4.2.0)
 boot               1.3-28     2021-05-03 [2] CRAN (R 4.2.0)
 broom            * 0.8.0      2022-04-13 [1] CRAN (R 4.2.0)
 bslib              0.3.1      2021-10-06 [1] CRAN (R 4.2.0)
 cellranger         1.1.0      2016-07-27 [1] CRAN (R 4.2.0)
 class              7.3-20     2022-01-16 [2] CRAN (R 4.2.0)
 cli                3.3.0      2022-04-25 [1] CRAN (R 4.2.0)
 coda               0.19-4     2020-09-30 [1] CRAN (R 4.2.0)
 codetools          0.2-18     2020-11-04 [2] CRAN (R 4.2.0)
 colorspace         2.0-3      2022-02-21 [1] CRAN (R 4.2.0)
 compiler           4.2.0      2022-05-15 [2] local
 correlation        0.8.0      2022-02-14 [1] CRAN (R 4.2.0)
 crayon             1.5.1      2022-03-26 [1] CRAN (R 4.2.0)
 data.table         1.14.2     2021-09-27 [1] CRAN (R 4.2.0)
 datasets         * 4.2.0      2022-05-15 [2] local
 datawizard         0.4.1      2022-05-16 [1] CRAN (R 4.2.0)
 DBI                1.1.2      2021-12-20 [1] CRAN (R 4.2.0)
 dbplyr             2.1.1      2021-04-06 [1] CRAN (R 4.2.0)
 DEoptimR           1.0-11     2022-04-03 [1] CRAN (R 4.2.0)
 digest             0.6.29     2021-12-01 [1] CRAN (R 4.2.0)
 dplyr            * 1.0.9      2022-04-28 [1] CRAN (R 4.2.0)
 effectsize         0.6.0.1    2022-01-26 [1] CRAN (R 4.2.0)
 ellipsis           0.3.2      2021-04-29 [1] CRAN (R 4.2.0)
 emmeans            1.7.4-1    2022-05-15 [1] CRAN (R 4.2.0)
 estimability       1.3        2018-02-11 [1] CRAN (R 4.2.0)
 evaluate           0.15       2022-02-18 [1] CRAN (R 4.2.0)
 fansi              1.0.3      2022-03-24 [1] CRAN (R 4.2.0)
 farver             2.1.0      2021-02-28 [1] CRAN (R 4.2.0)
 fastmap            1.1.0      2021-01-25 [1] CRAN (R 4.2.0)
 FNN                1.1.3      2019-02-15 [1] CRAN (R 4.2.0)
 forcats          * 0.5.1      2021-01-27 [1] CRAN (R 4.2.0)
 foreach            1.5.2      2022-02-02 [1] CRAN (R 4.2.0)
 fs                 1.5.2      2021-12-08 [1] CRAN (R 4.2.0)
 future             1.25.0     2022-04-24 [1] CRAN (R 4.2.0)
 future.apply       1.9.0      2022-04-25 [1] CRAN (R 4.2.0)
 generics           0.1.2      2022-01-31 [1] CRAN (R 4.2.0)
 ggbeeswarm       * 0.6.0      2017-08-07 [1] CRAN (R 4.2.0)
 ggcorrplot         0.1.3      2019-05-19 [1] CRAN (R 4.2.0)
 ggplot2          * 3.3.6      2022-05-03 [1] CRAN (R 4.2.0)
 ggstatsplot        0.9.1      2022-01-14 [1] CRAN (R 4.2.0)
 globals            0.15.0     2022-05-09 [1] CRAN (R 4.2.0)
 glue               1.6.2      2022-02-24 [1] CRAN (R 4.2.0)
 gower              1.0.0      2022-02-03 [1] CRAN (R 4.2.0)
 graphics         * 4.2.0      2022-05-15 [2] local
 grDevices        * 4.2.0      2022-05-15 [2] local
 grid               4.2.0      2022-05-15 [2] local
 gridExtra          2.3        2017-09-09 [1] CRAN (R 4.2.0)
 gtable             0.3.0      2019-03-25 [1] CRAN (R 4.2.0)
 gtools             3.9.2      2021-06-06 [1] CRAN (R 4.2.0)
 hardhat            0.2.0      2022-01-24 [1] CRAN (R 4.2.0)
 haven              2.5.0      2022-04-15 [1] CRAN (R 4.2.0)
 highr              0.9        2021-04-16 [1] CRAN (R 4.2.0)
 hms                1.1.1      2021-09-26 [1] CRAN (R 4.2.0)
 htmltools          0.5.2      2021-08-25 [1] CRAN (R 4.2.0)
 httr               1.4.3      2022-05-04 [1] CRAN (R 4.2.0)
 insight            0.17.1     2022-05-13 [1] CRAN (R 4.2.0)
 ipred              0.9-12     2021-09-15 [1] CRAN (R 4.2.0)
 iterators          1.0.14     2022-02-05 [1] CRAN (R 4.2.0)
 jquerylib          0.1.4      2021-04-26 [1] CRAN (R 4.2.0)
 jsonlite           1.8.0      2022-02-22 [1] CRAN (R 4.2.0)
 kableExtra       * 1.3.4      2021-02-20 [1] CRAN (R 4.2.0)
 knitr            * 1.39       2022-04-26 [1] CRAN (R 4.2.0)
 labeling           0.4.2      2020-10-20 [1] CRAN (R 4.2.0)
 lattice          * 0.20-45    2021-09-22 [2] CRAN (R 4.2.0)
 lava               1.6.10     2021-09-02 [1] CRAN (R 4.2.0)
 lifecycle          1.0.1      2021-09-24 [1] CRAN (R 4.2.0)
 listenv            0.8.0      2019-12-05 [1] CRAN (R 4.2.0)
 lubridate        * 1.8.0      2021-10-07 [1] CRAN (R 4.2.0)
 magrittr           2.0.3      2022-03-30 [1] CRAN (R 4.2.0)
 MASS               7.3-56     2022-03-23 [2] CRAN (R 4.2.0)
 Matrix             1.4-1      2022-03-23 [2] CRAN (R 4.2.0)
 MatrixModels       0.5-0      2021-03-02 [1] CRAN (R 4.2.0)
 mc2d               0.1-21     2021-07-05 [1] CRAN (R 4.2.0)
 methods          * 4.2.0      2022-05-15 [2] local
 missRanger         2.1.3      2021-03-30 [1] CRAN (R 4.2.0)
 ModelMetrics       1.2.2.2    2020-03-17 [1] CRAN (R 4.2.0)
 modelr             0.1.8      2020-05-19 [1] CRAN (R 4.2.0)
 multcomp           1.4-19     2022-04-26 [1] CRAN (R 4.2.0)
 munsell            0.5.0      2018-06-12 [1] CRAN (R 4.2.0)
 mvoutlier          2.1.1      2021-07-30 [1] CRAN (R 4.2.0)
 mvtnorm            1.1-3      2021-10-08 [1] CRAN (R 4.2.0)
 nlme               3.1-157    2022-03-25 [2] CRAN (R 4.2.0)
 nnet               7.3-17     2022-01-16 [2] CRAN (R 4.2.0)
 outForest          0.1.2      2022-01-31 [1] CRAN (R 4.2.0)
 paletteer          1.4.0      2021-07-20 [1] CRAN (R 4.2.0)
 parallel           4.2.0      2022-05-15 [2] local
 parallelly         1.31.1     2022-04-22 [1] CRAN (R 4.2.0)
 parameters         0.17.0     2022-03-10 [1] CRAN (R 4.2.0)
 patchwork          1.1.1      2020-12-17 [1] CRAN (R 4.2.0)
 pbapply            1.5-0      2021-09-16 [1] CRAN (R 4.2.0)
 performance        0.9.0      2022-03-30 [1] CRAN (R 4.2.0)
 pillar             1.7.0      2022-02-01 [1] CRAN (R 4.2.0)
 pkgconfig          2.0.3      2019-09-22 [1] CRAN (R 4.2.0)
 plyr               1.8.7      2022-03-24 [1] CRAN (R 4.2.0)
 prismatic          1.1.0      2021-10-17 [1] CRAN (R 4.2.0)
 pROC               1.18.0     2021-09-03 [1] CRAN (R 4.2.0)
 prodlim            2019.11.13 2019-11-17 [1] CRAN (R 4.2.0)
 purrr            * 0.3.4      2020-04-17 [1] CRAN (R 4.2.0)
 R6                 2.5.1      2021-08-19 [1] CRAN (R 4.2.0)
 ranger             0.13.1     2021-07-14 [1] CRAN (R 4.2.0)
 RColorBrewer       1.1-3      2022-04-03 [1] CRAN (R 4.2.0)
 Rcpp               1.0.8.3    2022-03-17 [1] CRAN (R 4.2.0)
 readr            * 2.1.2      2022-01-30 [1] CRAN (R 4.2.0)
 readxl             1.4.0      2022-03-28 [1] CRAN (R 4.2.0)
 recipes            0.2.0      2022-02-18 [1] CRAN (R 4.2.0)
 rematch2           2.1.2      2020-05-01 [1] CRAN (R 4.2.0)
 reprex             2.0.1      2021-08-05 [1] CRAN (R 4.2.0)
 reshape            0.8.9      2022-04-12 [1] CRAN (R 4.2.0)
 reshape2           1.4.4      2020-04-09 [1] CRAN (R 4.2.0)
 rlang              1.0.2      2022-03-04 [1] CRAN (R 4.2.0)
 rmarkdown        * 2.14       2022-04-25 [1] CRAN (R 4.2.0)
 robustbase         0.95-0     2022-04-02 [1] CRAN (R 4.2.0)
 rpart              4.1.16     2022-01-24 [2] CRAN (R 4.2.0)
 rstantools         2.2.0      2022-04-08 [1] CRAN (R 4.2.0)
 rstudioapi         0.13       2020-11-12 [1] CRAN (R 4.2.0)
 rvest              1.0.2      2021-10-16 [1] CRAN (R 4.2.0)
 sandwich           3.0-1      2021-05-18 [1] CRAN (R 4.2.0)
 sass               0.4.1      2022-03-23 [1] CRAN (R 4.2.0)
 scales             1.2.0      2022-04-13 [1] CRAN (R 4.2.0)
 sessioninfo        1.2.2      2021-12-06 [1] CRAN (R 4.2.0)
 sgeostat           1.0-27     2016-02-03 [1] CRAN (R 4.2.0)
 splines            4.2.0      2022-05-15 [2] local
 stats            * 4.2.0      2022-05-15 [2] local
 stats4             4.2.0      2022-05-15 [2] local
 statsExpressions   1.3.1      2022-03-29 [1] CRAN (R 4.2.0)
 stringi            1.7.6      2021-11-29 [1] CRAN (R 4.2.0)
 stringr          * 1.4.0      2019-02-10 [1] CRAN (R 4.2.0)
 survival           3.3-1      2022-03-03 [2] CRAN (R 4.2.0)
 svglite            2.1.0      2022-02-03 [1] CRAN (R 4.2.0)
 systemfonts        1.0.4      2022-02-11 [1] CRAN (R 4.2.0)
 TH.data            1.1-1      2022-04-26 [1] CRAN (R 4.2.0)
 tibble           * 3.1.7      2022-05-03 [1] CRAN (R 4.2.0)
 tidyr            * 1.2.0      2022-02-01 [1] CRAN (R 4.2.0)
 tidyselect         1.1.2      2022-02-21 [1] CRAN (R 4.2.0)
 tidyverse        * 1.3.1      2021-04-15 [1] CRAN (R 4.2.0)
 timeDate           3043.102   2018-02-21 [1] CRAN (R 4.2.0)
 tools              4.2.0      2022-05-15 [2] local
 tzdb               0.3.0      2022-03-28 [1] CRAN (R 4.2.0)
 utf8               1.2.2      2021-07-24 [1] CRAN (R 4.2.0)
 utils            * 4.2.0      2022-05-15 [2] local
 vctrs              0.4.1      2022-04-13 [1] CRAN (R 4.2.0)
 vipor              0.4.5      2017-03-22 [1] CRAN (R 4.2.0)
 viridisLite        0.4.0      2021-04-13 [1] CRAN (R 4.2.0)
 vroom              1.5.7      2021-11-30 [1] CRAN (R 4.2.0)
 webshot            0.5.3      2022-04-14 [1] CRAN (R 4.2.0)
 withr              2.5.0      2022-03-03 [1] CRAN (R 4.2.0)
 writexl          * 1.4.0      2021-04-20 [1] CRAN (R 4.2.0)
 WRS2               1.1-3      2021-07-20 [1] CRAN (R 4.2.0)
 xfun               0.31       2022-05-10 [1] CRAN (R 4.2.0)
 xml2               1.3.3      2021-11-30 [1] CRAN (R 4.2.0)
 xtable             1.8-4      2019-04-21 [1] CRAN (R 4.2.0)
 yaml               2.3.5      2022-02-21 [1] CRAN (R 4.2.0)
 zeallot            0.1.0      2018-01-28 [1] CRAN (R 4.2.0)
 zoo                1.8-10     2022-04-15 [1] CRAN (R 4.2.0)

 [1] /home/robby/R/x86_64-suse-linux-gnu-library/4.2
 [2] /usr/lib64/R/library

**Comment by IndrajeetPatil** [comment]
This is due to _insight_ package update.

You can install the GitHub versions of _statsExpressions_ and _ggstatsplot_ for now, which should solve the problem:

```r
remotes::install_github("IndrajeetPatil/statsExpressions")
remotes::install_github("IndrajeetPatil/ggstatsplot")
```

They should be available on CRAN soon.

**Comment by robby81** [comment]
Thanks for help!

**Comment by IndrajeetPatil** [comment]
Both *statsExpressions* and *ggstatsplot* updates are now on CRAN, so all these issues should go away.

**Comment by ana-serrano** [comment]
I started having this same issue suddenly today (in code that used to work until very recently). Any idea what may be happening? Minimal examples also give me this error: 

**Code**: 
    set.seed(123)
    library(WRS2)
    library(ggstatsplot)

    ggwithinstats(
      data = bugs_long,
      x = condition,
      y = desire
    )

**Error**: 
    Error in `mutate()`:
    i In argument: `n_label = paste0(condition, "\n(n = ", .prettyNum(n), ")")`.
    Caused by error in `vapply()`:
    ! values must be length 1,
    but FUN(X[[1]]) result is length 3

**Session info**: 
        sessioninfo::session_info(include_base = TRUE)
        - Session info ---------------------------------------------------------------------------------------------------------------------------
         setting  value
         version  R version 4.0.4 (2021-02-15)
         os       Windows 10 x64 (build 19045)
         system   x86_64, mingw32
         ui       RStudio
         language (EN)
         collate  Spanish_Spain.1252
         ctype    Spanish_Spain.1252
         tz       Europe/Paris
         date     2023-05-17
         rstudio  1.4.1106 Tiger Daylily (desktop)
         pandoc   3.1.2 @ C:\\Users\\PC\\AppData\\Local\\Pandoc\\pandoc.exe
        
        - Packages -------------------------------------------------------------------------------------------------------------------------------
         ! package          * version    date (UTC) lib source
           abind              1.4-5      2016-07-21 [1] CRAN (R 4.0.3)
           afex               1.3-0      2023-04-17 [1] CRAN (R 4.0.4)
           base             * 4.0.4      2021-02-15 [?] local
           BayesFactor        0.9.12-4.2 2018-05-19 [1] CRAN (R 4.0.5)
           bayestestR         0.13.1     2023-04-07 [1] CRAN (R 4.0.4)
           boot               1.3-28.1   2022-11-22 [1] CRAN (R 4.0.4)
           BWStest            0.2.2      2018-10-18 [1] CRAN (R 4.0.5)
           cachem             1.0.6      2021-08-19 [1] CRAN (R 4.0.5)
           car                3.1-2      2023-03-30 [1] CRAN (R 4.0.4)
           carData            3.0-5      2022-01-06 [1] CRAN (R 4.0.5)
           cli                3.6.1      2023-03-23 [1] CRAN (R 4.0.4)
           coda               0.19-4     2020-09-30 [1] CRAN (R 4.0.5)
           codetools          0.2-19     2023-02-01 [1] CRAN (R 4.0.4)
           colorspace         2.1-0      2023-01-23 [1] CRAN (R 4.0.4)
         P compiler           4.0.4      2021-02-15 [2] local
           correlation        0.8.4      2023-04-06 [1] CRAN (R 4.0.4)
         P datasets         * 4.0.4      2021-02-15 [2] local
           datawizard         0.7.1      2023-04-03 [1] CRAN (R 4.0.4)
           dplyr              1.1.1      2023-03-22 [1] CRAN (R 4.0.4)
           effectsize         0.8.3      2023-01-28 [1] CRAN (R 4.0.4)
           ellipsis           0.3.2      2021-04-29 [1] CRAN (R 4.0.5)
           emmeans            1.7.1-1    2021-11-29 [1] CRAN (R 4.0.4)
           estimability       1.4.1      2022-08-05 [1] CRAN (R 4.0.4)
           fansi              1.0.4      2023-01-22 [1] CRAN (R 4.0.4)
           fastmap            1.1.0      2021-01-25 [1] CRAN (R 4.0.5)
           generics           0.1.3      2022-07-05 [1] CRAN (R 4.0.4)
           ggplot2            3.4.2      2023-04-03 [1] CRAN (R 4.0.4)
           ggstatsplot      * 0.9.0      2021-10-19 [1] CRAN (R 4.0.5)
           glue               1.4.2      2020-08-27 [1] CRAN (R 4.0.5)
           gmp                0.6-2.1    2021-11-02 [1] CRAN (R 4.0.5)
         P graphics         * 4.0.4      2021-02-15 [2] local
         P grDevices        * 4.0.4      2021-02-15 [2] local
         P grid               4.0.4      2021-02-15 [2] local
           gtable             0.3.3      2023-03-21 [1] CRAN (R 4.0.4)
           gtools             3.9.2      2021-06-06 [1] CRAN (R 4.0.5)
           insight            0.19.1     2023-03-18 [1] CRAN (R 4.0.4)
           kSamples           1.2-9      2019-05-20 [1] CRAN (R 4.0.5)
           lattice            0.20-41    2020-04-02 [2] CRAN (R 4.0.4)
           lifecycle          1.0.3      2022-10-07 [1] CRAN (R 4.0.4)
           lme4               1.1-27.1   2021-06-22 [1] CRAN (R 4.0.5)
           lmerTest           3.1-3      2020-10-23 [1] CRAN (R 4.0.5)
           magrittr           2.0.1      2020-11-17 [1] CRAN (R 4.0.5)
           MASS               7.3-53     2020-09-09 [2] CRAN (R 4.0.4)
           Matrix             1.3-2      2021-01-06 [2] CRAN (R 4.0.4)
           MatrixModels       0.5-0      2021-03-02 [1] CRAN (R 4.0.5)
           mc2d               0.1-22     2022-11-20 [1] CRAN (R 4.0.4)
           memoise            2.0.1      2021-11-26 [1] CRAN (R 4.0.5)
         P methods          * 4.0.4      2021-02-15 [2] local
           minqa              1.2.4      2014-10-09 [1] CRAN (R 4.0.5)
           multcomp           1.4-23     2023-03-09 [1] CRAN (R 4.0.4)
           multcompView       0.1-9      2023-04-09 [1] CRAN (R 4.0.4)
           munsell            0.5.0      2018-06-12 [1] CRAN (R 4.0.5)
           mvtnorm            1.1-3      2021-10-08 [1] CRAN (R 4.0.5)
           nlme               3.1-152    2021-02-04 [2] CRAN (R 4.0.4)
           nloptr             1.2.2.3    2021-11-02 [1] CRAN (R 4.0.5)
           numDeriv           2016.8-1.1 2019-06-06 [1] CRAN (R 4.0.3)
           paletteer          1.5.0      2022-10-19 [1] CRAN (R 4.0.4)
         P parallel           4.0.4      2021-02-15 [2] local
           parameters         0.21.0     2023-04-19 [1] CRAN (R 4.0.4)
           patchwork          1.1.1      2020-12-17 [1] CRAN (R 4.0.5)
           pbapply            1.7-0      2023-01-13 [1] CRAN (R 4.0.4)
           performance        0.10.3     2023-04-07 [1] CRAN (R 4.0.4)
           pillar             1.9.0      2023-03-22 [1] CRAN (R 4.0.4)
           pkgconfig          2.0.3      2019-09-22 [1] CRAN (R 4.0.5)
           plyr               1.8.6      2020-03-03 [1] CRAN (R 4.0.5)
           PMCMRplus          1.9.3      2021-11-13 [1] CRAN (R 4.0.5)
           purrr              0.3.4      2020-04-17 [1] CRAN (R 4.0.5)
           R6                 2.5.1      2021-08-19 [1] CRAN (R 4.0.5)
           Rcpp               1.0.7      2021-07-07 [1] CRAN (R 4.0.5)
         D RcppParallel       5.1.4      2021-05-04 [1] CRAN (R 4.0.5)
           rematch2           2.1.2      2020-05-01 [1] CRAN (R 4.0.5)
           reshape            0.8.9      2022-04-12 [1] CRAN (R 4.0.5)
           reshape2           1.4.4      2020-04-09 [1] CRAN (R 4.0.5)
           rlang              1.1.0      2023-03-14 [1] CRAN (R 4.0.4)
           Rmpfr              0.8-7      2021-10-28 [1] CRAN (R 4.0.5)
           rstantools         2.3.1      2023-03-30 [1] CRAN (R 4.0.4)
           rstudioapi         0.14       2022-08-22 [1] CRAN (R 4.0.4)
           sandwich           3.0-2      2022-06-15 [1] CRAN (R 4.0.4)
           scales             1.2.1      2022-08-20 [1] CRAN (R 4.0.4)
           sessioninfo        1.2.2      2021-12-06 [1] CRAN (R 4.0.5)
         P splines            4.0.4      2021-02-15 [2] local
         P stats            * 4.0.4      2021-02-15 [2] local
           statsExpressions   1.2.0      2021-10-19 [1] CRAN (R 4.0.5)
           stringi            1.7.3      2021-07-16 [1] CRAN (R 4.0.5)
           stringr            1.4.0      2019-02-10 [1] CRAN (R 4.0.5)
           SuppDists          1.1-9.5    2020-01-18 [1] CRAN (R 4.0.5)
           survival           3.2-7      2020-09-28 [2] CRAN (R 4.0.4)
           TH.data            1.1-2      2023-04-17 [1] CRAN (R 4.0.4)
           tibble             3.2.1      2023-03-20 [1] CRAN (R 4.0.4)
           tidyr              1.1.4      2021-09-27 [1] CRAN (R 4.0.5)
           tidyselect         1.2.0      2022-10-10 [1] CRAN (R 4.0.4)
         P tools              4.0.4      2021-02-15 [2] local
           utf8               1.2.3      2023-01-31 [1] CRAN (R 4.0.4)
         P utils            * 4.0.4      2021-02-15 [2] local
           vctrs              0.6.1      2023-03-22 [1] CRAN (R 4.0.4)
           withr              2.5.0      2022-03-03 [1] CRAN (R 4.0.5)
           WRS2             * 1.1-3      2021-07-20 [1] CRAN (R 4.0.5)
           xtable             1.8-4      2019-04-21 [1] CRAN (R 4.0.5)
           zeallot            0.1.0      2018-01-28 [1] CRAN (R 4.0.5)
           zoo                1.8-9      2021-03-09 [1] CRAN (R 4.0.5)
