### ISSUE TITLE
Package Installation without .rmd files

### ISSUE THREAD

**Issue by rbratslaver** [IndrajeetPatil/ggstatsplot#75]
Hi - my employer blocks .rmd files and this unfortunately prevents me from being able to install the package; I was wondering if there was a way to install it without these - not sure how this would work, but figured I would ask. Thanks for your time. 

this is a snippet of the error:  **/README.Rmd': Permission denied**

**Comment by IndrajeetPatil** [comment]
Hmm, never encountered this issue before, so not sure. Can you try the following and see if it works?

``` r
# downloading the package from GitHub
devtools::install_github(
  repo = "IndrajeetPatil/ggstatsplot", # package path on GitHub
  dependencies = FALSE,                # assumes that you already have all packages installed needed for this package to work
  build_opts = "--no-build-vignettes"  # skips building vignettes
) 
```

**Comment by rbratslaver** [comment]
Thanks for the quick response - that didn't work, but I'm working with our
IT to see if they can make an exception; thanks for taking a look, feel
free to close this ticket.
