### ISSUE TITLE
in ggscatterstats.rmd file, what you know the the data were 3.32 times more probable under the null hypothesis as compared to the alternative hypothesis. 

### ISSUE THREAD

**Issue by LiXingguangBrandonStark** [IndrajeetPatil/ggstatsplot#752]
Pearson’s correlation test revealed that, across 32 cars, a measure of acceleration (1/4 mile time; qsec) was positively correlated with rear axle ratio (drat), but this effect was not statistically significant. The effect size (𝑟=0.09) was small, as per Cohen’s (1988) conventions. The Bayes Factor for the same analysis revealed that the data were 3.32 times more probable under the null hypothesis as compared to the alternative hypothesis. This can be considered moderate evidence (Jeffreys, 1961) in favor of the null hypothesis (of absence of any correlation between these two variables).

**Comment by IndrajeetPatil** [comment]
`3.32` is the Bayes Factor value and is obtained by taking the exponent of the log of Bayes Factor present in the plot caption:

![image](https://user-images.githubusercontent.com/11330453/169538774-9cf79168-e734-4620-9547-faa2ef8f4841.png)


So, for this analysis:

```r
> exp(1.2)
[1] 3.320117
```

**Comment by LiXingguangBrandonStark** [comment]
thank you. Very nice.
