### ISSUE TITLE
Plot "plm", "panelmodel" regression class

### ISSUE THREAD

**Issue by alexmufeq** [IndrajeetPatil/ggstatsplot#762]
Hi, I want to plot a "plm", "panelmodel" regression class, is it possible to do this?

Thank you

**Comment by IndrajeetPatil** [comment]
# `plm`

``` r
library(ggstatsplot)
library(plm)

data("Produc", package = "plm")

zz <- plm(log(gsp) ~ log(pcap) + log(pc) + log(emp) + unemp,
          data = Produc, index = c("state","year"))

ggcoefstats(zz)
```

![](https://i.imgur.com/SmicTSZ.png)

<sup>Created on 2022-06-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by IndrajeetPatil** [comment]
# `panelmodel`

``` r
library(ggstatsplot)
library(plm)

data("EmplUK", package = "plm")

z1 <- pgmm(log(emp) ~ lag(log(emp), 1:2) + lag(log(wage), 0:1)
           + log(capital) + lag(log(output), 0:1) | lag(log(emp), 2:99),
           data = EmplUK, effect = "twoways", model = "twosteps")

ggcoefstats(z1)
```

![](https://i.imgur.com/iBm7Bhq.png)

<sup>Created on 2022-06-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by IndrajeetPatil** [comment]
Next time, please check if the function works and only then create an issue. Thanks.
