### ISSUE TITLE
How to modify labels for p-values and size in ggstatsplot

### ISSUE THREAD

**Issue by covid19ec** [IndrajeetPatil/ggstatsplot#765]
I am working on a plot using ggstatsplot R package. After completing the plot I have an issue. This is the code for my plot:

```
library(ggstatsplot)
#Data
data("movies_long")
movies_long
#Plot
Myplot <- ggbarstats(
  data             = movies_long,
  x                = mpaa,
  y                = year,
  title            = "Distribution of movies per year",
  xlab             = "year",
  legend.title     = "",
  ggplot.component = list(ggplot2::scale_x_discrete(guide = ggplot2::guide_axis(n.dodge = 2))),
  palette          = "Set2"
  )
```

The output is next:
![imagen](https://user-images.githubusercontent.com/84138212/174493795-445729a6-f9e2-4593-8d6f-5a086f55124e.png)

The plot is very useful but it has two problems. First is the overlap of p-values at top of bars. Second is the size n which also has overlap, how could I improve the p-values labels at the top of bars and also the size n at bottom?

Is there any way to take these p-values and translate in p<0.001, p<0.1 using confidence levels?

![imagen](https://user-images.githubusercontent.com/84138212/174493811-5d9edc5d-a4dd-4452-a58c-eb80b8c65c7f.png)

Many thanks for your help. In the extreme case, is there any way to know how to compute the p-values (which test is being applied) at each bar, so that I can replicate it and create a similar plot using ggplot2?

**Comment by IndrajeetPatil** [comment]
This seems to have been answered [here](https://stackoverflow.com/questions/72679072/how-to-modify-labels-for-p-values-and-size-in-ggstatsplot).

To get data frames of statistical analysis results, have a look at this function:
https://indrajeetpatil.github.io/ggstatsplot/reference/extract_stats.html

To understand which tests were carried out, see:
https://indrajeetpatil.github.io/ggstatsplot/articles/web_only/ggbarstats.html#summary-of-tests
