### ISSUE TITLE
Limit of y-axis

### ISSUE THREAD

**Issue by drdknykrisztina** [IndrajeetPatil/ggstatsplot#769]
In short, I would like to set the limit to y axis to max value while running grouped_ggscatterstats (three variable for grouping, each of them has different max values), but I couldn't find a usable method to do it, neither of this working:
- expand_limits(y=max),
- lim(y=max)

Error message:

_Error in FUN(X[[i]], ...) : 
  attempt to replicate an object of type 'builtin'_

**Comment by IndrajeetPatil** [comment]
Does FAQ#7 solve your issue?

https://indrajeetpatil.github.io/ggstatsplot/articles/web_only/faq.html#how-can-i-have-uniform-y-axes-ranges-in-grouped_-functions

**Comment by drdknykrisztina** [comment]
I tried, but had a new error:

_Error in .f(data = .l[[1L]][[i]], title = .l[[2L]][[i]], output = .l[[3L]][[1L]],  : 
  formal argument "ggplot.component" matched by multiple actual arguments_

**Comment by IndrajeetPatil** [comment]
> formal argument "ggplot.component" matched by multiple actual arguments

This means that you are specifying `ggplot.component` argument more than once.

**Comment by drdknykrisztina** [comment]
yes, it's true, so I modified like this:

**ggplot.component = list(ggplot2::scale_x_continuous(
  breaks = seq(2, 9, 1),
  limits = (c(0, 9)))),
  ggplot2::scale_y_continuous(
  breaks = seq(0, 30, 1),
  limits = (c(0, 30)))**

The incoming error now:
_Error in as.vector(x, "character") : 
  cannot coerce type 'environment' to vector of type 'character'_

**Comment by IndrajeetPatil** [comment]
That code is not correct. It should instead be:

```r
ggplot.component = list(
  ggplot2::scale_x_continuous(
    breaks = seq(2, 9, 1),
    limits = (c(0, 9))
  ),
  ggplot2::scale_y_continuous(
    breaks = seq(0, 30, 1),
    limits = (c(0, 30))
  )
)

```

**Comment by drdknykrisztina** [comment]
Thank you very much, It worked.

**Comment by IndrajeetPatil** [comment]
Great!
