### ISSUE TITLE
ggpiestats not recycling colors

### ISSUE THREAD

**Issue by ibecav** [IndrajeetPatil/ggstatsplot#77]
trying to use ggpiestats on a variable that has more than 8 levels.  The first 8 levels are working fine, anything above 8 does not get a color assigned.  Perhaps that's by design but seems dysfunctional.  Could it at least recycle colors so the extras are not white?  Or am I doing something wrong? 

Very, very very simple reprex below

``` r
library(ggstatsplot)
mainexample <- rep(c("one","two","three","four","five","six","seven","eight","nine","ten"),5)
mainexample<-as.data.frame(mainexample)
# This shows the problem
ggpiestats(data = mainexample, main = "mainexample")
```

![](https://i.imgur.com/kQSID7b.png)

``` r
# I can of course manually force a different palette
ggpiestats(data = mainexample, main = "mainexample", palette = "Set3")
```

![](https://i.imgur.com/UpJGA3i.png)

<sup>Created on 2018-10-24 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by IndrajeetPatil** [comment]
Yeah, this is expected behavior from this function. The recycling doesn't happen because this is the `ggplot2` behavior as well and I wanted to be consistent with `ggplot2`'s behavior. 

``` r
ggplot(data = mainexample,
       mapping = aes(x = mainexample, fill = mainexample)) +
  geom_bar() + scale_fill_brewer(palette = "Dark2")
#> Warning in RColorBrewer::brewer.pal(n, pal): n too large, allowed maximum for palette Dark2 is 8
#> Returning the palette you asked for with that many colors
```

![](https://i.imgur.com/Ff3ANam.png)

<sup>Created on 2018-10-24 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>


This issue actually affects all functions in the package where multiple colors are used (`ggbetweenstats` is another example). To be backward compatible, I have not changed the palette from `Dark2` (from `RColorBrewer` package) to some other palette which has many more colors. I am counting on the user to change the palette, as you have shown in your example. I am guessing it will be helpful to add message promting the user to change the palette in case of more than 8 factor levels.

**Comment by ibecav** [comment]
Yes thank you a warning or note would helpful. I got about halfway through gg coefficient rmd before I got distracted by work I’ll get back to it when I can

**Comment by IndrajeetPatil** [comment]
Sure, no worries. Just keep your branch synced with mine. Made few minor changes to the vignette to keep the CI platform builds from failing.

**Comment by IndrajeetPatil** [comment]
Next commit will fix this-
``` r
library(ggstatsplot)
set.seed(123)

# example with texas housing dataset

# ggpiestats
# when insufficient no. of colors in the palette
ggstatsplot::ggpiestats(data = ggplot2::txhousing, main = year)
#> Warning: Number of factor levels is greater than the specified palette color count.
#>  Try using another color palette (and/or package).
#> 
```

![](https://i.imgur.com/AE1h0Qf.png)

``` r

# otherwise
ggstatsplot::ggpiestats(
  data = ggplot2::txhousing,
  main = year,
  package = "dichromat",
  palette = "DarkRedtoBlue.18"
)
```

![](https://i.imgur.com/mkVwkVb.png)

``` r

# ggbetweenstats
ggstatsplot::ggbetweenstats(
  data = ggplot2::txhousing,
  x = year,
  y = listings,
  messages = FALSE
)
#> Warning: Number of factor levels is greater than the specified palette color count.
#>  Try using another color palette (and/or package).
#> 
```

![](https://i.imgur.com/lJK4H7o.png)

``` r

# even if the default palette is changed and there are still not enough colors
ggstatsplot::ggbetweenstats(
  data = ggplot2::txhousing,
  x = year,
  y = listings,
  messages = FALSE,
  palette = "Set3"
)
#> Warning: Number of factor levels is greater than the specified palette color count.
#>  Try using another color palette (and/or package).
#> 
```

![](https://i.imgur.com/LsEKkZM.png)

``` r

# ggcoefstats
# if not enough colors in the palette, defaults to "black"
ggstatsplot::ggcoefstats(x = stats::lm(
  formula = rating ~ belief * outcome * item,
  data = ggstatsplot::intent_morality
))
#> Warning: Number of factor levels is greater than the specified palette color count.
#>  Try using another color palette (and/or package).
#> 
```

![](https://i.imgur.com/n8JsOTk.png)

``` r

# if yes, the usual behavior
ggstatsplot::ggcoefstats(
  x = stats::lm(
    formula = rating ~ belief * outcome * item,
    data = ggstatsplot::intent_morality
  ),
  package = "ggthemes",
  palette = "stata_colors"
)
```

![](https://i.imgur.com/W0dAIp0.png)

<sup>Created on 2018-10-28 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
