### ISSUE TITLE
Why axes are inverter in ggbarstats (and ggpiestats)?

### ISSUE THREAD

**Issue by lucavd** [IndrajeetPatil/ggstatsplot#779]
```
# for reproducibility
[set.seed](https://rdrr.io/r/base/Random.html)(123)

## plot
[ggbarstats](https://indrajeetpatil.github.io/ggstatsplot/reference/ggbarstats.html)(
  data = Titanic_full,
  x = Survived,
  y = Sex
)
```
`Survived` variation is on the y axis but should be inserted in the x one. I think it is counterintuitive, but maybe I am wrong.

Thank you for your effort and work

**Comment by IndrajeetPatil** [comment]
I am not sure what you mean. They are not comparable; `ggpiestats()` is in polar coordinates, `ggbarstats()` isn't.

At any rate, if you don't agree with the defaults, you can either switch `x` argument with `y`, or even use `{ggplot2}` to customize it further.

``` r
library(ggstatsplot)

ggpiestats(
  data = Titanic_full,
  x = Survived,
  y = Sex
)
```

![](https://i.imgur.com/six14gb.png)

``` r

ggbarstats(
  data = Titanic_full,
  x = Survived,
  y = Sex
)
```

![](https://i.imgur.com/aKsSNfN.png)

<sup>Created on 2022-08-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

``` r
library(ggstatsplot)
#> You can cite this package as:
#>      Patil, I. (2021). Visualizations with statistical details: The 'ggstatsplot' approach.
#>      Journal of Open Source Software, 6(61), 3167, doi:10.21105/joss.03167

ggbarstats(
  data = Titanic_full,
  x = Survived,
  y = Sex,
  ggplot.component = list(ggplot2::coord_flip())
)
```

![](https://i.imgur.com/JBlKvCJ.png)

<sup>Created on 2022-08-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>
