### ISSUE TITLE
Hiding repeated ylabel in grouped_ggwithinstats

### ISSUE THREAD

**Issue by andreifoldes** [IndrajeetPatil/ggstatsplot#786]
**Describe the solution you'd like**
Greetings, 
I think it would make for nice publishable plots if for the "grouped_ggwithinstats" plots the repeated ylabels could be hidden (e.g: for https://indrajeetpatil.github.io/ggstatsplot/reference/grouped_ggwithinstats.html#ref-examples hide "desire" for Male column, but keeping it for the Female column) . Additionally, would be nice to optionally be able to merge all the xlabels into one centered xlabel.

**How could we do it?**
merge_xlabels/merge_y_labels?

**Comment by IndrajeetPatil** [comment]
I am not aware of `merge_xlabels()` or `merge_y_labels()`. If you have seen this in any extension packages, please post a link.

I think the best solution here is for you to remove the duplicated plot elements and then customize the annotations yourself using `{ggplot2}`/`{patchwork}`.

For example, here I am removing the duplicated secondary Y axis label and including it only once in the caption. You can do similar things with other annotations.

``` r
library(ggstatsplot)
library(ggplot2)

grouped_ggbetweenstats(
  data = dplyr::filter(
    movies_long,
    genre %in% c("Action", "Comedy"),
    mpaa %in% c("R", "PG", "PG-13")
  ),
  x = mpaa,
  y = rating,
  grouping.var = genre
)
```

<img src="https://i.imgur.com/u90kNU7.png" width="100%" />

``` r

grouped_ggbetweenstats(
  data = dplyr::filter(
    movies_long,
    genre %in% c("Action", "Comedy"),
    mpaa %in% c("R", "PG", "PG-13")
  ),
  x = mpaa,
  y = rating,
  grouping.var = genre,
  ggplot.component = list(theme(axis.title.y.right = element_blank())),
  annotation.args = list(caption = "Pairwise test: Games-Howell")
)
```

<img src="https://i.imgur.com/gbzs71B.png" width="100%" />

<sup>Created on 2022-09-21 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by andreifoldes** [comment]
Thanks!

> I am not aware of merge_xlabels() or merge_y_labels(). If you have seen this in any extension packages, please post a link.

Sorry this was meant as a "Feature suggestion",

**Comment by IndrajeetPatil** [comment]
Ah, I see. I think the right place for this to be implemented would be `{patchwork}` package, which is what is internally used by `{ggstatsplot}`.

It currently supports combining legends, maybe it can also support what you have in mind, and then `{ggstatsplot}` will benefit from it upstream.

https://github.com/thomasp85/patchwork/issues

**Comment by IndrajeetPatil** [comment]
Actually, there is already an issue about this: https://github.com/thomasp85/patchwork/issues/282

Hopefully this is supported 🤞
