### ISSUE TITLE
Is it possible to use ggbarstats without stack

### ISSUE THREAD

**Issue by hhchang0210** [IndrajeetPatil/ggstatsplot#787]
Hi,
This is a great tool for statistics. I have a problem when I use ggbarstats. Can I only show MPAA == PG in y-axis [https://github.com/IndrajeetPatil/ggstatsplot/raw/main/man/figures/README-ggbarstats1-1.png](url)? Thank you very much.

**Comment by IndrajeetPatil** [comment]
I would recommend just filtering the data to only the factor levels you are interested in, and then feeding it to `ggbarstats()`.
