### ISSUE TITLE
installation faild for older version of ggstatsplot packge

### ISSUE THREAD

**Issue by taoshengqiansui** [IndrajeetPatil/ggstatsplot#791]
I want to use the I want to use the marginal.type argument in the old version of ggstatsplot package, but when i run "remotes::install_version("ggstatsplot",version = "0.8.0")",it returns an ERROR of "lazy loading failed for package 'ggstatsplot'"

**Comment by IndrajeetPatil** [comment]
Try:

```r
packageurl <- "http://cran.r-project.org/src/contrib/Archive/ggstatsplot/ggstatsplot_0.8.0.tar.gz"
install.packages(packageurl, repos=NULL, type="source")
```

**Comment by IndrajeetPatil** [comment]
This should do it:

```r
require(devtools)
install_version("ipmisc", version = "6.0.2", repos = "http://cran.us.r-project.org")
install_version("statsExpressions", version = "1.1.0", repos = "http://cran.us.r-project.org")
install_version("pairwiseComparisons", version = "3.1.6", repos = "http://cran.us.r-project.org")
install_version("ggstatsplot", version = "0.8.0", repos = "http://cran.us.r-project.org")
```

**Comment by taoshengqiansui** [comment]
it works,Thank you very much!

**Comment by taoshengqiansui** [comment]
> This should do it:
> 
> ```r
> require(devtools)
> install_version("ipmisc", version = "6.0.2", repos = "http://cran.us.r-project.org")
> install_version("statsExpressions", version = "1.1.0", repos = "http://cran.us.r-project.org")
> install_version("pairwiseComparisons", version = "3.1.6", repos = "http://cran.us.r-project.org")
> install_version("ggstatsplot", version = "0.8.0", repos = "http://cran.us.r-project.org")
> ```

Hello!
here i encountered another problem
when i run
"pall <- lapply(genert, function(i){
  print(i)
  p <- ggscatterstats(nc,y = {{i}},x = "Macrophage",
                      type = "pearson",
                      centrality.para = "mean",
                      margins = "both",
                      xfill = "#009E73",
                      yfill = "#D55E00",
                      marginal = T,
                      title = paste0("Relationship between ",i," and Macrophage"))
  return(p)
})

library(patchwork)
pall[[1]]+pall[[2]]+pall[[3]]+pall[[4]]"
it retured an error of "non-numeric argument to binary operator", for the 0.80 version of ggstasplot, can this error be avoided by changing of the code.
Thany you for your kind suggestion!
