### ISSUE TITLE
Getting rid of the 'boxviolin' on the grouped_ggwithinstats

### ISSUE THREAD

**Issue by martynagalazka** [IndrajeetPatil/ggstatsplot#795]
Hello, 
Just a visual preference here. I'm plotting grouped_ggwithinstats plot. 
I specified 
plot.type = "box" 
but I am still getting box + the violin around the box
Is there a way to get rid of the 'petals' around it and just keep the boxes? 

Thanks a lot, 
Martyna 

```r
# insert reprex here
```

**Comment by IndrajeetPatil** [comment]
This is because `ggwithinstats()` doesn't have `plot.type` argument - only `ggbetweenstats()` does.

Closing in favour of https://github.com/IndrajeetPatil/ggstatsplot/issues/670.
