### ISSUE TITLE
T-test for scatter plot?!

### ISSUE THREAD

**Issue by AbdurrahmanMN** [IndrajeetPatil/ggstatsplot#799]
**Describe the solution you'd like**
The function **ggscatterstats** shows student T test at top. 
https://indrajeetpatil.github.io/ggstatsplot/articles/web_only/ggscatterstats.html

**How could we do it?**
Can the test name be corrected (I believe it's pearson's correlation test but this confuses me a lot) or kindly correct me if it's indeed t-test.

Thank you for your great package

**Comment by IndrajeetPatil** [comment]
That expression is correct.

The estimate is Pearson's correlation coefficient, but inference is drawn based on the _t_-statistic.

**Comment by IndrajeetPatil** [comment]
It's the same statistic that you see here:

``` r
cor.test(mtcars$wt, mtcars$mpg)
#> 
#>  Pearson's product-moment correlation
#> 
#> data:  mtcars$wt and mtcars$mpg
#> t = -9.559, df = 30, p-value = 1.294e-10
#> alternative hypothesis: true correlation is not equal to 0
#> 95 percent confidence interval:
#>  -0.9338264 -0.7440872
#> sample estimates:
#>        cor 
#> -0.8676594
```

<sup>Created on 2022-10-14 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by AbdurrahmanMN** [comment]
Thank you!
To report in APA Format, is this a valid report based on the results in the first example in the vignette?

"There was a weak positive correlation between the two variables, r(1577) = .05, p = .003."

**Comment by IndrajeetPatil** [comment]
Yes.
