### ISSUE TITLE
Problem installing ggstatplot - NON ZERO EXIT status

### ISSUE THREAD

**Issue by sfd99** [IndrajeetPatil/ggstatsplot#80]
Hi, 

As prescribed,
tried installing ggstatsplot from CRAN
but get the **error message (below)**.
_Same error_
if I try to install from GITHUB ("If you have time" install code)

**ERROR messages at the end of install...**
* installing *source* package ‘rgl’ ...
** package ‘rgl’ successfully unpacked and MD5 sums checked
checking for gcc... gcc -std=gnu99
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc -std=gnu99 accepts -g... yes
checking for gcc -std=gnu99 option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -std=gnu99 -E
checking for gcc... (cached) gcc -std=gnu99
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc -std=gnu99 accepts -g... (cached) yes
checking for gcc -std=gnu99 option to accept ISO C89... (cached) none needed
checking for libpng-config... yes
configure: using libpng-config
configure: using libpng dynamic linkage
checking for X... libraries , headers 
checking GL/gl.h usability... no
checking GL/gl.h presence... no
checking for GL/gl.h... no
checking GL/glu.h usability... no
checking GL/glu.h presence... no
checking for GL/glu.h... no
configure: error: missing required header GL/gl.h
ERROR: configuration failed for package ‘rgl’
* removing ‘/home/ray/R/i686-pc-linux-gnu-library/3.5/rgl’
Error in i.p(...) : 
  (converted from warning) installation of package ‘rgl’ had non-zero exit status
> 

And so, ggstatsplot is not installed...
Help! 
**SFd99
San Francisco**
----------------
**Using latest Rstudio, w/R 351, Ubuntu Linux 14.04 32-bits.**

**Comment by IndrajeetPatil** [comment]
Hmm, this is saying that `ggstatsplot` can't be installed because one the packages it relies on-`rgl`- can't be downloaded. 

Can you see if you can install the `rgl` package from `CRAN`? 
```r
utils::install.packages("rgl")
```

If you can't, then the problem is with `rgl`, and not `ggstatsplot`.

**Comment by sfd99** [comment]
**_Thanks Indrajeet!._**
Installed "rgl" separately (as you suggested),
and the install of ggstatsplot pkg. worked ok.

**Quick Q** (if I may...):
In the ggbetweenstats example  iris plot,
what does the "**p < 0.001**" (at the top) mean/represent?
Sorry, it's my limited stats knowledge...

**Comment by IndrajeetPatil** [comment]
It means that p-value is less than or equal to 0.001.
