### ISSUE TITLE
I want to change colour by group variable

### ISSUE THREAD

**Issue by IDOJI** [IndrajeetPatil/ggstatsplot#814]
I am using "ggscatterstats", but
no matter what options I try, I can't change colour of points by some group variable in the dataset.
like "geom_point(aes(colour=!!group), data)" doesn't work.

Do you have any options for this? Or "ggscatterstats" doesn't have any options for this?

**Comment by IndrajeetPatil** [comment]
Hi,

No, unfortunately, this is not possible. There are also no plans to add another aesthetic variable to what are inherently bivariate visualizations in `{ggstatsplot}`.

That said, it's actually quite easy to prepare such a plot yourself and then display results from the analysis.

``` r
library(ggstatsplot)
library(ggside)
library(statsExpressions)

df <- mtcars
df$cyl <- as.factor(df$cyl)

rez <- corr_test(df, wt, mpg)

ggplot(df, aes(wt, mpg)) + 
  geom_point(aes(color = cyl)) + 
  geom_xsidehistogram(aes(y = after_stat(count), fill = cyl)) + 
  geom_ysidehistogram(aes(x = after_stat(count), fill = cyl)) +
  labs(subtitle = rez$expression[[1]])
```

![](https://i.imgur.com/MOu0A0G.png)

<sup>Created on 2022-11-22 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by IDOJI** [comment]
I appreciate your reply.
Thank you very much.
My problem is solved perfectly!
