### ISSUE TITLE
Negative trimmed mean values in ggbetweenstats

### ISSUE THREAD

**Issue by ShailNair** [IndrajeetPatil/ggstatsplot#822]
Hi, thank you for the awesome package. when I plot ggbetweenstats with my data all the samples show negative trimmed mean values (even though I do not have any negative value within the samples).
```
ggbetweenstats(
  data = cl,
  x = day,
  y = rpkm, 
  type = "robust", 
  xlab = "Days", ## label for the x-axis
  ylab = "Abundance (RPKM) of virulent phages", 
  plot.type = "boxviolin", 
) +
  ggplot2::scale_y_continuous(
    limits = c(0, 2),
    breaks = seq(from = 0, to = 2, by = 0.5)
  )
```
![000010](https://user-images.githubusercontent.com/59241611/208054193-a9ba80dd-a65e-4267-92b8-3be66d3f1e2c.png)
is that normal to have negative trimmed mean values for data without any negative data points?

**Comment by IndrajeetPatil** [comment]
Sorry, I don't understand. 

The Y-axis **starts** at 0. Where are the negative values? Seems like there are many close-to-0 values which are all clustered at the bottom.

**Comment by ShailNair** [comment]
My bad. I misunderstood. It is equal to (=) sign and not minus (-). Due to the compactness of the plot the "=" looks as "-" on my PC. After zooming the plot I realized that it is indeed an "=" sign.
Thank you for the quick reply.
