### ISSUE TITLE
external dependencies for functions in DESCRIPTION

### ISSUE THREAD

**Issue by pmenzel** [IndrajeetPatil/ggstatsplot#837]
Hi,

would it be possible to add external dependencies that are needed for only some functions to the `Imports` section of the [DESCRIPTION](https://github.com/IndrajeetPatil/ggstatsplot/blob/main/DESCRIPTION) file instead of the `Suggests` section? For example, `ggwithinstats()` needs the `afex` package.

That would make it easier to use ggstatsplot through conda, so that one just needs to add ggstatsplot to the environment and all dependencies would be installed automatically.

I wanted to make a [PR to the conda-forge recipe](https://github.com/conda-forge/r-ggstatsplot-feedstock/pull/31), which adds the dependency there, but they only include dependencies when they are listed in DESCRIPTION/Imports.

**Comment by IndrajeetPatil** [comment]
Hi, thanks for the feedback. I agree that some suggested dependencies should be hard dependencies of _ggstatsplot_ for better user experience. 

I have made the necessary changes now and plan to update both _statsExpressions_ and _ggstatsplot_ on CRAN soon.
