### ISSUE TITLE
Remove histograms in ggscatterstats?

### ISSUE THREAD

**Issue by AntoineSoetewey** [IndrajeetPatil/ggstatsplot#838]
Hello,

Is there a way to remove the histograms when using ggscatterstats?
If possible, I'd like to keep everything else.

I tried playing with xsidehistogram.args and ysidehistogram.args, without success.

Thanks in advance.

**Comment by IndrajeetPatil** [comment]
Is this what you are looking for?

``` r
library(ggstatsplot)

ggscatterstats(mtcars, wt, mpg, marginal = FALSE)
```

![](https://i.imgur.com/a4FKNWy.png)

<sup>Created on 2023-03-15 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by AntoineSoetewey** [comment]
Exactly, many thanks for your help !
