### ISSUE TITLE
Round p-values to 3 digits

### ISSUE THREAD

**Issue by AntoineSoetewey** [IndrajeetPatil/ggstatsplot#842]
Hello,

For a project, I performed the following test:

![image](https://user-images.githubusercontent.com/17910063/226317890-f3e4c1f8-5c3e-42c3-9f7c-20a3485c1c16.png)

I take $\alpha = 0.05$.
Since the p-value $\ge$ 0.05, I do not reject H0.

However, when I perform the test, I obtain a p-value of 0.048, so I would reject H0:

<img width="849" alt="Screenshot 2023-03-20 at 11 49 30" src="https://user-images.githubusercontent.com/17910063/226318256-1d483002-6f50-40b5-9767-e5db5807ac8b.png">

I concede that when the p-value is rounded to 2 digits, it would be equal to 0.05. However, that leads to a different conclusion of the test.

Is there a possibility to round p-values to 3 digits? It might not be needed to round all p-values to 3 digits, but when it is close to the significance level of 5%, it might be useful to have 3 digits instead of 2, as shown in the above example.

*(As a sidenote, I understand that there is a debate about applying 0.05 as a strict threshold (one would argue that 0.048 is very close to 0.05, so we should be careful when concluding that H0 is rejected), but for my students this is beyond the scope of the class.)*

Regards,
Antoine

**Comment by IndrajeetPatil** [comment]
You can control this using the (extremely poorly named) `k` parameter available in all function signatures:

``` r
library(ggstatsplot)

ggbetweenstats(mtcars, am, wt)
```

![](https://i.imgur.com/mjUWp1A.png)

``` r

ggbetweenstats(mtcars, am, wt, k = 3L)
```

![](https://i.imgur.com/1pISSbZ.png)

<sup>Created on 2023-03-20 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by AntoineSoetewey** [comment]
Thanks a lot!
