### ISSUE TITLE
Mean dot appearance when combining plots

### ISSUE THREAD

**Issue by zberry37** [IndrajeetPatil/ggstatsplot#846]
Hello! I have been using ggstatsplot::ggbetweenstats() to create plots and store as objects, that I then combine into a master plot using ggstatsplot::combine_plots(). When I combine two plots, the visualization looks perfect (see below). 

# plot 1
lossdf <- df %>% 
  filter(reason == "Loss of Passion")
p1 <- ggbetweenstats(data = lossdf, x = Judgment, y = 'Moral Character', results.subtitle = FALSE, title = "Loss of Passion") +
  ggplot2::scale_y_continuous(limits = c(1,7), breaks = seq(from = 1, to = 7, by = 1)) +
  ggplot2::theme( 
    text = element_text(size = 8, color = "black"),
    axis.text = element_text(size = 10, color = "black"),
    axis.title = element_text(size = 12),
    axis.ticks = element_blank(),
    panel.grid = element_line(color = "#b4aea9"),
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.major.y = element_line(linetype = "dashed"),
    plot.title = element_text(hjust = 0.5))

# plot 2
diffdf <- df %>% 
  filter(reason == "Too Difficult")
p2 <- ggbetweenstats(data = diffdf, x = Judgment, y = 'Moral Character', results.subtitle = FALSE, title = "Too Difficult") +
  ggplot2::scale_y_continuous(limits = c(1,7), breaks = seq(from = 1, to = 7, by = 1)) +
  ggplot2::theme( 
    text = element_text(size = 8, color = "black"),
    axis.text = element_text(size = 10, color = "black"),
    axis.title = element_text(size = 12),
    axis.ticks = element_blank(),
    panel.grid = element_line(color = "#b4aea9"),
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.major.y = element_line(linetype = "dashed"),
    plot.title = element_text(hjust = 0.5))

# combine plots
combine_plots(
  list(p1,p2),
  plotgrid.args = list(nrow =1),
  annotation.args = list(
    title = "Panel A",
    theme = theme(
      plot.title = element_text(size = 20)
    )
  )
)

<img width="887" alt="image" src="https://user-images.githubusercontent.com/94022342/227783662-de37a4ac-9a73-4dbb-98c4-0a4e4adcd3a6.png">

However, when I try to combine 3+ plots, the red dots that represent the means disappear on half of the violins.

# plot 1
lossdf <- df %>% 
  filter(reason == "Loss of Passion")
p1 <- ggbetweenstats(data = lossdf, x = Judgment, y = 'Moral Character', results.subtitle = FALSE, title = "Loss of Passion") +
  ggplot2::scale_y_continuous(limits = c(1,7), breaks = seq(from = 1, to = 7, by = 1)) +
  ggplot2::theme( 
    text = element_text(size = 8, color = "black"),
    axis.text = element_text(size = 10, color = "black"),
    axis.title = element_text(size = 12),
    axis.ticks = element_blank(),
    panel.grid = element_line(color = "#b4aea9"),
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.major.y = element_line(linetype = "dashed"),
    plot.title = element_text(hjust = 0.5))

# plot 2
diffdf <- df %>% 
  filter(reason == "Too Difficult")
p2 <- ggbetweenstats(data = diffdf, x = Judgment, y = 'Moral Character', results.subtitle = FALSE, title = "Too Difficult") +
  ggplot2::scale_y_continuous(limits = c(1,7), breaks = seq(from = 1, to = 7, by = 1)) +
  ggplot2::theme( 
    text = element_text(size = 8, color = "black"),
    axis.text = element_text(size = 10, color = "black"),
    axis.title = element_text(size = 12),
    axis.ticks = element_blank(),
    panel.grid = element_line(color = "#b4aea9"),
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.major.y = element_line(linetype = "dashed"),
    plot.title = element_text(hjust = 0.5))

# plot 3
findf <- df %>% 
  filter(reason == "Financial Strain")
p3 <- ggbetweenstats(data = findf, x = Judgment, y = 'Moral Character', results.subtitle = FALSE, title = "Financial Strain") +
  ggplot2::scale_y_continuous(limits = c(1,7), breaks = seq(from = 1, to = 7, by = 1)) +
  ggplot2::theme( 
    text = element_text(size = 8, color = "black"),
    axis.text = element_text(size = 10, color = "black"),
    axis.title = element_text(size = 12),
    axis.ticks = element_blank(),
    panel.grid = element_line(color = "#b4aea9"),
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.major.y = element_line(linetype = "dashed"),
    plot.title = element_text(hjust = 0.5))

# combine plots
combine_plots(
  list(p1,p2,p3),
  plotgrid.args = list(nrow =1),
  annotation.args = list(
    title = "Panel A",
    theme = theme(
      plot.title = element_text(size = 20)
    )
  )
)

<img width="888" alt="image" src="https://user-images.githubusercontent.com/94022342/227783745-f8921d92-db68-4559-9313-99b917fd6632.png">

Is there any way to bring back in those red dots for the other half of the violins? I'm not sure why they are disappearing when trying to combine 3+ plots.

**Comment by IndrajeetPatil** [comment]
The dots are not disappearing. They are just hidden behind the labels. The label position is determined stochastically. It's difficult to prevent their overlap in an automated way.

The way you can make sure that the red dot is always visible is by changing the figure width. If you are using [`ggsave()`](https://ggplot2.tidyverse.org/reference/ggsave.html), specify `width` argument. If you are using _knitr_, then specify `fig.width`. You can experiment with a few values and see which one works for you.

**Comment by zberry37** [comment]
This is very helpful, thank you, Indrajeet!
