### ISSUE TITLE
R4.3.0 ggbetweenstats outlier does not work anymore

### ISSUE THREAD

**Issue by quant39** [IndrajeetPatil/ggstatsplot#856]
With R4.3.0, the function ggbetweenstats with outlier.tagging = TRUE does not work. Here is the sample code and the data with outlier values 70 and 67,

# Load the package
library(ggplot2)
library(ggstatsplot)

# Load the dataset 
data("warpbreaks")

# Create a boxplot of the dataset, outliers are shown as two distinct points
fig1 <- boxplot(warpbreaks)
fig1

#Create a boxplot that labels the outliers  
fig2 <- ggbetweenstats(data=warpbreaks,
               x=wool, y=breaks, outlier.tagging = TRUE)
fig2

**Comment by IndrajeetPatil** [comment]
Thanks for creating the issue. 

This actually has nothing to do with R 4.3. In the latest CRAN release, the outlier tagging functionality has been retired. Have a look at the change log here for the reasons: 

https://indrajeetpatil.github.io/ggstatsplot/news/index.html

**Comment by quant39** [comment]
Sorry to know that. It is only a useful feature for my use case in the ggstatplot package besides a very nice picture. Attached is the sample chart, and hope that you could put outlier.tagging back. Thanks.
![S P500_YTD](https://user-images.githubusercontent.com/118830750/235356404-37d42d25-f6b4-443f-b0ff-ad6fa62b9ffd.PNG)
