### ISSUE TITLE
grouped_ issue

### ISSUE THREAD

**Issue by eshuman1650** [IndrajeetPatil/ggstatsplot#866]
When I run any of the grouped_ functions I get the following error:

> df <- dplyr::tibble(
+   grp = c(rep("c", 5), rep("a", 5), rep("b", 5)),
+   val1 = runif(15),
+   val2 = runif(15)
+ )
> grouped_ggscatterstats(df, val1, val2, grouping.var = grp)
Error in unique.default(x, nmax = nmax) : 
  unique() applies only to vectors

Any idea what is going on? It doesn't matter which grouped function it is (e.g. ggscatterstats, ggbetweenstats, etc.) or what kind of data I give it.

```r
df <- dplyr::tibble(
  grp = c(rep("c", 5), rep("a", 5), rep("b", 5)),
  val1 = runif(15),
  val2 = runif(15)
)

grouped_ggscatterstats(df, val1, val2, grouping.var = grp)
```

**Comment by IndrajeetPatil** [comment]
Yeah, I think you just need to update your packages and the issue should resolve itself: 

``` r
df <- dplyr::tibble(
  grp = c(rep("c", 5), rep("a", 5), rep("b", 5)),
  val1 = runif(15),
  val2 = runif(15)
)

library(ggstatsplot)
grouped_ggscatterstats(df, val1, val2, grouping.var = grp)
```

![](https://i.imgur.com/78krgKH.png)

<sup>Created on 2023-07-20 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
