### ISSUE TITLE
boxplot.args does not do anything

### ISSUE THREAD

**Issue by yuliaUU** [IndrajeetPatil/ggstatsplot#869]
Using a reference: https://indrajeetpatil.github.io/ggstatsplot/reference/ggbetweenstats.html
the argument below:
```
boxplot.args = list(width = 0.3, alpha = 0.2, na.rm = TRUE),
```
Changing anything there has no effect on a plot

**Comment by paulyashna** [comment]
Hi,
I have the same issue, And because of this I cannot make the double plotting of the outliers go away. outlier.shape=NA also does not work. Would you have a solution to this?

**Comment by IndrajeetPatil** [comment]
I think the development branch version should have fixed this.

Can you download that version, refresh your R session, and see if you can reproduce the following output?

Download devel version:

```r
remotes::install_github("IndrajeetPatil/ggstatsplot@cran-rc-012")
```

Code to run:

``` r
library(ggstatsplot)
ggbetweenstats(mtcars, am, wt)
```

![](https://i.imgur.com/tqQFwZi.png)

``` r

ggbetweenstats(mtcars, am, wt,
  boxplot.args = list(
    color = "blue",
    linetype = "dashed",
    fill = "lightblue"
  )
)
```

![](https://i.imgur.com/MUt1v6c.png)

<sup>Created on 2023-07-20 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by yuliaUU** [comment]
almost works! the width argument breaks the plots:

```
ggbetweenstats(mtcars, am, wt,
               boxplot.args = list(
                 color = "blue",width = 3,
                 linetype = "dashed"))
```
boxplots and violins no longer alligned
![image](https://github.com/IndrajeetPatil/ggstatsplot/assets/54612866/0e86fb6d-335b-45de-a68d-4c7e9e42357d)

**Comment by IndrajeetPatil** [comment]
Yes, you will also need to adjust the other `geom`s accordingly (e.g. violin width also needs to be changed). But that's not related to the main issue here, which was whether `boxplot.args` is working.

**Comment by yuliaUU** [comment]
Understood! Thanks for the fix!
