### ISSUE TITLE
How to remove text on the right in grouped_ggbetweenstats

### ISSUE THREAD

**Issue by yuliaUU** [IndrajeetPatil/ggstatsplot#870]
Using the example listed in https://indrajeetpatil.github.io/ggstatsplot/articles/web_only/ggbetweenstats.html

```r
## select part of the dataset and use it for plotting
gapminder::gapminder %>%
  dplyr::filter(year %in% c(1967, 1987, 2007), continent != "Oceania") %>%
  grouped_ggbetweenstats(
    ## arguments relevant for ggbetweenstats
    x = continent,
    y = lifeExp,
    grouping.var = year,
    xlab = "Continent",
    ylab = "Life expectancy",
    pairwise.display = "significant", ## display only significant pairwise comparisons
    p.adjust.method = "fdr", ## adjust p-values for multiple tests using this method
    # ggtheme = ggthemes::theme_tufte(),
    package = "ggsci",
    palette = "default_jco",
    ## arguments relevant for combine_plots
    annotation.args = list(title = "Changes in life expectancy across continents (1967-2007)"),
    plotgrid.args = list(nrow = 3)
  )
```
![image](https://github.com/IndrajeetPatil/ggstatsplot/assets/54612866/2b5ba7df-8907-468c-99ea-21d12979daef)

I could not figure out how to remove the highlighted text

**Comment by IndrajeetPatil** [comment]
You can use `ggplot.component` argument to remove the secondary Y-axis label:

``` r
library(ggstatsplot)

gapminder::gapminder %>%
  dplyr::filter(year %in% c(1967, 1987, 2007), continent != "Oceania") %>%
  grouped_ggbetweenstats(
    x = continent,
    y = lifeExp,
    grouping.var = year,
    ggplot.component = list(
      ggplot2::scale_y_continuous(sec.axis = ggplot2::dup_axis(name = NULL))
    )
  )
```

![](https://i.imgur.com/Zc6egqX.png)

<sup>Created on 2023-07-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by yuliaUU** [comment]
But I don't have secondary  axis

**Comment by IndrajeetPatil** [comment]
The highlighted text you have shown your issue is a label for the secondary axis. ggbetweenstats adds one by default and shows the details of pairwise comparison test, if relevant.

**Comment by yuliaUU** [comment]
Thank you! Works !

**Comment by nbstutzman** [comment]
Renaming the secondary Y-axis label as null removes the label but adds ticks for the secondary axis. This can be seen in the example solution above. What's the way to remove the label without adding duplicate axis ticks?
