### ISSUE TITLE
ggcoefstats: standardised coefficients

### ISSUE THREAD

**Issue by MyosotisMatt** [IndrajeetPatil/ggstatsplot#873]
I would like to plot the standardized coefficients for my linear model. 
In the material online (https://indrajeetpatil.github.io/ggstatsplot/articles/web_only/ggcoefstats.html) the following call produces the correct graph with standardized regression coefficient Beta.
`ggcoefstats(mod1)`
This is equivalent to what sJplots does here

```r
library(sjPlot)

mod <- lm(formula = mpg ~ cyl * am, data = mtcars)

sjPlot::plot_model(mod, type="std")
```

However, in the `ggcoefstats` reference page (https://indrajeetpatil.github.io/ggstatsplot/reference/ggcoefstats.html) the same call just shows the non-standardised estimates.

```r
mod <- lm(formula = mpg ~ cyl * am, data = mtcars)

ggcoefstats(mod)
```

I can't find a way to fix this trivial problem.
I am using `ggstatsplot`  0.11.1

**Comment by IndrajeetPatil** [comment]
You can use the `...` argument to pass additional arguments to `parameters::model_parameters()`, which does allow a way to standardize coefficients:

``` r
library(ggstatsplot)

mod <- lm(formula = mpg ~ cyl * am, data = mtcars)

ggcoefstats(mod, standardize = "refit")
```

![](https://i.imgur.com/xwQc2Nj.png)

<sup>Created on 2023-07-30 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

For all available options, see:

https://easystats.github.io/parameters/reference/model_parameters.html#standardization-of-model-coefficients
