### ISSUE TITLE
ggbetweenstats: Welch's ANOVA producing NAs

### ISSUE THREAD

**Issue by M-Colley** [IndrajeetPatil/ggstatsplot#880]
Hey there, I am doing a between-subjects analysis with 6 groups. Therefore, either the one-way ANOVA or the kruskal-wallis test should be used. 

However, ggbetweenstats tries to (and thus, fails) report the welch test:

![image](https://github.com/IndrajeetPatil/ggstatsplot/assets/39366189/900c2095-30a1-4f1d-9836-5ab25be2a8f4)

I am happy to send you the data privately for any inspection. Is there anything I might be forgetting?

The code only is 

```
ggbetweenstats(data = df_for_analysis, x = group_id, y = "trust", ylab = "Trust", xlabels = xlabels)
```

**Comment by IndrajeetPatil** [comment]
It's correct. What's being reported are results from Welch's ANOVA:

![image](https://github.com/IndrajeetPatil/ggstatsplot/assets/11330453/f4486d0d-1b43-4105-8500-68368360615b)


For more, see the details section here:

https://indrajeetpatil.github.io/ggstatsplot/reference/ggbetweenstats.html

**Comment by M-Colley** [comment]
Thanks! I then believe the error is due to for GroupE that all values are the same. Do you, by any chance, know what I can/should do in this case?

Kind regards

**Comment by IndrajeetPatil** [comment]
I am not sure what you mean by error here. Do you mean the fact that the values are all NA?

If yes, then I would require to see the data that is producing these results. You can send it to me in an email.

**Comment by IndrajeetPatil** [comment]
The problem is that there is no variation in trust scores for GroupE and so Welch's ANOVA fails.

``` r
df <- structure(
  list(
    group = structure(
      c(
        6L, 6L, 6L, 6L, 6L, 6L, 6L,
        6L, 6L, 6L, 6L, 6L, 6L, 6L, 6L, 6L, 6L, 6L, 4L, 3L, 5L, 2L, 3L,
        2L, 3L, 3L, 4L, 3L, 4L, 5L, 3L, 1L, 2L, 1L, 5L, 1L, 4L, 2L, 3L,
        1L, 4L, 5L, 3L, 3L, 4L, 3L, 3L, 2L, 2L, 2L, 1L, 1L, 5L, 1L, 4L,
        4L, 2L, 1L, 1L, 2L, 2L, 1L, 4L, 2L, 4L, 2L, 2L, 3L, 4L, 5L, 2L,
        2L, 1L, 5L, 5L, 1L, 3L, 4L, 3L, 3L, 5L, 4L, 5L, 1L, 4L, 1L, 4L,
        4L, 1L, 3L, 2L, 4L, 5L, 5L, 4L, 4L, 4L, 2L, 1L, 5L, 1L, 3L, 5L,
        2L, 4L, 1L, 3L
      ),
      levels = c(
        "GroupA", "GroupB", "GroupC", "GroupD",
        "GroupE", "GroupF"
      ),
      class = "factor"
    ),
    t = c(
      5, 4, 4, 4, 5,
      3.5, 3, 4, 3, 4, 5, 4.5, 4.5, 3.5, 4.5, 5, 4, 4, 2, 5, 5, 1.5,
      4.5, 4, 4, 3, 5, 5, 2, 5, 5, 4, 4, 4, 5, 5, 2, 5, 4, 4, 4, 5,
      5, 2.5, 4.5, 2, 2, 5, 5, 4, 2, 3, 5, 5, 5, 5, 5, 2.5, 4.5, 4,
      3, 4, 3, 5, 4, 4, 5, 4, 2.5, 5, 5, 4, 5, 5, 5, 5, 5, 2, 1, 2.5,
      5, 2.5, 5, 5, 4, 5, 3, 4, 5, 3, 3, 4.5, 5, 5, 2, 5, 3.5, 5, 5,
      5, 3, 4, 5, 4, 5, 4, 2
    )
  ),
  row.names = c(NA, -107L),
  class = c("tbl_df", "tbl", "data.frame")
)

oneway.test(t ~ group, data = df)
#> 
#>  One-way analysis of means (not assuming equal variances)
#> 
#> data:  t and group
#> F = NaN, num df = 5, denom df = NaN, p-value = NA
```

<sup>Created on 2023-09-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

So you can instead run Fischer's ANOVA by assuming equal variance:

```r
library(ggstatsplot)
ggbetweenstats(df, group, t, var.equal = TRUE)
```

![](https://i.imgur.com/cafbEiu.png)

<sup>Created on 2023-09-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by M-Colley** [comment]
Thank you very very much!!!
