### ISSUE TITLE
package ‘ggstatsplot’ is not available (for R version 3.6.3)

### ISSUE THREAD

**Issue by Jozef259** [IndrajeetPatil/ggstatsplot#890]
I wanted to install, but the version isnt available.

**Comment by IndrajeetPatil** [comment]
Hi,

Unfortunately, `{ggstatsplot}` now requires minimum R 4.1 because some of its dependencies require this version. You will either need to upgrade to R 4.1, or go through CRAN archive for ggstatsplot and choose a version that doesn't require R 4.1.
