### ISSUE TITLE
p-value arrow-heads not being displayed in graph

### ISSUE THREAD

**Issue by deepika090** [IndrajeetPatil/ggstatsplot#893]
![image](https://github.com/IndrajeetPatil/ggstatsplot/assets/75111435/527bbdf5-0341-4ed8-998f-429c53ca8dbc)
 Hi,

the p value between groups not appearing in graph, though the the p value is significant..

**Comment by IndrajeetPatil** [comment]
I don't know what you mean by "not appearing in graph".

If you are referring to pairwise comparisons, they are relevant only when there are more than two groups.
