### ISSUE TITLE
Outlier values included within min-max range of boxplot

### ISSUE THREAD

**Issue by IndrajeetPatil** [IndrajeetPatil/ggstatsplot#895]
Reported by Li, Bowen at Purdue

**Comment by IndrajeetPatil** [comment]
Minimal reprex:

The boxplot bug appears strangely only when the violin plot width is set to `0`.

``` r
library(ggplot2)

df <- dplyr::filter(mpg, class %in% c("compact", "midsize"))

ggplot(df, aes(class, hwy)) +
  geom_boxplot(outlier.colour = "red")
```

![](https://i.imgur.com/OpmfGpn.png)

``` r

suppressPackageStartupMessages(library(ggstatsplot))

ggbetweenstats(df, class, hwy, results.subtitle = FALSE)
```

![](https://i.imgur.com/shertIP.png)

``` r

ggbetweenstats(df, class, hwy, results.subtitle = FALSE, violin.args = list(width = 0))
```

![](https://i.imgur.com/H1A3wyc.png)

<sup>Created on 2023-12-10 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by IndrajeetPatil** [comment]
Actually, this has nothing to do with ggstatsplot. This is how ggplot2 itself behaves. I think this because violin plot increases the range of data by interpolating data until the outlier points, which makes the outlier points no longer outliers. 

``` r
library(ggplot2)

df <- dplyr::filter(mpg, class %in% c("compact", "midsize"))

p <- ggplot(df, aes(class, hwy)) + geom_violin() + geom_boxplot() 

p
```

![](https://i.imgur.com/Zw74x3u.png)

``` r

p + geom_violin(width = 0)
```

![](https://i.imgur.com/9BdnNJi.png)

<sup>Created on 2023-12-10 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by IndrajeetPatil** [comment]
The correct way to remove violin plot is not only to set `width` to `0` but also to set `linewidth` to `0`.

``` r
library(ggplot2)

df <- dplyr::filter(mpg, class %in% c("compact", "midsize"))

p1 <- ggplot(df, aes(class, hwy)) + geom_violin() + geom_boxplot() 

p1
```

![](https://i.imgur.com/CRYkGmN.png)

``` r

p2 <- ggplot(df, aes(class, hwy)) + geom_violin(width = 0, linewidth = 0) + geom_boxplot() 

p2
```

![](https://i.imgur.com/Q55OHHh.png)

<sup>Created on 2023-12-10 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by AntoineSoetewey** [comment]
Thank you!
