### ISSUE TITLE
Significance is indicated by “*”  instead of a specific value

### ISSUE THREAD

**Issue by ShuangyuLiu0727** [IndrajeetPatil/ggstatsplot#899]
Instead of using the specific value of p-value in the final plot, I would like to identify it with a * sign, such as * for p<0.05; ** for p<0.01; *** for p<0.001. I used some code to change this identification, but it failed. I think it might be because this R package is updated?
If you have any good idea or suggestion? Thank you.

**Comment by IndrajeetPatil** [comment]
Yes, _ggstatsplot_ no longer show asterisks to denote significance and only shows _p_-values because such conventions differ across disciplines. And, in any case, the actual _p_-values are more important rather than their degree of significance.
