### ISSUE TITLE
Simpler statistical results

### ISSUE THREAD

**Issue by qianghuazhou** [IndrajeetPatil/ggstatsplot#901]
Can you provide an option to give simpler statistical results on the plots? When I chose results.subtitle = FALSE, the statistics were all gone. Thanks.

**Comment by IndrajeetPatil** [comment]
Can you expound on what you mean by "simpler statistical results"? What details would you expect in such an output?

**Comment by IndrajeetPatil** [comment]
Closing this in favour of #669 and #720. I think this is the same issue as these existing issues.
