### ISSUE TITLE
Invalid class "ddenseModelMatrix" object

### ISSUE THREAD

**Issue by xarrama** [IndrajeetPatil/ggstatsplot#908]
When I run ggstatsplot::ggbetweenstats, I get this error, but plots are created anyway.

Error in validObject(.Object) : 
  invalid class "ddenseModelMatrix" object: superclass "xMatrix" not defined in the environment of the object's class

ggstatsplot v0.12.1
R version 4.3.2
Windows 10 x64 build 22631

Thank you!

**Comment by IndrajeetPatil** [comment]
This is not related to _ggstatsplot_, but an update to _Matrix_:

https://stackoverflow.com/questions/77530214/error-dsparsemodelmatrix-object-superclass-xmatrix-not-defined/77530730#77530730

Just run the following, refresh R session, and then try again:

```r
install.packages("MatrixModels", type = "source")
```
