### ISSUE TITLE
Error in `filter()`: ! In argument: `!is.na(x)`. Caused by error:

### ISSUE THREAD

**Issue by tjhwangxiong** [IndrajeetPatil/ggstatsplot#909]
I have a data.frame, and I hope to use lapply using ggscatterstats, therefore I constructed a function as following:
```r
plot_sc=function(x){ggstatsplot::ggscatterstats(
  data = dat, 
  x = x,
  y = "Riskscore",
  type = "np",
  k = 2L,
  title = '',
  messages = FALSE,
  marginal.type = "density")
}
```
Here is my dat
![image](https://github.com/IndrajeetPatil/ggstatsplot/assets/94770704/b1a156e3-c5c5-4373-b673-ac3ee5cd606b)

> colnames(dat)
 [1] "Elephantin_1835"  "Sorafenib_1085"   "Entinostat_1593"  "Vorinostat_1012" 
 [5] "Oxaliplatin_1806" "Acetalax_1804"    "Trametinib_1372"  "Dasatinib_1079"  
 [9] "Sapitinib_1549"   "SCH772984_1564"   "Riskscore"  

When I run

```r
splots=lapply(colnames(dat)[1:10],plot_sc)
```
![image](https://github.com/IndrajeetPatil/ggstatsplot/assets/94770704/a74179a4-f1e1-43db-90af-3a450b255539)

**Comment by IndrajeetPatil** [comment]
You just need to unquote the variable: 

```r
plot_sc = function(x) { ggstatsplot::ggscatterstats(
  data = dat, 
  x = !!x,
  y = "Riskscore",
  type = "np",
  k = 2L,
  title = '',
  messages = FALSE,
  marginal.type = "density")
}
```

Here is minimal reprex:

``` r
library(rlang)
plot_sc = function(x) ggstatsplot::ggscatterstats(mtcars, !!x, "mpg")
splots = lapply(colnames(mtcars)[2:3], plot_sc)
```

<sup>Created on 2024-03-03 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
