### ISSUE TITLE
Second Confidence Interval Always 1.00 For K-W?

### ISSUE THREAD

**Issue by ludist** [IndrajeetPatil/ggstatsplot#919]
Hello-- thank you so much for an excellent package, Dr. Patil. I've been using it extensively for my dissertation and I really appreciate the time and effort you put into it. Since I've been using it a lot, I noticed a few things that seem to be wrong to me but admittedly neither stats nor scripting are my strong suits so please forgive me if any of this feedback is misguided.

Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

The high bound CI(95%) for Kruskal-Wallis (I assume for epsilon squared) is always 1.00. This seems exceedingly unlikely since the lower bound for epsilon squared in my data goes from something like .000001 to .7 and the high bound is 1.00 in both (and for all intervening points).  I am using the same dataset for all of the graphs I'm producing so perhaps there's an issue with the data I'm not aware of causing the problem. However, the same issue pops up in the iris_long standard dataset.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

Brief description of the problem
Upper bound of CI with K-W test is always 1.00.

```r
library(ggstatsplot)
#> You can cite this package as:
#>      Patil, I. (2021). Visualizations with statistical details: The 'ggstatsplot' approach.
#>      Journal of Open Source Software, 6(61), 3167, doi:10.21105/joss.03167
ggbetweenstats(
  iris_long,
  Species,
  value
)
#> Warning in min(x): no non-missing arguments to min; returning Inf
#> Warning in max(x): no non-missing arguments to max; returning -Inf
```

![](https://i.imgur.com/zKQRFrw.png)

<sup>Created on 2024-03-20 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
```

**Comment by ludist** [comment]
Looking at the closed issues, I see you very recently addressed this at #906 [here](https://github.com/IndrajeetPatil/ggstatsplot/issues/906) for a slightly different issue and I notice there's been a very recent commit. I'll update my package installation and investigate.

**Comment by ludist** [comment]
Wow, I don't know what changed in the last 72 hours or so but updating statsExpression sent me into an hour and a half dependency hell where I had to manually install a gfortran compiler and 3 other packages on macOS x64 before I could get it working again. If anyone reading this has the same problem, just save yourself the hassle and google the package names and "macOS binaries" to get to the r-project page and then install the .tgz manually.

Anyway, I tried running the code again, along with several attempts at parameter calls based on my review of the commits, and I still get 1.00 for the second CI. If it's fixed and requires a parameter call, could you expand on the documentation a bit? Thanks again!

**Comment by IndrajeetPatil** [comment]
Yes, this upper bound for the effect size for KW (rank epsilon squared) is `1.0`.

For more, see: https://easystats.github.io/effectsize/reference/rank_epsilon_squared.html

<img width="1257" alt="Screenshot 2024-03-21 at 18 57 44" src="https://github.com/IndrajeetPatil/ggstatsplot/assets/11330453/d461a3a9-08ce-4bb9-bc0b-c71748a85e95">

**Comment by ludist** [comment]
Thank you!

**Comment by IndrajeetPatil** [comment]
The underlying functions used to run inferential statistics and effect size estimation are catalogued here, and more details can be found in linked pages:

https://indrajeetpatil.github.io/ggstatsplot/reference/ggbetweenstats.html#one-way-anova
