### ISSUE TITLE
ggbetweenstats  Hedge's g change it to Cohen's d

### ISSUE THREAD

**Issue by hasibagen** [IndrajeetPatil/ggstatsplot#922]
**Describe the solution you'd like**
This is my current code
ggbetweenstats(
     data = data_9,
     x = group,
     y = mean,
     type = "parametric",
     var.equal = TRUE,
     p.adjust.method = "bonferroni",
     ggtheme = theme_classic(),
) +
     scale_color_lancet() +
     scale_fill_lancet()
The upper left corner of the image shows Hedge's g. Is there a way to change it to Cohen's d?
I have been looking at the api and github issues for a long time, but I have not found a solution. I would like to ask if anyone has a solution?
https://indrajeetpatil.github.io/ggstatsplot/reference/ggbetweenstats.html

**How could we do it?**
Could you please tell me how to change the Hedge's g shown in the picture to Cohen's d?

**Comment by IndrajeetPatil** [comment]
``` r
library(ggstatsplot)

ggbetweenstats(mtcars, am, wt,  effsize.type = "d")
```

![](https://i.imgur.com/fV6LnXK.png)

<sup>Created on 2024-03-27 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
