### ISSUE TITLE
Highlight some points in violin plots

### ISSUE THREAD

**Issue by 2WG73** [IndrajeetPatil/ggstatsplot#929]
**Describe the solution you'd like**

Instead of displaying all points, I would be happy to define some points (say a vector), which could be then highlighted on the violin plot.

**How could we do it?**

Implementing an extra argument in the function

**Comment by IndrajeetPatil** [comment]
No plans to support such functionality in ggstatsplot. 

You should build a custom plot (maybe using [gghighlight](https://cran.r-project.org/web/packages/gghighlight/vignettes/gghighlight.html)) and then use [statsExpressions](https://indrajeetpatil.github.io/statsExpressions/) to include statistical analysis in the plot.
