### ISSUE TITLE
Question: are numerical results available in the plot object?

### ISSUE THREAD

**Issue by olearydj** [IndrajeetPatil/ggstatsplot#936]
I would like to be able to access the results that are normally presented in the subtitle, but use the subtitle for a more descriptive interpretation of the chart. When setting `results.subtitle = FALSE` to suppress that display, `extract_subtitle` returns NULL.

Here's an example of the information I'm looking for:
```r
list(chi["Kruskal-Wallis"]^2 * "(" * 3 * ")" == "26.8", italic(p) ==
    "6.4e-06", widehat(epsilon)["ordinal"]^2 == "0.5", CI["95%"] ~
    "[" * "0.4", "1.0" * "]", italic("n")["obs"] == "54")
```

I've dug through the plot object but couldn't find these components anywhere in the structure. Admittedly, it is almost as dense as I am, so it could have been overlooked!

Could you point me in the right direction so I can use the results as part of in-line R expressions for my Quarto reports?

Many thanks for this great and powerful package!

**Comment by IndrajeetPatil** [comment]
I think you are looking for `extract_stats()` function, which would return results in data frames:

https://indrajeetpatil.github.io/ggstatsplot/reference/extract_stats.html

**Comment by olearydj** [comment]
oh geeze... yeah, thank you!

**Comment by olearydj** [comment]
wait, I'm sorry - I was sure I tried that. when `results.subtitle` is set to false, the $subtitle_data section is not included in `extract_stats` results:

here with `results.subtitle = TRUE`:

```r
> ggstatsplot::extract_stats(h1b_plot)
$subtitle_data
# A tibble: 1 × 15
  parameter1 parameter2 statistic df.error   p.value method                       effectsize     
  <chr>      <chr>          <dbl>    <int>     <dbl> <chr>                        <chr>          
1 avg_uce    treatment       25.5        3 0.0000122 Kruskal-Wallis rank sum test Epsilon2 (rank)
  estimate conf.level conf.low conf.high conf.method          conf.iterations n.obs expression
     <dbl>      <dbl>    <dbl>     <dbl> <chr>                          <int> <int> <list>    
1    0.481       0.95    0.339         1 percentile bootstrap             100    54 <language>

$caption_data
...
```

but when set to `TRUE`:
```r
> h1b_res
$subtitle_data
NULL

$caption_data
...
```

It would be nice if this is present and extractable regardless of the display setting.

**Comment by IndrajeetPatil** [comment]
That's not possible. If you turn off running statistical tests in the visualization, it would be inefficient to still run them.

In this case, you can use _statsExpressions_, which is the stats backend of _ggstatsplot_: https://indrajeetpatil.github.io/statsExpressions/

**Comment by olearydj** [comment]
You are still running the pairwise analysis and it seems that display of results should be decoupled from calculating them. Anyway, thanks for considering my request, and being so responsive here. Your package is outstanding and will have a well-earned citation in my work(s).

**Comment by IndrajeetPatil** [comment]
> You are still running the pairwise analysis

- if `result.subtitle` is `FALSE`, global hypothesis testing and effect size estimation is turned off
- if `pairwise.comparisons` is `FALSE`, pairwise comparisons are turned off

Admittedly, the first should have the second effect, but, in the past, users have asked to support display the latter even if they didn't want to show the former in the plot. This is why their behaviours are independently controlled.
