### ISSUE TITLE
ggscatterstats - requires 'scales_add_defaults()' function that is missing?

### ISSUE THREAD

**Issue by jillymackay** [IndrajeetPatil/ggstatsplot#939]
Hey Indrajeet,

I love this package. I was prepping a learning resource for some students and noticed that `ggscatterstats` is giving me an error:

Error:
! Problem while computing aesthetics.
ℹ Error occurred in the 3rd layer.
Caused by error in `scales_add_defaults()`:
! could not find function "scales_add_defaults"
Run `rlang::last_trace()` to see where the error occurred.

```r
iris |> 
ggscatterstats(x = Petal.Width, y = Sepal.Width)

```

I get this even when `tidyverse` and `easystats` are loaded, so I'm not sure where `scales_add_defaults()` is supposed to be loading from (and google is not being helpful) 

Backtrace:
     ▆
  1. ├─base (local) `<fn>`(x)
  2. ├─ggplot2:::print.ggplot(x)
  3. │ ├─ggplot2::ggplot_build(x)
  4. │ └─ggplot2:::ggplot_build.ggplot(x)
  5. │   └─ggplot2:::by_layer(...)
  6. │     ├─rlang::try_fetch(...)
  7. │     │ ├─base::tryCatch(...)
  8. │     │ │ └─base (local) tryCatchList(expr, classes, parentenv, handlers)
  9. │     │ │   └─base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
 10. │     │ │     └─base (local) doTryCatch(return(expr), name, parentenv, handler)
 11. │     │ └─base::withCallingHandlers(...)
 12. │     └─ggplot2 (local) f(l = layers[[i]], d = data[[i]])
 13. │       └─l$compute_aesthetics(d, plot)
 14. │         └─ggplot2 (local) compute_aesthetics(..., self = self)
 15. └─base::.handleSimpleError(...)
 16.   └─rlang (local) h(simpleError(msg, call))
 17.     └─handlers[[1L]](cnd)
 18.       └─cli::cli_abort(...)
 19.         └─rlang::abort(...)

**Comment by IndrajeetPatil** [comment]
This is the same issue as https://github.com/jtlandis/ggside/issues/56

You just need to update ggside and ggstatsplot to their latest CRAN versions.

**Comment by jillymackay** [comment]
Fab! thanks!
