### ISSUE TITLE
adding missing tests

### ISSUE THREAD

**Issue by IndrajeetPatil** [IndrajeetPatil/ggstatsplot#94]
Some of the following functions were discovered to have bugs and this escaped before because there were no tests for them-

- **context("subtitle_ggscatterstats")**

- [x] Pearson's _r_ 
- [x] percentage bend correlations
- [x] bayes factor

- **context("subtitle_t_onesample")**

- [x] Wilcox test
- [x] robust location measure test

- **context("subtitle_mann_nonparametric")**

- [x] within-subjects design

- **context("effctsize_ci")**
(new functions introduced in `0.0.7`)
- [x] yuend_ci
- [x] kw_eta_h_ci

- **context("pairwise comparisons")**
- [x] tests for `pairwise_p()` function

**Comment by ibecav** [comment]
Yes I should be able to look at these late this week or early next

**Comment by ibecav** [comment]
Looks like there are only two left?

**Comment by IndrajeetPatil** [comment]
Yes, those are the only two left now.

**Comment by IndrajeetPatil** [comment]
For all the tests we currently have for testing effect size confidence interval helper functions, do you mind also adding checks for different types of confidence interval types? 

The [code coverage](https://codecov.io/gh/IndrajeetPatil/ggstatsplot/src/master/R/helpers_effsize_ci.R) for these functions is still not 100% because for most of the functions, we are just checking `conf.type = "norm"` but there are also other available options that need to be checked (e.g., `"bca"`, `"basic"`, etc.).

I am almost done with having about 100% coverage for the rest of the `.R` files.

**Comment by ibecav** [comment]
I'll take a look but in many cases they fail simply because of the data not because the code is bad

**Comment by IndrajeetPatil** [comment]
The tests are not failing, but rather there are no tests at all to check if different entries to argument `conf.type` in these functions are working.

**Comment by ibecav** [comment]
> ggstatsplot:::kw_eta_h_ci(
+     data = movies_long,
+     genre,
+     budget,
+     nboot = 50,
+     conf.level = 0.999, conf.type = "bca"
+ )
Error in bca.ci(boot.out, conf, index[1L], L = L, t = t.o, t0 = t0.o,  : 
  estimated adjustment 'a' is NA
In addition: There were 50 or more warnings (use warnings() to see the first 50)

**Comment by IndrajeetPatil** [comment]
Hmm, I'll look into this. Closing this issue since all tests necessary for the next release are already in place.
