### ISSUE TITLE
The marginal.type parameter does not seem to work

### ISSUE THREAD

**Issue by ibzhuai** [IndrajeetPatil/ggstatsplot#945]
Hello, 
Correlation analysis the marginal.type parameter in the ggscatterstats function does not seem to work

Many thanks for this great and powerful package!

Here's my code---------------------------------------

ggscatterstats(
  data =CC,
  x = GZMA,
  y = CXCR6,
  #conf.level = 0.99,
  type = "spearman",
  centrality.para = "mean",  
  xlab = "A Expression",
  ylab = "B",
  title = "A and B correlation in XX",
  #caption = expression(paste(italic("Note"), ": XXXX")),  # caption text for the plot
  point.args = list(size = 2.7, alpha = 0.4, stroke = 1),
  smooth.line.args = list(linewidth = 1.5, color = "#E31A1C", method = "lm", formula = y ~x),
  marginal = T,
  xsidehistogram.args = list(fill = "#1F78B4", color = "#A6CEE3", na.rm = TRUE),
  ysidehistogram.args = list(fill = "#00a087", color = "#82C3A5", na.rm = TRUE),  #"#847bb5","#49b07b",
  marginal.type = "densigram", #histogram, density, boxplot, violin, densigram
  ggtheme = theme_minimal(base_size = 10, base_family = "ArialMT"))

![image](https://github.com/IndrajeetPatil/ggstatsplot/assets/126430275/97d96b73-faa9-4763-82c6-982b9f893d32)

**Comment by IndrajeetPatil** [comment]
Yes, this hasn't possible since `0.9.0` release:

https://indrajeetpatil.github.io/ggstatsplot/news/index.html#ggstatsplot-090

<img width="817" alt="Screenshot 2024-06-23 at 22 02 10" src="https://github.com/IndrajeetPatil/ggstatsplot/assets/11330453/3c3b817f-c48a-4a3e-8fdd-493631d79a2f">
