### ISSUE TITLE
writing unit tests for bootstrapped effect sizes

### ISSUE THREAD

**Issue by IndrajeetPatil** [IndrajeetPatil/ggstatsplot#95]
Somehow even after setting the seed to the same value, the subtitle prepared by the bare function and the one computed in the function environment consistently differ slightly. This is because the confidence intervals for effect size are not identical. 

How do you write tests for such cases? 
Want to make sure here that the entire call is identical in the helper subtitle function and its instantiation in the plotting function.

``` r

# plot
set.seed(123)
p <- ggstatsplot::ggbetweenstats(
  data = mtcars,
  x = cyl,
  y = wt,
  nboot = 50,
  var.equal = TRUE,
  messages = FALSE,
  k = 3
)


# subtitle
set.seed(123)
p_subtitle <- ggstatsplot::subtitle_anova_parametric(
  data = mtcars,
  x = cyl,
  y = wt,
  nboot = 50,
  var.equal = TRUE,
  messages = FALSE,
  k = 3
)

# checking if these two are equal
p$labels$subtitle
#> paste(italic("F"), "(", 2, ",", "29", ") = ", "22.911", ", ", 
#>     italic("p"), " = ", "< 0.001", ", ", omega["p"]^2, " = ", 
#>     "0.578", ", CI"["95%"], " [", "0.432", ", ", "0.774", "]", 
#>     ", ", italic("n"), " = ", 32L)

p_subtitle
#> paste(italic("F"), "(", 2, ",", "29", ") = ", "22.911", ", ", 
#>     italic("p"), " = ", "< 0.001", ", ", omega["p"]^2, " = ", 
#>     "0.578", ", CI"["95%"], " [", "0.431", ", ", "0.770", "]", 
#>     ", ", italic("n"), " = ", 32L)
```

<sup>Created on 2018-11-29 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by IndrajeetPatil** [comment]
@ibecav Any ideas?

**Comment by IndrajeetPatil** [comment]
My question was more about how to run the test I want to run.

As for the results not making sense, I don't see anything wrong with the results-

- You get the same output from **`JASP` for `anova` with the same model**:

![image](https://user-images.githubusercontent.com/11330453/49254263-6bbb4080-f3ee-11e8-9086-e227c07b4ce3.png)

- Also from **`jamvoi` for `anova` with the same model**:

![image](https://user-images.githubusercontent.com/11330453/49254585-2f3c1480-f3ef-11e8-8ffd-2587a538a4c5.png)

The results being displayed in both these softwares (`JASP`, `jamovi`) and `ggstatsplot` are based on `oneway.test`, not `aov`-
``` r
stats::oneway.test(data = mtcars, formula = wt ~ cyl, var.equal = TRUE)
#> 
#>  One-way analysis of means
#> 
#> data:  wt and cyl
#> F = 22.911, num df = 2, denom df = 29, p-value = 1.075e-06

stats::oneway.test(data = mtcars, formula = wt ~ cyl, var.equal = FALSE)
#> 
#>  One-way analysis of means (not assuming equal variances)
#> 
#> data:  wt and cyl
#> F = 20.249, num df = 2.000, denom df = 18.974, p-value = 1.963e-05
```
For example, `ggstatsplot` results will be similar to these results-
``` r
ggstatsplot::ggbetweenstats(mtcars, cyl, wt, var.equal = TRUE, messages = FALSE)
```

![](https://i.imgur.com/g5moQ8c.png)

``` r
ggstatsplot::ggbetweenstats(mtcars, cyl, wt, var.equal = FALSE, messages = FALSE)
```

![](https://i.imgur.com/HBEkMMz.png)

**Comment by IndrajeetPatil** [comment]
Anyway, I solved this by writing tests with `k = 2`. That should suffice for now.

**Comment by ibecav** [comment]
Right sorry busy week at work this week.  More time next week.
