### ISSUE TITLE
ggcoefstats()  Warning messages: 1: Argument `effectsize_type` is deprecated. Use `es_type` instead

### ISSUE THREAD

**Issue by Rosie23** [IndrajeetPatil/ggstatsplot#950]
ggcoefstats() gives the  warning "Argument `effectsize_type` is deprecated. Use `es_type` instead" when run.

`library(ggstatsplot)`
 `library(ggplot2)`
 `mod_aov <- stats::aov(formula = rating ~ mpaa * genre, data = movies_long)`
` ggcoefstats(x = mod_aov)`

Warning messages:
1: Argument `effectsize_type` is deprecated. Use `es_type` instead. 
2: Argument `effectsize_type` is deprecated. Use `es_type` instead.

**Comment by IndrajeetPatil** [comment]
You just need to update to use latest `{ggstatsplot}` (0.12.4), which fixes this warning:

https://cran.r-project.org/web/packages/ggstatsplot/index.html
