### ISSUE TITLE
asterisks instead of p-values

### ISSUE THREAD

**Issue by marta179** [IndrajeetPatil/ggstatsplot#961]
First of all, thank you for developing ggststsplot :)
I've read that from the 0.1.1 version "pairwise.annotation now defaults to "p.value" rather than "asterisk" [...] because the asterisk conventions are not consistent across various scientific disciplines."

And I would love to have the option to replace the actual p-value with the asterisks: :" for p<0.05, "" for p < 0.01 and "" for p < 0.001.  Can you please inform us how we can go back to these settings?

**Comment by IndrajeetPatil** [comment]
I removed that feature for reasons mentioned here: https://github.com/IndrajeetPatil/ggstatsplot/issues/899

If you still wish to achieve it, see:

https://indrajeetpatil.github.io/ggstatsplot/articles/web_only/faq.html#how-can-i-change-annotation-in-pairwise-comparisons

**Comment by marta179** [comment]
Thank you for your reply:) 
Does the solution suggest that the solution also works for showing horizontal lines for statistically significant relations only?
I don't want to see ns lines on the plot.
