### ISSUE TITLE
gghistostats() function

### ISSUE THREAD

**Issue by ebertbrea** [IndrajeetPatil/ggstatsplot#965]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

Brief description of the problem

Why do I unable now include normal curve in a ggstatsplot histogram when use ggstatsplot version 0.12.4?

Thanks in advance.

```r
# insert reprex here
if(!require(ggstatsplot)){install.packages("ggstatsplot");library(ggstatsplot)}

set.seed(123)

gghistostats(
  data       = ggplot2::msleep,
  x          = awake,
  title      = "Amount of time spent awake",
  test.value = 12,
  binwidth   = 1,
  normal.curve  = TRUE,
  normal.curve.args = list(color = "red", size = 1)
)
```

**Comment by IndrajeetPatil** [comment]
<img width="822" alt="Screenshot 2024-10-14 at 00 17 05" src="https://github.com/user-attachments/assets/461ff50d-b5c0-4ee0-a8e4-f2fcaf98a26e">
