### ISSUE TITLE
goals for `0.0.8` release

### ISSUE THREAD

**Issue by IndrajeetPatil** [IndrajeetPatil/ggstatsplot#99]
Planned date: early Feb 2019

(Goal for release date: last week of December)

To do:

- [x] Massively refactor subtitle maker functions to avoid repetition of code across functions
- [ ] Go full `rlang` rather than using short-cuts
- [x] Since https://github.com/IndrajeetPatil/ggstatsplot/issues/38 was solved, `ggscatterstats` arguments `label.var` and `label.expression` work only with characters but not bare expressions. This is incosistent with the API principles for the rest of the functions in the package. See if there is a way to implement this.
- [x] Refactor `grouped_` variants of functions to remove the ugly `purrr` hack they currently implement
- [ ] Refactor code to remove `stats::na.omit()`. Take a more fine-grained approach to remove `NA`s only from columns of interest.
- [ ] Showing both 50% and 95% CIs for `ggcoefstats` (like in Bayesian inference plots: e.g., https://twitter.com/tjmahr/status/1048226472710873089)
- [ ] Check font size for `theme_ggstatsplot` function; maybe give user arguments option to change all aspects of the theme?
- [ ] Clean up `.Rmd` file language using `gramr` package 
- [ ] When there are many levels in a factor, `ggpiestats` labels can overlap; give the option to have the labels to be either `"internal"` (current default) or `"external"` to the slices
- [ ] Add `group` option for `ggscatterstats` to support grouped marginals (https://github.com/daattali/ggExtra/blob/master/inst/vignette_files/ggExtra_files/figure-markdown_strict/ggmarginal-grouping-1.png)
- [x] Add `ggplot.function` argument to `grouped_` variants to make modifications with `ggplot2` functions to customize the plot 
- [ ] Make the package lighter; the number of dependencies is getting out of control

**Comment by IndrajeetPatil** [comment]
@ibecav You can raise the ideas you had for `0.0.8` release here and we can discuss them in this thread.

**Comment by IndrajeetPatil** [comment]
1. Just commented on that PR.

2. Yeah, that shouldn't be happening. I will look into what's going on. 

3. Yeah, unfortunately, I've made peace with this issue. The problem is that the `ggrepel` labels need to be jittered in the same way as the underlying raw data points and I couldn't figure out a way to do that. So instead I am using **non-jittered data points**, which are flagged by `geom_boxplot()`. I'll be happy to accept a PR that circumvents this issue.

**Comment by ibecav** [comment]
#1.  I'm done with the PR.

#3 outlier labelling.  I think I may have done a poor job explaining my issue.  I'm content with the ggrepel labels I understand there is only so much you can do.  My concern is that every outlier is being plotted twice once by geom_point (this happens first) then again by geom_boxplot.  That means that there are extra points about.

I'm not toally sure but I think we can just use some of your existing condition code in front of the geom_point to set a filter to only plot points which are NOT outliers and then let boxplot handle plotting the ouliers.  Here';s a very simple reprex to show you.

``` r
library(ggstatsplot)
library(ggplot2)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
theme_set(theme_bw())
xxx <- movies_long %>% 
  group_by(mpaa) %>% 
  mutate(
    isanoutlier = ifelse(
      ggstatsplot:::check_outlier(rating,coef = 1.5),
      yes = TRUE, 
      no = FALSE)
    )
ggplot(data = xxx, aes(x=mpaa, y=rating, label = title)) + 
  geom_point(data = filter(xxx, !isanoutlier), aes(color=mpaa), position = position_jitterdodge( jitter.width = 1)) + 
  stat_boxplot(alpha=.2, outlier.color = "black", outlier.alpha = 1.0) + 
  ggrepel::geom_label_repel(data = filter(xxx, isanoutlier)) 
```

![](https://i.imgur.com/r0BtzKO.png)

<sup>Created on 2018-12-11 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Notice that outliers no longer have both a color point and a black point.

![screen shot 2018-12-11 at 12 22 47](https://user-images.githubusercontent.com/26557145/49818359-82438f00-fd40-11e8-8e41-de9119ddf218.png)

**Comment by ibecav** [comment]
Okay I think I have  a path to a proper PR sorted out for the outliers.  I made break it into two separate PRs just to keep things manageable.  More tomorrow.

**Comment by IndrajeetPatil** [comment]
@ibecav Since the upstream dependency has [broken](https://cran.r-project.org/web/checks/check_results_ggstatsplot.html) CRAN version of `ggstatsplot`, I will have to submit a newer version soon. I will be submitting it on the 5th of January. 

If you get a chance, can you take a look at refactoring the `purrr` [hack](https://github.com/IndrajeetPatil/ggstatsplot/blob/master/R/grouped_ggpiestats.R) in `grouped_ggpiestats`, similar to what you did for `grouped_ggscatterstats`?

**Comment by ibecav** [comment]
Okay likely be Monday

**Comment by ibecav** [comment]
Work complete.  Managed to not break any tests or change any doco.  PR with reprex in a minute

**Comment by IndrajeetPatil** [comment]
Awesome! Thanks, Chuck. Everything looked good and I've merged the PR.

**Comment by IndrajeetPatil** [comment]
@ibecav Do you think you will have time to refactor the `grouped_ggcorrmat` function? 
This is the only `grouped_` function remaining that still relies on the `purrr` hack. I can push back submission date to 8th if you think you will have time to do this before then.

**Comment by ibecav** [comment]
I'll take a look today.  First issue is that I have to visit the base command `ggcorrmat` because this doesn't work...

`# setting `output = "ci"` will return the confidence intervals for unique correlation pairs

ggstatsplot::ggcorrmat(
  data = ggplot2::msleep,
  cor.vars = "sleep_total:bodywt",
  p.adjust.method = "BH",
  output = "ci"
)`

**Comment by IndrajeetPatil** [comment]
Shouldn't that be `"sleep_total":"bodywt"`, and not `"sleep_total:bodywt"` as the former will basically mean that there is a **single variable** named "sleep_total:bodywt" in the dataframe?

At any rate, this function seems to work across a wide array of entry methods for this argument-
``` r
# works
ggstatsplot::ggcorrmat(
  data = ggplot2::msleep,
  cor.vars = "sleep_total":"bodywt",
  p.adjust.method = "BH",
  output = "ci"
)

#> Note: In the correlation matrix,
#> the upper triangle: p-values adjusted for multiple comparisons
#> the lower triangle: unadjusted p-values.
#> 
#> # A tibble: 15 x 7
#>    pair       r   lower   upper         p lower.adj upper.adj
#>    <chr>  <dbl>   <dbl>   <dbl>     <dbl>     <dbl>     <dbl>
#>  1 1      0.752  0.617   0.844  2.92e- 12   0.531     0.877  
#>  2 2     -0.474 -0.706  -0.150  6.17e-  3  -0.786     0.0302 
#>  3 3     -1.000 -1.000  -1.000  2.42e-226  -1.000    -1.000  
#>  4 4     -0.360 -0.569  -0.108  6.35e-  3  -0.653     0.0257 
#>  5 5     -0.312 -0.494  -0.103  4.09e-  3  -0.572     0.00539
#>  6 6     -0.338 -0.614   0.0120 5.84e-  2  -0.715     0.191  
#>  7 7     -0.752 -0.844  -0.617  2.91e- 12  -0.877    -0.531  
#>  8 8     -0.221 -0.476   0.0670 1.31e-  1  -0.580     0.209  
#>  9 9     -0.328 -0.535  -0.0826 9.95e-  3  -0.620     0.0452 
#> 10 10     0.474  0.150   0.706  6.17e-  3  -0.0302    0.786  
#> 11 11     0.852  0.709   0.927  2.42e-  9   0.603     0.950  
#> 12 12     0.418  0.0809  0.669  1.73e-  2  -0.0997    0.757  
#> 13 13     0.360  0.108   0.569  6.35e-  3  -0.0257    0.653  
#> 14 14     0.312  0.103   0.494  4.09e-  3  -0.00543   0.572  
#> 15 15     0.934  0.889   0.961  9.16e- 26   0.858     0.970

# works
ggstatsplot::ggcorrmat(
  data = ggplot2::msleep,
  cor.vars = c("sleep_total":"bodywt"),
  p.adjust.method = "BH",
  output = "ci"
)
#> Note: In the correlation matrix,
#> the upper triangle: p-values adjusted for multiple comparisons
#> the lower triangle: unadjusted p-values.
#> 
#> # A tibble: 15 x 7
#>    pair       r   lower   upper         p lower.adj upper.adj
#>    <chr>  <dbl>   <dbl>   <dbl>     <dbl>     <dbl>     <dbl>
#>  1 1      0.752  0.617   0.844  2.92e- 12   0.531     0.877  
#>  2 2     -0.474 -0.706  -0.150  6.17e-  3  -0.786     0.0302 
#>  3 3     -1.000 -1.000  -1.000  2.42e-226  -1.000    -1.000  
#>  4 4     -0.360 -0.569  -0.108  6.35e-  3  -0.653     0.0257 
#>  5 5     -0.312 -0.494  -0.103  4.09e-  3  -0.572     0.00539
#>  6 6     -0.338 -0.614   0.0120 5.84e-  2  -0.715     0.191  
#>  7 7     -0.752 -0.844  -0.617  2.91e- 12  -0.877    -0.531  
#>  8 8     -0.221 -0.476   0.0670 1.31e-  1  -0.580     0.209  
#>  9 9     -0.328 -0.535  -0.0826 9.95e-  3  -0.620     0.0452 
#> 10 10     0.474  0.150   0.706  6.17e-  3  -0.0302    0.786  
#> 11 11     0.852  0.709   0.927  2.42e-  9   0.603     0.950  
#> 12 12     0.418  0.0809  0.669  1.73e-  2  -0.0997    0.757  
#> 13 13     0.360  0.108   0.569  6.35e-  3  -0.0257    0.653  
#> 14 14     0.312  0.103   0.494  4.09e-  3  -0.00543   0.572  
#> 15 15     0.934  0.889   0.961  9.16e- 26   0.858     0.970

# works
ggstatsplot::ggcorrmat(
  data = ggplot2::msleep,
  cor.vars = sleep_total:bodywt,
  p.adjust.method = "BH",
  output = "ci"
)
#> Note: In the correlation matrix,
#> the upper triangle: p-values adjusted for multiple comparisons
#> the lower triangle: unadjusted p-values.
#> 
#> # A tibble: 15 x 7
#>    pair       r   lower   upper         p lower.adj upper.adj
#>    <chr>  <dbl>   <dbl>   <dbl>     <dbl>     <dbl>     <dbl>
#>  1 1      0.752  0.617   0.844  2.92e- 12   0.531     0.877  
#>  2 2     -0.474 -0.706  -0.150  6.17e-  3  -0.786     0.0302 
#>  3 3     -1.000 -1.000  -1.000  2.42e-226  -1.000    -1.000  
#>  4 4     -0.360 -0.569  -0.108  6.35e-  3  -0.653     0.0257 
#>  5 5     -0.312 -0.494  -0.103  4.09e-  3  -0.572     0.00539
#>  6 6     -0.338 -0.614   0.0120 5.84e-  2  -0.715     0.191  
#>  7 7     -0.752 -0.844  -0.617  2.91e- 12  -0.877    -0.531  
#>  8 8     -0.221 -0.476   0.0670 1.31e-  1  -0.580     0.209  
#>  9 9     -0.328 -0.535  -0.0826 9.95e-  3  -0.620     0.0452 
#> 10 10     0.474  0.150   0.706  6.17e-  3  -0.0302    0.786  
#> 11 11     0.852  0.709   0.927  2.42e-  9   0.603     0.950  
#> 12 12     0.418  0.0809  0.669  1.73e-  2  -0.0997    0.757  
#> 13 13     0.360  0.108   0.569  6.35e-  3  -0.0257    0.653  
#> 14 14     0.312  0.103   0.494  4.09e-  3  -0.00543   0.572  
#> 15 15     0.934  0.889   0.961  9.16e- 26   0.858     0.970

# works
ggstatsplot::ggcorrmat(
  data = ggplot2::msleep,
  cor.vars = c(sleep_total:bodywt),
  p.adjust.method = "BH",
  output = "ci"
)
#> Note: In the correlation matrix,
#> the upper triangle: p-values adjusted for multiple comparisons
#> the lower triangle: unadjusted p-values.
#> 
#> # A tibble: 15 x 7
#>    pair       r   lower   upper         p lower.adj upper.adj
#>    <chr>  <dbl>   <dbl>   <dbl>     <dbl>     <dbl>     <dbl>
#>  1 1      0.752  0.617   0.844  2.92e- 12   0.531     0.877  
#>  2 2     -0.474 -0.706  -0.150  6.17e-  3  -0.786     0.0302 
#>  3 3     -1.000 -1.000  -1.000  2.42e-226  -1.000    -1.000  
#>  4 4     -0.360 -0.569  -0.108  6.35e-  3  -0.653     0.0257 
#>  5 5     -0.312 -0.494  -0.103  4.09e-  3  -0.572     0.00539
#>  6 6     -0.338 -0.614   0.0120 5.84e-  2  -0.715     0.191  
#>  7 7     -0.752 -0.844  -0.617  2.91e- 12  -0.877    -0.531  
#>  8 8     -0.221 -0.476   0.0670 1.31e-  1  -0.580     0.209  
#>  9 9     -0.328 -0.535  -0.0826 9.95e-  3  -0.620     0.0452 
#> 10 10     0.474  0.150   0.706  6.17e-  3  -0.0302    0.786  
#> 11 11     0.852  0.709   0.927  2.42e-  9   0.603     0.950  
#> 12 12     0.418  0.0809  0.669  1.73e-  2  -0.0997    0.757  
#> 13 13     0.360  0.108   0.569  6.35e-  3  -0.0257    0.653  
#> 14 14     0.312  0.103   0.494  4.09e-  3  -0.00543   0.572  
#> 15 15     0.934  0.889   0.961  9.16e- 26   0.858     0.970
```

<sup>Created on 2019-01-04 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by ibecav** [comment]
Right not complaining just saying I need to start at the base and see what works then work my way up.  All depends on how kind you want to be to the user's input.

**Comment by IndrajeetPatil** [comment]
No, I am not taking that as a complaint. I am just trying to understand if you think the users might enter a range of variables in the form of `"x:y"`, which is clearly used for a single variable both inside and outside of tidyeval domain, and not `"x":"y"`, or `x:y`, or `c("x":"y")`, or `c(x:y)`.

**Comment by ibecav** [comment]
Lol they're users they could do just about anything! Including the old fashioned 6:10 notation (which works.  I'll sort it out anything is possible I just need to check the possibilities

**Comment by ibecav** [comment]
Prepping the PR now.  Went a slightly different route on this one.
